#! /bin/sh
# Run CSHOT with CWP X Graphics

demo=1

x1beg=0 x1end=10000 x2beg=0 x2end=10000

cshot1 |
cshotplot  >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par  \
	title="Dome " \
	-geometry 600x600+650-70 \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &
