#! /bin/sh

suplane |
sufilter |
 supsimage npair=3,3,3 curve=curve1,curve2,curve3 curvecolor=red,black,cyan  \
	> image.eps &

suplane |
sufilter |
supswigb npair=3,3,3 curve=curve1,curve2,curve3 curvecolor=red,black,cyan  \
	> wigb.eps &

suplane |
sufilter |
 supswigp npair=3,3,3 curve=curve1,curve2,curve3 curvecolor=red,black,cyan  \
	> wigp.eps &

echo "You may view the files  image.eps  wigb.eps wigp.eps with your"
echo "PostScript Previewer"
exit 0
