#! /bin/sh

suplane |
sufilter |
 suximage npair=3,3,3 curve=curve1,curve2,curve3 curvecolor=red,black,cyan \
	xbox=50 ybox=50 &

suplane |
sufilter |
 suxwigb npair=3,3,3 curve=curve1,curve2,curve3 curvecolor=red,black,cyan \
	xbox=650 ybox=50 &

suplane |
sufilter |
 suxwigb npair=96 curve=curve4 curvecolor=red \
	xbox=650 ybox=50 &

exit 0
