#!/bin/sh
# PSsuwaveform2 - Demo shell script for program SUWAVEFORM
# Author: Nils Maercklin, 2006
#
# This demo shell script shows the generation of Berlage wavelets
# with different time exponent tn or decay factor (PS plots).

# Set constant waveform parameters:
ns=101     # trace length in samples
dt=0.004   # time sampling rate in seconds
fpeak=20   # peak frequency
cdecay=80  # constant exponential decay factor (berlage_wavelet1.su)
ctn=2      # constant time exponent  (berlage_wavelet2.su)


# Create empty wavelet output files:
> berlage_wavelet1.su
> berlage_wavelet2.su

# Generate Berlage wavelets with different time exponent tn,
# normalize by maximum amplitude, and store tn in header 
# otrav for plotting:
for tn in 0 1 2 3 4 5
do
    # Berlage wavelet:
    suwaveform type=berlage fpeak=$fpeak tn=$tn decay=$cdecay \
        ns=$ns dt=$dt \
    | sushw key=otrav a=$tn \
    | sugain qbal=1 >> berlage_wavelet1.su
done

# Generate Berlage wavelets with different time exponent tn,
# normalize by maximum amplitude, and store decay in header 
# otrav for plotting:
for decay in 20 40 60 80 100 120
do
    # Berlage wavelet:
    suwaveform type=berlage fpeak=$fpeak tn=$ctn decay=$decay \
        ns=$ns dt=$dt \
    | sushw key=otrav a=$decay \
    | sugain qbal=1 >> berlage_wavelet2.su
done


# PS plot of Berlage wavelets with different tn:
supswigp <berlage_wavelet1.su key=otrav grid1=dot xcur=0.75 \
    title="type=berlage fpeak=$fpeak decay=$cdecay" \
    xcur=0.75 label1=" time (s)" label2="time exponent tn" \
    linewidth=0 > berlage_wavelet1.ps

# PS plot of Berlage wavelets with different decay:
supswigp <berlage_wavelet2.su key=otrav grid1=dot xcur=0.75 \
    title="type=berlage fpeak=$fpeak tn=$ctn" \
    xcur=0.75 label1=" time (s)" label2="exponential decay factor" \
    linewidth=0 > berlage_wavelet2.ps

# Merge the two PS plots onto one page:
merge2 berlage_wavelet1.ps berlage_wavelet2.ps > berlage_wavelets.ps


# User info:
cat <<EOF >> /dev/stderr
 Files created by demo PSsuwaveform2:

 berlage_wavelet1.su   data file 1, Berlage wavelets with different tn
 berlage_wavelet2.su   data file 2, Berlage wavelets with different decay

 berlage_wavelet1.ps   PS plot of data file 1
 berlage_wavelet2.ps   PS plot of data file 2
 berlage_wavelets.ps   both PS plots merged onto one page

EOF

exit 0
