#! /bin/sh
#
set -x

nt=300 dt=0.004 ft=0.0  nxm=100 dxm=0.01 fxm=0.0 dxo=0 nxo=1 fxo=0.0
fpeak=20 ls=0 dvdx=0.5 dvdz=0.5 ndpfz=5 v00=2.0 
pert=0 ob=1 er=0

DIR=.
output=$DIR/rawdatasplit.su
migdata=$DIR/datamigsplit.su
migps=$DIR/migsplit.ps
vfile=$DIR/vfile
T1=$DIR/split1.ps
T2=$DIR/split2.ps

susynlv nt=$nt dt=$dt ft=$ft fpeak=$fpeak ls=1 verbose=1 smooth=0\
	nxm=$nxm dxm=$dxm fxm=$fxm dvdx=$dvdx dvdz=$dvdz v00=$v00\
        ref="1:0.3,0.3;0.6,0.3" \
	ref="1:0.3,0.5;0.6,0.6" >$output

supsimage < $output n1=$nt d1=$dt n2=$nxm d2=$dxm f2=$fxm\
        label1="Traveltime (s)" label2="Midpoint (km)"\
	title="Zero-offset section dx=10m" perc=99.5 > $T1

makevel nx=100 nz=100 dvdx=.005 dvdz=.005 > $vfile

sumigsplit < $output nz=100 dz=0.01 vfile=$vfile >$migdata 

supsimage <$migdata f1=0 d1=0.01 f2=0 d2=0.01 perc=99.9 \
label1="Depth (km)" label2="Midpoint (km)" \
title="Migrated data using SPLIT-STEP" >$T2

merge2 $T1 $T2 >$migps 

echo
echo "You may view the file:  $migps   with your PostScript previewer." 

exit 0

