#! /bin/sh

# display impulse responses
suximage < data.su wbox=300 hbox=300 xbox=10 ybox=10 \
   title="Test impulse data" &
suximage < mig.split wbox=300 hbox=300 xbox=330 ybox=10 \
   title="Split Step" &
suximage < mig.ffd  wbox=300 hbox=300 xbox=630 ybox=10 \
   title="Fourier Finite Difference" &
suximage < mig.fd wbox=300 hbox=300 xbox=10 ybox=330 \
   title="Finite Difference" &
suximage < mig.pspi wbox=300 hbox=300 xbox=330 ybox=330 \
   title="PSPI" &
suximage < mig.stolt wbox=300 hbox=300 xbox=630 ybox=330 \
   title="Stolt" &
suximage < mig.gazdag wbox=300 hbox=300 xbox=10 ybox=10 \
   title="Gazdag" &

exit 0
