#! /bin/sh
# Gaussian Beam 

#set -x

# use a  v(z,x) velocity profile here
vfile=hunewvelzx.bin
stacked=put_your_stacked_data_here

# vary the values of dz and nz as a test before running the full model
sumiggbzo < $stacked dx=12.5 dz=3 nz=1500 \
verbose=1 vfile=$vfile  > gb.seismic.su


exit 0
