#! /bin/sh

# fake data no multiples
sunull nt=1500 ntr=60 dt=.004 |
sushw key=gx,offset a=3300,-3237 b=25,50 c=1,1 |
suchw key1=sx key2=gx key3=offset a=0 b=1 c=1 |
suaddevent type=nmo nt=1500 t0=.5  dt=.004 vel=1500  |
suaddevent type=nmo nt=1500 t0=.6  dt=.004 vel=1525 |
suaddevent type=nmo nt=1500 t0=.7  dt=.004 vel=1550 |
suaddevent type=nmo nt=1500 t0=.8  dt=.004 vel=1580 |
suaddevent type=nmo nt=1500 t0=.9  dt=.004 vel=1600 |
suaddevent type=nmo nt=1500 t0=1.0  dt=.004 vel=1620 |
suaddevent type=nmo nt=1500 t0=1.1  dt=.004 vel=1650 |
suaddevent type=nmo nt=1500 t0=1.3  dt=.004 vel=1700 |
suaddevent type=nmo nt=1500 t0=1.6  dt=.004 vel=1850 |
suaddevent type=nmo nt=1500 t0=1.9  dt=.004 vel=2000 |
suaddevent type=nmo nt=1500 t0=2.0  dt=.004 vel=2050 amp=2 |
suaddevent type=nmo nt=1500 t0=2.1  dt=.004 vel=2100 |
suaddevent type=nmo nt=1500 t0=2.4  dt=.004 vel=2150 |
suaddevent type=nmo nt=1500 t0=2.5  dt=.004 vel=2200 |
suaddevent type=nmo nt=1500 t0=2.7  dt=.004 vel=2250 |
suaddevent type=nmo nt=1500 t0=3.0  dt=.004 vel=2350 |
suaddevent type=nmo nt=1500 t0=3.1  dt=.004 vel=2400 |
suaddevent type=nmo nt=1500 t0=3.3  dt=.004 vel=2450 |
suaddevent type=nmo nt=1500 t0=3.5  dt=.004 vel=2500 |
suaddevent type=nmo nt=1500 t0=3.7  dt=.004 vel=2500 |
suaddevent type=nmo nt=1500 t0=4.0  dt=.004 vel=2500 |
suaddevent type=nmo nt=1500 t0=4.1  dt=.004 vel=2550 |
suaddevent type=nmo nt=1500 t0=4.3  dt=.004 vel=2550 |
suaddevent type=nmo nt=1500 t0=4.5  dt=.004 vel=2550 |
suaddevent type=nmo nt=1500 t0=4.6  dt=.004 vel=2600 |
suaddevent type=nmo nt=1500 t0=5.0  dt=.004 vel=2600 |
suaddevent type=nmo nt=1500 t0=5.1  dt=.004 vel=2650 |
suaddevent type=nmo nt=1500 t0=5.5  dt=.004 vel=2650 |
sufilter f=0,5,40,50 | suaddnoise sn=10 > fake.su


# fake data waterbottom multiples only
sunull nt=1500 ntr=60 dt=.004 |
sushw key=gx,offset a=3300,-3237 b=25,50 c=1,1 |
suchw key1=sx key2=gx key3=offset a=0 b=1 c=1 |
suaddevent nt=1500 t0=0.5  dt=.004 vel=1500 |
suaddevent nt=1500 t0=1.0  dt=.004 vel=1500 |
suaddevent nt=1500 t0=1.5  dt=.004 vel=1500 |
suaddevent nt=1500 t0=2.0  dt=.004 vel=1500 |
suaddevent nt=1500 t0=2.5  dt=.004 vel=1500 |
suaddevent nt=1500 t0=3.0  dt=.004 vel=1500 |
suaddevent nt=1500 t0=3.5  dt=.004 vel=1500 |
suaddevent nt=1500 t0=4.0  dt=.004 vel=1500 |
suaddevent nt=1500 t0=4.5  dt=.004 vel=1500 |
suaddevent nt=1500 t0=5.0  dt=.004 vel=1500 |
suaddevent nt=1500 t0=5.5  dt=.004 vel=1500 |
sufilter f=0,5,40,50  | suaddnoise sn=20 > waterbottom.su

# pegleg multiples
sunull nt=1500 ntr=60 dt=.004 |
sushw key=gx,offset a=3300,-3237 b=25,50 c=1,1 |
suchw key1=sx key2=gx key3=offset a=0 b=1 c=1 |
suaddevent type=nmo nt=1500 t0=1.6  dt=.004 vel=1600 |
suaddevent type=nmo nt=1500 t0=2.1  dt=.004 vel=1550 |
suaddevent type=nmo nt=1500 t0=2.6  dt=.004 vel=1525 |
suaddevent type=nmo nt=1500 t0=3.1  dt=.004 vel=1500 |
suaddevent type=nmo nt=1500 t0=3.6  dt=.004 vel=1500 |
suaddevent type=nmo nt=1500 t0=4.1  dt=.004 vel=1500 |
suaddevent type=nmo nt=1500 t0=4.6  dt=.004 vel=1500 |
suaddevent type=nmo nt=1500 t0=5.1  dt=.004 vel=1500 |
suaddevent type=nmo nt=1500 t0=5.6  dt=.004 vel=1500 |
sufilter f=0,5,40,50 | suaddnoise sn=10 > pegleg1.1sec.su


suaddevent < pegleg1.1sec.su type=nmo nt=1500 t0=2.5  dt=.004 vel=2000 |
suaddevent type=nmo nt=1500 t0=3.0  dt=.004 vel=1950 |
suaddevent type=nmo nt=1500 t0=3.5  dt=.004 vel=1900 |
suaddevent type=nmo nt=1500 t0=4.0  dt=.004 vel=1850 |
suaddevent type=nmo nt=1500 t0=4.5  dt=.004 vel=1800 |
suaddevent type=nmo nt=1500 t0=5.0  dt=.004 vel=1750 |
suaddevent type=nmo nt=1500 t0=5.5  dt=.004 vel=1700  \
> pegleg1.1+2.0sec.su


suaddevent <  pegleg1.1+2.0sec.su type=nmo nt=1500 t0=3.8  dt=.004 vel=2400 |
suaddevent type=nmo nt=1500 t0=4.3  dt=.004 vel=2350 |
suaddevent type=nmo nt=1500 t0=4.8  dt=.004 vel=2300 |
suaddevent type=nmo nt=1500 t0=5.1  dt=.004 vel=2250 |
suaddevent type=nmo nt=1500 t0=5.6  dt=.004 vel=2200 \
> pegleg1.1+2.0+3.3sec.su

cp pegleg1.1+2.0+3.3sec.su pegleg.su

susum fake.su waterbottom.su > fake+water.su

susum  fake+water.su pegleg.su > fake+water+pegleg.su


exit 0
