#! /bin/sh

# convert a single RMS velocity to Interval velocity.

# put your values of tnmo= and vnmo=  here.
tnmo=
vnmo=

#output file
outfile=suttoz.par

suintvel t0=$tnmo vs=$vnmo  outpar=$outfile
echo t=$tnmo >> $outfile

echo "use v= and t=  values for suttoz "
echo " result output in $outfile"

exit 0
