#! /bin/sh

# break up the data in to subsets

data=gain.jon=1.cdp.su

suwind key=cdp min=1 max=500 < $data > junk.cdp=1-500.su
suwind key=cdp min=501 max=1000 < $data > junk.cdp=501-1000.su
suwind key=cdp min=1001 max=1500 < $data > junk.cdp=1001-1500.su
suwind key=cdp min=1501  < $data > junk.cdp=1501-2142.su


exit 0
