#! /bin/sh

vnmo=1500,1757,2510 
tnmo=0.0,1.5,3.38 
data=gain.jon\=1.cdp\=265.su

# view nmo corrected data in the Radon domain
sunmo  vnmo=$vnmo tnmo=$tnmo < $data |
suradon offref=-3237 interoff=-287 pmin=-2000 \
pmax=2000 dp=8 choose=0 igopt=2 \
depthref=1000 | suximage perc=99 &

exit 0

# nmo->radon-> inverse NMO: for multiple suppression
sunmo  vnmo=$vnmo tnmo=$tnmo < $data |
suradon offref=-3237 interoff=-287 pmin=-2000 \
pmax=2000 dp=8 choose=1 igopt=2 \
pmula=0 pmulb=0 \
depthref=1000 |
sunmo vnmo=$vnmo tnmo=$tnmo invert=1 > junk1.su

# view semblance
suvelan < junk1.su dv=15 fv=1450 nv=150 |
suximage d2=15 f2=1450 cmap=hsv2 bclip=.5 &

exit 0
