#! /bin/sh
# Velocity analyses for the cmp gathers
# Authors: Dave Hale, Jack K. Cohen, with modifications by John Stockwell
# NOTE: Comment lines preceeding user input start with  ##
#set -x

## Set parameters
datadir=.

velpanel=your_data_cdp.su  # data sorted in cdps, multiple-suppressed
vpicks=nmovel.par       # output file of vnmo= and tnmo= values
normpow=0               # see selfdoc for suvelan
slowness=0              # see selfdoc for suvelan
cdpfirst=1              # minimum cdp value in data
cdplast=2142            # maximum cdp value in data
cdpmin=128              # minimum cdp value used in velocity analysis
cdpmax=2110             # maximum cdp value used in velocity analysis
dcdp=64                # change in cdp for velocity scans
fold=120                # maximum number of traces per cdp gather
dxcdp=12.5              # distance between successive midpoints
                        # in full data set

## Set velocity sampling and band pass filters
nv=200			# number of velocities in scan
dv=15.0			# velocity sampling interval in scan	
fv=1450.0		# first velocity in scan
nout=1500		# ns in data		

## Set interpolation type for velocity function plots
interpolation=mono	# choices are linear, spline, akima, mono

## set filter values for wiggle trace plots
f=1,5,70,80		# bandwidth of data to pass
amps=0,1,1,0		# don't change

## suximage information
wclip=0		# This number should be between 0 to .15 for real data 
bclip=.4	# this number should be around .5
cmap=hsv2	# colormap 
perc=97		# clip above perc percential in amplitude
xcur=2		# allow xcur trace xcursion in wiggle trace plots


#average velocity
vaverage=2100        # this may be adjusted
######## You shouldn't have to change anything below this line ###########

# binary files output
vrmst=vrmst.bin		# VRMS(t) interpolated rms velocities
vintt=vintt.bin		# VINT(t,x) as picked
vinttav=vinttav.bin	# average  VINT(t) of VINT(t,x)
vrmstav=vrmstav.bin	# average  VRMS(t) of VRMS(t,x)
vinttuni=vinttuni.bin	# interploated Vint(t,x)
vintzx=vintzx.bin	# VINT(z,x)interpolated interval velocities
vintzav=vintzav.bin	# average  VINT(z) of VINT(z,x)
vintxz=vintxz.bin	# VINT(x,z)interpolated interval velocities

### Get header info
cdpcount=0		 #  counting variable
dxout=0.004		# don't change this

nout=`sugethw ns <$velpanel | sed 1q | sed 's/.*ns=//'`
dt=`sugethw dt <$velpanel | sed 1q | sed 's/.*dt=//'`
dxout=`bc -l <<END
	$dt / 1000000
END`

cdptotal=`bc -l <<END
	$cdplast - $cdpfirst
END`

dtsec=`bc -l <<END
        $dt / 1000000
END`

echo  "Skip Introduction? (y/n) " | tr -d "\012" >/dev/tty
read response
case $response in
n*) # continue velocity analysis


### give instructions
echo
echo
echo
echo
echo "            Instructions for Velocity Analysis."
echo
echo "  A contour semblance map will appear on the right of your screen."
echo "  A wiggle trace plot of the cdp panel being analysed will appear"
echo "  on the left as an aid in picking. Click on the semblance contour"
echo "  map to make that window active."
echo
echo "  Pick velocities by placing cursor on each peak (do not click) in the"
echo "  semblance plot and typing 's'. Type 'q' when last peak is picked."
echo "  Note, this is 'blind' picking. You will not see any indication"
echo "  on the contour plot that a point has been picked."
echo
echo "  Note also, that it is best if a value of the velocity is picked "
echo "  at the beginning of the data (t=0.0 usually). The picks must "
echo "  be increasing in time. If you feel you have made an incorrect pick"
echo "  you will be given an opportunity to pick the velocities again. "
echo
pause
echo
echo "  Finally, a reasonable value at the latest time of the section "
echo "  should be picked. (Picking reasonable values for the top and bottom"
echo "  of the section ensures that interpolations of the velocities are"
echo "  reasonable. You don't want the wavespeed profile to start at zero "
echo "  velocity."
echo
echo "  Caveat, the interval velocities plotted should not be taken too"
echo "  seriously as these are interpolated from just a handful of values."
echo "  This curve is supplied for reference only."
echo
echo "  A graph of the velocity function will appear, and a prompt to" 
echo "  hit the return key will be seen in this terminal window.  You"
echo "  will then see an nmo corrected version of the cdp gather you that"
echo "  you are performing velocity analysis on." 
echo
echo "  You will be prompted in the terminal window to hit return. Then "
echo "  you will be  will be asked if your picks are ok. This gives you "
echo "  a chance to re-pick the velocities if you do not like the velocity"
echo "  function you have obtained."
echo
echo "  When the shell script reruns, it will ask you about reusing velocity"
echo "  panels. Once these are made, you do not need to remake them, so answer"
echo "  yes to reuse, in this case."

pause

;;
*y) #continue

echo
echo
echo "Beginning the velocity analysis"
echo
echo
echo

;;
esac

########################### start velocity analysis #####################



cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
	cdpcount=` expr $cdpcount + 1 `
	ok=false
	reusepanel=false

	
	# see if panel.$cdp exists
	if [ -f $datadir/panel.$cdp ]
	then
		echo  "panel.$cdp exists. Reuse? (y/n) " | tr -d "\012" >/dev/tty
		read response
		case $response in
		n*) # continue velocity analysis
			reusepanel=false
		;;
		y*) # no need to get velocity panel
			reusepanel=true
		;;
		esac
	fi

	# see if par.$cdp and $vrmst.$cdp exist
	if [ -f par.$cdp ]
	then

		if [ -f $vrmst.$cdp ]
		then
			echo
			echo " file $vrmst.$cdp already exists"
			echo " indicating that cdp $cdp has been picked"
		fi
		echo
		echo " file par.$cdp already exists"
		echo " indicating that cdp $cdp has been picked"
		echo

		echo  "Redo velocity analysis on cdp $cdp? (y/n) " | tr -d "\012" >/dev/tty
		read response
		case $response in
		n*) # continue velocity analysis with next cdp
			ok=true
		;;
		y*) # continue with same value of cdp
			ok=false
		;;
		esac
	fi

	# begin velocity analysis
	while [ $ok = false ]
	do
		echo "Starting velocity analysis for cdp $cdp"

		# capture the current cmp gather
		if [ $reusepanel = false ]
		then
			suwind < $velpanel key=cdp min=$cdp max=$cdp \
					count=$fold > $datadir/panel.$cdp 
			reusepanel=true
		fi

		# plot the wiggle traces of the cmp gather
		suxwigb < $datadir/panel.$cdp  title="CDP gather for cdp=$cdp" \
				xbox=50 mpicks=mpicks.$cdp key=offset \
				perc=$perc xcur=$xcur wbox=300 &

		# make a semblance panel
		sufilter < $datadir/panel.$cdp f=$f amps=$amps |
		suvelan nv=$nv dv=$dv fv=$fv |
		suximage wclip=$wclip bclip=$bclip \
		f2=$fv d2=$dv xbox=450 wbox=600 legend=1 \
		units="semblance" cmap=$cmap \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Velocity Scan (semblance plot) for CMP $cdp" \
		mpicks=mpicks.$cdp

		# make a par file for this cdp based on the velocity and time picks
		sort <mpicks.$cdp  -n |
		mkparfile string1=tnmo string2=vnmo >par.$cdp

		# view the picked velocity function  as both inter
		echo "Putting up velocity function for cdp $cdp"
		sed <par.$cdp '
			s/tnmo/xin/
			s/vnmo/yin/
		' >unisam.p
		unisam nout=$nout fxout=0.0 dxout=$dxout \
			par=unisam.p method=$interpolation > uni.temp.bin
		velconv intype=vrmst outtype=vintt nt=$nout dt=$dt < uni.temp.bin > vel.temp.bin
			cat uni.temp.bin vel.temp.bin > graph.temp.bin
		xgraph < graph.temp.bin n=$nout nplot=2 d1=$dxout linewidth=2,3  f1=0.0 width=400 height=700 \
			label1="Time (sec)" label2="Velocity (m/sec)" \
			title="Red:RMS Velocity function  Blue: approx Interval Velocity: CMP $cdp" \
			linecolor=2,4  &

		pause

		# view an NMO of the panel
		echo "Hit return after nmo panel comes up"
                sunmo par=par.$cdp < $datadir/panel.$cdp |
                suxwigb title="NMO of cdp=$cdp" wbox=300 xcur=$xcur \
			perc=$perc xcur=$xcur  key=offset &

		pause  


		# check to see if the picks are ok
		echo  "Picks OK? (y/n) "  | tr -d "\012" >/dev/tty
		read response
		case $response in
		n*) ok=false ;;
		*) ok=true 
			# capture resampled velocity
			unisam nout=$nout fxout=0.0 dxout=$dxout \
			par=unisam.p method=$interpolation > $vrmst.$cdp

			# clean up the screen
			zap ximage
			zap xgraph
			zap xwigb
			zap xcontour
		;;
		esac

	done </dev/tty

	echo
	echo
	echo  "Continue with velocity analysis? (y/n) "  | tr -d "\012" >/dev/tty
	read response
	case $response in
	n*)	# if quitting set cdp to a value large enough to
		# break out of loop 
		cdp=`expr $cdpmax + 1`
	;;
	y*)
		# else get the next cdp
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
	;;
	esac

done

set +x


### Combine the individual picks into a composite sunmo par file
echo "Editing pick files ..."
>$vpicks
echo  "cdp=" | tr -d "\012" >>$vpicks
cdp=$cdpmin
echo  "$cdp"  | tr -d "\012" >>$vpicks
cdp=`bc -l <<END
	$cdp + $dcdp
END`
while [ $cdp -le $cdpmax ]
do
	echo  ",$cdp"  | tr -d "\012" >>$vpicks
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
done
echo >>$vpicks

cdpcount=0
rm $vrmst
cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
	cat $vrmst.$cdp >> $vrmst
	cat par.$cdp >>$vpicks
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
	cdpcount=` expr $cdpcount + 1 `
done

# build velocity files to be used for comparison (not recommended for migration)
vrmstpar=vrmst.par
vinttpar=vintt.par
vinttplotpar=vinttplot.par
vintzplotpar=vintzplot.par
unipar=unisam.par

# build par files
echo "n1=$nout d1=$dt n2=$cdpcount f2=$cdpmin d2=$dcdp " > $vrmstpar
echo "nt=$nout d1=$dt ns=$nout nx=$cdpcount fx=$cdpmin dx=$dcdp  " > $vinttpar
echo "n=$nout nplot=1 d1=$dxout  width=400 height=700  " > $vinttplotpar
echo "nx1=$nout nx2=$cdpcount n1=$nout n2=$cdptotal" > $unipar

# convert rms velocities to interval velocities 
velconv intype=vrmst outtype=vintt  par=$vinttpar < $vrmst > $vintt

# make an average velocity profile
suaddhead < $vintt ns=$nout | sustack | sustrip  > $vinttav 

# make an average velocity profile
suaddhead < $vrmst ns=$nout | sustack | sustrip  > $vrmstav 

# build a uniformly sampled v(t,x) velocity profile
unisam2 < $vintt par=$unipar  | smooth2 r1=5 r2=5 par=$unipar >  $vinttuni

                                                                                
# get depth sampling interval
dzout=`bc -l <<END
        ( $vaverage * $dtsec ) / 2.0
END`
                                                                                
echo $dzout

# par file for average interval velocity
echo "n=$nout nplot=1 d1=$dzout  xbox=500 width=400 height=700  " > $vintzplotpar
                                                                                
# build v(z,x) 
velconv intype=vintt outtype=vintz  dt=$dtsec \
nx=$cdplast nz=$nout dz=$dzout < $vinttuni |
smooth2 r1=10 r2=20 n1=$nout n2=$cdplast > $vintzx

suaddhead < $vintzx ns=1500 |
sushw key=cdp a=1 |
sustack | sustrip > $vintzav
                                                                                
# build v(x,z)
transp < $vintzx n1=$nout > $vintxz



# final echos
echo "V(t) RMS (stacking) velocity file: $vrmst is ready"
echo "V(t,x) Interval velocity file: $vintt is ready"
echo "V(z) INT (interval) velocity file: $vintz is ready"
echo "V(z,x) Interval velocity file: $vintzx is ready"
echo "V(x,z) Interval velocity file: $vintxz is ready"
echo "sunmo par file: $vpicks is ready"


exit 0
