#! /bin/sh

# Plot traces 
a2b <teose_SU  n1=1 |
xwigb n1=155  d1=0.002  f1=0.500 \
       n2=60   d2=0.10   f2=0.10  \
       wbox=3.0 hbox=8.0 \
       grid1=solid \
       label1="Time (s)" \
       label2="P-waves;  azimuth = 0, 30, 60, 90, 120, 150" \
       labelsize=16 \
       perc=99.9 \
       style=seismic &

