#! /bin/sh
# Invert the data created by CSHOT

recordfile=record

################
cd inversion.dir	# where inversion files are
################

echo "Run time information being stored in file:  $recordfile"
>$recordfile

(

	### Preprocessing
	rm -f DATA1
	cz1in <data1in
	rm -f PTRACES
	cz1

	### Inversion
	cxzco

) > $recordfile 2>&1

sleep 20

### Move record up to demo directory
mv -f $recordfile ..
echo "run time info now in file:  $recordfile"

### Plotting the section
ftnstrip <sync  |
xwigb  n1=301 n2=200 f1=0.0 d1=25 f2=1000 d2=40 perc=99 \
	-geometry 560x430+50+570 \
	title="Inversion of syncline model" \
	label1="Depth (m)"  label2="Range (m)" \
	x2beg=$x2beg x2end=$x2end &
