#! /bin/sh

demo=2

# Examine model with CSHOT, use CWP X Graphics for display
# Change Data/modelgeometry to move subsurface shot around, etc.
# Display the model with subsurface rays

############
cd model.dir	# where model stuff is
############

cp param1.model param1

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 560x430+650+75 \
	title="Model $demo with Subsurface Rays" \
	label1="Depth (m)"  label2="Range (m)" &


# Build synthetic data with CSHOT, display with CWP X Graphics

# Make time section information
echo "Making time section (takes time) ..."

cp param1.traces param1
cshot1 >/dev/null

# Make time section
cshot2

# Move data to the inversion directory
mv demo${demo}traces ../inversion.dir

cd ../inversion.dir
# Display section
ftnstrip <demo${demo}traces | suaddhead n1=500 | sushw key=dt a=4000 |
suxmovie  f1=0.0 f2=0 d2=20 perc=99 \
	-geometry 560x430+50+75 \
	title="Synthetic Section" \
	label1="Time (s)" label2="Range (m)" &

exit 0
