#! /bin/sh
# set -x


#B=${HOME}/Release/bin

# Example-shell for hti2stiff.c

sign=1             # sign of c13+c55 ( for most materials sign=1)
outpar=/dev/tty    # output to screen

# to review definition of HTI parameters, see
# CWP-235  Reflection coeff and azimuthal AVO 
# in anisotropic media by Andreas Rueger

hti2stiff \
	alpha=3.58963 beta=2 rho=2.41 \
	ev=-0.11469 dv=-0.119443 gamma=0.0586255 \
	sign=$sign outpar=$outpar

exit
