#! /bin/sh

vp=2               # symm.axis p-wave velocity                         
vs=1               # symm.axis s-wave velocity                         
eps=0.1            # Thomsen's (generic) epsilon                               
gamma=0.3          # Thomsen's generic gamma                                  
weak=1             # compute weak approximation                               
outpar=/dev/tty    # output parameter file                           

thom2stiff vp=$vp vs=$vs eps=$eps gamma=$gamma weak=1 outpar=$outpar


