#! /bin/sh
# noise movie

jmax=30
j=1

rm junk1.su

while [ "$j" -ne "$jmax" ]
do
	suplane | sufilter | suaddnoise sn=$j >> junk1.su
	j=`expr $j + 1`
done

suxmovie < junk1.su n2=32 loop=1 title="suaddnoise sn=%g" clip=1.0 &

exit 0
	
