#! /bin/ksh
set -x
cat cos1 out1|
 psgraph n=50,50  d1=80,80 f1=3000 >f1\
  x2beg=0. x2end=2. ybox=3.5 hbox=4 \
  lineoff=0,5.0 grid1=dash grid2=dash\
  label1='midpoint(m)' label2='Cosine of angle' \
  title='First interface ' &
rm -f a b c

cat cos2 out2|
psgraph n=50,50  d1=80,80 f1=3000>f2 \
  x2beg=0. x2end=2. ybox=3.5 hbox=4 \
  lineoff=0,5.0 grid1=dash grid2=dash\
  label1='midpoint(m)' label2='Cosine of angle' \
  title='Second interface ' &
rm -f a b c  
