#! /bin/sh
# Run CSHOT with CWP X Graphics

demo=5

x1beg=0 x1end=5500 x2beg=-100 x2end=10000

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par

xgraph <demo${demo}plot par=demo${demo}par  \
	-geometry 600x400+500+500 \
	title="Rays for demo$demo" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &
