#! /bin/sh
# shell for uniformly sampling velocity from a layered model
set -v

nz=51 dz=50 fz=0.0  labelz="Depth (m)"
nx=201 dx=50 fx=0  labelx="Distance (m)"
ninf=0 npmax=201 
unif2 <input_datum >vfile_datum method=mono ninf=$ninf npmax=$npmax \
	nz=$nz dz=$dz fz=$fz nx=$nx dx=$dx fx=$fx \
	v00=2000\
	dvdz=0
exit 0

