#! /bin/sh

origdata=model.data
data=shot_TOPO.data

shot=4000

rec1=`expr $shot - 2000`
rec2=`expr $shot + 2000`

suwind<$data key=sx min=$shot max=$shot |
suwind key=gx min=$rec1 max=$rec2 |
suwind tmin=0 tmax=3.0 |
suximage legend=1 f2=-2.0 d2=0.025 label1="Time (s)" label2="Offset (km)" \
	title="Shot $shot with topography" hbox=600 wbox=400 perc=99.2 &

suwind<$origdata key=sx min=$shot max=$shot |
suwind key=gx min=$rec1 max=$rec2 |
suwind tmin=0 tmax=3.0 |
suximage legend=1 f2=-2.0 d2=0.025 label1="Time (s)" label2="Offset (km)" \
	title="Shot $shot original data" hbox=600  wbox=400 xbox=500  perc=99.2 &
