#! /bin/sh
# Best results starting with suspecfx and using some indicated sufilters
demo=filt2

perc=90   # accept value in book
tpow=3.2  # accept value in oz25.H

f=0,10,15,20
amps=0.,0.,1.,1.
sufilter <data.su f=$f amps=$amps |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="f=$f + gain"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.1.eps

f=0,10,20,25
amps=0.,0.,1.,1.
sufilter <data.su f=$f amps=$amps |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="f=$f + gain"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.2.eps


f=0,15,20,25
amps=0.,0.,1.,1.
sufilter <data.su f=$f amps=$amps |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="f=$f + gain"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.3.eps

f=0,15,25,30
amps=0.,0.,1.,1.
sufilter <data.su f=$f amps=$amps |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="f=$f + gain"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.4.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0
