#! /bin/sh
demo=look

# Look at raw data using par file to supply all parameters
# This would work even we did not use sushw in MakeDataBig/Little
supsimage<data.su par=oz25.H >${demo}.1.eps

# Repeat using SU headers and adding the suggested tpow in oz25.H
tpow=3.191650
sugain <data.su tpow=$tpow |
supsimage \
	title="Oz 25 with tpow=$tpow"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.2.eps

# Add perc option to remove "outliers" this only affects the
#	display, not the data itself
perc=90
supsimage<data.su perc=$perc \
	title="With perc=$perc"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.3.eps

perc=75
supsimage<data.su par=oz25.H perc=$perc \
	title="With perc=$perc"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.4.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0
