#! /bin/sh
# Use sumute to eliminate direct arrivals on the filtered data
demo=mute

perc=90
tpow=2

f=0,15,25,30
amps=0.,0.,1.,1.

sufilter <data.su f=$f amps=$amps |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="f=$f + gain"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.1.eps

xmute=1,49,97
tmute=1.0,.2,1.0
ntaper=0

sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="xmute=$xmute tmute=$tmute ntaper=$ntaper"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.2.eps

xmute=1,49,97
tmute=1.2,.2,1.2
ntaper=0

sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="xmute=$xmute tmute=$tmute ntaper=$ntaper"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.3.eps

xmute=1,49,97
tmute=1.2,.2,1.2
ntaper=5

sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
supsimage  perc=$perc \
	title="xmute=$xmute tmute=$tmute ntaper=$ntaper"\
	label1="Time (sec)" label2="Offset (km)" >${demo}.4.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0
