#! /bin/sh
# Try some display gains on the muted, filtered data
WIDTH=600
HEIGHT=450
WIDTHOFF1=0
WIDTHOFF2=640
HEIGHTOFF1=50
HEIGHTOFF2=530

perc=90

f=0,15,25,30
amps=0.,0.,1.,1.

xmute=1,49,97
tmute=1.2,.2,1.2
ntaper=5

tpow=1
sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="filter, mute & tpow=$tpow" \
	windowtitle="tpow=$tpow" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF1} &

tpow=2
sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="filter, mute & tpow=$tpow"\
	windowtitle="tpow=$tpow" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF1} &

tpow=3
sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="filter, mute & tpow=$tpow"\
	windowtitle="tpow=$tpow" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF2} &

tpow=2.2
sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="filter, mute & tpow=$tpow"\
	windowtitle="tpow=$tpow" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF2} &

exit 0
