#! /bin/sh
WIDTH=600
HEIGHT=450
WIDTHOFF1=0
WIDTHOFF2=640
HEIGHTOFF1=50
HEIGHTOFF2=530

# Look at raw data using par file to supply all parameters
# This would work even we did not use sushw in MakeDataBig/Little
suxmovie<data.su par=oz25.H windowtitle="Raw Data"\
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF1} &

# Repeat using SU headers and adding the suggested tpow in oz25.H
tpow=3.191650
sugain <data.su tpow=$tpow |
suxmovie \
	title="Oz 25 with tpow=$tpow" windowtitle="tpow=$tpow" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF1} &

# Add perc option to remove "outliers" this only affects the
#	display, not the data itself
perc=90
suxmovie<data.su perc=$perc \
	title="With perc=$perc" windowtitle="perc=$perc" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF2} &

perc=75
suxmovie<data.su par=oz25.H perc=$perc \
	title="With perc=$perc" windowtitle="perc=$perc" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF2} &

exit 0
