#! /bin/sh
# Use sumute to eliminate direct arrivals on the filtered data
WIDTH=600
HEIGHT=450
WIDTHOFF1=0
WIDTHOFF2=640
HEIGHTOFF1=50
HEIGHTOFF2=530

perc=90
tpow=2

f=0,15,25,30
amps=0.,0.,1.,1.

sufilter <data.su f=$f amps=$amps |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="f=$f + gain" windowtitle="f=$f" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF1} &

xmute=1,49,97
tmute=1.0,.2,1.0
ntaper=0

sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="xmute=$xmute tmute=$tmute ntaper=$ntaper" \
	windowtitle="tmute=$tmute" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF1} &

xmute=1,49,97
tmute=1.2,.2,1.2
ntaper=0

sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="xmute=$xmute tmute=$tmute ntaper=$ntaper" \
	windowtitle="tmute=$tmute" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF2} &

xmute=1,49,97
tmute=1.2,.2,1.2
ntaper=5

sufilter <data.su f=$f amps=$amps |
sumute key=tracl xmute=$xmute tmute=$tmute ntaper=$ntaper |
sugain tpow=$tpow |
suxmovie  perc=$perc \
	title="xmute=$xmute tmute=$tmute ntaper=$ntaper" \
	windowtitle="plus taper" \
	label1="Time (sec)" label2="Offset (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF2} &

exit 0
