#! /bin/sh
#### Control shell to 
####   1. create syncline model
####   2. generate zero-offset data including all rays
####   3. generate zero-offset data including only reflected rays
####   4. as (3), but higher ray coverage

Model
Seis1
Seis2
Seis3

exit 0
