#! /bin/sh
# shell for plotting synthetic data and migrated data

supsimage<data  perc=99.5\
	label1="Time (s)" label2="Midpoint (m)" \
	ybox=4 hbox=4 \
	title="Synthetic Data"  > syndata.eps

# Plotting migrated data

supsimage<kd.data perc=99.5\
	label1="Depth (km)" label2="Midpoint (km)" \
	ybox=4 hbox=4 \
	title="Kirchhoff Depth Migration" > migdata.eps

echo "Output as the PostScript files:  syndata.eps migdata.eps"
echo "You may view these with your PostScript Previewer"
