#! /bin/sh
# shell for plotting the original and smoothed v(x,z) model
#set -v

WIDTH=400
HEIGHT=600
WIDTHOFF1=10
HEIGHTOFF1=20

nz=51 dz=50 fz=.0  labelz="Depth (m)"
nx=71 dx=50 fx=0000.0  labelx="Distance (m)"
ninf=0 npmax=201 

ximage <vfile  style=seismic legend=1 units=vel cmap=hsv5 \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	title="Velocity" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF1 & 
exit 0

