#! /bin/sh
# shell for plotting the original and smoothed v(x,z) model
#set -v

WIDTH=400
HEIGHT=600
WIDTHOFF1=10
WIDTHOFF2=430
WIDTHOFF3=860
HEIGHTOFF1=20

# Plot Synthetic data 

nt=501 dt=0.004 ft=0.0  nx=121 dx=25 fx=0  
suximage < data d1=$dt f1=$ft d2=$dx f2=$fx  perc=99.5\
	label1="Time (sec)" label2="Midpoint (m)" grid1=solid \
 	hbox=$HEIGHT wbox=$WIDTH xbox=$WIDTHOFF2 ybox=$HEIGHTOFF1 \
	title="Synthetic Data" &


# Plot inverted data 

n1=501 n2=121 f2=500 d1=3 d2=25 
suximage < kd.data n1=$n1 n2=$n2 d1=$d1 f2=$f2 d2=$d2  perc=99.5\
	label1="Depth (m)" label2="Midpoint (m)" \
    	d1num=500 \
 	hbox=$HEIGHT wbox=$WIDTH xbox=$WIDTHOFF3 ybox=$HEIGHTOFF1 \
	title="Kirchhoff Depth Migration" & 
exit
