#! /bin/sh
# shell for plotting synthetic data
n1=51 f1=0 d1=50 n2=61 d2=50 f2=500 n3=41 d3=100 

xmovie<tfile n1=$n1 d1=$d1 f1=$f1 n2=$n2 d2=$d2 f2=$f2 n3=$n3 d3=$d3 \
	label1="Depth (m)" label2="Midpoint (m)" \
	ybox=3 hbox=4 \
	bclip=2 d1num=500 d2num=1000 \
	title="Traveltime Tables" loop=1 &


# Plotting inverted data
