/*<license>
 -------------------------------------------------------------------------------
  Copyright (c) 2007 ConocoPhillips Company
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 -------------------------------------------------------------------------------
 </license>*/
"CubeSlice*version_2_0.background: red",
"CubeSlice*version_2_0.labelString:\
-----------------------------------------------\\n\
Please contact Bill Menger bill.menger@gmail.com\n\
to request new options, report bugs, or to get user assistance.",
"*fontList: -*-*-bold-r-normal-*-*-120-*-*-p-*-iso8859-1",
"*main_form.resizePolicy:   RESIZE_NONE",
"*useColorObj: False",
"*background: lightgray",
"*acube.width:   600",
"*acube.height:  700",
"*primsw.resizePolicy:   RESIZE_NONE",
"*plot.width: 1200",
"*plot.height: 1200",
"*scrwin.width: 800",
"*scrwin.height: 600",
"*XmDrawingArea.resizePolicy: RESIZE_NONE",
"*addfile.accelerator:         Meta<Key>A",
"*addfile.acceleratorText:     Alt-A",
"*cbar.accelerator:            Meta<Key>B",
"*cbar.acceleratorText:        Alt-B",
"*control.accelerator:         Meta<Key>C",
"*control.acceleratorText:     Alt-C",
"*color.accelerator:           Meta<Key>K",
"*color.acceleratorText:       Alt-K",
"*quit.accelerator:            Meta<Key>Q",
"*quit.acceleratorText:        Alt-Q",
"*zline.accelerator:           Meta<Key>U",
"*zline.acceleratorText:       Alt-U",
"*zxline.accelerator:          Meta<Key>V",
"*zxline.acceleratorText:      Alt-V",
"*zts.accelerator:             Meta<Key>W",
"*zts.acceleratorText:         Alt-W",
"*zrl.accelerator:             Meta<Key>X",
"*zrl.acceleratorText:         Alt-X",
"*zdown.accelerator:           Meta<Key>D",
"*zdown.acceleratorText:       Alt-D",
"*zop.accelerator:              Meta<Key>Y",
"*zop.acceleratorText:          Alt-Y",
"*zorgin.accelerator:          Meta<Key>S",
"*zorgin.acceleratorText:      Alt-S",
"*accel_inline_movie_left.accelerator:     Meta<Key>1",
"*accel_inline_movie_right.accelerator:    Meta<Key>2",
"*accel_crossline_movie_left.accelerator:  Meta<Key>3",
"*accel_crossline_movie_right.accelerator: Meta<Key>4",
"*accel_timeslice_movie_left.accelerator:  Meta<Key>5",
"*accel_timeslice_movie_right.accelerator: Meta<Key>6",
"*accel_cube_movie_left.accelerator:       Meta<Key>7",
"*accel_cube_movie_right.accelerator:      Meta<Key>8",
"*accel_inline_scan_left.accelerator:      Ctrl<Key>1",
"*accel_inline_scan_right.accelerator:     Ctrl<Key>2",
"*accel_crossline_scan_left.accelerator:   Ctrl<Key>3",
"*accel_crossline_scan_right.accelerator:  Ctrl<Key>4",
"*accel_timeslice_scan_left.accelerator:   Ctrl<Key>5",
"*accel_timeslice_scan_right.accelerator:  Ctrl<Key>6",
"*accel_inline_dataload.accelerator:       Ctrl<Key>7",
"*accel_crossline_dataload.accelerator:    Ctrl<Key>8",
"*accel_timeslice_dataload.accelerator:    Ctrl<Key>9",
"*file.labelString:      File",
"*option.labelString:    Option",
"*tools.labelString:     Tools",
"*zoom.labelString:      Zoom",
"*window.labelString:    Window",
"*custom.labelString:    Custom",
"*help.labelString:      Help",
"*addfile.labelString:      Add Cube...",
"*changefile.labelString:   Change Cube...",
"*quit.labelString:         Quit",
"*scrlock.labelString:      Lock Scrolling",
"*overvis.labelString:      Show Overlay",
"*sync_slices.labelString:  Lock All Cubes",
"*add_graph.labelString:    New Window",
"*rem_graph.labelString:    Close this Window",
"*zline.labelString:   Zoom Line",
"*zxline.labelString:  Zoom Cross Line",
"*zts.labelString:     Zoom Time Slice",
"*zrl.labelString:     Zoom Random Line",
"*zop.labelString:     Zoom Options",
"*inline_hard.labelString:  Line Hard Copy",
"*xline_hard.labelString:   Cross Line Hard Copy",
"*ts_hard.labelString:      Time Slice Hard Copy",
"*control.labelString:      Control Panel...",
"*cube_table.labelString:   Loaded Cube List...",
"*cbar.labelString:         Color Bar...",
"*showil.labelString:      Show Line",
"*showxl.labelString:      Show Cross Line",
"*showts.labelString:      Show Time Slice",
"*showwf.labelString:      Show Wire Frame",
"*color.labelString:       Color...",
"*section.labelString:     Modify Plot Parameters...",
"*anno.labelString:        Modify Annotation Parameters...",
"*amp.labelString:         Modify Amplitude Scaling...",
"*version.labelString:     On Version...",
"*overview.labelString:    Overview Help...",
"*ctx.labelString:         Context Sensitive",
"*mousehelp.labelString:   Show Status Line",
"*showil.set:      True",
"*showxl.set:      True",
"*showts.set:      True",
"*showwf.set:      True",
"*scrlock.set:     True",
"*overvis.set:     True",
"*mousehelp.set:   True",
"*sync_slices.set: True",
"*trace_edit.screenNumber: otherScreen",
"*cross_hair.labelString:  Coupled cursor",
"*crosshair_off.labelString:  Cursor off",
"*crosshair_off.set: False",
"*crosshair_small.labelString:  Cursor small",
"*crosshair_small.set: True",
"*crosshair_big.labelString:  Cursor big",
"*crosshair_big.set: False",
"cubeSlice*sp-port:  6060",
"cubeSlice*sp-host:  poepsn03.po.dupont.com",
"*queue.optionCount: 2",
"*queue.optionElement_0: paper_A",
"*queue.optionElement_1: hp650_1",
"*queue.value:           paper_A",
