#! /bin/sh
# shell for generating a plane data set
set -v

suplane	nt=501 dt=0.004 ntr=121 \
	dip1=0 dip2=2 dip3=4 \
	len1=81 len2=81 len3=81 |
	sushw key=sx a=300 b=25 |
	sushw key=gx a=700 b=25 >data

exit 0
