#! /bin/sh

WIDTH=300
HEIGHT=300
XOFF1=50
YOFF1=50
XOFF2=500
YOFF2=500


# Plot Synthetic data 

suximage < kdsyn.data  perc=99.5\
	label1="Time (sec)" label2="Midpoint (m)"  \
	title="Synthesized Data" \
	hbox=$HEIGHT wbox=$WIDTH xbox=$XOFF1 ybox=$YOFF1 &


# Plot migration data 

n1=501 n2=121 f2=500 d1=3 d2=25 
sustrip<kd.data |
ximage n1=$n1 n2=$n2 d1=$d1 f2=$f2 d2=$d2  perc=99.5\
	label1="Depth (m)" label2="Midpoint (m)" \
    	d1num=500  \
	title="Migrated Section" \
	hbox=$HEIGHT wbox=$WIDTH xbox=$XOFF2 ybox=$YOFF1 &
exit
