#! /bin/sh
# Run cwell with CWP X Graphics

demo=9
MACHINE=keller
USER="-l jkc"

# If NEXTFILE is empty (eg. comment off), display with image on NeXT
#NEXTFILE="~jkc/Images/CWELL/demo${demo}wig.eps"

if [ -z "$NEXTFILE" ]
then
	remoteCommand="images"
else
	remoteCommand="cat >$NEXTFILE"
fi


cwell

cshot2

suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suaddnoise sn=5000 |		# to help pswigp
supswigp title="Crosswell Data (AGC)" \
	label1="Time in Seconds"  label2="Trace" |
rsh $MACHINE $USER $remoteCommand
