#! /bin/sh
# Run cwell with CWP X Graphics

demo=10

x1beg=0 x1end=6500 x2beg=-100 x2end=10000

cwell |
cshotplot >demo${demo}plot  outpar=demo${demo}par

xgraph <demo${demo}plot par=demo${demo}par  \
	-geometry 600x400+0-70 \
	title="Head Wave Rays" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

cshot2

suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=1.0 |
suxwigb title="Head Wave Data (agc)" \
	ybox=20 xbox=650 \
	label1="Time in Seconds"  label2="Trace" &
