#! /bin/sh

CIN=/u/elbert/zliu/bin

cp ../mod/sync.shot .

>record

(

rm -f DATA1
cz1in <data1in
cz1

$CIN/cxzcs
)   >record 2>&1
rm -f PTRACES CZ2DAT

 suaddhead ns=301 ftn=1<reflect|
 supsimage n1=301 d1=40 d2=80 f2=80 perc=99\
     label1=" Depth(ft)" style=seismic\
     label2=" Midpoint(ft)"\
     ybox=3.5 hbox=4 grid1=dash grid2=dash  \
     title=" Inversion  "\
