#!/bin/csh -f
if ($?CLASSPATH != 0) then
  setenv OLD_CLASSPATH ${CLASSPATH}
else
  if ($?OLD_CLASSPATH != 0) then
    unsetenv OLD_CLASSPATH
  endif
endif
setenv CLASSPATH .
foreach CL_PATH(`cat ${SPWSINSTALLDIR}/lib/${ARCHITECTURE}/spws_jars`)
     eval setenv CLASSPATH ${CLASSPATH}:${CL_PATH}
end
if ($?OLD_CLASSPATH != 0) then
  setenv CLASSPATH ${CLASSPATH}:${OLD_CLASSPATH}
  unsetenv OLD_CLASSPATH
endif
