#! /bin/sh
# Velocity analyses for the cmp gathers
# Authors: Dave Hale, Jack K. Cohen, with modifications by John Stockwell
# NOTE: Comment lines preceeding user input start with  ##
#set -x

## Set parameters
velpanel=modeldata	# gained and deconvolved seismic data,
			 		# sorted in cdp's
vpicks=stkvel.p1	# output file of vnmo= and tnmo= values
normpow=0		# see selfdoc for suvelan
slowness=0		# see selfdoc for suvelan
cdpfirst=1		# minimum cdp value in data
cdplast=3500		# maximum cdp value in data
cdpmin=1500		# minimum cdp value used in velocity analysis
cdpmax=3500		# maximum cdp value used in velocity analysis
dcdp=500		# change in cdp for velocity scans
fold=12		 	# only have 12 shots, otherwise would be 
			#  64/2=32 for dsx=dgx, or maximum number
			#  of traces per cdp gather
dxcdp=50		# distance between successive midpoints
                        #    in full datas set


## Set velocity sampling and band pass filters
nv=120			# number of velocities in scan
dv=75.0			# velocity sampling interval in scan	
fv=4000.0		# first velocity in scan
nout=501		# ns in data		

## Set interpolation type 
interpolation=akima	# choices are linear, spline, akima, mono

## set filter values
f=1,10,80,100		# bandwidth of data to pass
amps=0,1,1,0		# don't change

## number of contours in contour plot
nc=35		# this number should be at least 25
fc=.05		# This number should be between .05 to .15 for real data 
ccolor=black,grey,green,black,grey,cyan,black,grey,blue,black,grey,blue,red,red,red
perc=97		# clip above perc percential in amplitude
xcur=3		# allow xcur trace xcursion

######## You shouldn't have to change anything below this line ###########
#average velocity
vaverage=3000        # this may be adjusted

# binary files output
vrmst=vrmst.bin		# VRMS(t) interpolated rms velocities
vintt=vintt.bin		# VINT(t,x) as picked
vinttav=vinttav.bin	# average  VINT(t) of VINT(t,x)
vinttuni=vinttuni.bin	# interploated Vint(t,x)
vintzx=vintzx.bin	# VINT(z,x)interpolated interval velocities
vintxz=vintxz.bin	# VINT(x,z)interpolated interval velocities

### Get header info
cdpcount=0		 #  counting variable
dxout=0.004		# don't change this

nout=`sugethw ns <$velpanel | sed 1q | sed 's/.*ns=//'`
dt=`sugethw dt <$velpanel | sed 1q | sed 's/.*dt=//'`
dxout=`bc -l <<END
	$dt / 1000000
END`

cdptotal=`bc -l <<END
	$cdplast - $cdpfirst
END`

dtsec=`bc -l <<END
        $dt / 1000000
END`

echo  "Skip Introduction? (y/n) " | tr -d "\012" >/dev/tty
read response
case $response in
n*) # continue velocity analysis


### give instructions
echo
echo
echo
echo
echo "            Instructions for Velocity Analysis."
echo
echo "  A contour semblance map will appear on the left of your screen."
echo "  A wiggle trace plot of the cdp panel being analysed will appear"
echo "  on the right as a aid in picking. Click on the semblance contour"
echo "  map to make that window active."
echo
echo "  Pick velocities by placing cursor on each peak in the"
echo "  semblance plot and typing 's'. Type 'q' when last peak is picked."
echo "  Note, this is 'blind' picking. You will not see any indication"
echo "  on the contour plot that a point has been picked."
echo
echo "  Note also, that it is best if a value of the velocity is picked "
echo "  at the beginning of the data (t=0.0 usually). The picks must "
echo "  be increasing in time. If you feel you have made an incorrect pick"
echo "  you will be given an opportunity to pick the velocities again. "
echo
pause
echo
echo "  Finally, a reasonable value at the latest time of the section "
echo "  should be picked. (Picking reasonable values for the top and bottom"
echo "  of the section ensures that interpolations of the velocities are"
echo "  reasonable. You don't want the wavespeed profile to start at zero "
echo "  velocity."
echo
echo "  For this demo dataset, there will be a maximum of 4 peaks to be"
echo "  picked, as this is the number of reflectors in the model. However,"
echo "  for the far-offset CDP gathers, it may be difficult to pick all "
echo "  4 peaks."
echo
echo "  A graph of the velocity function will appear, and a prompt to" 
echo "  hit the return key will be seen in this terminal window.  You"
echo "  will then see an nmo corrected version of the cdp gather you that"
echo "  you are performing velocity analysis on." 

echo
echo "  You will be prompted in the terminal window to hit return. Then "
echo "  you will be  will be asked if your picks are ok. This gives you "
echo "  a chance to re-pick the velocities if you do not like the velocity"
echo "  function you have obtained."

pause

;;
*y) #continue

echo
echo
echo "Beginning the velocity analysis"
echo
echo
echo

;;
esac

########################### start velocity analysis #####################



cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
	cdpcount=` expr $cdpcount + 1 `
	ok=false
	reusepanel=false

	
	# see if panel.$cdp exists
	if [ -f panel.$cdp ]
	then
		echo  "panel.$cdp exists. Reuse? (y/n) " | tr -d "\012" >/dev/tty
		read response
		case $response in
		n*) # continue velocity analysis
			reusepanel=false
		;;
		y*) # no need to get velocity panel
			reusepanel=true
		;;
		esac
	fi

	# see if par.$cdp and $vrmst.$cdp exist
	if [ -f par.$cdp ]
	then

		if [ -f $vrmst.$cdp ]
		then
			echo
			echo " file $vrmst.$cdp already exists"
			echo " indicating that cdp $cdp has been picked"
		fi
		echo
		echo " file par.$cdp already exists"
		echo " indicating that cdp $cdp has been picked"
		echo

		echo  "Redo velocity analysis on cdp $cdp? (y/n) " | tr -d "\012" >/dev/tty
		read response
		case $response in
		n*) # continue velocity analysis with next cdp
			ok=true
		;;
		y*) # continue with same value of cdp
			ok=false
		;;
		esac
	fi

	# begin velocity analysis
	while [ $ok = false ]
	do
		echo "Starting velocity analysis for cdp $cdp"

		if [ $reusepanel = false ]
		then
			suwind < $velpanel key=cdp min=$cdp max=$cdp \
					count=$fold > panel.$cdp 
			reusepanel=true
		fi

		suxwigb < panel.$cdp title="CDP gather for cdp=$cdp" \
				xbox=50 mpicks=mpicks.$cdp \
				perc=$perc xcur=$xcur wbox=300 &
		sugain tpow=2 < panel.$cdp |
		sufilter f=$f amps=$amps |
		suvelan nv=$nv dv=$dv fv=$fv |
		suxcontour nc=$nc f2=$fv d2=$dv xbox=450 wbox=600 \
		units="semblance" fc=$fc ccolor=$ccolor \
		label1="Time (sec)" label2="Velocity (m/sec)" \
		title="Velocity Scan (semblance plot) for CMP $cdp" \
		mpicks=mpicks.$cdp

		sort <mpicks.$cdp  -n |
		mkparfile string1=tnmo string2=vnmo >par.$cdp

		# view the picked velocity function 
		echo "Putting up velocity function for cdp $cdp"
		sed <par.$cdp '
			s/tnmo/xin/
			s/vnmo/yin/
		' >unisam.p
		unisam nout=$nout fxout=0.0 dxout=$dxout \
			par=unisam.p method=$interpolation |
		xgraph n=$nout nplot=1 d1=$dxout f1=0.0 width=400 height=700 \
			label1="Time (sec)" label2="Velocity (m/sec)" \
			title="Stacking Velocity Function: CMP $cdp" \
			grid1=solid grid2=solid \
			linecolor=2 style=seismic &

		pause

		# view an NMO of the panel
		echo "Hit return after nmo panel comes up"
                sunmo < panel.$cdp par=par.$cdp |
                suxwigb title="NMO of cdp=$cdp" wbox=300 xcur=$xcur \
			perc=$perc xcur=$xcur  &

		pause  


		# check to see if the picks are ok
		echo  "Picks OK? (y/n) "  | tr -d "\012" >/dev/tty
		read response
		case $response in
		n*) ok=false ;;
		*) ok=true 
			# capture resampled velocity
			unisam nout=$nout fxout=0.0 dxout=$dxout \
			par=unisam.p method=$interpolation > $vrmst.$cdp

			# clean up the screen
			zap ximage
			zap xgraph
			zap xwigb
			zap xcontour
		;;
		esac

	done </dev/tty

	echo
	echo
	echo  "Continue with velocity analysis? (y/n) "  | tr -d "\012" >/dev/tty
	read response
	case $response in
	n*)	# if quitting set cdp to a value large enough to
		# break out of loop 
		cdp=`expr $cdpmax + 1`
	;;
	y*)
		# else get the next cdp
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
	;;
	esac

done

set +x


### Combine the individual picks into a composite sunmo par file
echo "Editing pick files ..."
>$vpicks
echo  "cdp=" | tr -d "\012" >>$vpicks
cdp=$cdpmin
echo  "$cdp"  | tr -d "\012" >>$vpicks
cdp=`bc -l <<END
	$cdp + $dcdp
END`
while [ $cdp -le $cdpmax ]
do
	echo  ",$cdp"  | tr -d "\012" >>$vpicks
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
done
echo >>$vpicks

cdpcount=0
rm $vrmst
cdp=$cdpmin
while [ $cdp -le $cdpmax ]
do
	cat $vrmst.$cdp >> $vrmst
	cat par.$cdp >>$vpicks
	cdp=`bc -l <<END
		$cdp + $dcdp
END`
	cdpcount=` expr $cdpcount + 1 `
done

# build velocity files to be used for later migration
vrmstpar=vrmst.par
vinttpar=vintt.par
vinttplotpar=vinttplot.par
unipar=unisam.par

# build par files
echo "n1=$nout n2=$cdpcount f2=$cdpmin d2=$dcdp " > $vrmstpar
echo "nt=$nout ns=$nout nx=$cdpcount fx=$cdpmin dx=$dcdp  " > $vinttpar
echo "n=$nout nplot=1 d1=$dxout style=seismic width=400 height=700  " > $vinttplotpar
echo "nx1=$nout nx2=$cdpcount n1=$nout n2=$cdptotal" > $unipar

# convert rms velocities to interval velocities 
velconv intype=vrmst outtype=vintt  par=$vinttpar < $vrmst > $vintt

# make an average velocity profile
suaddhead < $vintt ns=$nout | sustack | sustrip  > $vinttav 

# build a uniformly sampled v(t,x) velocity profile
unisam2 < $vintt par=$unipar  | smooth2 r1=5 r2=5 par=$unipar >  $vinttuni

                                                                                
# get depth sampling interval
dzout=`bc -l <<END
        ( $vaverage * $dtsec ) / 2.0
END`
                                                                                
echo $dzout
                                                                                
# build v(z,x)
velconv intype=vintt outtype=vintz  dt=$dtsec \
nx=$cdplast nz=$nout dz=$dzout < $vinttuni |
smooth2 r1=10 r2=20 n1=$nout n2=$cdplast > $vintzx
                                                                                
# build v(x,z)
transp < $vintzx n1=$nout > $vintxz


# final echos
echo "V(t) RMS (stacking) velocity file: $vrmst is ready"
echo "V(t,x) Interval velocity file: $vintt is ready"
echo "V(z,x) Interval velocity file: $vintzx is ready"
echo "sunmo par file: $vpicks is ready"


exit 0
