#! /bin/sh

WIDTH=300
WIDTHOFF=50
WIDTHOFF2=50
HEIGHT=600
HEIGHTOFF=50
HEIGHTOFF2=250
HEIGHTOFF3=500
HEIGHT2=200
WIDTH2=600


vrmst=vrmst.bin
vintt=vintt.bin
vinttav=vinttav.bin
rmspar=vrmst.par
intpar=vintt.par
vinttplot=vinttplot.par
unipar=unisam.par
vinttuni=vinttuni.bin
vintxz=vintxz.bin
vintzx=vintzx.bin

# plot rms velocities
ximage par=$rmspar  legend=1 title="rms velocities" <  $vrmst \
wbox=${WIDTH2} hbox=${HEIGHT2} xbox=${WIDTHOFF} ybox=${HEIGHTOFF} &


# plot interval velocities
ximage par=$rmspar  legend=1 title="interval velocities" <  $vintt \
wbox=${WIDTH2} hbox=${HEIGHT2} xbox=${WIDTHOFF} ybox=${HEIGHTOFF2} &

# plot average velocity
xgraph par=$vinttplot legend=1 title="average interval velocities" <  $vinttav &

# plot interpolated interval velocities
ximage par=$unipar  legend=1 title="interpolated interval velocities" <  $vinttuni \
wbox=${WIDTH2} hbox=${HEIGHT2} xbox=${WIDTHOFF} ybox=${HEIGHTOFF3} &

