 
################ makefile.depend ##################
 
############## fortran dependencies ###############
 
 
################ xml dependencies #################
 
 
############# c and c++ dependencies ##############
 

workstation.o:					\
		workstation.c			\
		trciof77.h			\
		c2f_interface.h

csvtrot.o:					\
		csvtrot.cc			\
		cube.h			\
		c2f_interface.h			\
		trciof77.h			\
		upgrade264.h
 
################ end dependencies #################
 
