#! /bin/sh


# make null traces with sunull, add linear moveout arrivals with suaddevent
sunull nt=500 dt=0.004 ntr=100 |
sushw key=offset a=-1000 b=20 |
suaddevent v=1000 t0=0.05 type=lmo |
suaddevent v=1800 t0=0.8 |
sufilter f=8,12,75,90 | suxwigb clip=1 & 

exit 0
