#! /bin/sh
# Run cwell with CWP X Graphics

demo=9


cwell

cshot2

suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Crosswell Data (agc)" \
	ybox=70 xbox=650\
	label1="Time in Seconds"  label2="Trace" &
