#! /bin/sh
# Shell: Unisam2 
# use unisam2 to make a uniformly sampled wavespeed profiles
# Author: John Stockwell, 27 August 1992

set -x

# Background Velocity Model 1  
# constant wavespeed (of 11750) model  250x500 samples
echo "11750" > junkv              # make ascii data

a2b < junkv n1=1 > infile.v    # convert to binary	
unisam2 < infile.v x1=0 n1=500 d1=1 x2=0 n2=250 d2=1 f2=0 > outfile.v 

mv outfile.v junkv

exit 0
