#! /bin/sh
# Run CSHOT with CWP X Graphics
# Zero-offset data corresponding to a model
# with topography, base of weathering and 
# a reflector at depth

demo=14

x1beg=-1000 x1end=4000 x2beg=0 x2end=18000

cp param1.1 param1
cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 400x300+500+0 \
	title="Weathering Model" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

cp param1.2 param1
cshot1 >/dev/null
cshot2
suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
suchw key1=sx key2=tracl b=50 |
suchw key1=gx key2=sx b=1 |
sugain gagc=1 wagc=0.5 > demo.su
cp demo.su ../
cp demo14plot ../
cp demo14par ../
suximage < demo.su title="Common Offset (agc)" \
	xbox=20 ybox=0 wbox=400 hbox=300 \
	label1="Time (s)" label2="Midpoint (kft)" f2=.05 d2=.05 &
