#! /bin/sh
# Run CSHOT with CWP PostScript Graphics

demo=1
psfile=demo${demo}.eps

x1beg=0 x1end=5500 x2beg=-100 x2end=10000

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
exit

psgraph <demo${demo}plot par=demo${demo}par style=seismic \
	title="Model for demo$demo" \
	label1="Depth (ft)"  label2="Range (ft)" \
	wbox=6 hbox=4 \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end >$psfile

# Put the PostScript on screen or printer according to local lore
cat $psfile | rsh keller -l jkc pwin
#cat $psfile | rsh dix -l jkc lpr -P$DixPrinter
#xpwin <$psfile


