#! /bin/sh

# compute and view phase velocity dispersion

suwind j=50 < hseis.out |
suphasevel fv=1500 dv=25 nv=400 |
suamp mode=amp |
suximage cmap=hsv2 perc=99 style=normal wbox=800 hbox=400 \
     label2="frequency (hz)" label1="Phase Velocity (km/s)" \
      title="Phase velocity dispersion"
