#! /bin/sh
#set -v
data=data3d.su
output=inv.su
psout1=data3d.ps
psout2=inversion.ps

nzo=101 nxo=32 nyo=32

sustrip<$data |pscube n1=$nzo n2=$nxo n3=$nyo > $psout1

nzo=32 nxo=32 nyo=32

sustrip<$output|pscube n1=$nzo n2=$nxo n3=$nyo > $psout2

echo 
echo "You may view the files $psout1 and $psout2 with your PostScript previewer"
echo 

exit 0
