#! /bin/sh
set -x
input=./data3d.su
vfile=./vfile
output=inv.su
 dt=0.01  i=1 doff=0 n=1 offs=0 dfxm=0 fxm=0. ny=32
 nxm=32 dxm=100  dxo=100 nxo=32 dyo=100 nyo=32 fxo=0. fyo=0. dzo=20 nzo=101 
 fzo=0.  nz=101 dy=100 dz=20 fx=0. nxb=5  ang=10 

sufrac<$input dt=$dt phase=0.5|
suinvzco3d dt=$dt offs=$offs ny=$ny nxm=$nxm dxm=$dxm dyo=$dyo nyo=$nyo ang=$ang\
 fxm=$fxm fxo=$fxo fyo=$fyo fzo=$fzo nzo=$nzo dzo=$dzo\
  dxo=$dxo nxo=$nxo  nx=$nx nz=$nz fx=$fx dx=$dx dy=$dy dz=$dz \
  fmax=0.01 vfile=$vfile verbose=1 nxb=$nxb nxd=$nxd > $output

exit 0
