#! /bin/sh
# shell for running unif2 --- uniformly sampled Cshot model
# data is smoothed with smo2d
set -v

nx=1 dx=80 fx=1000  labelx="Distance (m)"
nz=101 dz=80 fz=.0  labelz="Depth (m)"
ninf=5 npmax=201 
xsmoothing=0 zsmoothing=0

unif2 <interface ninf=$ninf  npmax=$npmax \
	nz=$nz dz=$dz fz=$fz nx=$nx dx=$dx fx=$fx \
	v00=5000,5000,5000,5000 >vfile 
exit 0
