#! /bin/sh
#set -v

WIDTH=250
HEIGHT=250
XOFF=0
YOFF=0
XOFF1=300
YOFF1=300
XOFF2=600
YOFF2=600




data=data3d.su
output=inv.su
nzo=101 nxo=32 nyo=32

echo "inline view"

suxmovie <$data loop=1 n1=$nzo n2=$nxo n3=$nyo mode=0 \
	-geometry ${WIDTH}x${HEIGHT}+${XOFF}+${YOFF} \
	title="Point Scatterer data (inline view)" &

suxmovie <$output loop=1 n1=$nzo n2=$nxo n3=$nyo mode=0 \
	-geometry ${WIDTH}x${HEIGHT}+${XOFF}+${YOFF1} \
	clip=2.15e-8 title="Inversion Output (inline view)" perc=99 &

echo "crossline view"

sleep 2

suxmovie <$data loop=1 n1=$nzo n2=$nxo n3=$nyo mode=1 \
	-geometry ${WIDTH}x${HEIGHT}+${XOFF1}+${YOFF} \
	title="Point Scatterer data (crossline view)" &

suxmovie <$output loop=1 n1=$nzo n2=$nxo n3=$nyo mode=1 \
	-geometry ${WIDTH}x${HEIGHT}+${XOFF1}+${YOFF1} \
	clip=2.15e-8 title="Inversion Output (crossline view)" perc=99 &


echo "time/depth view"

sleep 2

suxmovie <$data loop=1 n1=$nzo n2=$nxo n3=$nyo mode=2 \
	-geometry ${WIDTH}x${HEIGHT}+${XOFF2}+${YOFF} \
	title="Point Scatterer data (timeslice view)" &

suxmovie <$output loop=1 n1=$nzo n2=$nxo n3=$nyo mode=2 \
	-geometry ${WIDTH}x${HEIGHT}+${XOFF2}+${YOFF1} \
	clip=2.15e-8 title="Inversion Output (depth slice view)" perc=99 &
exit 0
