#! /bin/sh
# suimp2d, suimp3d --- impulsive seismic data over a point scatterer 2D,3D
# Author: John Stockwell, 7 Jun 1993

demo=spike

## Example 1: default -- one record zero offset above a point scatterer 
##	one shot at (0,0)
##	one receiver at (0,0)
##	scatterer at (1000,1000)

suimp2d x0=0 | 
supswigp title="Single Trace" >${demo}.1.eps

## Example 2: common shot data set above a point scatterer
##	one shot at (0,0)
##	range of receivers from (0,0) to (0,2000)
##	scatterer at (1000,1000)

suimp2d nrec=100 dgx=20 |
supswigp title="Common Shot data" >${demo}.2.eps


## Example 3: common offset data above a point scatterer
##	100 shots with a spacing of 20 (meters)
##	range of shots from (0,0) to (0,2000)
##	100 receivers with a spacing of 20 (meters)
##	range of receivers from (0,0) to (0,2000)
##	scatterer at (1000,1000)
###	common offset = 100 (using suwind).

echo "This one will take a couple of seconds"
echo
suimp2d nshot=100 nrec=100 dgx=20 dsx=20 |
suwind key=offset min=100 max=100 count=100 |
supswigp title="Common Offset data" >${demo}.3.eps


exit 0
