#! /bin/sh
# suimp2d, suimp3d --- impulsive seismic data over a point scatterer 2D,3D
WIDTH=420
HEIGHT=700
XOFF1=0
XOFF2=430
XOFF3=860
YOFF=150

echo "The third of three windows in this demo takes some time to come up"
echo

## Example 1: default -- one record zero offset above a point scatterer 
##	one shot at (0,0)
##	one receiver at (0,0)
##	scatterer at (1000,1000)

suimp2d x0=0 | 
suxwigb perc=$perc \
	title="Single Trace" \
	windowtitle="Single Trace" \
	label1="Time (sec)" label2="Trace" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF1} ybox=${YOFF} &

## Example 2: common shot data set above a point scatterer
##	one shot at (0,0)
##	range of receivers from (0,0) to (0,2000)
##	scatterer at (1000,1000)

suimp2d nrec=100 dgx=20 |
suximage perc=$perc d2=20  \
	title="Common Shot data" \
	windowtitle="Shot data" \
	label1="Time (sec)" label2="Offset (m)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF2} ybox=${YOFF} &

## Example 3: common offset data above a point scatterer
##	100 shots with a spacing of 20 (meters)
##	range of shots from (0,0) to (0,2000)
##	100 receivers with a spacing of 20 (meters)
##	range of receivers from (0,0) to (0,2000)
##	scatterer at (1000,1000)
###	common offset = 100 (using suwind).

suimp2d nshot=100 nrec=100 dgx=20 dsx=20 |
suwind key=offset min=100 max=100 count=100 |
suximage perc=$perc \
	title="Common Offset data" \
	windowtitle="Offset data" \
	label1="Time (sec)" label2="Channel" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF3} ybox=${YOFF} &

exit 0
