#! /bin/sh

kaperture both=1 fmin=50 fmax=125 x0=0 y0=1000 nfreq=100 dgx=10 \
ngeo=1000 nstep=0 | 
xy2z nx1=200 nx2=200 npairs=200000 > junk1.bin

psimage < junk1.bin n1=200 n2=200 wbox=4 hbox=4 style=normal > junk.ps






