#! /bin/sh


kaperture both=1 fmin=50 fmax=125 x0=500 y0=1000 nfreq=100 dsx=10 \
ngeo=1000 nstep=0 |
xgraph title="common shot (500,1000)"  n=200000,100 \
mark=1,0 marksize=1,0 linewidth=0,1 style=normal &

kaperture both=1 fmin=50 fmax=125 x0=1000 y0=1000 nfreq=100 dsx=10 \
ngeo=1000 nstep=0 |
xgraph title="common shot (1000,1000)"  n=200000,100 \
mark=1,0 marksize=1,0 linewidth=0,1 style=normal &

