#! /bin/sh
# Model 4:  Cerveny (multi layer model with a lens and fault)

# model number
model=4

# data directory (optional, if not set data will go into current directory)
datadir=../datadir/

psfile=${datadir}model${model}.eps
datafile=${datadir}model${model}.data

##### Built the Cerveny model
##### note: this is the model that appears in figure 1 of the GBmod
##### documentation

trimodel xmin=0 zmin=0 xmax=20.0 zmax=10.0 maxangle=5 \
1       xedge=0.0,5.0,10.0,15.0,20.0 \
	zedge=0.0,0.0,0.0,0.0,0.0 \
	sedge=0,0,0,0,0 \
2       xedge=0.0,5.0,10.0,15.0,20.0 \
	zedge=0.0,0.8,0.0,0.6,0.0 \
	sedge=0,0,0,0,0 \
3 	xedge=0.00,5.20,10.00,20.00 \
	zedge=2.5,2.40,2.80,2.4 \
	sedge=0,0,0,0\
4       xedge=0.00,2.00,10.00 \
	zedge=5.00,4.80,2.80 \
	sedge=0,0,0 \
5       xedge=7.00,10.50,15.00 \
	zedge=5.30,4.50,5.00\
	sedge=0,0,0 \
6       xedge=7.00,10.50,15.00 \
	zedge=5.30,5.30,5.00\
	sedge=0,0,0 \
7       xedge=2.00,10.00,20.00 \
	zedge=4.80,6.50,6.50 \
	sedge=0,0,0 \
8       xedge=0.00,8.00 \
	zedge=9.00,8.00 \
	sedge=0,0 \
9       xedge=8.00,8.50 \
	zedge=8.00,9.50 \
	sedge=0,0 \
10      xedge=8.50,20.00 \
	zedge=9.50,9.00 \
	sedge=0,0 \
11      xedge=0.00,20.00 \
	zedge=10.00,10.00 \
	sedge=0,0 \
kedge=1,2,3,4,5,6,7,8,9,10,11 \
v1	sfill=0.01,1.01,0,0,0.90,0,0.0 \
        sfill=0.01,3.00,0,0,.70,0,0.0 \
        sfill=10.0,5.00,0,0,1.0,0,0.0 \
        sfill=10.0,6.00,2.0,5,0.40,0.05,0.0 \
        sfill=10.0,7.00,2.0,5,0.40,0.05,0.05 \
        sfill=5.0,9.50,0,0,.30,0,0.0 \
        sfill=5.0,0.10,0,0,1.40,0,0.0 \
        sfill=15.0,0.10,0,0,1.40,0,0.0 \
	>$datafile

# generate PostScript output
spsplot <$datafile gtri=-1\
	label1="Depth (km)" label2="Distance (km)" \
	hbox=3.5 wbox=6  title="Cerveny Model" \
	>$psfile

##### Put the PostScript on screen 
##### the user may set the shell environment variable 
##### PSPREVIEWER to have PostScript output viewed on the screen

if test "$PSPREVIEWER" = ""
then
	echo "Environment variable PSPREVIEWER is not set."
else
	$PSPREVIEWER <$psfile &
fi

exit 0

