#! /bin/sh
# Model 1 - constant sloth (and hence constant wavespeed) medium

# model number
model=1

# data directory (optional, if unset put datafiles in current directory)
datadir=../datadir/

psfile=${datadir}model${model}.eps
datafile=${datadir}model${model}.data


##### Constant Sloth model

trimodel xmin=0 zmin=0 xmax=1.0 zmax=1 \
1	xedge=0,1 \
	zedge=0,0 \
	sedge=0,0 \
2	xedge=0,1 \
	zedge=1,1 \
	sedge=0,0 \
	sfill=0.5,0.5,0,0,1.5,0,0 \
	kedge=1,2 \
	>$datafile


##### Create PostScript 
spsplot <$datafile gtri=1 \
	xmin=0 zmin=0 xmax=1.0 zmax=1 \
	labelx="Distance (km)" labelz="Depth (km)" \
	hbox=5 wbox=5 gmin=0.5  title="Constant V model" \
	>$psfile

##### Put the PostScript on screen 
##### the user may set the shell environment variable 
##### PSPREVIEWER to have PostScript output viewed on the screen

if test "$PSPREVIEWER" = ""
then
	echo "Environment variable PSPREVIEWER is not set."
else
	$PSPREVIEWER <$psfile  &
fi

exit 0

