#! /bin/sh
# Model 1 - constant sloth (and hence constant wavespeed) medium

# model number
model=1


# data directory (optional, if unset put datafiles in current directory)
datadir=../datadir/

datafile=${datadir}model${model}.data

##### Constant Sloth model

trimodel xmin=0 zmin=0 xmax=1.0 zmax=1 \
1	xedge=0,1 \
	zedge=0,0 \
	sedge=0,0 \
2	xedge=0,1 \
	zedge=1,1 \
	sedge=0,0 \
	sfill=0.5,0.5,0,0,1.5,0,0 \
	kedge=1,2 \
	>$datafile

sxplot <$datafile -geom 650x650+0+0 \
        label1="Depth (km)" label2="Distance (km)" \
        title="First Model (constant V)"  &

exit 0
