#! /bin/sh
# Model 5: Salt dome model
set +x
# model number
model=5

# data directory (optional, if not set data will go into current directory)
datadir=../datadir/
datafile=${datadir}model${model}.data

##### Build the dome salt model.
##### Note how sedge is used to generate a continuous velocity field

trimodel xmin=0 zmin=0 xmax=8 zmax=4  \
1       xedge=0.0,8.0 \
	zedge=0.0,0.0 \
	sedge=1.00,1.00 \
2       xedge=0.0,1.0,2.0,3.0,8.0 \
        zedge=0.2,0.23,0.25,0.26,0.27 \
        sedge=1.00,1.00,1.00,1.00,1.00 \
3       xedge=0.0,1.0,1.0,1.0,1.5 \
        zedge=1.0,1.0,2.0,3.0,4.0 \
        sedge=0.40,0.40,0.30,0.20,0.10 \
4       xedge=1.0,1.5,8.0 \
	zedge=1.0,1.3,2.2 \
	sedge=0.40,0.40,0.40 \
5       xedge=1.0,1.5,8.0 \
	zedge=2.0,2.4,3.3 \
	sedge=0.30,0.30,0.30 \
6       xedge=0.0,1.5,8.0 \
	zedge=4.0,4.0,4.0 \
	sedge=0.10,0.10,0.10 \
        sfill=0.1,3.1,0.0,0.0,0.10,0.00,0.00 \
        kedge=1,2,3,4,5,6 >$datafile


# Generate X-windows graphics
sxplot <$datafile -geom 650x650+0+0\
        label1="Depth (km)" label2="Distance (km)" \
        title="Salt Dome Model"  &

exit 0

