#! /bin/sh
# Model 2 :  two constant sloth media in contact with a syncline/anticline
#	     boundary

# model number
model=2

#data directory (optional, if not set data will go into current directory)
datadir=../datadir/

datafile=${datadir}model${model}.data

##### Build two media, syncline/anticline model
### note: this model appears as figure 23 of the GBmod documentation
####

trimodel xmin=-1 zmin=0 xmax=5.0 zmax=2.0 \
1	xedge=-1,0,1,2,3,4,5 \
	zedge=0,0,0,0,0,0,0 \
	sedge=0,0,0,0,0,0,0 \
2       xedge=-1,0,0.5,1.0,1.5,2,2.5,3,4,5 \
	zedge=1,1,1.1,1.3,1.1,1,1.1,1,1,1  \
	sedge=0,0,0,0,0,0,0,0,0,0 \
3	xedge=-1,0,1,2,3,4,5 \
	zedge=2,2,2,2,2,2,2 \
	sedge=0,0,0,0,0,0,0 \
	sfill=1,0.5,0,0,0.25,0,0 \
	sfill=1,1.8,0,0,0.1,0,0 \
	kedge=1,2,3 \
	>$datafile

##### Create X-Windows display
sxplot <$datafile -geom 1200x450+0+0 title="Simple 2 media model" \
        label1="Depth (km)" label2="Distance (km)" &

exit 0
