#! /bin/sh
# Run CSHOT with CWP PostScript Graphics

model=1

cshot1 >/dev/null
cshot2
suaddhead <comodel${model}traces ftn=1 ns=701 |
sushw key=dt a=2000 >flat3lay500off.su

rm -f comodel1*

rm -f junk.su
exit 0
