#! /bin/sh
set -v

input=flat3lay500off.su
vfile=vfile
tfile=t
ampfile=amp
d21file=d21
d22file=d22
d23file=d23
d31file=d31
d32file=d32
d33file=d33
a1file=a1
b1file=b1
output=inv500offw3.su
output1=inv500offw3.ps

geo_type=3
com_type=3

fxt=0.0 dxt=50.0 nxt=81 
fyt=0.0 dyt=50.0 nyt=81 
fzt=0.0 dzt=25.0 nzt=61 

dt=0.002  offs=500 
dxm=10 nxm=301  fxm=0.0
dym=10 nym=241  fym=0.

fxo=800.0 dxo=20 nxo=71
fyo=2000.0 dyo=20 nyo=1
fzo=0. dzo=5 nzo=301 

dxv=10 nxv=1     fxv=0.
dyv=10 nyv=1     fyv=0.
dzv=15 nzv=101   fzv=0.

nxb=100 
fmax=30 ang=10
r1=0
power=1
apet=30
alias=1

sufrac<$input dt=$dt sign=1 power=1.0 |
suinvco3d geo_type=$geo_type com_type=$com_type dt=$dt offs=$offs\
	dxm=$dxm nym=$nym nxm=$nxm fxm=$fxm dxm=$dxm dym=$dym \
	fxt=$fxt dxt=$dxt nxt=$nxt fyt=$fyt dyt=$dyt nyt=$nyt\
	fzt=$fzt nzt=$nzt dzt=$dzt \
	fxo=$fxo dxo=$dxo nxo=$nxo fyo=$fyo dyo=$dyo nyo=$nyo\
	fzo=$fzo nzo=$nzo dzo=$dzo \
	fxv=$fxv dxv=$dxv nxv=$nxv fyv=$fyv dyv=$dyv nyv=$nyv\
	fzv=$fzv nzv=$nzv dzv=$dzv \
	nxb=$nxb na=$na fmax=$fmax alias=$alias\
  	vfile=$vfile tfile=$tfile ampfile=$ampfile \
	d21file=$d21file d22file=$d22file d23file=$d23file\
	d31file=$d31file d32file=$d32file d33file=$d33file\
	a1file=$a1file b1file=$b1file\
	apet=$apet verbose=1 > $output


supsimage< $output >$output1


exit 0
