#! /bin/sh
set -v

in1=t.a
in2=amp.a
in3=d21.a
in4=d22.a
in5=d23.a
in6=d31.a
in7=d32.a
in8=d33.a
in9=a1.a
in10=b1.a

out1=t
out2=amp
out3=d21
out4=d22
out5=d23
out6=d31
out7=d32
out8=d33
out9=a1
out10=b1

tableq

a2b<$in1 n1=1>$out1
a2b<$in2 n1=1>$out2
a2b<$in3 n1=1>$out3
a2b<$in4 n1=1>$out4
a2b<$in5 n1=1>$out5
a2b<$in6 n1=1>$out6
a2b<$in7 n1=1>$out7
a2b<$in8 n1=1>$out8
a2b<$in9 n1=1>$out9
a2b<$in10 n1=1>$out10

rm -f  $in1 $in2 $in3 $in4 $in5 $in6 $in7 $in8 $in9 $in10 

