#! /bin/sh
#set -v

ximage<vfile n1=101 \
        d1=0.015  d2=4.0 f2=1 label1="Depth (km)" label2="X (km)"\
	title="Velocity"\
        d1num=0.4 d2num=1 whbox=700 hbox=400\
	titlesize=30 labelsize=24\
	x2beg=0 x2end=4&

suximage<flat3lay500off.su \
        d1=0.002 d2=0.01 f2=0.0 label1="Traveltime (s)" label2="X (km)"\
	title="Synthetic data (offset=0.5 km)"\
        d1num=0.4 d2num=1 wbox=700 hbox=500\
        titlesize=30 labelsize=24\
        x2beg=0 x2end=4&

suximage<inv500offw3.su title="Output of Kirchhoff inversion"\
         d1=0.005 d2=0.020 f2=0.8 label1="Depth (km)" label2="X (km)"\
         d1num=0.4  d2num=0.5 wbox=700 hbox=400\
         titlesize=30 labelsize=24&
exit 0
