#! /bin/sh
# Sufdmod2 --- example script for sufdmod2
# finite-difference modeling, part 2 the output files
# Author: John Stockwell
WIDTH=450
HEIGHT=450
WIDTHOFF1=20
WIDTHOFF2=510
WIDTHOFF3=930
HEIGHTOFF1=50
HEIGHTOFF2=530

clip=.5

suwind <vseis.pml.out j=3 | suxwigb clip=$clip  \
	title="Vertical line of seismograms" \
	windowtitle="Vertical" \
	label1="Time (sec)" label2="Depth (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF3} ybox=${HEIGHTOFF1} &

suwind <hseis.pml.out j=3 | suxwigb  clip=$clip \
	title="Horizontal line of seismograms" \
	windowtitle="Horizontal" \
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF1} ybox=${HEIGHTOFF2} &

suxwigb <sseis.pml.out  \
	title="Source point seismogram" \
	windowtitle="Source" \
	label1="Time (sec)" label2="Trace" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF2} ybox=${HEIGHTOFF2} &

exit 0
