#=======================================================================
#                   Mac OS X Lion  Makefile.config 
#-----------------------------------------------------------------------
# This file is used as a template for Makefile.config if there is not
# a predefined file in ${CWPROOT}/src/configs.
#
# Likely source of issues will be the setting of preprocessor symbols
# to properly pick up common, non-ANSI & non-POSIX extensions in
# /usr/include/stdio.h for popen(3c), pclose(3c), fdopen(3c), etc.
#
# If you are using this file rather than a preconfigured version
# please post it to the seisunix mailing list along w/ the output
# from the sys_arch command.
#
#=======================================================================


#-----------------------------------------------------------------------
# pick up the Make rules (Gnu make required)
#-----------------------------------------------------------------------

include $(CWPROOT)/src/Rules/gnumake.rules
include $(CWPROOT)/src/Rules/abbrev.rules
include $(CWPROOT)/src/Rules/cflags.rules
include $(CWPROOT)/src/Rules/suffix.rules
include $(CWPROOT)/src/Rules/misc.rules
include $(CWPROOT)/src/Rules/opengl.rules

#-----------------------------------------------------------------------
#                      CWP feature options
#-----------------------------------------------------------------------
#
# LINEHDRFLAG=SU_LINEHEADER  - adds 3200 byte text & 400 byte SEG-Y 
#                              style line headers to output. CWP/SU
#                              always reads either format unless SUXDR
#                              has been selected.
#
# XDRFLAG=-DSUXDR            - forces all SU data to be big endian
#                              independent of processor architecture
#
# LARGE_FILE_FLAG            - controls access to files > 2 GB on
#                              some systems.
#
# -DSLTSU_SEGY_H             - if defined selects SLT/SU trace header
#                              layout so both packages are compatible
#-----------------------------------------------------------------------

LINEHDRFLAG = 
XDRFLAG = -DSUXDR
ENDIANFLAG = -DCWP_LITTLE_ENDIAN
#LARGE_FILE_FLAG = -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DGNU_SOURCE
LARGE_FILE_FLAG =

CWP_FLAGS = $(LARGE_FILE_FLAG) $(ENDIANFLAG) $(XDRFLAG) $(LINEHDRFLAG)

#-----------------------------------------------------------------------
# system stuff
#-----------------------------------------------------------------------

SHELL = /bin/sh
ROOT = $(CWPROOT)

LN = ln  # this needs to be changed to cp for FAT32 filesystems
AR = ar
ARFLAGS = rv
RANLIB = ranlib
RANFLAGS = 
ICHMODLINE = chmod 644 $@
MCHMODLINE = chmod 755 $@

POSTLFLAGS = 

#-----------------------------------------------------------------------
# use both X11 path conventions
#-----------------------------------------------------------------------

IX11 = /usr/X11/include
LX11 = /usr/X11/lib
IMOTIF = /usr/X11R6/include
LMOTIF = /usr/X11R6/lib

LD_LIBRARY_PATH += $(CWPROOT)/lib:${LX11}:${LMOTIF}

#-----------------------------------------------------------------------
# Gnu compilers by default just because they are the most common
#-----------------------------------------------------------------------

CPP = /usr/bin/cpp

CC = /usr/bin/gcc
#OPTC = -g -c90  -m64 -Wall -ansi  -Wno-long-long 
OPTC = -g -std=c90  -m64 -Wall -ansi  -Wno-long-long 
CFLAGS = -I$I $(OPTC) $(CWP_FLAGS)

FC = gfortran
FOPTS = -g 
FFLAGS = $(FOPTS) -ffixed-line-length-none

C++FLAGS = -I$I $(OPTC) $(CWP_FLAGS)
