#!/bin/sh

#-----------------------------------------------------------------------
# cleanup working directories of old files
#-----------------------------------------------------------------------

find . -exec touch {} \; \( -name '*.o' -o -name '*.a' -o -name INSTALL \) -exec  /bin/rm -f  {} \;


