 
################ makefile.depend ##################
 
############## fortran dependencies ###############
 
 
################ xml dependencies #################
 
 
############# c and c++ dependencies ##############
 

transform.o:					\
		transform.c			\
		transform.h
 
################ end dependencies #################
 
