#!/bin/csh -f
#<CPS_v1 type="SCRIPT" pretag="#"/>


#<copyright>
#*******************************************************************************
#*******                        COPYRIGHT NOTICE                         *******
#******* CONFIDENTIAL AND PROPRIETARY INFORMATION OF CONOCOPHILLIPS INC. *******
#*******      PROTECTED BY THE COPYRIGHT LAW AS AN UNPUBLISHED WORK      *******
#*******************************************************************************
#</copyright>


#<brief_doc>
#-------------------------------------------------------------------------------
#                         C P S   S C R I P T   
#
# Name   : sol62_purify
# Written: 2003-06-13   by: Tom Stoeckley
# Revised: 2006-10-25   by: Kruger Corn
# Purpose: Run purify with Solaris Fortran 6.2 compiler.
#
#-------------------------------------------------------------------------------
#</brief_doc>


#<descript_doc>
#-------------------------------------------------------------------------------
#                            DOCUMENTATION
#
# Run purify with the Solaris Fortran 6.2 compiler.
#
#-------------------------------------------------------------------------------
#</descript_doc>


#<history_doc>
#-------------------------------------------------------------------------------
#                           REVISION HISTORY                
#
#     Date        Author     Description
#     ----        ------     -----------
#  4. 2006-10-25  Corn       Change license manager location to 2701@holm.
#  3. 2004-04-16  Stoeckley  Change license manager location to 27029@holm.
#  2. 2004-02-25  Stoeckley  Add attempt to filter out Stab printouts.
#  1. 2003-06-13  Stoeckley  Initial version.
#
#-------------------------------------------------------------------------------
#</history_doc>


if($?PATH == 0) then
   setenv PATH /usr/app/SUNWspro/bin
else
   setenv PATH /usr/app/SUNWspro/bin:$PATH
endif

if($?MANPATH == 0) then
   setenv MANPATH /usr/app/SUNWspro/man
   setenv MANPATH /usr/app/SUNWspro/lib:$MANPATH
else
   setenv MANPATH /usr/app/SUNWspro/man:$MANPATH
   setenv MANPATH /usr/app/SUNWspro/lib:$MANPATH
endif

#setenv LM_LICENSE_FILE 4570@hotce06
#setenv LM_LICENSE_FILE 27029@holm
setenv LM_LICENSE_FILE 27017@holm

if ($?LD_LIBRARY_PATH == 0) then
   setenv LD_LIBRARY_PATH /usr/app/SUNWspro/lib
else
   setenv LD_LIBRARY_PATH /usr/app/SUNWspro/lib:$LD_LIBRARY_PATH
endif

#purify $*

### Various attempts to filter out the "Stab" comments:

#purify $* |& grep -v 'Stab of unknown type' | fgrep -v -x '' | grep -v 'While processing file'
#purify $* |& egrep -v 'Stab of unknown type | While processing file'
#purify $* |& egrep -v 'Stab of unknown type | While processing file' | fgrep -v -x ""
#purify $* >& junk
#purify $*  |& awk '$1=="Purify" { next }'
#purify $*  |& awk '$4!="Stab" && $2!="Stab" && $0!="" && $3!="While" { printf(" %s\n", $0) } END { printf("\n") }'
#purify $*  |& awk '{ if($1=="Purify") { printf("xxxxxxxxxxxxx %s\n", $1) } else { printf("yyyyyyyyyyyyy %s\n", $0) } }'
#purify $*  |& awk '{ if($4!="Stab" && $2!="Stab" && $0!="" && $3!="While" && $0!=".") { printf("%s\n", $0) } \
#                           else { printf(".") } } }'
#purify $*  |& awk '{ if($4!="Stab" && $2!="Stab" && $0!="" && $3!="While" && substr($0,0,1)!=".") { printf("%s\n", $0) } \
#                        else { if(substr($0,0,1)==".") { printf(" %s",$0) } } }'
#purify $*  |& awk '{ if($4!="Stab" && $2!="Stab" && $0!="" && $3!="While" && substr($0,0,1)!=".") { printf("%s\n", $0) } \
#                        else { if(substr($0,0,1)==".") { printf(" %s",$0) } } }'
#purify $*  |& awk '{ if($4=="Stab" || $2=="Stab" || $3=="While" || substr($0,0,1)==".") { printf("%s", substr($0,0,1)) } \
#                        else { if(NF>0) { printf("%s\n", $0) } } }'

purify $*  |& awk '{ if($4!="Stab" && $2!="Stab" && $0!="" && $3!="While" && $0!=".") { printf("%s\n", $0) } \
                        else { if($0==".") { printf(".") } } }'

