#! /bin/csh -f

# check_rcs_files_everywhere
#
# $Id: check_rcs_files_everywhere,v 1.1 2004/05/25 22:01:40 spws Exp spws $
#
# Run this script to check the RCS files in all of the ~spws directories.
#
# Simply type this:
#
#                    check_rcs_files_everywhere  option
#
# where  <option>  (optional) specifies which files should be listed.
#
#     option   files listed
#     ------   ------------
#       -1     not checked in or not checked out.
#       -2     not checked in, not checked out, or not matching.
#       -3     not checked in, not checked out, matching, or not matching.
#
# Option -2 is used for any other option (or unspecified option).
#
# This script verifies that all checked-out files are the same as the latest
# versions of files in the RCS directories.
#
# The output of this script goes to standard out and to a log file.
# The log file will be in ~spws/making.
# If the user is not spws, the log file will be in the user's home directory.
#
# The environment variables SPWSDIR and SPWSMAKEDIR must be set.

#-------------------------------------------------------------------------------

if($?SPWSDIR == 0 || $SPWSDIR == "") then
     echo SPWSDIR not set
     exit
endif

if($?SPWSMAKEDIR == 0 || $SPWSMAKEDIR == "") then
     echo SPWSMAKEDIR not set
     exit
endif

set option = $1

$SPWSMAKEDIR/private_rcs_everywhere check_rcs_files $option

#-------------------------------------------------------------------------------

