#! /bin/sh
# Make some zero offset data to examine headers

######Work in km (synlv puts 10^3 in header fields)######
#  ref="1:1,2;4,2"      reflector(s):  "amplitude:x1,z1;x2,z2;x3,z3;..."
REF="1.0:0.0,1.0;5.0,1.0"

nt=750 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing

dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # P-wave velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF verbose=0 | surange

exit
		               
