#! /bin/sh
# Make some zero offset data to examine plot defaults in slow direction

###########################################################################
# Here set fxm = dxm (not equal 0), then susynlv takes care of the x-plot
# settings.

REF="1.0:0.0,1.0;5.0,1.0"
nt=751 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing
dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
supsimage perc=99 title="nxm=101 fxm=0.05 dxm=0.05" \
	label1="Time (sec)" label2="Distance (km)" >label1.eps

###########################################################################
# Now insist that first midpoint is at 0, then susynlv sets tr.f2
# to 0.0, which means that as far as SU is concerned, this field is
# NOT set at all!  This means that supsimage gets to set f2 and it
# picks the value 1 (tracr from the first trace), so we get the
# "wrong" labeling in x.

REF="1.0:0.0,1.0;5.0,1.0"
nt=751 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=101 fxm=0.0 dxm=0.05   # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing
dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
supsimage perc=99 title="change fxm=0.0, note bad x ticks"\
	label1="Time (sec)" label2="Distance (km)" >label2.eps

###########################################################################
# Again take first midpoint at 0, but use a getpar to supsimage to
# guarantee the right x labeling in supsimage.

REF="1.0:0.0,1.0;5.0,1.0"
nt=751 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=101 fxm=0.0 dxm=0.05   # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing
dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
supsimage perc=99 title="same, but getpar f2=0 in supsimage"\
	label1="Time (sec)" label2="Distance (km)"\
	f2=0 >label3.eps
###########################################################################

echo 
echo "Output PostScript files:  label1.eps label2.eps label3.eps"
echo 
echo "You may view these with your PostScript Previewer"

exit
