#! /bin/sh
# Make some zero offset data to examine plot defaults in slow direction
WIDTH=540
HEIGHT=800
XOFF1=0
XOFF2=535
XOFF3=1070
YOFF=150
WIDTH=420
HEIGHT=700
XOFF1=0
XOFF2=430
XOFF3=860
YOFF=150

###########################################################################
# Here set fxm = dxm (not equal 0), then susynlv takes care of the x-plot
# settings.

REF="1.0:0.0,1.0;5.0,1.0"
nt=751 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing
dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="nxm=101 fxm=0.05 dxm=0.05" windowtitle="Good Ticks"\
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF1} ybox=${YOFF} &

###########################################################################
# Now insist that first midpoint is at 0, then susynlv sets tr.f2
# to 0.0, which means that as far as SU is concerned, this field is
# NOT set at all!  This means that suximage gets to set f2 and it
# picks the value 1 (tracr from the first trace), so we get the
# "wrong" labeling in x.

REF="1.0:0.0,1.0;5.0,1.0"
nt=751 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=101 fxm=0.0 dxm=0.05   # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing
dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="change fxm=0.0, note bad x ticks" \
	windowtitle="Bad Ticks" \
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF2} ybox=${YOFF} &

###########################################################################
# Again take first midpoint at 0, but use a getpar to suximage to
# guarantee the right x labeling in suximage.

REF="1.0:0.0,1.0;5.0,1.0"
nt=751 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=101 fxm=0.0 dxm=0.05   # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing
dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="now getpar f2=0 in suximage" \
	windowtitle="Forced Ticks" \
	label1="Time (sec)" label2="Distance (km)" \
	f2=0 \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF3} ybox=${YOFF} &

###########################################################################
exit 0
