#! /bin/sh
# Zero offset sections

WIDTH=300
HEIGHT=400
XOFF1=0
XOFF2=315
XOFF3=630
XOFF4=945
YOFF1=50
YOFF2=500

# Flat model and data
nx=101 fx=0 dx=0.05
nz=101 fz=0 dz=0.04
unif2 <model00deg ninf=2 nx=$nx nz=$nz dx=$dx dz=$dz \
	v00=1.0,1.0 method=linear |
ximage  perc=99 title="Flat Model" windowtitle="Flat Model"\
	label1="Depth (km)" label2="Distance (km)" \
	 n1=$nz f1=$fz d1=$dz  n2=$nx f2=$fx d2=$dx \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF1} ybox=${YOFF1} &

######Work in km (synlv puts 10^3 in header fields)######
#  ref="1:1,2;4,2"      reflector(s):  "amplitude:x1,z1;x2,z2;x3,z3;..."
REF="1.0:0.0,1.0;5.0,1.0"

nt=750 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing

dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # P-wave velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="Zero Dip Backscatter" windowtitle="Flat Data"\
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF2} ybox=${YOFF1} &

#################################################################
# Twenty degree model and data
nx=101 fx=0 dx=0.05
nz=101 fz=0 dz=0.04
unif2 <model20deg ninf=2 nx=$nx nz=$nz dx=$dx dz=$dz \
	v00=1.0,1.0 method=linear |
ximage  perc=99 title="20 degree Model" windowtitle="20 Model"\
	label1="Depth (km)" label2="Distance (km)" \
	 n1=$nz f1=$fz d1=$dz  n2=$nx f2=$fx d2=$dx \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF3} ybox=${YOFF1} &

######Work in km (synlv puts 10^3 in header fields)######
#  ref="1:1,2;4,2"      reflector(s):  "amplitude:x1,z1;x2,z2;x3,z3;..."
REF="1.0:0.0,1.0;5.0,1.81985"

nt=750 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing

dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # P-wave velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="20 degree Backscatter" windowtitle="20 Data"\
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF4} ybox=${YOFF1} &

#################################################################
# Forty degree model and data
nx=101 fx=0 dx=0.05
nz=101 fz=0 dz=0.04
unif2 <model40deg ninf=2 nx=$nx nz=$nz dx=$dx dz=$dz \
	v00=1.0,1.0 method=linear |
ximage  perc=99 title="40 degree Model" windowtitle="40 Model"\
	label1="Depth (km)" label2="Distance (km)" \
	 n1=$nz f1=$fz d1=$dz  n2=$nx f2=$fx d2=$dx \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF1} ybox=${YOFF2} &

######Work in km (synlv puts 10^3 in header fields)######
#  ref="1:1,2;4,2"      reflector(s):  "amplitude:x1,z1;x2,z2;x3,z3;..."
REF="1.0:0.0,1.0;5.0,4.1955"

nt=750 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing

dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # P-wave velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="40 degree Backscatter" windowtitle="40 Data"\
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF2} ybox=${YOFF2} &

#################################################################
# Sixty degree model and data
nx=101 fx=0 dx=0.05
nz=101 fz=0 dz=0.04
unif2 <model60deg ninf=2 nx=$nx nz=$nz dx=$dx dz=$dz \
	v00=1.0,1.0 method=linear |
ximage  perc=99 title="60 degree Model" windowtitle="60 Model"\
	label1="Depth (km)" label2="Distance (km)" \
	 n1=$nz f1=$fz d1=$dz  n2=$nx f2=$fx d2=$dx \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF3} ybox=${YOFF2} &

######Work in km (synlv puts 10^3 in header fields)######
#  ref="1:1,2;4,2"      reflector(s):  "amplitude:x1,z1;x2,z2;x3,z3;..."
REF="1.0:0.0,1.0;5.0,8.66025"

nt=750 ft=0.0 dt=0.008     # time information: number, first, spacing
nxm=100 fxm=0.05 dxm=0.05  # midpoint information: number, first, spacing
nxo=1 fxo= dxo=            # offset information: number, first, spacing

dvdz=0.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=2.0     # P-wave velocity at surface in km/s
ob=1        # include obliquity (both sides of interface are reflecting)
er=1        # use exploding reflector amps
smooth=0    # connect picks on reflectors linearly

susynlv	nt=$nt ft=$ft dt=$dt \
	nxo=$nxo fxo=$fxo dxo=$dxo \
	nxm=$nxm fxm=$fxm dxm=$dxm \
	v00=$v00 dvdx=$dvdx dvdz=$dvdz \
	ob=$ob er=$er smooth=$smooth  \
	ref=$REF |
suximage perc=99 title="60 degree Backscatter" windowtitle="60 Data"\
	label1="Time (sec)" label2="Distance (km)" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${XOFF4} ybox=${YOFF2} &

exit
