amode=1         # anisotropic run
vmax=5823.      # maximum velocity in grid
vmin=1768.      # minimum velocity in grid
nx=231          # number of grid points in x-direction
nz=231          # number of grid points in z-direction
nt=250          # number of time steps
dx=17.5         # grid spacing in x-direction
dz=17.5         # grid spacing in z-direction
dt=0.004        # time sample increment in time sections
dtsnap=0.02     # time increment between snapshots
sntyp=0,1,2,3   # four snapshot types (P, S, UX, UZ)
sflag=2         # Ricker wavelet
fmax=50.        # max. frequency of Ricker wavelet
iabso=1         # use absorbing boundaries
abso=0.07       # damping parameter for absorbing boundaries
nbwx=20         # width of absorbing boundaries (x-direction)
nbwz=20         # width of absorbing boundaries (z-direction)
irz=50,50,50,50 # depths of receiver lines
rxtyp=0,1,2,3   # types of receivers (P, S, UX, UZ)
isx=115         # horizontal grid point index of source
isz=80          # vertical grid point index of source
styp=3          # source type (FZ)
samp=1.         # amplitude of source
