#! /bin/sh

nt=250 indexdt=0 dt=0.001   time=0.25   

## THE MODEL:  
nx=100 nz=100 dx=5.0 dz=5.0 

## THE SOURCE:
fpeak=30 
sx=50 sz=10

# source=1 means that it is a point source
source=1 

# Source information (index=direction of source)
indexux=0 indexuy=0 indexuz=1 wavelet=2

# impulse is 1 is a single source
impulse=1 

## THE RECEIVERS:
receiverdepth=20

## OUTPUT (using suheaders on seismograms): 
suhead=1
reflxfile=xreflectionx  reflyfile=yreflectiony  reflzfile=zreflectionz
afile= cfile= ffile= lfile= nfile=
vspxfile=  vspzfile=

## THE NUMERICAL METHOD:
# Order of numercal method
order=4
eta=0.015
eta0=0.012


# Coordinates to start/stop using FCT (in gridpoints)
fctxbeg=0 fctxend=100 fctzbeg=0 fctzend=100

# isurf=1 means that we have an absorbing boundary at the top as well
isurf=1 

# using FCT
dofct=1 

# Using moving boundaries
movebc=1 
mbx1=10
mbx2=900
mbz1=10
mbz2=90


# The files are:
# cfile - c33
# lfile - c44
# afile - c11
# nfile - c66
# ffile - c13


suximage < zreflectionz \
        labelsize=28 label1="Time (s) " label2="Surface coord. (m) "  \
        wbox=500 hbox=500 xbox=50 ybox=50 \
        perc=99.5 \
        titlesize=36 title="Vertical component of horizontal section." &

suximage < xreflectionx \
        labelsize=28 label1="Time (s) " label2="Surface coord. (m) "  \
        wbox=500 hbox=500 xbox=500 ybox=50 \
        perc=99.5 \
        titlesize=36 title="Radial component of horizontal section." &

exit 0
