 
################ makefile.depend ##################
 
############## fortran dependencies ###############
 
 
################ xml dependencies #################
 
 
############# c and c++ dependencies ##############
 

ccell.o:					\
		ccell.c

chrtine.o:					\
		chrtine.c			\
		c2f_interface.h

timedate.o:					\
		timedate.c
 
################ end dependencies #################
 
