#! /bin/sh

suspike nspk=1  ix1=32 it1=32 nt=64 ntr=64 > junk.spk

suximage title="Spike Data" wbox=400 hbox=400 < junk.spk &

suk1k2filter < junk.spk |
suximage title="Filtered Spike data" wbox=400 hbox=400 xbox=660 &

suk1k2filter < junk.spk | suspeck1k2 |
suximage title="Filter" ybox=500 xbox=660 wbox=400 hbox=400 &

exit 0

