#! /bin/sh
# Run cwell with CWP X Graphics

demo=3
MACHINE=keller
USER="-l jkc"

# If NEXTFILE is empty string (eg. comment off), display with image on NeXT
NEXTFILE="~jkc/Images/CWELL/demo${demo}graph.eps"

if [ -z "$NEXTFILE" ]
then
	remoteCommand="images"
else
	remoteCommand="cat >$NEXTFILE"
fi


x1beg=0 x1end=6500 x2beg=-100 x2end=10000

cwell |
cshotplot >demo${demo}plot  outpar=demo${demo}par

psgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 600x400+650-70 \
	title="Model, Source Well and Receiver Well" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end |
rsh $MACHINE $USER $remoteCommand
