 
################ makefile.depend ##################
 
############## fortran dependencies ###############
 
 
################ xml dependencies #################
 
 
############# c and c++ dependencies ##############
 

rmod.o:					\
		rmod.c			\
		cprim.h			\
		c2f_interface.h			\
		c2f_interface.h
 
################ end dependencies #################
 
