#! /bin/sh

#### 2D prestack migration of spike data
##
# create spike data at (768,640), 1 shot gather
suimp2d nt=512 nshot=1 nrec=200 dgx=8 dsx=8 x0=640 z0=768 c=2000 |
sukfilter k=.001,.002,.3,.4 amps=0,1,1,0 > 1shot_spike.su

# model data
suximage < 1shot_spike.su title="1 shotgather data " \
xbox=10 ybox=10 wbox=350 hbox=350 &

# K-domain representation
suspeck1k2 < 1shot_spike.su |
suximage x1beg=-.8 x2beg=-.8 x2end=.8 x1end=.8 \
xbox=400 ybox=10 wbox=350 hbox=350 \
legend=1 cmap=hsv4 \
title="K-domain representation 1 shotgather data" &

## make data with 10 shots
suimp2d nt=512 nshot=10 nrec=200 dgx=8 dsx=160 x0=640 z0=768 c=2000 |
sukfilter k=.001,.002,.3,.4 amps=0,1,1,0 > 10shots_spike.su

# model data
suximage < 10shots_spike.su title="10 shotgathers" \
xbox=10 ybox=400 wbox=350 hbox=350 perc=99&

# K domain aperture
suspeck1k2 < 10shots_spike.su |
suximage x1beg=-2.0 x2beg=-2.0 x2end=2.0 x1end=2.0 \
xbox=400 ybox=400 wbox=350 hbox=350 \
legend=1 cmap=hsv4 \
title="K-domain aperture 10 shotgathers" &


exit 0
