/*<license>
 -------------------------------------------------------------------------------
  Copyright (c) 2007 ConocoPhillips Company
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 -------------------------------------------------------------------------------
 </license>*/
"#################  Version widget information       ##################",
"Cbyt*version_2_3_revision_2.labelString:\
-----------------------------------------------\\n\
Please contact Bill Menger bill.menger@gmail.com\\n\
to request new options, report bugs, or to get user assistance.",
"################# End of version widget information ##################",
"*background: lightgray",
"*foreground: black",
"Cbyt*Mbar.spacing:    10",
"*fontList: -*-*-*-r-normal-*-*-120-*-*-p-*-*-*",
"*XmText.marginHeight: 1",
"*XmText.marginWidth: 1",
"*XmDrawingArea.resizePolicy: RESIZE_NONE",
"*gsColors: 127",
"*frameBuffer: False",
"*highlightColor:        red",
"*highlightThickness:        2",
"*zoomLineWidth: 3",
"*zoomLineColor: blue",
"Cbyt*ControlF.width:          595",
"Cbyt*ControlF.height:         670",
"Cbyt.minWidth:                   540",
"Cbyt.minHeight:                  200",
"Cbyt*ControlF.resizePolicy:   RESIZE_NONE",
"Cbyt*XmText.marginHeight:        1",
"*movie.marginBottom:             2",
"*movie.marginTop:                2",
"*bottomShadowColor:              Black",
"*topShadowColor:                 White",
"Cbyt*tlinesep.background:        red",
"Cbyt*Swindow.scrollingPolicy:    AUTOMATIC",
"Cbyt*Stie_win.scrollingPolicy:   AUTOMATIC",
"Cbyt*tlinesep.leftOffset:  -3",
"Cbyt*Stie_win.leftOffset:  -3",
"Cbyt*Swindow.rightOffset:  -3",
"Cbyt*Swindow.topOffset: 5",
"Cbyt*Swindow.leftOffset:  3",
"Cbyt*Swindow.bottomOffset:           5",
"Cbyt*scanform.shadowThickness:       0",
"Cbyt*scanform.leftAttachment:        XmATTACH_FORM",
"Cbyt*scanform.bottomAttachment:      XmATTACH_FORM",
"Cbyt*scanform.leftOffset:            3",
"Cbyt*scanform.bottomOffset:          5",
"Cbyt*scanform*shadowThickness:       0",
"Cbyt*moviel.arrowDirection:          ARROW_LEFT",
"Cbyt*movier.arrowDirection:          ARROW_RIGHT",
"Cbyt*movieform.XmArrowButton.width:  40",
"Cbyt*movieform.XmArrowButton.height: 40",
"Cbyt*movie_scale.orientation:      XmHORIZONTAL",
"Cbyt*movie_scale.titleString:      Movie Control",
"Cbyt*movie_scale.showValue:        TRUE",
"Cbyt*movie_scale.maximum:          10",
"Cbyt*movie_scale.minimum:           1",
"Cbyt*movie_scale.value:             1",
"Cbyt*movie_scale.fontList:       -*-*-bold-r-*--14-*-*-*-*-*-*-1",
"Cbyt*movie_scale.shadowThickness:   2",
"Cbyt*movieform.leftAttachment:      XmATTACH_FORM",
"Cbyt*movieform.bottomAttachment:    XmATTACH_FORM",
"Cbyt*movieform.leftOffset:          3",
"Cbyt*movieform.bottomOffset:        5",
"Cbyt*movieform*shadowThickness:     0",
"Cbyt*color_pop.cancelLabelString:    No",
"Cbyt*color_pop.okLabelString:        Yes",
"Cbyt*scanl.arrowDirection:               ARROW_LEFT",
"Cbyt*scanr.arrowDirection:               ARROW_RIGHT",
"Cbyt*scanform.XmArrowButton.width:       40",
"Cbyt*scanform.XmArrowButton.height:      40",
"Cbyt*scanrL.labelString:                 Scan\\nRight",
"Cbyt*scanlL.labelString:                 Scan\\nLeft",
"Cbyt*scanrL.leftOffset:                  5",
"Cbyt*scanform.XmLabel.fontList:  -*-*-bold-r-*--14-*-*-*-*-*-*-1",
"Cbyt*scanform.XmLabel.marginHeight:      1",
"Cbyt*scanform.XmLabel.marginWidth:       0",
"Cbyt*ginfo_box.labelFontList:    -*-*-bold-r-*-*-*-140-*-*-m-*-*-*",
"Cbyt*bottomrc.orientation:               HORIZONTAL",
"Cbyt*zoom_abort.labelString:             Abort\\nZoom",
"Cbyt*remtline.labelString:               Remove\\nTie\\nLine",
"Cbyt*tllock.labelString:                 Reset\\nTime\\nTie",
"Cbyt*bottomrc*fontList:          -*-*-bold-r-*--14-*-*-*-*-*-*-1",
"Cbyt*zoom_abort.background:              red",
"Cbyt*ginfo_box_popup.title:              Plot Selection Information",
"Cbyt*popmTitle.labelString:              Quick Options",
"Cbyt*tloffset.columns:       12",
"Cbyt*statline*XmText.fontList:   -*-*-bold-r-*--14-*-*-*-*-*-*-1",
"Cbyt*statline*XmText.rows:               2",
"Cbyt*statline*XmText.editMode:           MULTI_LINE_EDIT",
"Cbyt*statline*XmText.editable:           False",
"Cbyt*statline*XmText.traversalOn:        False",
"Cbyt*statline*XmText.highlightOnEnter:   False",
"Cbyt*statline*XmText.highlightThickness: 0",
"Cbyt*statline*XmText.resizable:          False",
"Cbyt*statline.mode_disp.columns:         24",
"Cbyt*statline.mhelp.rightOffset:         3",
"Cbyt*filecas.labelString:       File",
"Cbyt*addfile.labelString:          Setup/Change Plot...",
"Cbyt*tieline.labelString:          Tie Line",
"Cbyt*optioncas.labelString:     Option",
"cbyt*cbar.labelString:             Color Bar...",
"Cbyt*dotdmp.labelString:           Trace Header Dump...",
"Cbyt*dumpscr.labelString:          Dump Plot to file...",
"Cbyt*ginfo.labelString:            Plot Infomation...",
"Cbyt*globals.labelString:          View History File...",
"Cbyt*ovjd.labelString:             Display OVJD marks...",
"Cbyt*xyon.labelString:             Automatic location display",
"Cbyt*tlsepop.labelString:          Tie Adjust",
"Cbyt*slave_plot.labelString:       Remote Plot",
"Cbyt*add_graph.labelString:        Open New Display Window",
"Cbyt*rem_graph.labelString:        Close This Window",
"Cbyt*zoomcas.labelString:       Zoom-Scan",
"Cbyt*zup.labelString:              Zoom Up",
"Cbyt*zdown.labelString:            Zoom Down",
"Cbyt*zorgin.labelString:           Original Size",
"Cbyt*zop.labelString:              Zoom-Scan Options...",
"Cbyt*pickcas.labelString:       Pick",
"Cbyt*mute.labelString:             Mute picking",
"Cbyt*scrs.labelString:             SCRS refraction picking",
"Cbyt*tracepick.labelString:        General trace picking",
"Cbyt*siscpick.labelString:         SISC correlation picking",
"Cbyt*fishpick.labelString:         FISH correlation picking",
"Cbyt*static.labelString:           Static picking",
"Cbyt*model.labelString:            Model picking",
"Cbyt*customcas.labelString:     Customize",
"Cbyt*custom.labelString:           Variable Density Options..",
"Cbyt*unitcas.labelString:          Units",
"Cbyt*metric.labelString:                Metric",
"Cbyt*english.labelString:               English",
"Cbyt*typecas.labelString:          Input Data Type",
"Cbyt*timetype.labelString:              Time",
"Cbyt*depthtype.labelString:             Depth",
"Cbyt*helpcas.labelString:       Help",
"Cbyt*help1.labelString:            Display Context Sensitive Help",
"Cbyt*help2.labelString:            Overview of Cbyt",
"Cbyt*setmhelp.labelString:         Insert/Remove Status Information Line",
"Cbyt*ver_help.labelString:         Show Version",
"Cbyt*endpick.background:        red",
"Cbyt*endpick.labelString:       End\\nPicking",
"Cbyt*muteinfo.labelString:      Mute\\nParam\\nInfo",
"Cbyt*model_ctl.labelString:     Model\\nControl\\nPanel",
"Cbyt*scrs_ctl.labelString:      SCRS\\nControl\\nPanel",
"Cbyt*tracepick_ctl.labelString: Trace\\nPicking\\nControl\\nPanel",
"Cbyt*siscpick_ctl.labelString:  SISC\\nPicking\\nControl\\nPanel",
"Cbyt*fishpick_ctl.labelString:  FISH\\nPicking\\nControl\\nPanel",
"Cbyt*attr.labelString:          Static\\nControl\\nPanel",
"Cbyt*mute.indicatorOn:          False",
"Cbyt*setmhelp.set:              true",
"Cbyt*xyon.set:                  true",
"Cbyt*english.set:               true",
"Cbyt*timetype.set:              true",
"Cbyt*type.radioBehavior:        true",
"Cbyt*secondstype.set:           true",
"Cbyt*units.radioBehavior:       true",
"Cbyt*ovjd_prompt.selectionLabelString:      Enter OVJD velocity:",
"Cbyt*ovjd_prompt.textColumns:               6",
"Cbyt*ovjd_prompt.textString:                5000",
"Cbyt*ovjd_prompt_popup.title:               OVJD value",
"Cbyt*addfile.accelerator:        Meta<Key>A",
"Cbyt*addfile.acceleratorText:    Alt-A",
"Cbyt*tieline.accelerator:        Meta<Key>T",
"Cbyt*tieline.acceleratorText:    Alt-T",
"Cbyt*quit.accelerator:           Meta<Key>Q",
"Cbyt*quit.acceleratorText:       Alt-Q",
"Cbyt*add_graph.accelerator:      Meta<Key>N",
"Cbyt*add_graph.acceleratorText:  Alt-N",
"Cbyt*ginfo.accelerator:          Meta<Key>I",
"Cbyt*ginfo.acceleratorText:      Alt-I",
"Cbyt*ovjd.accelerator:           Meta<Key>J",
"Cbyt*ovjd.acceleratorText:       Alt-J",
"Cbyt*tlsepop.accelerator:        Meta<Key>X",
"Cbyt*tlsepop.acceleratorText:    Alt-X",
"Cbyt*dumpscr.accelerator:        Meta<Key>R",
"Cbyt*dumpscr.acceleratorText:    Alt-R",
"Cbyt*globals.accelerator:        Meta<Key>G",
"Cbyt*globals.acceleratorText:    Alt-G",
"Cbyt*zup.accelerator:            Meta<Key>U",
"Cbyt*zup.acceleratorText:        Alt-U",
"Cbyt*zdown.accelerator:          Meta<Key>D",
"Cbyt*zdown.acceleratorText:      Alt-D",
"Cbyt*zoompop.accelerator:        Meta<Key>Y",
"Cbyt*zoompop.acceleratorText:    Alt-Y",
"Cbyt*zorgin.accelerator:         Meta<Key>S",
"Cbyt*zorgin.acceleratorText:     Alt-S",
"Cbyt*mute.accelerator:           Meta<Key>M",
"Cbyt*mute.acceleratorText:       Alt-M",
"Cbyt*custom.accelerator:         Meta<Key>K",
"Cbyt*custom.acceleratorText:     Alt-K",
"Cbyt*help1.accelerator:          Meta<Key>H",
"Cbyt*help1.acceleratorText:      Alt-H",
"Cbyt*ver_help.accelerator:       Meta<Key>V",
"Cbyt*ver_help.acceleratorText:   Alt-V",
"Cbyt*units.accelerator:          Meta<Key>U",
"Cbyt*units.acceleratorText:      Alt-U",
"Cbyt*filecas.mnemonic:           F",
"Cbyt*zoomcas.mnemonic:           Z",
"Cbyt*optioncas.mnemonic:         O",
"Cbyt*pickcas.mnemonic:           P",
"Cbyt*customcas.mnemonic:         C",
"Cbyt*outrc.XmText.columns:       11",
"Cbyt*outrc.XmText.traversalOn:   false",
"Cbyt*outrc.XmText.editable:      false",
"Cbyt*outrc.orientation:          HORIZONTAL",
"Cbyt*outrc.rightAttachment:      XmATTACH_FORM",
"Cbyt*outrc.rightOffset:          1",
"Cbyt*outrc.bottomAttachment:     XmATTACH_FORM",
"Cbyt*outrc.bottomOffset:         40",
"Cbyt*aout.rightAttachment:       XmATTACH_FORM",
"Cbyt*aout.rightOffset:           5",
"Cbyt*aout.bottomAttachment:      XmATTACH_FORM",
"Cbyt*aout.bottomOffset:          10",
"Cbyt*aout.columns:               23",
"Cbyt*ibox_popup.title:                 Information",
"Cbyt*errbox_popup.title:               ERROR",
"Cbyt*errbox.dialogStyle:               dialog_application_modal",
"Cbyt*q_prompt_popup.title:             Question ?????",
"Cbyt*size_prompt.cancelLabelString:    No",
"Cbyt*size_prompt.okLabelString:        Yes",
"Cbyt*q_prompt.dialogStyle:             dialog_application_modal",
"Cbyt*q_prompt.okLabelString:           Yes",
"Cbyt*q_prompt.cancelLabelString:       No",
"Cbyt*zoompop_popup.title:        Zoom-Scan Options",
"Cbyt*zoompop.width:       400",
"Cbyt*zoompop.height:      600",
"Cbyt*zoompop.resizePolicy:      RESIZE_NONE",
"Cbyt*zoprcframe.shadowThickness:           2",
"Cbyt*zoprcframe.topAttachment: XmATTACH_POSITION",
"Cbyt*zoprcframe.leftAttachment: XmATTACH_POSITION",
"Cbyt*zoompop.XmLabel.leftAttachment: XmATTACH_POSITION",
"Cbyt*zoprcframe.leftPosition:     20",
"Cbyt*zoprcframe.topPosition:      10",
"Cbyt*zoprc.radioBehavior:   true",
"Cbyt*zpointer.set:   true",
"Cbyt*zopL.leftPosition:       40",
"Cbyt*zopL.bottomOffset:       10",
"Cbyt*zopL.labelString:       Zoom Options",
"Cbyt*zpointer.labelString:   Zoom by pointer selection",
"Cbyt*zbox.labelString:       Zoom by area",
"Cbyt*zs_sep.topAttachment: XmATTACH_POSITION",
"Cbyt*zs_sep.leftAttachment: XmATTACH_FORM",
"Cbyt*zs_sep.leftOffset: 10",
"Cbyt*zs_sep.rightAttachment: XmATTACH_FORM",
"Cbyt*zs_sep.rightOffset: 10",
"Cbyt*zs_sep.topPosition:      50",
"Cbyt*zs_sep.shadowThickness:      2",
"Cbyt*soprcframe.shadowThickness:           2",
"Cbyt*soprcframe.topAttachment: XmATTACH_POSITION",
"Cbyt*soprcframe.leftAttachment: XmATTACH_POSITION",
"Cbyt*soprcframe.leftPosition:     4",
"Cbyt*soprcframe.topPosition:     60",
"Cbyt*sopL.leftPosition:       40",
"Cbyt*sopL.bottomOffset:       10",
"Cbyt*sopL.labelString:       Scan Options",
"Cbyt*scanscreen.labelString:   Scan a Screen",
"Cbyt*orgwhenscan.labelString:  Original Scale",
"Cbyt*numtoscan.columns:                     5",
"Cbyt*numtoscanL.labelString:         Number of Traces\\n to scan",
"Cbyt*numtoscanL.topAttachment: XmATTACH_POSITION",
"Cbyt*numtoscan.topAttachment: XmATTACH_POSITION",
"Cbyt*numtoscanL.leftAttachment: XmATTACH_POSITION",
"Cbyt*numtoscan.leftAttachment: XmATTACH_POSITION",
"Cbyt*numtoscanL.topPosition: 60",
"Cbyt*numtoscan.topPosition: 70",
"Cbyt*numtoscanL.leftPosition: 60",
"Cbyt*numtoscan.leftPosition: 70",
"Cbyt*zoompop.XmScale.topAttachment: XmATTACH_POSITION",
"Cbyt*zoompop.XmScale.leftAttachment: XmATTACH_POSITION",
"Cbyt*zoom_scale.topPosition: 30",
"Cbyt*zoom_scale.leftPosition: 4",
"Cbyt*zoom_scale.orientation: XmHORIZONTAL",
"Cbyt*zoom_scale.showValue: TRUE",
"Cbyt*zoom_scale.maximum: 100",
"Cbyt*zoom_scale.minimum: 20",
"Cbyt*zoom_scale.value: 20",
"Cbyt*zoom_scale.titleString: Select Zoom Factor",
"Cbyt*zoom_scale.decimalPoints:      1",
"Cbyt*box_scale.value: 300",
"Cbyt*box_scale.topPosition: 30",
"Cbyt*box_scale.leftPosition: 50",
"Cbyt*box_scale.orientation: XmHORIZONTAL",
"Cbyt*box_scale.showValue: TRUE",
"Cbyt*box_scale.maximum: 500",
"Cbyt*box_scale.minimum: 50",
"Cbyt*box_scale.titleString: Select Zoom Area size",
"*button_control.shadowThickness:                 0",
"*button_control.rightOffset:                     10",
"*button_control.leftOffset:                      10",
"*button_control.bottomOffset:                    15",
"*button_control.OK.marginLeft:                   10",
"*button_control.OK.marginRight:                  10",
"*button_control.Help.marginLeft:                 7",
"*button_control.Help.marginRight:                7",
"Cbyt*tdmp.width:       585",
"Cbyt*tdmp.height:      420",
"Cbyt*tdmp.resizePolicy:            RESIZE_NONE",
"Cbyt*tdmp_popup.title:        Trace Dump Display",
"Cbyt*tdmp*OK.labelString:     Remove\\nWindow",
"Cbyt*tdmp*Apply.labelString:  Enter\\nTrace Dump ",
"Cbyt*tdmp*Cancel.labelString: Clear\\nand Reset",
"Cbyt*tdmptxt.fontList:                 -*-*-bold-r-*-*-*-140-*-*-m-*-*-*",
"*button_control.Help.leftPosition:               90",
"*button_control.Cancel.leftPosition:             65",
"*button_control.Apply.leftPosition:              30",
"*globalpop_popup.title:                 View History",
"*globalpop.width:                       770",
"*globalpop.height:                      375",
"*globalpop.resizePolicy:                RESIZE_NONE",
"*globalpop.title:                       History",
"*globalpop*globalform.topAttachment:    XmATTACH_FORM",
"*globalpop*globalform.rightAttachment:  XmATTACH_FORM",
"*globalpop*globalform.leftAttachment:   XmATTACH_FORM",
"*globalpop*globalform.topOffset:        15",
"*globalpop*globalform.rightOffset:      30",
"*globalpop*globalform.leftOffset:       15",
"*globalpop*globalform.shadowThickness:  0",
"*globalpop*infile.leftOffset:           10",
"*globalpop*filebutton.labelString:      History File...",
"*globalpop*Fileshell*dirMask:           *.glbl",
"*globalpop*OK.labelString:              View",
"*globalpop*Cancel.labelString:          Remove",
"*glbltxtscr.fontList:                   -*-*-bold-r-*-*-*-140-*-*-m-*-*-*",
"*glbltxtscr.topAttachment:              XmATTACH_FORM",
"*glbltxtscr.topOffset:                  50",
"*pmutepop_popup.title:        Mute Pick Options",
"*pmutepop.width:       585",
"*pmutepop.height:      420",
"*pmutepop.resizePolicy:            RESIZE_NONE",
"*pmutepop*fileform.topAttachment:         XmATTACH_FORM",
"*pmutepop*fileform.rightAttachment:       XmATTACH_FORM",
"*pmutepop*fileform.leftAttachment:        XmATTACH_FORM",
"*pmutepop*fileform.topOffset:           20",
"*pmutepop*fileform.rightOffset:         10",
"*pmutepop*fileform.leftOffset:          15",
"*pmutepop*fileform.shadowThickness:      0",
"*pmutepop*ifil.leftOffset:       10",
"*pmutepop*fbut.labelString:       Mute Input File...",
"*pmutepop*ofilL.labelString:      Mute Output File:",
"*pmutepop*errbox.dialogStyle: dialog_application_modal",
"*pmutepop*userpoint.topAttachment:         XmATTACH_POSITION",
"*pmutepop*userpoint.leftAttachment:        XmATTACH_POSITION",
"*pmutepop*userpoint.topPosition:           27",
"*pmutepop*userpoint.leftPosition:          2",
"*pmutepop*userpoint.labelString:           User Defined Locations",
"*pmutepop*userpoint.shadowThickness:       0",
"*pmutepop*XmRowColumn.orientation:            HORIZONTAL",
"*pmutepop*XmRowColumn.packing:                PACK_COLUMN",
"*pmutepop*XmRowColumn.spacing:                0",
"*pmutepop*XmRowColumn.numColumns:             8",
"*pmutepop*XmText.marginHeight:                1",
"*pmutepop*XmText.columns:                     7",
"*pmutepop.mute_info.topAttachment:            XmATTACH_POSITION",
"*pmutepop.mute_info.leftAttachment:           XmATTACH_POSITION",
"*pmutepop.mute_info.topPosition:              80",
"*pmutepop.mute_info.leftPosition:             3",
"*pmutepop.mute_info.traversalOn:              False",
"*pmutepop.mute_info.highlightOnEnter:         False",
"*pmutepop.mute_info.highlightThickness:       0",
"*pmutepop.mute_info.editable:                 False",
"*pmutepop.terc.topAttachment:      XmATTACH_POSITION",
"*pmutepop.terc.leftAttachment:     XmATTACH_POSITION",
"*pmutepop.terc.topPosition:        35",
"*pmutepop.terc.leftPosition:       2",
"*pmutepop*mpckL.labelString:       Number Of Picks",
"*pmutepop*hwdL.labelString:        Primary Header",
"*pmutepop*hwd2L.labelString:       Secondary Header",
"*pmutepop*minoffL.labelString:     Min Offset",
"*pmutepop*maxoffL.labelString:     Max Offset",
"*pmutepop*mpck.value:                     8",
"*pmutepop*hwd.value:                      17",
"*pmutepop*hwd2.value:                      6",
"*pmutepop*ifil.value:                      NONE",
"*pmutepop*ofil.value:                      mute.pick",
"*pmutepop*minoff.value:                   1.0",
"*pmutepop*maxoff.value:                   2.0",
"*pmutepop*Fileshell*dirMask:                     *.mute",
"Cbyt*mute_infobox_popup.title:              Mute Parameter Information",
"Cbyt*mute_infobox.labelFontList:            -*-*-bold-r-*-*-*-140-*-*-m-*-*-*",
"Cbyt*modpop.resizePolicy:               XmRESIZE_ANY",
"Cbyt*modpop*input_form.resizePolicy:    XmRESIZE_ANY",
"Cbyt*modpop*ctl_form.resizePolicy:      XmRESIZE_ANY",
"*modpop.height:      700",
"*modpop.width:       430",
"*modpop*XmForm.shadowThickness:               0",
"*modpop*hrcframe.topAttachment:          XmATTACH_FORM",
"*modpop*hrcframe.topOffset:              5 ",
"*modpop*hrcframe.leftAttachment:         XmATTACH_FORM",
"*modpop*hrcframe.leftOffset:             20",
"*modpop*hrc.numColumns: 2",
"*modpop*hrc.packing: XmPACK_COLUMN",
"*modpop*ptyprc.packing:                PACK_COLUMN",
"*modpop*ptyprc.numColumns:             1",
"*modpop*ptypL.leftAttachment:          ATTACH_POSITION",
"*modpop*ptypL.leftPosition:            55",
"*modpop*ptypL.topOffset:            12",
"*modpop*XmToggleButton.marginHeight:      0",
"*modpop*addend.set:                       True",
"*modpop*FileChoice.fileExtension:     pck",
"*modpop*Fileshell*dirMask:      *.pck",
"*modpop*ifil.annoType:     pushbutton",
"*modpop*ifil.labelString:  Input Pick File:",
"*modpop*ifil.rightAttachment: XmATTACH_FORM",
"*modpop*ofil.annoType:  label",
"*modpop*ofil.labelString:  Output Pick File:",
"*modpop*ofil.topOffset:  5",
"*modpop*ofil.fileFlags:  IsRequired Writable OverWriteWarn",
"*modpop*ofil.fileDescription: Output pick file",
"*modpop*ifil.fileDescription: Input pick file",
"*modpop*hzctlop*XmLabelGadget.shadowThickness: 0 ",
"*modpop*XmRowColumn*XmLabelGadget.width: 75",
"*modpop*XmRowColumn*XmLabelGadget.alignment: XmALIGNMENT_BEGINNING",
"*modpop*XmRowColumn*alignment: XmALIGNMENT_BEGINNING",
"*modpop*pheadL.labelString:         Prim. Header",
"*modpop*sheadL.labelString:         Sec. Header",
"*modpop*theadL.labelString:         Tert Header",
"*modpop*pcktyp.labelString:         Pick Type...",
"*modpop*horL.labelString:           HORIZON\\n\\/Color",
"*modpop*segL.labelString:           Segment\\ntotal: 5 ",
"*modpop*vbld.labelString:           VBLD",
"*modpop*shft.labelString:           New",
"*modpop*gwsg.labelString:           GWS Generic",
"*modpop*XmRowColumn*XmPushButton.alignment: XmALIGNMENT_BEGINNING",
"*modpop*hzctlop*XmLabel.width:      70",
"*modpop*newhort.labelString:        New   \\nHorizon",
"*modpop*delseg.labelString:         Delete\\nSegment",
"*modpop*delhor.labelString:         Delete\\nHorizon",
"*modpop*endseg.labelString:         End   \\nSegment",
"*modpop*manno.labelString:          Manual\\nNo Snap",
"*modpop*manwith.labelString:        Manual\\nDo Snap",
"*modpop*auto.labelString:           Auto\\nTrack",
"*modpop*peak.labelString:           Peak",
"*modpop*troff.labelString:          Trough",
"*modpop*ptom.labelString:           + to -",
"*modpop*mtop.labelString:           - to +",
"*modpop*vbld.set:                   True",
"*modpop*gwsg.set:                   False",
"*modpop*infobox_popup.title:        Picking Information",
"*modpop*phead.value:                      17",
"*modpop*shead.value:                      0",
"*modpop*thead.value:                      0",
"*modpop*ptypL.labelString:           Picking Options:",
"*modpop*addbeg.labelString:          Add to beg.",
"*modpop*addend.labelString:          Add to end",
"*modpop*movseg.labelString:          Move Seg.",
"*modpop*inspck.labelString:          Insert pick",
"*modpop*shpck.labelString:           Pick info",
"*modpop*edit.labelString:           Select for Edit",
"*modpop*undo.labelString:           Undo xxxxx",
"*modpop*chor_lab.labelString:       Horizon:    NONE",
"*modpop*chor_lab.alignment:         ALIGNMENT_BEGINNING",
"*modpop*chor_lab.topOffset:         12",
"*modpop*msg.leftOffset:              5",
"*modpop*msg.rightOffset:             5",
"*modpop*msg.rows:                    2",
"*modpop*terc.topOffset:              20",
"*modpop*terc.orientation:            HORIZONTAL",
"*modpop*terc.packing:                PACK_COLUMN",
"*modpop*terc.spacing:                0",
"*modpop*terc.numColumns:             3",
"*modpop*XmText.columns:              7",
"*modpop*hor_list.topOffset:          5",
"*modpop*hor_list.bottomOffset:       80",
"*modpop*hor_list.leftPosition:       2",
"*modpop*hor_list.rightPosition:      48",
"*modpop*hor_list.boldLabels:         True",
"*modpop*hor_list.fontList:       -*-*-bold-r-*--14-*-*-*-*-*-*-1",
"*modpop*segscl.showValue:             True",
"*modpop*segscl.maximum:               2",
"*modpop*segscl.minimum:               1",
"*modpop*segscl.orientation:           HORIZONTAL",
"*modpop*segscl.titleString:           Current Segment",
"*modpop*segscl.leftAttachment:        XmATTACH_FORM",
"*modpop*segscl.rightOffset:            5",
"*modpop*segscl.leftOffset:            15",
"*modpop*segscl.topOffset:             20",
"*pattr_pop_popup.title:       Static Control Panel",
"*pstarpop_popup.title:        Stat Pick Options",
"*pstarpop.width:       585",
"*pstarpop.height:      420",
"*pstarpop.resizePolicy:            RESIZE_NONE",
"*pstarpop*fileform.topAttachment:         XmATTACH_FORM",
"*pstarpop*fileform.rightAttachment:       XmATTACH_FORM",
"*pstarpop*fileform.leftAttachment:        XmATTACH_FORM",
"*pstarpop*fileform.topOffset:           20",
"*pstarpop*fileform.rightOffset:         10",
"*pstarpop*fileform.leftOffset:          15",
"*pstarpop*fileform.shadowThickness:      0",
"*pstarpop*ifil.leftOffset:       10",
"*pstarpop*fbut.labelString:       Stat Input File...",
"*pstarpop*ofilL.labelString:      Stat Output File:",
"*pstarpop*errbox.dialogStyle: dialog_application_modal",
"*pstarpop.terc.topAttachment:      XmATTACH_POSITION",
"*pstarpop.terc.topPosition:        35",
"*pstarpop*mhorL.labelString:  Max  Number of Horizons",
"*pstarpop*msexL.labelString:  Max  Number of Sections",
"*pstarpop*hwd1L.labelString:   Primary  Header Word",
"*pstarpop*hwd2L.labelString:  Secondary Header Word",
"*pstarpop.offlab.topAttachment:      XmATTACH_POSITION",
"*pstarpop.offlab.leftAttachment:      XmATTACH_POSITION",
"*pstarpop.offlab.topPosition:        40",
"*pstarpop.offlab.leftPosition:        140",
"*pstarpop.offlab.alignment:        ALIGNMENT_BEGINNING",
"*pstarpop*XmRowColumn.orientation:            HORIZONTAL",
"*pstarpop*XmRowColumn.packing:                PACK_COLUMN",
"*pstarpop*XmRowColumn.spacing:                0",
"*pstarpop*XmRowColumn.numColumns:             4",
"*pstarpop*XmText.marginHeight:                1",
"*pstarpop*XmText.columns:                     7",
"*pstarpop*mpck.value:                     8",
"*pstarpop*hwd.value:                      17",
"*pstarpop*ifil.value:                      NONE",
"*pstarpop*minoff.value:                   1.0",
"*pstarpop*maxoff.value:                   2.0",
"*pstarpop*Fileshell*dirMask:                     *.stat",
"*custompop_popup.title:                   Variable Density Options",
"*custompop.width:                         575",
"*custompop.height:                        580",
"*custompop_popup.minWidth:                560",
"*custompop_popup.minHeight:               580",
"*custompop.resizePolicy:                  RESIZE_NONE",
"*customrc1frame.topAttachment:            XmATTACH_POSITION",
"*customrc1frame.leftAttachment:           XmATTACH_POSITION",
"*customrc1frame.topPosition:              3",
"*customrc1frame.leftPosition:             3",
"*customrc1frame.shadowThickness:          2",
"*customrc1.radioBehavior:                 true",
"*customrc1.XmToggleButton.shadowThickness:0",
"*customrc1*sgray.labelString:             Gray Scale",
"*customrc1*sgray.set:                     true",
"*customrc1*medram.labelString:            Median Ram",
"*customrc1*medram.set:                    false",
"*customrc1*coloropt.labelString:          Color",
"*customrc1*coloropt.set:                  false",
"*customrc2frame.topAttachment:            XmATTACH_POSITION",
"*customrc2frame.leftAttachment:           XmATTACH_POSITION",
"*customrc2frame.topPosition:              3",
"*customrc2frame.leftPosition:             47",
"*customrc2frame.shadowThickness:          2",
"*customrc2.XmToggleButton.shadowThickness:0",
"*customrc2*gradev.labelString:            Grade Vertical",
"*customrc2*gradeh.labelString:            Grade Horizontal",
"*customrc2*gradev.set:                    true",
"*customrc3frame.topAttachment:            XmATTACH_POSITION",
"*customrc3frame.leftAttachment:           XmATTACH_POSITION",
"*customrc3frame.topPosition:              30",
"*customrc3frame.leftPosition:             3",
"*customrc3frame.shadowThickness:          2",
"*customrc3.radioBehavior:                 true",
"*customrc3.XmToggleButton.shadowThickness:0",
"*customrc3*cbar.labelString:              Use File---->",
"*customrc3*pre.labelString:               Use Defined->",
"*customrc3*pre.set:                       false",
"*customrc4frame.topAttachment:            XmATTACH_POSITION",
"*customrc4frame.leftAttachment:           XmATTACH_POSITION",
"*customrc4frame.topPosition:              52",
"*customrc4frame.leftPosition:             3",
"*customrc4frame.shadowThickness:          2",
"*customrc4.radioBehavior:                 true",
"*customrc4.XmToggleButton.shadowThickness:0",
"*customrc4*camp.labelString:              Bar Values",
"*customrc4*vamp.labelString:              Amplitudes->",
"*customrc4*pamp.labelString:              Percentage->",
"*customrc4*pamp.set:                      false",
"*custompop*overlay.topAttachment:         XmATTACH_POSITION",
"*custompop*overlay.leftAttachment:        XmATTACH_POSITION",
"*custompop*overlay.rightAttachment:       XmATTACH_POSITION",
"*custompop*overlay.topPosition:           17",
"*custompop*overlay.leftPosition:          74",
"*custompop*overlay.rightPosition:         80",
"*custompop*overlay.value:                 0",
"*custompop*overlayl.topAttachment:        XmATTACH_POSITION",
"*custompop*overlayl.leftAttachment:       XmATTACH_POSITION",
"*custompop*overlayl.topPosition:          17",
"*custompop*overlayl.leftPosition:         46",
"*custompop*overlayl.labelString:          Overlay Increment",
"*custompop*customsc1.topAttachment:       XmATTACH_POSITION",
"*custompop*customsc1.leftAttachment:      XmATTACH_POSITION",
"*custompop*customsc1.topPosition:         34",
"*custompop*customsc1.leftPosition:        55",
"*custompop*customsc1.orientation:         XmHORIZONTAL",
"*custompop*customsc1.showValue:           TRUE",
"*custompop*customsc1.minimum:             1",
"*custompop*customsc1.maximum:             4",
"*custompop*customsc1.decimalPoints:       0",
"*custompop*customsc2.topAttachment:       XmATTACH_POSITION",
"*custompop*customsc2.leftAttachment:      XmATTACH_POSITION",
"*custompop*customsc2.topPosition:         63",
"*custompop*customsc2.leftPosition:        38",
"*custompop*customsc2.orientation:         XmHORIZONTAL",
"*custompop*customsc2.showValue:           TRUE",
"*custompop*customsc2.minimum:             0",
"*custompop*customsc2.maximum:             100",
"*custompop*customsc2.value:              100",
"*custompop*customsc2.decimalPoints:       0",
"*custompop*customsc3.topAttachment:       XmATTACH_POSITION",
"*custompop*customsc3.leftAttachment:      XmATTACH_POSITION",
"*custompop*customsc3.topPosition:         63",
"*custompop*customsc3.leftPosition:        64",
"*custompop*customsc3.orientation:         XmHORIZONTAL",
"*custompop*customsc3.showValue:           TRUE",
"*custompop*customsc3.minimum:             0",
"*custompop*customsc3.maximum:             100",
"*custompop*customsc3.decimalPoints:       0",
"*custompop*customsc3.value:               100",
"*custompop*customform1.topAttachment:     XmATTACH_POSITION",
"*custompop*customform1.rightAttachment:   XmATTACH_POSITION",
"*custompop*customform1.leftAttachment:    XmATTACH_POSITION",
"*custompop*customform1.topPosition:       30",
"*custompop*customform1.rightPosition:     85",
"*custompop*customform1.leftPosition:      32",
"*custompop*customform1.shadowThickness:   0",
"*custompop*fileb.labelString:             Color File...",
"*custompop*errbox.dialogStyle:            dialog_application_modal",
"*custompop*customform2.topAttachment:     XmATTACH_POSITION",
"*custompop*customform2.leftAttachment:    XmATTACH_POSITION",
"*custompop*customform2.rightAttachment:   XmATTACH_POSITION",
"*custompop*customform2.topPosition:       59",
"*custompop*customform2.leftPosition:      30",
"*custompop*customform2.rightPosition:     85",
"*custompop*customform2.shadowThickness:   0",
"*custompop*vmin.topAttachment:            XmATTACH_POSITION",
"*custompop*vmin.leftAttachment:           XmATTACH_POSITION",
"*custompop*vmin.topPosition:              1",
"*custompop*vmin.leftPosition:             15",
"*custompop*vmax.topAttachment:            XmATTACH_POSITION",
"*custompop*vmax.leftAttachment:           XmATTACH_FORM",
"*custompop*vmax.topPosition:              1",
"*custompop*vmax.leftOffset:               70",
"*custompop*vminl.topAttachment:           XmATTACH_POSITION",
"*custompop*vminl.leftAttachment:          XmATTACH_POSITION",
"*custompop*vminl.topPosition:             1",
"*custompop*vminl.leftPosition:            1",
"*custompop*vminl.labelString:             MIN",
"*custompop*vmaxl.topAttachment:           XmATTACH_POSITION",
"*custompop*vmaxl.leftAttachment:          XmATTACH_POSITION",
"*custompop*vmaxl.topPosition:             1",
"*custompop*vmaxl.leftPosition:            47",
"*custompop*vmaxl.labelString:             MAX",
"*custompop*pnc.value:                     100",
"*custompop*ppc.value:                     100",
"*custompop*XmRowColumn.orientation:       HORIZONTAL",
"*custompop*XmRowColumn.packing:           PACK_COLUMN",
"*custompop*XmRowColumn.spacing:           0",
"*custompop*XmRowColumn.numColumns:        4",
"*custompop*XmText.marginHeight:           1",
"*custompop*XmText.columns:                7",
"*custompop*Fileshell*dirMask:             *.rgb",
"*custompop*custcolor.topAttachment:       XmATTACH_POSITION",
"*custompop*custcolor.leftAttachment:      XmATTACH_POSITION",
"*custompop*custcolor.rightAttachment:     XmATTACH_POSITION",
"*custompop*custcolor.bottomAttachment:    XmATTACH_POSITION",
"*custompop*custcolor.topPosition:         3",
"*custompop*custcolor.leftPosition:        87",
"*custompop*custcolor.rightPosition:       99",
"*custompop*custcolor.bottomPosition:      89",
"*custompop*custcolor.shadowThickness:     2",
"*customtitle1.labelString:                COLOR SELECTION PARAMETERS",
"*customtitle1.topAttachment:              XmATTACH_POSITION",
"*customtitle1.leftAttachment:             XmATTACH_POSITION",
"*customtitle1.topPosition:                23",
"*customtitle1.leftPosition:               20",
"*customtitle2.labelString:                TRACE AMPLITUDE PARAMETERS",
"*customtitle2.topAttachment:              XmATTACH_POSITION",
"*customtitle2.leftAttachment:             XmATTACH_POSITION",
"*customtitle2.topPosition:                45",
"*customtitle2.leftPosition:               20",
"*customlabel1.labelString:                Color Number",
"*customlabel1.topAttachment:              XmATTACH_POSITION",
"*customlabel1.leftAttachment:             XmATTACH_POSITION",
"*customlabel1.topPosition:                37",
"*customlabel1.leftPosition:               32",
"*customlabel2.labelString:                PNC",
"*customlabel2.topAttachment:              XmATTACH_POSITION",
"*customlabel2.leftAttachment:             XmATTACH_POSITION",
"*customlabel2.topPosition:                66",
"*customlabel2.leftPosition:               31",
"*customlabel3.labelString:                PPC",
"*customlabel3.topAttachment:              XmATTACH_POSITION",
"*customlabel3.leftAttachment:             XmATTACH_POSITION",
"*customlabel3.topPosition:                66",
"*customlabel3.leftPosition:               57",
"*customsep1.topAttachment:                XmATTACH_POSITION",
"*customsep1.leftAttachment:               XmATTACH_POSITION",
"*customsep1.rightAttachment:              XmATTACH_POSITION",
"*customsep1.leftPosition:                 1",
"*customsep1.rightPosition:                86",
"*customsep1.topPosition:                  22",
"*customsep1.shadowThickness:              2",
"*customsep2.topAttachment:                XmATTACH_POSITION",
"*customsep2.leftAttachment:               XmATTACH_POSITION",
"*customsep2.rightAttachment:              XmATTACH_POSITION",
"*customsep2.topPosition:                  44",
"*customsep2.leftPosition:                 1",
"*customsep2.rightPosition:                86",
"*customsep2.shadowThickness:              2",
"*customsep3.topAttachment:                XmATTACH_POSITION",
"*customsep3.leftAttachment:               XmATTACH_POSITION",
"*customsep3.rightAttachment:              XmATTACH_POSITION",
"*customsep3.topPosition:                  71",
"*customsep3.leftPosition:                 1",
"*customsep3.rightPosition:                86",
"*customsep3.shadowThickness:              2",
"Cbyt*cbar.accelerator:        Meta<Key>B",
"Cbyt*cbar.acceleratorText:     Alt-B",
"*cbarpop_popup.title:                     Data Color",
"*cbarpop.width:                           175",
"*cbarpop.height:                          660",
"*cbarpop.minWidth:                        140",
"*cbarpop.minHeight:                       400",
"*cbarpop.resizePolicy:                    RESIZE_NONE",
"*cbarpop*cbarcolor.topAttachment:         XmATTACH_POSITION",
"*cbarpop*cbarcolor.leftAttachment:        XmATTACH_POSITION",
"*cbarpop*cbarcolor.rightAttachment:       XmATTACH_POSITION",
"*cbarpop*cbarcolor.bottomAttachment:      XmATTACH_POSITION",
"*cbarpop*cbarcolor.topPosition:           1",
"*cbarpop*cbarcolor.leftPosition:          1",
"*cbarpop*cbarcolor.rightPosition:         99",
"*cbarpop*cbarcolor.bottomPosition:        70",
"*cbarpop*cbarcolor.shadowThickness:       2",
"*cbarpop*cbarsc1.topAttachment:           XmATTACH_POSITION",
"*cbarpop*cbarsc1.leftAttachment:          XmATTACH_FORM",
"*cbarpop*cbarsc1.rightAttachment:         XmATTACH_FORM",
"*cbarpop*cbarsc1.topPosition:             69",
"*cbarpop*cbarsc1.leftOffset:              5",
"*cbarpop*cbarsc1.rightOffset:             5",
"*cbarpop*cbarsc1.titleString:             Intensity",
"*cbarpop*cbarsc1.orientation:             XmHORIZONTAL",
"*cbarpop*cbarsc1.showValue:               TRUE",
"*cbarpop*cbarsc1.minimum:                 1",
"*cbarpop*cbarsc1.maximum:                 20",
"*cbarpop*cbarsc1.value:                   10",
"*cbarpop*cbarsc1.decimalPoints:           1",
"*cbarpop*cbarsc2.topAttachment:           XmATTACH_POSITION",
"*cbarpop*cbarsc2.topPosition:             80",
"*cbarpop*cbarsc2.rightAttachment:         XmATTACH_FORM",
"*cbarpop*cbarsc2.rightOffset:             5",
"*cbarpop*cbarsc2.leftAttachment:          XmATTACH_FORM",
"*cbarpop*cbarsc2.leftOffset:              5",
"*cbarpop*cbarsc2.titleString:             Compression",
"*cbarpop*cbarsc2.orientation:             XmHORIZONTAL",
"*cbarpop*cbarsc2.showValue:               TRUE",
"*cbarpop*cbarsc2.minimum:                 -100",
"*cbarpop*cbarsc2.maximum:                 100",
"*cbarpop*cbarsc2.value:                   0",
"*cbarpop*cbarsc2.decimalPoints:           0",
"*cbarpop*OK.labelString:                  Remove",
"*cbarpop*OK.rightAttachment:              XmATTACH_FORM",
"*cbarpop*OK.leftAttachment:               XmATTACH_FORM",
"*cbarpop*OK.rightOffset:                  5",
"*cbarpop*OK.leftOffset:                   5",
"Cbyt*dtyperc.radioBehavior:                          true",
"Cbyt*dtyperc.topAttachment:                          XmATTACH_POSITION",
"Cbyt*dtyperc.topPosition:              40",
"Cbyt*dtyperc.leftAttachment:                         XmATTACH_POSITION",
"Cbyt*dtyperc.leftPosition:             30",
"Cbyt*dumpfileL.labelString:               Dump file:",
"Cbyt*dumpfile.value:                      x.xwd",
"Cbyt*pixdump.labelString:                 Dump Whole Plot",
"Cbyt*windump.labelString:                 Dump only Visible Data",
"Cbyt*pixdump.set:                         true",
"Cbyt*dumpfileL.topAttachment:                        XmATTACH_POSITION",
"Cbyt*dumpfileL.topPosition:            10",
"Cbyt*dumpfile.rightAttachment:                       XmATTACH_FORM",
"Cbyt*dumpfile.rightOffset:             7",
"Cbyt*dumpfileL.leftAttachment:                       XmATTACH_FORM",
"Cbyt*dumpfileL.leftOffset:             5",
"*dumppop_popup.title:        Dump Options",
"*dumppop.width:       450",
"*dumppop.height:      350",
"Cbyt*dqbox.dialogStyle: dialog_application_modal",
"Cbyt*dqbox.okLabelString:               Yes",
"Cbyt*dqbox.cancelLabelString:           No",
"Cbyt*dqbox_popup.title:                 Question ?????",
"*Popform.width:                              500",
"*Popform.height:                             650",
"*fileinfo_popup.minWidth:                    400",
"*tieline_popup.minWidth:                     400",
"*tieline_popup.minHeight:                    500",
"Cbyt*Popform.resizePolicy:      RESIZE_NONE",
"*fileinfo_popup.title:                       Input File Information",
"*tieline_popup.title:                        Tie Line File Information",
"*Popform.allowOverlap:                       false",
"*Popform.autoUnmanage:                       false",
"*rc1.topPosition:                            18",
"*rc1.leftPosition:                           5",
"*Popform*ntotL.labelString:                  Nplt:",
"*Popform*ntot.value:                     100",
"*Popform*iskpL.labelString:                  Initial Skip:",
"*Popform*iskp.value:                     0",
"*Popform*nskpL.labelString:                  Nskp:",
"*Popform*nskp.value:                     0",
"*Popform*ndoL.labelString:                   Ndo:",
"*Popform*ndo.value:                      1 ",
"*rc2.topPosition:                            18",
"*rc2.leftPosition:                           50",
"*Popform*scanL.labelString:                  scan:",
"*Popform*tmaxL.labelString:                  Tmax:",
"*Popform*tmax.value:                      1.000",
"*Popform*tmin.value:                      0.000",
"*Popform*tminL.labelString:                  Tmin:",
"*Popform*tdecL.labelString:                  Tdec:",
"*Popform*tdec.value:                     1",
"*Popform.rc3.spacing:                        0",
"*Popform.rc3frame.shadowThickness:           2",
"*Popform*rc3*XmToggleButton.shadowThickness: 0",
"*Popform*rp.labelString:                     Reverse Polarity",
"*Popform*ct.labelString:                     ct",
"*Popform*RtoL.labelString:                   Plot Right to Left",
"*Popform*rd.labelString:                     Plot Right to Left",
"*Popform*inverty.labelString:                Invert Plot Y Axis",
"*Popform*norm.labelString:                   Normalize",
"*Popform*norm.set:                           false",
"*rc3frame.topPosition:                       49",
"*rc3frame.leftPosition:                      2",
"*rc4.radioBehavior:                          true",
"*Popform.rc4frame.shadowThickness:           2",
"*rc4.XmToggleButton.shadowThickness:         0",
"*rc4frame.topPosition:                       72",
"*rc4frame.leftPosition:                      2 ",
"*Popform*gs.labelString:                     Variable Density",
"*Popform*wonly.labelString:                  WiGl Only",
"*Popform*wfill.labelString:                  Variable Area",
"*Popform*wfill.set:                          true",
"*Popform*rc5.spacing:                        5",
"*Popform*rc5.topPosition:                    50",
"*Popform*rc5.leftPosition:                   45",
"*Popform*tiL.labelString:                    Traces / Inch:",
"*Popform*ti.value:                           20 ",
"*Popform*isL.labelString:                    Inches / Sec:",
"*Popform*is.value:                           2 ",
"*Popform*ctL.labelString:                    CT:",
"*Popform*ct.value:                           4 ",
"*tieline*rc5.numColumns:                    2",
"*Popform*rc6.spacing:                        5",
"*Popform*rc6.topPosition:                    71",
"*Popform*rc6.leftPosition:                   42",
"*Popform*anno.labelString:                   Annotation...",
"*Popform*scale.labelString:                  Processing...",
"*Popform*max.labelString:                    Maximize",
"*Popform*rc6.numColumns:             2",
"*tieline*rc6.numColumns:             1",
"*f2.shadowThickness:                         0",
"*Popform.f2.rightAttachment:                 XmATTACH_FORM",
"*Popform.f2.leftAttachment:                  XmATTACH_FORM",
"*Popform.f2.rightOffset:                     10",
"*Popform.f2.leftOffset:                      10",
"*f2.topPosition:                             93",
"*f2.ok.leftAttachment:                       XmATTACH_FORM",
"*f2.help.rightAttachment:                    XmATTACH_FORM",
"*Popform.f2.help.leftAttachment:             XmATTACH_NONE",
"*f2.help.leftPosition:                       90",
"*f2.cancel.leftPosition:                     46",
"*f2.leftPosition:        5",
"*Popform*f2.ok.labelString:                  OK",
"*Popform*f2.ok.marginLeft:                   10",
"*Popform*f2.ok.marginRight:                  10",
"*Popform*f2.help.labelString:                Help",
"*Popform*f2.help.marginLeft:                 7",
"*Popform*f2.help.marginRight:                7",
"*Popform*f2.cancel.labelString:              Cancel",
"*f3.shadowThickness:                         0",
"*Popform.f2frame.rightAttachment:                 XmATTACH_FORM",
"*Popform.f2frame.leftAttachment:                  XmATTACH_FORM",
"*f3frame.topPosition:                             84",
"*f3frame.leftPosition:                            38",
"*Popform*f3.mframesL.labelString:            Number Frames:",
"*Popform*f3.mframesL.leftOffset:             5",
"*Popform*f3.movie.shadowThickness:             0",
"Cbyt*Popform*f3.mframes.marginHeight:               1",
"Cbyt*Popform*f3.mframes.value:               10",
"Cbyt*Popform*f3.mframes.columns:                    4",
"Cbyt*Popform*f3.movie.set:                   false",
"*f1.shadowThickness:                         0",
"*f1.topPosition:                             10",
"*f1.rightAttachment:                         XmATTACH_FORM",
"*f1.leftAttachment:                          XmATTACH_FORM",
"*f1.rightOffset:                             5",
"*f1.leftOffset:                              4",
"*f1.filename.rightAttachment:                XmATTACH_FORM",
"*f1.filename.rightOffset:                    20",
"*showf.labelString:                          Filename...",
"*showf.bottomAttachment:                     XmATTACH_FORM",
"*showf.leftAttachment:                      XmATTACH_FORM",
"*f1.showf.leftOffset:                         15",
"*f1.filename.leftOffset:                     10",
"*filename.numColumns:                        50",
"*Sel_title.labelString:                      Data Selection Parameters",
"*Popform.Sel_title.topAttachment:            XmATTACH_NONE",
"*Sel_title.bottomOffset:                     10",
"*Sel_title.leftPosition:                     35",
"*Disp_title.labelString:                     Data Display Parameters",
"*Disp_title.topOffset:                       8",
"*sep.topPosition:                            43",
"*Popform*seplow.topAttachment:               XmATTACH_NONE",
"*Popform*seplow.bottomOffset:                5",
"*Popform.helpout.topAttachment:              XmATTACH_NONE",
"*Popform.helpout.bottomAttachment:           XmATTACH_FORM",
"*Popform.helpout.rightAttachment:            XmATTACH_FORM",
"*Popform.helpout.rightOffset:                5",
"*Popform.helpout.leftOffset:                 5",
"*Popform.helpout.bottomOffset:               3",
"*Popform*defaults.labelString:",
"*Popform*defaults.marginHeight:         0",
"*Popform.defaults.leftOffset:           30",
"*Popform*XmSeparator.leftAttachment:         XmATTACH_FORM",
"*Popform*XmSeparator.rightAttachment:        XmATTACH_FORM",
"*Popform*XmSeparator.rightOffset:            10",
"*Popform*XmSeparator.leftOffset:             10",
"*Disp_title.leftPosition:                    35",
"*Popform*Fileshell.dialogTitle:                 Choose A File",
"*Popform*Fileshell*dirMask:                     *.byt",
"*Popform*topAttachment:                      XmATTACH_POSITION",
"*Popform*leftAttachment:                     XmATTACH_POSITION",
"*Popform*XmRowColumn.orientation:            HORIZONTAL",
"*Popform*XmRowColumn.packing:                PACK_COLUMN",
"*Popform*XmRowColumn.spacing:                0",
"*Popform*XmRowColumn.numColumns:             5",
"Cbyt*Mbar.Popform*XmText.marginHeight:                1",
"#Cbyt*Popform*XmText.columns:                     7",
"Cbyt*Popform.XmRowColumn.XmText.columns:                     7",
"*Popform*errbox.dialogStyle: dialog_application_modal",
"*Popform*errbox_popup.title:                 ERROR",
"*TFIOspec*title                          : Trace File Specification ",
"*TFIOspec*EZHELP.dialogTitle             : Help for Trace File Specification",
"*TFIOspec*marginHeight   : 3",
"*HighlightThickness      : 3",
"*TFIOspec*<FILE>.labelString     : FILE...",
"*TFIOspec*<FILE>.x               : 50",
"*TFIOspec*<FILE>.y               : 40",
"*TFIOspec*<FILE>T.value          : NONE",
"*TFIOspec*<FILE>T.x              : 120",
"*TFIOspec*<FILE>T.y              : 40",
"*TFIOspec*<FILE>T.maxLength      : 64",
"Cbyt*TFIOspec*<FILE>T.columns    : 64",
"*TFIOspec.bulletinb.OK.x                   : 50",
"*TFIOspec.bulletinb.OK.y                   : 390",
"*TFIOspec*HELP.x                 : 320",
"*TFIOspec*HELP.y                 : 390",
"*TFIOspec*CANCEL.x               : 180",
"*TFIOspec*CANCEL.y               : 390",
"*TFIOspec*label0.labelString :   TFIO: FILE SPECIFICATION",
"*TFIOspec*label0.x           :   80",
"*TFIOspec*label0.y           :   5",
"*TFIOspec*label1.labelString :   NDPT  =",
"*TFIOspec*label1.x           :   50",
"*TFIOspec*label1.y           :   75",
"*TFIOspec*label2.labelString :   NBYDP =",
"*TFIOspec*label2.x           :   50",
"*TFIOspec*label2.y           :   105",
"*TFIOspec*label3.labelString :   NHDWD =",
"*TFIOspec*label3.x           :   50",
"*TFIOspec*label3.y           :   135",
"*TFIOspec*label4.labelString :   NBYHD =",
"*TFIOspec*label4.x           :   50",
"*TFIOspec*label4.y           :   165",
"*TFIOspec*text5.value        :   0",
"*TFIOspec*text5.maxLength   :    8",
"*TFIOspec*text5.columns     :    8",
"*TFIOspec*text5.x            :   145",
"*TFIOspec*text5.y            :   75",
"*TFIOspec*text6.value        :   1",
"*TFIOspec*text6.maxLength   :    8",
"*TFIOspec*text6.columns     :    8",
"*TFIOspec*text6.x            :   145",
"*TFIOspec*text6.y            :   105",
"*TFIOspec*text7.value        :   0",
"*TFIOspec*text7.maxLength   :    8",
"*TFIOspec*text7.columns     :    8",
"*TFIOspec*text7.x            :   145",
"*TFIOspec*text7.y            :   135",
"*TFIOspec*text8.value        :   1",
"*TFIOspec*text8.maxLength   :    8",
"*TFIOspec*text8.columns     :    8",
"*TFIOspec*text8.x            :   145",
"*TFIOspec*text8.y            :   165",
"*TFIOspec*label9.labelString :   NBYCLL =",
"*TFIOspec*label9.x           :   245",
"*TFIOspec*label9.y           :   75",
"*TFIOspec*label10.labelString:   NTRCLL =",
"*TFIOspec*label10.x          :   245",
"*TFIOspec*label10.y          :   105",
"*TFIOspec*label11.labelString:   GRECSIZ =",
"*TFIOspec*label11.x          :   245",
"*TFIOspec*label11.y          :   135",
"*TFIOspec*text12.value       :   512",
"*TFIOspec*text12.maxLength   :   10",
"*TFIOspec*text12.columns     :   10",
"*TFIOspec*text12.x           :   335",
"*TFIOspec*text12.y           :   75",
"*TFIOspec*text13.value       :   1",
"*TFIOspec*text13.maxLength   :   10",
"*TFIOspec*text13.columns     :   10",
"*TFIOspec*text13.x           :   335",
"*TFIOspec*text13.y           :   105",
"*TFIOspec*text14.value       :   1024",
"*TFIOspec*text14.maxLength   :   10",
"*TFIOspec*text14.columns     :   10",
"*TFIOspec*text14.x           :   335",
"*TFIOspec*text14.y           :   135",
"*TFIOspec*label15.labelString:   TFIO: TRACE ATTRIBUTES",
"*TFIOspec*label15.x          :   80",
"*TFIOspec*label15.y          :   210",
"*TFIOspec*label16.labelString:   Sample Rate  =",
"*TFIOspec*label16.x          :   50",
"*TFIOspec*label16.y          :   240",
"*TFIOspec*label17.labelString:   Starting Time=",
"*TFIOspec*label17.x          :   50",
"*TFIOspec*label17.y          :   270",
"*TFIOspec*label18.labelString:   File Type = ",
"*TFIOspec*label18.x          :   460",
"*TFIOspec*label18.y          :   75",
"*TFIOspec*text19.value       :   .004",
"*TFIOspec*text19.maxLength   :   10",
"*TFIOspec*text19.columns     :   10",
"*TFIOspec*text19.x           :   200",
"*TFIOspec*text19.y           :   240",
"*TFIOspec*text20.value       :   0",
"*TFIOspec*text20.maxLength   :   10",
"*TFIOspec*text20.columns     :   10",
"*TFIOspec*text20.x           :   200",
"*TFIOspec*text20.y           :   270",
"*TFIOspec*text21.value       :   ?????",
"*TFIOspec*text21.maxLength   :   6",
"*TFIOspec*text21.columns     :   6",
"*TFIOspec*text21.x           :   565",
"*TFIOspec*text21.y           :   75 ",
"*TFIOspec*lntr.labelString   :  NTRFIL =",
"*TFIOspec*lntr.x             :  245",
"*TFIOspec*lntr.y             :  165",
"*TFIOspec*ntrfil.value       :   0",
"*TFIOspec*ntrfil.maxLength   :   10",
"*TFIOspec*ntrfil.columns     :   10",
"*TFIOspec*ntrfil.x           :   335",
"*TFIOspec*ntrfil.y           :   165",
"Cbyt*Popform*Plotlabels*leftAttachment:XmATTACH_FORM",
"Cbyt*Popform*Plotlabels*rightAttachment:XmATTACH_NONE",
"Cbyt*Popform*Plotlabels*topAttachment:	XmATTACH_FORM",
"*PlotLabels*title:   Plot Annotation",
"*PlotLabels*EZHELP.dialogTitle  :   Help for Plot Annotation",
"*PlotLabels*lab1.labelString:   Primary Timing Lines",
"*PlotLabels*lab1.leftOffset          :   5",
"*PlotLabels*lab1.topOffset          :   50",
"*PlotLabels*ptl.value       :   1.0",
"*PlotLabels*ptl.maxLength   :   9",
"Cbyt*Popform*PlotLabels*ptl.columns     :   9",
"*PlotLabels*ptl.leftOffset           :   210",
"*PlotLabels*ptl.topOffset           :   50",
"*PlotLabels*lab2.labelString:   Secondary Timing Lines",
"*PlotLabels*lab2.leftOffset          :   5",
"*PlotLabels*lab2.topOffset          :   90",
"*PlotLabels*stl.value       :   0.2",
"*PlotLabels*stl.maxLength   :   9",
"Cbyt*Popform*PlotLabels*stl.columns     :   9",
"*PlotLabels*stl.leftOffset           :   210",
"*PlotLabels*stl.topOffset           :   90",
"*PlotLabels*lab3.labelString:   First Header=",
"*PlotLabels*lab3.leftOffset          :   5",
"*PlotLabels*lab3.topOffset          :   130",
"*PlotLabels*hdrwrd.value    :   1",
"*PlotLabels*hdrwrd.maxLength:   3",
"Cbyt*Popform*PlotLabels*hdrwrd.columns  :   3",
"*PlotLabels*hdrwrd.leftOffset        :   210 ",
"*PlotLabels*hdrwrd.topOffset        :   130 ",
"*PlotLabels*lab6.labelString:   Second Header=",
"*PlotLabels*lab6.leftOffset          :   325",
"*PlotLabels*lab6.topOffset          :   130",
"*PlotLabels*hdrwrdTwo.value    :   1",
"*PlotLabels*hdrwrdTwo.maxLength:   3",
"Cbyt*Popform*PlotLabels*hdrwrdTwo.columns  :   3",
"*PlotLabels*hdrwrdTwo.leftOffset        :   470",
"*PlotLabels*hdrwrdTwo.topOffset        :   130",
"*PlotLabels*lab4.labelString:   Starting trace=",
"*PlotLabels*lab4.leftOffset          :   325",
"*PlotLabels*lab4.topOffset          :   50",
"*PlotLabels*first.value     :   1",
"*PlotLabels*first.maxLength :   6",
"Cbyt*Popform*PlotLabels*first.columns   :   6",
"*PlotLabels*first.leftOffset         :   470",
"*PlotLabels*first.topOffset         :   50",
"*PlotLabels*lab5.labelString:   Trace Increment=",
"*PlotLabels*lab5.leftOffset          :   325",
"*PlotLabels*lab5.topOffset          :   90",
"*PlotLabels*tinc.value      :   20",
"*PlotLabels*tinc.maxLength  :   6",
"Cbyt*Popform*PlotLabels*tinc.columns    :   6",
"*PlotLabels*tinc.leftOffset         :   470",
"*PlotLabels*tinc.topOffset          :   90",
"*PlotLabels*lab7.labelString:	Plot Title=",
"*PlotLabels*lab7.leftOffset:	5",
"*PlotLabels*lab7.topOffset:		20",
"*PlotLabels*plabel.value:  ",
"*PlotLabels*plabel.maxLength:	40",
"Cbyt*Popform*PlotLabels*plabel.columns:	40",
"*PlotLabels*plabel.leftOffset:		210",
"*PlotLabels*plabel.topOffset:		20",
"Cbyt*PlotLabels*bulletinb.height: 250",
"Cbyt*PlotLabels*OK.bottomAttachment:	XmATTACH_FORM",
"Cbyt*PlotLabels*OK.topAttachment:	XmATTACH_NONE",
"Cbyt*PlotLabels*OK.leftAttachment:	XmATTACH_FORM",
"Cbyt*PlotLabels*OK.rightAttachment:	XmATTACH_NONE",
"Cbyt*PlotLabels*CANCEL.bottomAttachment:XmATTACH_FORM",
"Cbyt*PlotLabels*CANCEL.topAttachment:	XmATTACH_NONE",
"Cbyt*PlotLabels*CANCEL.leftAttachment:	XmATTACH_POSITION",
"Cbyt*PlotLabels*CANCEL.leftPosition:	45",
"Cbyt*PlotLabels*HELP.bottomAttachment:	XmATTACH_FORM",
"Cbyt*PlotLabels*HELP.topAttachment:	XmATTACH_NONE",
"Cbyt*PlotLabels*HELP.rightAttachment:	XmATTACH_FORM",
"Cbyt*PlotLabels*HELP.leftAttachment:	XmATTACH_NONE",
"Cbyt*xcfe*xcfesep.topAttachment: XmATTACH_NONE",
"Cbyt*xcfe*edofcw.topAttachment: XmATTACH_NONE",
"Cbyt*xcfe*setup.topAttachment: XmATTACH_NONE",
"*xcfe*XmList.translations :  #override \\n\
 <KeyPress>Return   : ListKbdBeginSelect() \\n\
 <KeyRelease>Return : ListKbdEndSelect()",
"*xcfehelpPath: /u/pospsva/spws/cfe/modules",
"*xcfe.BULL0.width: 680",
"*xcfe.BULL0.height: 540",
"*ezlis2.selectionPolicy: XmSINGLE_SELECT",
"*ezlis1.SLLP_title.labelString: XCFE MENU",
"*ezlis1*SLLP_list.itemCount: 0",
"*ezlis1*SLLP_list.visibleItemCount: 10",
"*ezlis1*SLLP_list.highlightColor: red",
"*ezlis1*SLLP_list.borderWidth: 2",
"*ezlis1*SLLP_list.borderColor: wheat",
"Cbyt*ezlis1*XmText.topAttachment: XmATTACH_NONE",
"Cbyt*ezlis1*XmSeparator.topAttachment: XmATTACH_NONE",
"*ezlis2.itemCount: 0",
"*ezlis2.visibleItemCount: 10",
"*ezlis2.highlightColor: red",
"*ezlis2.scrollBarDisplayPolicy: XmSTATIC",
"*ezlis2SW.highlightColor: red",
"*ezlis2SW.borderWidth: 2",
"*ezlis2SW.borderColor: wheat",
"*BULL0*rc1.radioBehavior:       True",
"*BULL0*rc1.leftOffset: 16",
"*BULL0*rc1.topOffset: 110",
"*BULL0*rc1.orientation: XmHORIZONTAL",
"*BULL0*rc1.numColumns:  6",
"*BULL0*rc1.packing:     XmPACK_COLUMN",
"*BULL0*rc2.radioBehavior:       True",
"*BULL0*rc2.orientation: XmHORIZONTAL",
"*BULL0*rc2.numColumns:  6",
"*BULL0*rc2.packing:     XmPACK_COLUMN",
"*xcfe.BULL0.OK.leftAttachment: XmATTACH_FORM",
"*xcfe.BULL0.OK.leftOffset: 10",
"*BULL0.OK.marginLeft:   10",
"*BULL0.OK.marginRight:  10",
"*xcfe.BULL0.OK.rightAttachment: XmATTACH_NONE",
"Cbyt*xcfe.BULL0.OK.topAttachment: XmATTACH_NONE",
"*xcfe.BULL0.OK.bottomAttachment: XmATTACH_FORM",
"*xcfe.BULL0.OK.bottomOffset: 15",
"*xcfe.BULL0.OK.labelString:  OK",
"*xcfe.BULL0.HELP.leftAttachment: XmATTACH_NONE",
"*xcfe.BULL0.HELP.rightAttachment: XmATTACH_FORM",
"*xcfe.BULL0.HELP.rightOffset: 10",
"*xcfe.BULL0.HELP.labelString: Help",
"Cbyt*xcfe.BULL0.HELP.topAttachment: XmATTACH_NONE",
"*xcfe.BULL0.HELP.bottomAttachment: XmATTACH_FORM",
"*xcfe.BULL0.HELP.bottomOffset: 15",
" ",
"*XmToggleButton.selectColor: wheat",
"*Banner.leftOffset:  100 ",
"*Banner.topOffset:  10",
"*Banner.labelString:	XCFE: BUILD A PROCESSING STREAM",
"*Topics.leftOffset:  16",
"*Topics.topOffset:  55",
"*Topics.labelString:	SELECTION\\nTOPICS   ",
"*Selection.leftOffset: 150",
"*Selection.topOffset: 70",
"*Selection.labelString:	CHOICES",
"*Mode.leftOffset:  360",
"*Mode.topOffset:  55",
"*Mode.labelString:	SELECTION\\nBEHAVIOR ",
"*Selected.labelString:	JOB    \\nSTREAM",
"*All.sensitive:		True",
"*IO.sensitive:		True",
"*Filters.sensitive:	True",
"*Amplitudes.sensitive:	True",
"*Synthetics.sensitive:  True",
"*setup.set: True",
"*dobatch.leftOffset:  300",
"*dobatch.topOffset:  365",
"*dobatch.labelString: Interactive Processing ",
"*dobatch.set: True",
"*dobatch.sensitive:  True",
"*BULL0*XmRowColumn.orientation: XmHorizontal",
"Cbyt*xcfe.BULL0*jobbat.labelString: Set Job Params...",
"Cbyt*xcfe.BULL0*jobbld.labelString: Build  Job File",
"Cbyt*xcfe.BULL0*jobsub.labelString: Submit Job File",
"Cbyt*xcfe.BULL0*jobcus.labelString: Customize Job",
"Cbyt*xcfe.BULL0.edofcw*Fileshell*dirMask:    *.cinf",
" ",
" ",
"*XmText.marginWidth : 1",
"*XmText.marginHeight : 1",
"*XmText.highlightColor : red",
"*XmPushButton.highlightColor : red",
"*XmLabel.marginWidth : 1",
"*XmLabel.marginHeight : 1",
" ",
"*XmText.navigationType : XmTAB_GROUP",
"*XmDrawingArea.navigationType : XmTAB_GROUP",
"*XmPushButton.navigationType : XmTAB_GROUP",
"*XmBulletinBoard.traversalOn : True",
"*XmDrawingArea.traversalOn : True",
"*XmText.traversalOn : True",
"*XmPushButton.traversalOn : True",
"*XmText.translations :  #override \\n\
 Meta Ctrl<KeyPress>Left  : beginning-of-line() \\n\
 Meta Ctrl<KeyPress>Right : end-of-line()",
" ",
"*bulletinb*XmText.rubberPositioning : False",
"*bulletinb*XmText.leftAttachment : XmATTACH_FORM",
"*bulletinb*XmLabel.leftAttachment : XmATTACH_FORM",
"*bulletinb*XmPushButton.leftAttachment : XmATTACH_FORM",
"*bulletinb*XmDrawingArea.leftAttachment : XmATTACH_FORM",
"*bulletinb*XmText.topAttachment : XmATTACH_FORM",
"*bulletinb*XmLabel.topAttachment : XmATTACH_FORM",
"*bulletinb*XmPushButton.topAttachment : XmATTACH_FORM",
"*bulletinb*XmDrawingArea.topAttachment : XmATTACH_FORM",
"*bulletinb*XmForm.leftAttachment : XmATTACH_FORM",
"*bulletinb*XmForm.leftAttachment : XmATTACH_FORM",
"*bulletinb*XmForm.topAttachment : XmATTACH_FORM",
"*bulletinb*XmForm.bottomAttachment : XmATTACH_FORM",
"*bulletinb*XmForm.rightAttachment : XmATTACH_FORM",
"*bulletinb*FileChoice.leftAttachment : XmATTACH_FORM",
"*bulletinb*FileChoice.topAttachment : XmATTACH_FORM",
"*bulletinb*FileChoice.rightAttachment : XmATTACH_FORM",
"*bulletinb*SESE.topOffset :  336",
"*bulletinb*PREV.topOffset :  336",
"*bulletinb*NEXT.topOffset :  336",
"*bulletinb*HELP.topOffset :  336",
" ",
"*bulletinb*SESE.rightAttachment : XmATTACH_NONE",
"*bulletinb*SESE.labelString : OK",
"*bulletinb*PREV.leftAttachment : XmATTACH_POSITION",
"*bulletinb*PREV.leftPosition : 25",
"*bulletinb*PREV.rightAttachment : XmATTACH_NONE",
"*bulletinb*PREV.labelString : PREVIOUS",
"*bulletinb*NEXT.rightAttachment : XmATTACH_POSITION",
"*bulletinb*NEXT.rightPosition : 75",
"*bulletinb*NEXT.leftAttachment : XmATTACH_NONE",
"*bulletinb*NEXT.labelString : NEXT",
"*bulletinb*HELP.rightAttachment : XmATTACH_FORM",
"*bulletinb*HELP.leftAttachment : XmATTACH_NONE",
"*bulletinb*HELP.labelString : HELP",
"*PlotLabels*XmText.marginWidth : 1",
"*PlotLabels*XmText.marginHeight : 1",
"*PlotLabels*XmText.highlightColor : red",
"*PlotLabels*XmPushButton.highlightColor : red",
"*PlotLabels*XmLabel.marginWidth : 1",
"*PlotLabels*XmLabel.marginHeight : 1",
"*PlotLabels*XmText.navigationType : XmTAB_GROUP",
"*PlotLabels*XmDrawingArea.navigationType : XmTAB_GROUP",
"*PlotLabels*XmPushButton.navigationType : XmTAB_GROUP",
"*PlotLabels*XmBulletinBoard.traversalOn : True",
"*PlotLabels*XmDrawingArea.traversalOn : True",
"*PlotLabels*XmText.traversalOn : True",
"*PlotLabels*XmPushButton.traversalOn : True",
"*PlotLabels*XmText.translations :  #override \\n\
 Meta Ctrl<KeyPress>Left  : beginning-of-line() \\n\
 Meta Ctrl<KeyPress>Right : end-of-line()",
"*XmText.translations: #override\\n\
       <Key>osfDelete:     delete-previous-character()\\n\
       <Key>F1:            Help()\\n\
       <Key>KP_F1:         Help()",
"Cbyt*autohelp*button_control.OK.labelString:            Remove",
"Cbyt*autohelp.paned.topOffset:            5",
"Cbyt*autohelp.paned.leftOffset:           5",
"Cbyt*autohelp.paned.rightOffset:          5",
"Cbyt*autohelp.paned.sashWidth: 80",
"Cbyt*autohelp.paned.spacing: 20",
"Cbyt*scrtext.height: 150",
"Cbyt*autohelp.width:       580",
"Cbyt*autohelp.height:      300",
"################## refpick.c resources",
"################## tracepick.c resources",
"################## siscpick.c resources",
"################## fishpick.c resources",
"################## (default custom resources are commented out)",
"*work_message.fontList:           8x13bold",
"*info_message.fontList:           8x13bold",
"*action_message.fontList:         8x13bold",
"*filepair_message1.fontList:      8x13bold",
"*filepair_message2.fontList:      8x13bold",
"*filepair_message3.fontList:      8x13bold",
"*static_header*fontList:          8x13bold",
"*refpick1*pair*pattern:        *.cst",
"*tracepick1*pair*pattern:      *.pick",
"*siscpick1*pair*pattern:       *.inc",
"*fishpick1*pair*pattern:       *.fish",
"*errorbox_popup*title:            Error",
"*errorbox_popup*background:       red",
"*errorbox_popup*dialogStyle:      DIALOG_FULL_APPLICATION_MODAL",
"Cbyt*bottom*marginWidth:          8",
"Cbyt*bottom*ok.marginWidth:       17",
"Cbyt*bottom*ok.labelString:       OK",
"Cbyt*bottom*remove.labelString:   Remove",
"Cbyt*bottom*cancel.labelString:   Cancel",
"Cbyt*bottom*update.labelString:   Update",
"Cbyt*bottom*help.labelString:     Help",
"###*picking_line_width:     3        width of drawn lines",
"###*picking_color_work:     blue     color of temporary working message",
"###*picking_color_error;    red      color of error message",
"###*picking_color_curr:     red      color of current picks",
"###*picking_color_orig:     brown    color of original picks (before changes)",
"###*picking_color_prev:     green4   color of picks from previous picks",
"###*picking_color_next:     blue     color of picks from next picks",
"###*picking_color_sel:      orange   color of picks from selected picks",
"###*picking_color_integ:    green4   color of picks from integrated picks",
"###*filepair_color_info:    green4   color of file info message",
"###*filepair_color_error:   red      color of file error message",
"###*filepair_color_action:  blue     color of file action message",
"####################### end",
