/*<license>
 -------------------------------------------------------------------------------
  Copyright (c) 2007 ConocoPhillips Company
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 -------------------------------------------------------------------------------
 </license>*/
"*cvmhelpPath: /u/pospsve/spws/app-defaults/",
"*XmText.fontList : -misc-fixed-medium-r-normal--13-120-75-75-c-80-iso8859-1",
"*XmLabel.fontList : -adobe-times-bold-r-*-*-*-140-100-100-p-100-iso8859-1",
"*XmPushButton.fontList : -adobe-times-bold-r-*-*-*-140-100-100-p-100-iso8859-1",
"CVMEdit*XmPushButton*background: blue",
"*main_form*resizePolicy: RESIZE_NONE",
"*main_form.width: 700",
"*main_form.height: 500",
"*main_form.bacground: red",
"*XmText.marginWidth : 1",
"*XmText.marginHeight : 1",
"*highlightColor : red",
"*XmText.highlightColor : red",
"*XmPushButton.highlightColor : red",
"*XmLabel.marginWidth : 1",
"*XmLabel.marginHeight : 1",
"CVMEdit*mbar*fontList: -adobe-times-bold-r-*-*-*-140-100-100-p-100-iso8859-1",
"CVMEdit*FILE.accelerator:      Meta<Key>F",
"CVMEdit*FILE.mnemonic:         F",
"CVMEdit*OPTION.accelerator:    Meta<Key>O",
"CVMEdit*OPTION.mnemonic:       O",
"CVMEdit*ZOOM.accelerator:      Meta<Key>Z",
"CVMEdit*ZOOM.mnemonic:         Z",
"CVMEdit*PICK.accelerator:      Meta<Key>P",
"CVMEdit*PICK.mnemonic:         P",
"CVMEdit*CUSTOMIZE.accelerator: Meta<Key>C",
"CVMEdit*CUSTOMIZE.mnemonic:    C",
"CVMEdit*MODELING.accelerator: Meta<Key>M",
"CVMEdit*MODELING.mnemonic:    M",
"CVMEdit*FILE.fil4.accelerator:   Meta<Key>S",
"CVMEdit*FILE.fil4.mnemonic:      S",
"CVMEdit*FILE.fil6.accelerator:   Meta<Key>E",
"CVMEdit*FILE.fil6.mnemonic:      E",
"CVMEdit*OPTION.opt6.accelerator: Meta<Key>V",
"CVMEdit*OPTION.opt6.mnemonic:    V",
"CVMEdit*OPTION.opt8.accelerator: Meta<Key>G",
"CVMEdit*OPTION.opt8.mnemonic:    G",
"CVMEdit*main.form.background: blue",
"CVMEdit*main*plot.topAttachment: XMATTACH_FORM",
" ",
"*autohelp.width:                          580",
"*autohelp.height:                         300",
"*autohelp*button_control.OK.leftAttachment: XmATTACH_POSITION",
"*autohelp*button_control.OK.labelString:  Remove",
"*autohelp*button_control.OK.leftPosition: 40",
"*autohelp*button_control.OK.marginLeft:   10",
"*autohelp*button_control.OK.marginRight:  10",
"*autohelp.scrtext.topOffset:              5",
"*autohelp.scrtext.leftOffset:             5",
"*autohelp.scrtext.rightOffset:            5",
"*autohelp*button_control.shadowThickness: 0",
"*autohelp*button_control.topAttachment: XmATTACH_NONE",
"*autohelp*button_control.rightAttachment: XmATTACH_FORM",
"*autohelp*button_control.leftAttachment:  XmATTACH_FORM",
"*autohelp*button_control.rightOffset:     10",
"*autohelp*button_control.leftOffset:      10",
"*autohelp*button_control.bottomAttachment: XmATTACH_FORM",
"*autohelp*button_control.bottomOffset:    15",
" ",
" ",
"*bulletinb.XmText.rubberPositioning : False",
"*bulletinb.XmText.leftAttachment : XmATTACH_FORM",
"*bulletinb.XmLabel.leftAttachment : XmATTACH_FORM",
"*bulletinb.XmPushButton.leftAttachment : XmATTACH_FORM",
"*bulletinb.XmDrawingArea.leftAttachment : XmATTACH_FORM",
"*bulletinb.XmText.topAttachment : XmATTACH_FORM",
"*bulletinb.XmLabel.topAttachment : XmATTACH_FORM",
"*bulletinb.XmPushButton.topAttachment : XmATTACH_FORM",
"*bulletinb.XmDrawingArea.topAttachment : XmATTACH_FORM",
"*bulletinb.XmForm.leftAttachment : XmATTACH_FORM",
"*bulletinb.XmForm.topAttachment : XmATTACH_FORM",
"*bulletinb.XmForm.bottomAttachment : XmATTACH_FORM",
"*bulletinb.XmForm.rightAttachment : XmATTACH_FORM",
"*bulletinb.FileChoice.leftAttachment : XmATTACH_FORM",
"*bulletinb.FileChoice.topAttachment : XmATTACH_FORM",
"*bulletinb.FileChoice.rightAttachment : XmATTACH_FORM",
"*glimits1.XmText.rubberPositioning : False",
"*glimits1.XmText.leftAttachment : XmATTACH_FORM",
"*glimits1.XmLabel.leftAttachment : XmATTACH_FORM",
"*glimits1.XmPushButton.leftAttachment : XmATTACH_FORM",
"*glimits1.XmDrawingArea.leftAttachment : XmATTACH_FORM",
"*glimits1.XmText.topAttachment : XmATTACH_FORM",
"*glimits1.XmLabel.topAttachment : XmATTACH_FORM",
"*glimits1.XmPushButton.topAttachment : XmATTACH_FORM",
"*glimits1.XmDrawingArea.topAttachment : XmATTACH_FORM",
"*glimits1.XmForm.leftAttachment : XmATTACH_FORM",
"*glimits1.XmForm.topOffset: 100",
"*glimits1.XmForm.topAttachment : XmATTACH_FORM",
"*glimits1.XmForm.rightAttachment : XmATTACH_FORM",
"*glimits1.FileChoice.leftAttachment : XmATTACH_FORM",
"*glimits1.FileChoice.topAttachment : XmATTACH_FORM",
"*glimits1.FileChoice.rightAttachment : XmATTACH_FORM",
" ",
"*bulletinb*SESE.rightAttachment : XmATTACH_NONE",
"*bulletinb*SESE.labelString : OK",
"*bulletinb*APP.labelString : APPLY",
"*bulletinb*HELP.rightAttachment : XmATTACH_FORM",
"*bulletinb*HELP.leftAttachment : XmATTACH_NONE",
"*bulletinb*HELP.labelString : HELP",
"*form.autoUnmanage: False",
"*HzEdit_popup.title: Velocity Horizon Editor",
"*StrucEdit_popup.title: Structural Horizon Editor",
" ",
"*mlimits1.title: CVM model limits",
"*mlimits1*scxnam.showValue: False",
"*mlimits1*scxnam.scaleMultiple: 1",
"*mlimits1*scynam.showValue: False",
"*mlimits1*scynam.scaleMultiple: 1",
"*mlimits1*scznam.showValue: False",
"*mlimits1*scznam.scaleMultiple: 1",
" ",
" ",
"*glimits1.title: CVM grid limits",
" ",
"*mlimshell*limits.orientation: XmHorizontal",
"*mlimshell*limits.packing: XmPACK_COLUMN",
"*mlimshell*limits.numColumns: 3",
"*glimshell*limits.orientation: XmHorizontal",
"*glimshell*limits.packing: XmPACK_COLUMN",
"*glimshell*limits.numColumns: 3",
"*gshell*limits.orientation: XmHorizontal",
"*gshell*limits.packing: XmPACK_COLUMN",
"*gshell*limits.numColumns: 3",
"*gshell*savrc.numColumns: 1",
"*gshell*visrc.numColumns: 1",
"*gshell*savrc.packing: XmPACK_COLUMN",
"*gshell*savrc.orientation: XmHorizontal",
"*gshell.form.glimits1.rightAttachment: XmATTACH_FORM",
"*gshell.form.glimits1.leftAttachment: XmATTACH_FORM",
"*gshell.form.ltypo.labelString: Output Grid Word Type:",
"*dispshell*XmRowColumn.orientation: XmHorizontal",
"*savshell*XmRowColumn.orientation: XmHorizontal",
"*opshell.form.width: 300",
"*opshell.form.height: 150",
"*FILE.labelString: File",
"*FILE.fil1.labelString: NewLayerModel...",
"*FILE.fil2.labelString: OpenLayerFile...",
"*FILE.fil3.labelString: SaveAs...",
"*FILE*fil4*labelString: SeismicData...",
"CVMEdit*FILE.fil4.labelString: SeismicData...",
"*FILE.fil5.labelString: Setup SeisGrid",
"*FILE.fil7.labelString: RemotePlot...",
"*FILE.fil8.labelString: HardCopy...",
"*FILE.fil6.labelString: Exit",
"*GridPop*ymax*labelString: zmax",
"*GridPop*ymin*labelString: zmin",
"*OPTION.labelString: Option",
"*OPTION.opt1.labelString: Model Limits...",
"*OPTION.opt2.labelString: Grid Limits...",
"*OPTION.opt3.labelString: Transforms...",
"*OPTION.opt4.labelString: Display CVM...",
"*OPTION.opt5.labelString: CellEdit...",
"*OPTION.opt6.labelString: VelocityEdit...",
"*OPTION.opt7.labelString: StructEdit...",
"*OPTION.opt8.labelString: GridEdit...",
"*OPTION.opt9.labelString: CoordChange...",
"*OPTION.opt10.labelString: Test(Null)",
"*ZOOM.labelString: Zoom",
"*ZOOM.zoom1.labelString: ZoomUp",
"*ZOOM.zoom2.labelString: ZoomDown",
"*ZOOM.zoom3.labelString: ZoomUpSeparate",
"*ZOOM.zoom4.labelString: ZoomNone",
"*PICK.labelString: Pick",
"*PICK.pikmod.labelString: InitPicking...",
"*MODELING.labelString: Modeling",
"*MODELING.mod1.labelString: RayShooting...",
"*MODELING.mod2.labelString: Time-Depth...",
"*CUSTOMIZE.labelString: Customize",
"*CUSTOMIZE.customize.labelString: ColorPanel...",
"*CUSTOMIZE.cbar.labelString: ColorBar...",
"*CUSTOMIZE.addlab.labelString: Add/Modify A Label",
"*CUSTOMIZE.dellab.labelString: Delete All Labels",
"*segedit*XmForm.leftAttachment:   XmATTACH_FORM",
"*segedit*XmForm.rightAttachment:  XmATTACH_FORM",
"*segedit*XmForm.topAttachment:    XmATTACH_FORM",
"*segedit*XmForm.bottomAttachment: XmATTACH_FORM",
"*transf1.title: CVM Transform Data",
"*transf1*EZresno2.labelString : COORDINATE TRANSFORMATIONS",
"*transf1*EZresno2.leftOffset:   50",
"*transf1*EZresno2.topOffset :   42",
"*transf1*EZresno4.leftOffset:   32",
"*transf1*EZresno4.rightOffset:  32",
"*transf1*EZresno4.topOffset:   105",
"*cell1.title: Material IDs and Cell Pointers",
"*cell1*EZresno2.labelString : +++ ASSIGN ROCK/MATERIAL ID TO EACH CELL +++",
"*cell1*EZresno2.leftOffset :   56",
"*cell1*EZresno2.topOffset :   21",
"*cell1*EZresno3.labelString : NUMBER OF COMPUTED CELLS=",
"*cell1*EZresno3.leftOffset :   56",
"*cell1*EZresno3.topOffset :   63",
"*cell1*EZresno4.value :",
"*cell1*EZresno4.maxLength : 2",
"*cell1*EZresno4.columns : 2",
"*cell1*EZresno4.leftOffset :  264",
"*cell1*EZresno4.topOffset :   63",
"*cell1*EZresno4.editable : False",
"*cell1*EZresno5.labelString : X UNITS NAME=",
"*cell1*EZresno5.leftOffset :   56",
"*cell1*EZresno5.topOffset :  105",
"*cell1*EZresno6.value :",
"*cell1*EZresno6.maxLength : 15",
"*cell1*EZresno6.columns : 15",
"*cell1*EZresno6.leftOffset :  168",
"*cell1*EZresno6.topOffset :  105",
"*cell1*EZresno6.editable : False",
"*cell1*EZresno7.labelString : Z UNITS NAME=",
"*cell1*EZresno7.leftOffset :   56",
"*cell1*EZresno7.topOffset :  126",
"*cell1*EZresno8.value :",
"*cell1*EZresno8.maxLength : 15",
"*cell1*EZresno8.columns : 15",
"*cell1*EZresno8.leftOffset :  168",
"*cell1*EZresno8.topOffset :  126",
"*cell1*EZresno8.editable : False",
"*cell1*EZresno10.leftOffset:   50",
"*cell1*EZresno10.rightOffset:  50",
"*cell1*EZresno10.topOffset:  189",
"*queue.optionCount: 3",
"*queue.optionElement_0: paper_A",
"*queue.optionElement_1: paper_B",
"*queue.optionElement_2: hp650_1",
"*queue.value:           paper_B",
"*trace_edit.screenNumber: otherScreen",
"~",
