#! /bin/sh

data=shot_TOPO.data

shot=4000

rec1=`expr $shot - 2000`
rec2=`expr $shot + 2000`

suwind<$data key=sx min=$shot max=$shot |
suwind key=gx min=$rec1 max=$rec2 |
suwind tmin=0 tmax=3.0 |
supswigb f2=-2.0 d2=0.025 label1="Time (s)" label2="Offset (km)" \
	title="Shot $1 from topography" perc=99.2 > data.eps

echo
echo " You may view the file   data.eps  with your PostScript previewer."
