#! /bin/sh
# shell for Kirchhoff Wave Equation Datuming for pre-stack data
#set -v
data=../Make_Data/shot_TOPO.data

echo "This script will take a few minutes on a 2 ghz workstation."

sudatumk2dr<$data par=kz_down.par \
	jpfile=jpfile.rec>kzshot.data
susort<kzshot.data>receiv.data gx sx
sudatumk2ds<receiv.data par=kz_down.par \
	jpfile=jpfile.sor>kzshot1.data
susort<kzshot1.data>shot_DATUM.data sx gx

exit 0
