#! /bin/sh
# 
#set -x
output=model.data

nt=501 dt=0.008 ft=0.0 tmin=0.2 nxs=181 dxs=0.025 fxs=2.75 nxo=181 \
fxo=-2.25 dxo=0.025 fpeak=15 ls=1 dvdx=0.2 dvdz=0.6 \
x0=0.0 z0=0 v00=2

susynlv dt=$dt ft=$ft nxs=$nxs dxs=$dxs fxs=$fxs nxo=$nxo dxo=$dxo \
fxo=$fxo tmin=$tmin dvdx=$dvdx dvdz=$dvdz \
fpeak=$fpeak ls=$ls nt=$nt x0=$x0 z0=$z0 v00=$v00 \
        ref="1:2.5,0.75;3.5,0.75;4.25,1.5" \
        ref="1:3.75,1;4.25,1;4.75,1.866" \
        ref="1:4.39434,1.25;5.60566,1.25" \
        ref="1:5.25,1.866;5.75,1;6.25,1" \
        ref="1:5.75,1.5;6.5,0.75;7.5,0.75">$output
 exit
