#! /bin/sh

flatdata=../Make_Data/model.data
topodata=../Make_Data/shot_TOPO.data
datumeddata=shot_DATUM.data

shot=4000

rec1=`expr $shot - 2000`
rec2=`expr $shot + 2000`

# plot flat data
suwind<$flatdata key=sx min=$shot max=$shot |
suwind key=gx min=$rec1 max=$rec2 |
suwind tmin=0 tmax=3.0 |
suximage legend=1 f2=-2.0 d2=0.025 label1="Time (s)" label2="Offset (km)" \
	title="Shot $shot original data" hbox=600 wbox=300 xbox=650 perc=99.2 &

# plot data with topography
suwind<$datumeddata key=sx min=$shot max=$shot |
suwind key=gx min=$rec1 max=$rec2 |
suwind tmin=0 tmax=3.0 |
suximage legend=1 f2=-2.0 d2=0.025 label1="Time (s)" label2="Offset (km)" \
	title="Shot $shot with datuming" hbox=600 wbox=300 perc=99.2 &

# plot data that has been datumed.
suwind<$topodata key=sx min=$shot max=$shot |
suwind key=gx min=$rec1 max=$rec2 |
suwind tmin=0 tmax=3.0 |
suximage legend=1 f2=-2.0 d2=0.025 label1="Time (s)" label2="Offset (km)" \
	title="Shot $shot original data with topographic effects" hbox=600  wbox=300 xbox=350  perc=99.2 &
