#! /bin/sh
# Invert the data created by CSHOT

recordfile=record

################
cd inversion.dir	# where inversion files are
################

echo "Run time information being stored in file:  $recordfile"
>$recordfile

(


	### Preprocessing
	rm -f DATA1
	cz1in <data1in
	rm -f PTRACES
	cz1

	### Inversion
	cxzco

) > $recordfile 2>&1

sleep 20

### Move record up to demo directory
mv -f $recordfile ..
echo "run time info now in file:  $recordfile"

### Plotting the section
ftnstrip <reflect |
xmovie  n1=151 n2=180 f1=0.0 d1=20 f2=0 d2=20 perc=99 \
	-geometry 560x430+50+570 \
	title="Inversion of simple model" \
	label1="Depth (m)"  label2="Range (m)" &
