#! /bin/sh

p2=6
p1=6
size=64

infile=ffile.dat 
reconfile=recon.dat
mrafile=mra.dat
dfile=d.dat

createf > $infile

mrafxzwt verbose=1 order=4 p2=$p2 p1=$p1 \
	mralevel2=3 mralevel1=3 \
	reconfile=$reconfile n1=$size n2=$size\
	dfile=$dfile recon=0 \
	<$infile >$mrafile
  
psimage n1=$size n2=$size title="Original Model" \
	style=normal\
	< $infile >orig.eps

psimage n1=$size n2=$size title="MRA of the Model" \
	< $mrafile >mra.eps 

psimage n1=$size n2=$size title="Reconstructed Model" style=normal \
	< $reconfile > recon.eps 

psimage n1=$size n2=$size title="Difference" style=normal \
	< $dfile > dif.eps 

echo ""
echo "You may now view the files:  orig.eps, mra.eps, recon.eps dif.eps "
echo "with your PostScript Previewer"

exit 0

