#! /bin/sh
# Investigate data with sugabor to ascertain a time-varying filter
# for sutvband
# Takes too long to be practical
demo=gabor

# Spectrum of raw data
suspecfx <data.su |
supsimage  \
	title="FX spectrum"\
	label1="Freq (Hz)" label2="Offset (km)" >${demo}.1.eps

perc=90
suspecfx <data.su |
supsimage  perc=$perc\
	title="FX spectrum: perc=$perc"\
	label1="Freq (Hz)" label2="Offset (km)" >${demo}.2.eps

supsimage <data.su perc=$perc\
	title="Data perc=$perc"\
	label1="Freq (Hz)" label2="Offset (km)" >${demo}.3.eps

# do trial and error to ascertain band and fmax and let sugabor tell n2
sugabor <data.su band=3 fmax=100 |
supsmovie n1=2000 n2=33 n3=97 perc=99 \
	label1="Time (sec)" label2="Freq (Hz)" >${demo}.4.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0

