/*<license>
 -------------------------------------------------------------------------------
  Copyright (c) 2007 ConocoPhillips Company
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 -------------------------------------------------------------------------------
 </license>*/
"Cbyt*version_3_1.background: red",
"Cbyt*version_3_1.labelString:\
-----------------------------------------------\\n\
Please contact Bill Menger bill.menger@gmail.com\\n\
to request new options, report bugs, or to get user assistance.",
"*fontList: -*-*-bold-r-normal-*-*-120-*-*-p-*-*-*",
"*main_form.resizePolicy:   RESIZE_NONE",
"*main_form.allowOverlap:   False",
"*main_form.width:   550",
"*main_form.height:  650",
"*background: lightgray",
"*foreground:        black",
"*dragInitiatorProtocolStyle:  DRAG_NONE",
"*dragReceiverProtocolStyle:  DRAG_NONE",
"Cbyt*useColorObj: False",
"*XmToggleButton.selectColor: wheat",
"*wboxmessagetext: dark green",
"Cbyt*enableToggleVisual:  False",
"*filecas.labelString:      File",
"*optioncas.labelString:    Option",
"*zoomcas.labelString:      Zoom",
"*headcas.labelString:      Header",
"*toolcas.labelString:      Tools",
"*pickcas.labelString:      Pick",
"*customcas.labelString:    Custom",
"*help.labelString:         Help",
"*addfile.labelString:      Setup/Change Plot...",
"*fileunder.labelString:    Underlay Plot...",
"*tieline.labelString:      Tieline Plot...",
"*tieunder.labelString:     Tieline Underlay Plot...",
"*multifile.labelString:    Multiple Files...",
"*quit.labelString:         Quit",
"*showanno.labelString:     Always Show Annotation ",
"*showover.labelString:     Show Underlay",
"*multi_movie_lock.labelString:  Multi-file Movie Lock",
"*tlsepop.labelString:      Tie Line: Adjust Bar",
"*tlscrlock.labelString:    Tie Line: Lock Scroll Bars",
"*tlshowamp.labelString:    Tie Line: Show Amps ",
"*remtline.labelString:     Tie Line: REMOVE",
"*tlreset.labelString:      Tie Line: Reset time Tie",
"*slave_plot.labelString:   Remote Plot...",
"*add_graph.labelString:    Open New Window...",
"*screens.labelString:      Open New Window on Screen-",
"*add_bw_graph.labelString: Open Wiggle Only Window...",
"*rem_graph.labelString:    Close this Window...",
"*zup.labelString:          Zoom Up",
"*zupsep.labelString:       Zoom Up Separate Window",
"*zdown.labelString:        Zoom Down",
"*zorgin.labelString:       Original Size",
"*zop.labelString:          Zoom-Scan Options...",
"*xyout.labelString:        Customize XY Readout...",
"*allhead.labelString:      All Header Readout...",
"*header_dump.labelString:  Header Dump...",
"*plothead.labelString:     Header Plot",
"*remplothead.labelString:  Remove Header Plot",
"*color.labelString:        Color...",
"*savdef.labelString:       Save Defaults...",
"*resdef.labelString:       Restore Defaults...",
"*sysdef.labelString:       System Defaults",
"*units.labelString:        Units",
"*metric.labelString:       Metric",
"*english.labelString:      English",
"*cbar.labelString:         Color Bar...",
"*ginfo.labelString:        Plot Info...",
"*ovjd.labelString:         Ovjd...",
"*shift.labelString:        Shift Traces...",
"*avast.labelString:        AVA Overlays...",
"*globals.labelString:      View History...",
"*hard_pop.labelString:     Hard Copy Plot...",
"*addlab.labelString:       Add/Modify A Label",
"*delalllab.labelString:    Delete All Labels",
"*vel_estimator.labelString: Velocity Estimator...",
"*file_choice_label_1.labelString: No input file specified",
"*file_choice_label_3.labelString: File not read yet",
"*ctx.labelString:          Context Sensitive Help...",
"*overview.labelString:     Overview Help...",
"*version.labelString:      Help on Version...",
"*mousehelp.labelString:    Show status line",
"*mute_menu.labelString:    Mute\\nPicking",
"*ref_menu.labelString:     Refraction Statics\\nPicking",
"*gen_menu.labelString:     General\\nPicking",
"*sisc_menu.labelString:    SISC\\nPicking",
"*fish_menu.labelString:    FISH\\nPicking",
"*fk_menu.labelString:      FK\\nPicking",
"*cc3d_menu.labelString:    CC3D\\nPicking",
"*tred_menu.labelString:    Trace\\nEditing",
"*end_pick.labelString:     End\\nPicking",
"*vel_end.labelString:      End Velocity\\nEstimator",
"*vel_end.background:       red",
"*seis_pick_end.labelString: End Seismic\\nPick",
"*seis_pick_end.background: red",
"*remtieline_b.labelString: Remove\\nTie Line",
"Cbyt*statline*XmText.fontList:   -*-*-bold-r-*-*-*-100-*-*-*-*-*-*",
"*sp_pop_popup.title:        Setup/Change Plot",
"*sp_under_pop_popup.title:  Underlay Plot",
"*tie_input_popup.title:     Tieline Plot",
"*tie_under_pop_popup.title: Tieline Under Plot",
"*zoomop_popup.title:        Zoom/Scan Options",
"*colorpop_popup.title:      Color Options",
"*addfile.accelerator:         Meta<Key>A",
"*addfile.acceleratorText:     Alt-A",
"*tieline.accelerator:         Meta<Key>T",
"*tieline.acceleratorText:     Alt-T",
"*quit.accelerator:            Meta<Key>Q",
"*quit.acceleratorText:        Alt-Q",
"*zup.accelerator:             Meta<Key>U",
"*zup.acceleratorText:         Alt-U",
"*zdown.accelerator:           Meta<Key>D",
"*zdown.acceleratorText:       Alt-D",
"*zoompop.accelerator:         Meta<Key>Y",
"*zoompop.acceleratorText:     Alt-Y",
"*zorgin.accelerator:          Meta<Key>S",
"*zorgin.acceleratorText:      Alt-S",
"*color.accelerator:           Meta<Key>K",
"*color.acceleratorText:       Alt-K",
" !",
"*cbar.accelerator:            Meta<Key>B",
"*cbar.acceleratorText:        Alt-B",
"*ovjd.accelerator:            Meta<Key>J",
"*ovjd.acceleratorText:        Alt-J",
"*globals.accelerator:         Meta<Key>G",
"*globals.acceleratorText:     Alt-G",
"*addlab.accelerator:          Meta<Key>L",
"*addlab.acceleratorText:      Alt-L",
"*header_dump.accelerator:     Meta<Key>H",
"*header_dump.acceleratorText: Alt-H",
"*filecas.mnemonic:           F",
"*zoomcas.mnemonic:           Z",
"*optioncas.mnemonic:         O",
"*pickcas.mnemonic:           P",
"*customcas.mnemonic:         C",
"*showanno.set:    True",
"*tlsepop.set:     True",
"*tlscrlock.set:   False",
"*tlshowamp.set:   False",
"*mousehelp.set:   True",
"*english.set:     True",
"*metric.set:      False",
"*movie*XmScale.scaleMultiple: 1",
"*header_dump.screenNumber: otherScreen",
"*all_headers_pops.screenNumber: otherScreen",
"*trace_edit.screenNumber: otherScreen",
"cbyt*sp-port:  6060",
"cbyt*sp-host:  hoeplgp01.conocophillips.net",
"*queue.optionCount: 19",
"*queue.optionElement_0:   lo1000_dj1055c",
"*queue.optionElement_1:   lo2007_dj5000",
"*queue.optionElement_2:   lo3020_c36",
"*queue.optionElement_3:   howl3_8103",
"*queue.optionElement_4:   howl8061_60_1",
"*queue.optionElement_5:   howl8061_60_2",
"*queue.optionElement_6:   howl8065_2",
"*queue.optionElement_7:   du3025_c42",
"*queue.optionElement_8:   du3025_c54",
"*queue.optionElement_9:   du3055_c36",
"*queue.optionElement_10:  pr2019_c14",
"*queue.optionElement_11:  pr2019_c42",
"*queue.optionElement_12:  pr2019_dj1055c",
"*queue.optionElement_13:  pr2019_dj2500",
"*queue.optionElement_14:  pr2019_dj755v",
"*queue.optionElement_15:  pr3021_c42",
"*queue.optionElement_16:  pr3021_dj1050c",
"*queue.optionElement_17:  pr3021_dj755",
"*queue.optionElement_18:  pr3037_dj1055c",
"*queue.value:             lo2007_dj5000",
