#! /bin/sh

# Set messages on
set -x

# Demo for supickamp: "verbose=2"
# Modification of Demo "PickData2"

#------------------------------------
# Create an su Data set with :
#
#     32 traces in input file
# tracl=32 tracr=32 offset=400 ns=64 dt=4000
#
#------------------------------------

temp=pickdata.bin

#-------- create data set ---------------------
suplane dip2=3 |sufilter f=10,20,40,50  > $temp

#-------- show testdata -----------------------
suxwigb < $temp  \
	perc=100 hbox=600 wbox=400 \
        d2=1 f2=0 \
        label1="Time (s)" label2="Trace #" &    

#--  Lets try to isolate the flat event using
#--
#--  search window determined by vectors <x_above>
#--  and <t_above> and windowlength parameter <wl>
#--  time sampling within searchwindow is <dt_resamp>
  
supickamp < $temp \
	format=binary d2=1 x2beg=0 verbose=2 \
	dt_resamp=0.001 \
	x_above=0,31 \
	t_above=0.12,0.12 wl=0.01 \
	arg2=tmax arg1=i2 outpar=pick.info |
xgraph 	label1="Time (s)" label2="Trace # " \
	title="Maxima" \
	d1num=0.05 d2num=5 \
	x1beg=0 x1end=0.25 \
	grid1=dot grid2=dot \
	mark=0 marksize=15 linewidth=0 \
	n=32 height=600 width=400 style=seismic &
 
# Exit politely from shell
exit

