#!/bin/csh -v

susorty > tmpfile1
suximage < tmpfile1 legend=1 units=meters cmap=hsv2 \
  wbox=400 hbox=400 title="susorty" &


susorty > tmpfile2
susort < tmpfile2 cdp offset > junk.su
suximage < junk.su legend=1 units=meters cmap=hsv2 \
  wbox=400 hbox=400 title="susorty | susort cdp" &


susorty > tmpfile3 
susort < tmpfile3 cdp offset > junk.su
suximage < junk.su legend=1 units=meters cmap=hsv2 \
  wbox=400 hbox=400 title="susorty | susort cdp offset" &

exit 0
