# Makefile for ...src/prop/local/Cwell

include $(CWPROOT)/src/Makefile.config

LFLAGS= $(PRELFLAGS) -L$L -lpar -lcwp -lm $(POSTLFLAGS)


CPROGS	=	$B/cshotplot
PROGS	=	$B/cwell

LIB = libcwell.a

ALTARCH =			\
		shoot.o		\
		interp.o	\
		chkcst.o	\
		raydat.o	\
		misc.o		\
		splines.o	\
		bisect.o	\
		hwsrc.o 	\
		graphics.o


INSTALL:	$(LIB) $(PROGS) $(CPROGS)
	@touch $@


$(PROGS):	$(FTARGET) $(LIB)
	$(FC) $(FFLAGS) $(@F).f -o $@ $(LIB)
	@chmod 755 $@
	@echo installing $(@F) in $B


$(CPROGS):      $(CTARGET)
	-$(CC) $(CFLAGS) $(@F).c $(LFLAGS) -o $@
	@chmod 755 $@
	@echo installing $(@F) in $B


$(LIB)	:	$(ALTARCH)
	$(AR) $(ARFLAGS) $(LIB) $(ALTARCH)
	$(RANLIB) $(LIB)
	@-rm *.o

remake:
	@-rm *.a *.o
	@-touch *.c *.f INSTALL
	$(MAKE)

clean	:
	rm -f *junk* *.a *.o cwell? INSTALL
