#! /bin/sh
# Run CSHOT with CWP X Graphics

demo=13

x1beg=0 x1end=9000 x2beg=-3500 x2end=13000

cp param1.1 param1
cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par  \
	-geometry 400x250+700+0 \
	title="Primary Rays" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &
cshot2
suaddhead <demo${demo}traces ftn=1 ns=751 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Primaries (agc)" \
	xbox=50 ybox=75 \
	wbox=300 hbox=430 \
	label1="Time in Seconds" label2="Trace" &

cp param1.2 param1
cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 400x250+700+350 \
	title="Primaries+01+12" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &
cshot2
suaddhead <demo${demo}traces ftn=1 ns=751 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Primaries+01+12 (agc)" \
	xbox=50 ybox=570 \
	wbox=300 hbox=430 \
	label1="Time in Seconds" label2="Trace" &

cp param1.3 param1
cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 400x250+700+700 \
	title="Primaries+01+12+23" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &
cshot2
suaddhead <demo${demo}traces ftn=1 ns=751 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Primaries+01+12+23 (agc)" \
	xbox=370 ybox=320 \
	wbox=300 hbox=430 \
	label1="Time in Seconds" label2="Trace" &
