#! /bin/sh
# shell for viewing data using X-windows graphics

HEIGHT=300
WIDTH=300
XOFF1=0
YOFF1=0
XOFF2=450
YOFF2=450


# plot velocity profile
suximage < data.seis -geometry 400x400+0+0 \
	label1="time (s)" label2="Midpoint (m)" \
	wbox=$WIDTH hbox=$HEIGHT \
	xbox=$XOFF1 ybox=$YOFF1 \
	title="Input Data" &

suximage < data.divcor -geometry 400x400+0+500 \
	label1="time (s)" label2="Midpoint (m)" \
	wbox=$WIDTH hbox=$HEIGHT \
	xbox=$XOFF2 ybox=$YOFF1 \
	title="Conventional Divergence Corr." &


exit 0
