/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cpseis_util_CpseisBase */

#ifndef _Included_org_cpseis_util_CpseisBase
#define _Included_org_cpseis_util_CpseisBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_cpseis_util_CpseisBase_nativeCreate
  (JNIEnv *, jobject);

/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cpseis_util_CpseisBase_nativeDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativeUpdate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cpseis_util_CpseisBase_nativeUpdate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativeWrapup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cpseis_util_CpseisBase_nativeWrapup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativePutTrace
 * Signature: (JI[D[F)V
 */
JNIEXPORT void JNICALL Java_org_cpseis_util_CpseisBase_nativePutTrace
  (JNIEnv *, jobject, jlong, jint, jdoubleArray, jfloatArray);

/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativeGetTrace
 * Signature: (JI[D[F)V
 */
JNIEXPORT void JNICALL Java_org_cpseis_util_CpseisBase_nativeGetTrace
  (JNIEnv *, jobject, jlong, jint, jdoubleArray, jfloatArray);

/*
 * Class:     org_cpseis_util_CpseisBase
 * Method:    nativeExecute
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_cpseis_util_CpseisBase_nativeExecute
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
