#! /bin/sh

# generate screen images and PostScript Hardcopy files

# Finite difference migration
suximage < fd.seismic.su wbox=750 hbox=550 perc=99 title="FD Migration" f2=0 &

supsimage < fd.seismic.su width=7.5 hbox=5.5 perc=99 title="FD Migration" f2=0 > fd.seismic.ps

# Fourier finite difference
suximage < ffd.seismic.su wbox=750 hbox=550 perc=99 title="FFD Migration" f2=0 &

supsimage < ffd.seismic.su width=7.5 hbox=5.5 perc=99 title="FFD Migration" f2=0 > ffd.seismic.ps

# Split Step 
suximage < split.seismic.su wbox=750 hbox=550 perc=99 title="SPLIT Migration" f2=0 &

supsimage < split.seismic.su width=7.5 hbox=5.5 perc=99 title="SPLIT Migration" f2=0 > split.seismic.ps

# Phase shift plus interpolation
suximage < pspi.seismic.su wbox=750 hbox=550 perc=99 title="PSPI Migration" f2=0 &

supsimage < pspi.seismic.su width=7.5 hbox=5.5 perc=99 title="PSPI Migration" f2=0 > pspi.seismic.ps

# Gaussian Beam Kirchhoff 
suximage < gb.seismic.su wbox=750 hbox=550 perc=99 title="GB Migration" f2=0 &

supsimage < gb.seismic.su width=7.5 hbox=5.5 perc=99 title="GB Migration" f2=0 > gb.seismic.ps


exit 0

