#! /bin/sh
#### Create Figure 21 in the GBmod documentation
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL PSdemo
#------------------------------------------------


data=../../datadir/
modelfile=${data}model.data

##### Generate Zero-offset section

nangle=131 fangle=-65 langle=65
nt=151 dt=0.025 bw=0 ft=0.0 prim=1

#### create zero offset section
triseis <$modelfile  xs=0,4 zs=0,0 xg=0,4 zg=0,0 \
        nangle=$nangle fangle=$fangle langle=$langle \
        kreflect=3 krecord=1 fpeak=8 lscale=0.5 \
        ns=101 fs=0 ds=0.04 dgds=1 bw=$bw prim=$prim \
        ng=1 fg=0 dg=0 nt=$nt dt=$dt ft=$ft reftrans=1|
pswigb  n1=151 d1=$dt f1=$ft x1end=3.5 \
        n2=101 d2=0.04 f2=0 grid1=none \
        perc=100 xcur=3.0 title="Zero-offset (only reflected rays)" \
        hbox=4 wbox=6 label1="Time (sec)" \
        label2="Midpoint (km)" |$PSPREVIEWER

exit 0
