#! /bin/sh


zcat marmhard.dat.gz | a2b n1=1 > marmhard.bin

ximage n1=122 n2=384 < marmhard.bin  \
xbox=10 ybox=20 wbox=768 hbox=244 \
legend=1 title="Marmousi model" &

smooth2 n1=122 n2=384 r1=5 r2=5 < marmhard.bin > marmsmooth.bin

ximage n1=122 n2=384 < marmsmooth.bin \
xbox=10 ybox=350 wbox=768 hbox=244 \
legend=1 title="smoothed Marmousi" &

exit 0
