# Master makefile for ./su

include $(CWPROOT)/src/Makefile.config

INSTALL:
	cd amplitudes ; $(MAKE)
	cd attributes_parameter_estimation ; $(MAKE)
	cd convolution_correlation ; $(MAKE)
	cd data_compression ; $(MAKE)
	cd data_conversion ; $(MAKE)
	cd datuming ; $(MAKE)
	cd decon_shaping ; $(MAKE)
	cd dip_moveout ; $(MAKE)
	cd filters ; $(MAKE)
	cd headers ; $(MAKE)
	cd interp_extrap ; $(MAKE)
	cd migration_inversion ; $(MAKE)
	cd multicomponent ; $(MAKE)
	cd noise ; $(MAKE)
	cd operations ; $(MAKE)
	cd picking ; $(MAKE)
	cd stacking ; $(MAKE)
	cd statics ; $(MAKE)
	cd stretching_moveout_resamp ; $(MAKE)
	cd supromax ; $(MAKE)
	cd synthetics_waveforms_testpatterns ; $(MAKE)
	cd tapering ; $(MAKE)
	cd transforms ; $(MAKE)
	cd velocity_analysis ; $(MAKE)
	cd well_logs ; $(MAKE)
	cd windowing_sorting_muting ; $(MAKE)

remake:
	cd amplitudes ; $(MAKE) remake
	cd attributes_parameter_estimation ; $(MAKE) remake
	cd convolution_correlation ; $(MAKE) remake
	cd data_compression ; $(MAKE) remake
	cd data_conversion ; $(MAKE) remake
	cd datuming ; $(MAKE) remake
	cd decon_shaping ; $(MAKE) remake
	cd dip_moveout ; $(MAKE) remake
	cd filters ; $(MAKE) remake
	cd headers ; $(MAKE) remake
	cd interp_extrap ; $(MAKE) remake
	cd migration_inversion ; $(MAKE) remake
	cd multicomponent ; $(MAKE) remake
	cd noise ; $(MAKE) remake
	cd operations ; $(MAKE) remake
	cd picking ; $(MAKE) remake
	cd stacking ; $(MAKE) remake
	cd statics ; $(MAKE) remake
	cd stretching_moveout_resamp ; $(MAKE) remake
	cd supromax ; $(MAKE) remake
	cd synthetics_waveforms_testpatterns ; $(MAKE) remake
	cd tapering ; $(MAKE) remake
	cd transforms ; $(MAKE) remake
	cd velocity_analysis ; $(MAKE) remake
	cd well_logs ; $(MAKE) remake
	cd windowing_sorting_muting ; $(MAKE) remake

remake:
