#! /bin/sh
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------


data=../../datadir
rayendsfile=${data}/rayends.data


#### generate and plot common shot record
gbbeam<$rayendsfile \
        bw=0 xg=0,8 zg=0,0 ng=101 lscale=0.8 \
	krecord=1 nt=251 dt=0.032 ft=0 |
xwigb   xbox=670 ybox=660 perc=100 xcur=3.0 \
        n1=251 d1=0.032 f1=0 hbox=300 wbox=650\
        n2=101 d2=0.08 f2=0 title="Common Shot Seismograms" \
        label1="Time (sec)" label2="Distance (km)" grid1=solid &
exit 0
