#! /bin/sh
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------


datadir=../../datadir/
modelfile=${datadir}model.data
rayendsfile=${datadir}rayends.data
rayfile=${datadir}rays.data

nxz=201 nangle=130 

####   shoot the rays
triray <$modelfile >$rayendsfile xs=3.0 zs=0 \
	rayfile=$rayfile nxz=$nxz krecord=1 \
       	nangle=$nangle fangle=-60 langle=0 \
        refseq=3,1 refseq=1,-1 
xgraph <$rayfile -geom 650x300+670+330 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=4 x2beg=0 x2end=8 style=seismic linecolor=7 \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" &

exit 0
