#! /bin/sh
#DEMO for program covAdap
set -x

model=model10Layers
trend=model10LayersInitial
mode=C
dz=0.01
targetbeg=1.00
targetend=1.08
window=0.08
verbose=1

time    covAdap				\
	model=$model			\
	trend=$trend			\
	mode=$mode			\
	dz=$dz				\
	targetbeg=$targetbeg		\
	targetend=$targetend		\
	window=$window			\
	verbose=$verbose
