#! /bin/sh
#DEMO for logBlock
set -x

logLAS=logExample
lmedian=30
mincontrast=5
ncols=5
columns=1,2,5,3
verbose=0
output=blockedLog

logBlock logLAS=$logLAS \
	lmedian=$lmedian \
	mincontrast=$mincontrast \
	ncols=$ncols \
	columns=$columns \
	verbose=$verbose > $output
