#! /bin/sh
# view model in the file "model"

# Plot the model
nx=100 fx=0 dx=80
nz=110 fz=0 dz=50
unif2 <model ninf=4 nx=$nx nz=$nz dx=$dx dz=$dz \
	v00=5000.0,6000.0,8000.0,10000.0,15000.0 |
psimage n1=$nz f1=$fz d1=$dz n2=$nx f2=$fx d2=$dx >model.eps

echo 
echo "Output is PostScript file:   model.eps"
echo 
echo "You may view it with your PostScript Previewer"

exit
