#! /bin/sh
# do and display nmo and stack

# Do NMO
sunmo <modeldata par=stkvel.p >nmodata

# Display NMO
suwind <nmodata key=sx s=1400 j=250 |
sugain tpow=2 gpow=0.5 |
supsimage label1="Time" label2="Gather" \
	title="Every 5th Shot Record After NMO" \
	f2=1 d2=0.078125 f2num=1 d2num=5  >nmo.eps

# Sort to CDP's and stack
susort <nmodata |
sustack normpow=1.0 >stackdata

# Display Stack (cdps from 350-4600, spacing is 50, full fold from 1450-3500)
sugain <stackdata tpow=2 gpow=0.5 |
supsimage label1="Time" label2="CMP" title="Stack" \
	f2=350 d2=50 >stack.eps

echo 
echo "Output are PostScript files:   nmo.eps   stack.eps"
echo 
echo "You may view these with your PostScript Previewer"

exit
