#! /bin/sh
WIDTH=300
WIDTHOFF=315
HEIGHT=400
HEIGHTOFF=50

# Plot the entire data set (for debugging, not shown here)
# Note: 64 offsets at nominal unit spacing (tracl), so d2 = 1/64
#suximage <modeldata perc=99 title="Shot Gathers"\
#	label1="Time (sec)" label2="Shot Gather" f2=1 d2=0.015625  \
#	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF ybox=$HEIGHTOFF &

# Plot every fifth shot record (d2=5/64)
suwind <modeldata key=sx s=1400 j=250 |
sugain tpow=2 gpow=0.5 |
suximage label1="Time" label2="Gather" \
	title="Every 5th Shot Record (display gained)" \
	windowtitle="Shots" \
	f2=1 d2=0.078125 f2num=1 d2num=5 legend=1 units="amplitude" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF ybox=$HEIGHTOFF &

exit
