#! /bin/sh
# X windows plot of output

WIDTH=400
HEIGHT=600
WIDTHOFF1=10
HEIGHTOFF1=20

nx=121 nz=51 dx=50 dz=50 fx=0.00 fz=0.00 

ximage <data.v legend=1 \
	n2=$nx n1=$nz d1=$dz d2=$dx f2=$fx  \
	label1="Depth (m)" label2="Midpoint (m)" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF1 \
	title="Velocity" &

