/*<license>
 -------------------------------------------------------------------------------
  Copyright (c) 2007 ConocoPhillips Company
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 -------------------------------------------------------------------------------
 </license>*/
"Cfg*version_2_0.background: purple",
"Cfg*version_2_0.labelString:\
-----------------------------------------------\\n\
Please contact Bill Menger bill.menger@gmail.com\\n\
to request new options, report bugs, or to get user assistance.",
"*fontList: -*-*-*-r-normal-*-*-120-*-*-p-*-iso8859-1",
"*main_form.resizePolicy:   RESIZE_NONE",
"*main_form.allowOverlap:   False",
"*main_form.width:   800",
"*main_form.height:  650",
"*background:        lightgray",
"*foreground:        black",
"*useColorObj: False",
"Cfg*enableToggleVisual:  False",
"Cfg*file.labelString:      File",
"Cfg*option.labelString:    Option",
"Cfg*table.labelString:     Table",
"Cfg*zoom.labelString:      Zoom",
"Cfg*plots.labelString:     Plots",
"Cfg*help.labelString:      Help",
"*file.mnemonic:     F",
"*option.mnemonic:   O",
"*table.mnemonic:    T",
"*plots.mnemonic:    P",
"Cfg*cfg.labelString:         Main Window...",
"Cfg*readjd.labelString:      Read JD File...",
"Cfg*savejd.labelString:      Save JD File...",
"Cfg*readsurvey.labelString:  Read Survey File...",
"Cfg*savesurvey.labelString:  Save Survey File...",
"Cfg*iconall.labelString:     Iconify all Windows",
"Cfg*quit.labelString:        Quit",
"Cfg*dcp.labelString:         Data control panel...",
"Cfg*tp.labelString:          Grid transformation...",
"Cfg*showstat.labelString:    Show Status Lines on Plots",
"Cfg*plotcolors.labelString:  Line/Flag Color Options...",
"Cfg*savdef.labelString:      Save Defaults...",
"Cfg*linelist.labelString:  List of Seismic Lines...",
"Cfg*ld.labelString:        Line Description Table... (LD)",
"Cfg*ld_qc.labelString:     LD Quality Control Table...",
"Cfg*ld_edit.labelString:   LD Edit Table...",
"Cfg*rptable.labelString:   Receiver Pattern Table... (RP)",
"Cfg*pp.labelString:        Profile Pattern Table...  (PP)",
"Cfg*zt1.labelString:       Zero Sources...           (ZT1)",
"Cfg*zt2.labelString:       Zero Receivers...         (ZT2)",
"Cfg*zt3.labelString:       Zero Traces in Groups...  (ZT3)",
"Cfg*zt4.labelString:       Zero Selected Ranges...   (ZT4)",
"Cfg*groups.labelString:    List of Source Gathers...",
"Cfg*midpoint.labelString:  List of CMP Gathers...",
"Cfg*head_pop.labelString:  CPS Trace Headers...",
"Cfg*miss_pop.labelString:  List of Missing Info...",
"Cfg*tred.labelString:      Trace Edit...             (TRED)",
"Cfg*zup.labelString:       Zoom Up",
"Cfg*zupsep.labelString:    Zoom Up Separate Window",
"Cfg*zdown.labelString:     Zoom Down",
"Cfg*zorgin.labelString:    Original Size",
"Cfg*zoomop.labelString:    Zoom Options...",
"Cfg*inmain.labelString:    Plot in Main Window",
"Cfg*fgxp_2d.labelString:   2d Cross Plots...",
"Cfg*fgxp_3d.labelString:   3d Cross Plots...",
"Cfg*fgqc.labelString:      QC Plots...",
"Cfg*map.labelString:       Map...",
"Cfg*ovjd.labelString:      Seismic Plots...",
"Cfg*chart.labelString:     Chart...",
"Cfg*options_menu_popup.title:    QC Options",
"Cfg*fgqc_plot_popup.title:       QC Plot",
"Cfg*qc_pop_popup.title:          QC Menu",
"Cfg*qc_main_popup.title:         QC Menu",
"Cfg*color_pop_popup.title:       Color Options",
"Cfg*cbar_popup.title:            Color Bar",
"Cfg*hill_shader_pop_popup.title: Hill Shader",
"Cfg*offset_menu_popup.title:     Offset Distribution",
"Cfg*pick_menu_popup.title:       Pick Options",
"Cfg*Seismic Select_popup.title:  Seismic Menu",
"Cfg*ovjd_plot_popup.title:       Seismic Data",
"Cfg*Offset Velocity_popup.title: Ovjd Options",
"Cfg*Options Menu_popup.title:    Options",
"Cfg*xp2dplotsin.labelString:   2d Cross Plots",
"Cfg*xp3dplotsin.labelString:   3d Cross Plots",
"Cfg*mapin.labelString:         Map",
"Cfg*qcplotsin.labelString:     QC Plots",
"Cfg*ovjdplotsin.labelString:   Seismic",
"Cfg*chartin.labelString:       Chart",
"*overview.labelString:     Overview Help...",
"*version.labelString:      Help on Version...",
"*fgxp2dplotsin.set:      False",
"*fgxp3dplotsin.set:      False",
"*mapin.set:              True",
"*qcplotsin.set:          False",
"*ovjdplotsin.set:         False",
"*showstat.set:           True",
"*readjd.accelerator:          Meta<Key>N",
"*readjd.acceleratorText:      Alt-N",
"*savejd.accelerator:          Meta<Key>S",
"*savejd.acceleratorText:      Alt-S",
"*iconall.accelerator:         Meta<Key>I",
"*iconall.acceleratorText:     Alt-I",
"*quit.accelerator:            Meta<Key>Q",
"*quit.acceleratorText:        Alt-Q",
"*dcp.accelerator:             Meta<Key>C",
"*dcp.acceleratorText:         Alt-C",
"*tp.accelerator:              Meta<Key>T",
"*tp.acceleratorText:          Alt-T",
"*ld.accelerator:            Meta<Key>L",
"*ld.acceleratorText:        Alt-L",
"*tablerp.accelerator:       Meta<Key>R",
"*tablerp.acceleratorText:   Alt-R",
"*pp.accelerator:            Meta<Key>P",
"*pp.acceleratorText:        Alt-P",
"*fgxp_2d.accelerator:            Meta<Key>X",
"*fgxp_2d.acceleratorText:        Alt-X",
"*fgxp_3d.accelerator:            Meta<Key>Y",
"*fgxp_3d.acceleratorText:        Alt-Y",
"*fgqc.accelerator:               Meta<Key>Z",
"*fgqc.acceleratorText:           Alt-Z",
"*map.accelerator:                Meta<Key>M",
"*map.acceleratorText:            Alt-M",
"*zup.accelerator:                Meta<Key>U",
"*zup.acceleratorText:            Alt-U",
"*zdown.accelerator:              Meta<Key>D",
"*zdown.acceleratorText:          Alt-D",
"*plot_background.value:   light gray",
"*active_flag.value:       blue",
"*selected_flag.value:     green",
"*computed_flag.value:     yellow",
"*default_flag.value:      red",
"*selectColor:      gold",
"*highlightColor:   red",
"*wboxbutton:       gray80",
"*wboxhighlight:    gray80",
"*wboxfont:         -bitstream-*-bold-r-*-*-*-80-*-*-m-*-iso8859-1",
"*clear_pop.dialogStyle:  DIALOG_FULL_APPLICATION_MODAL",
"*ld_edit*fontList:        -*-*-*-r-*-*-*-100-*-*-p-*-iso8859-1",
"*ld_edit.screenNumber:      otherScreen",
"*lines.screenNumber:        otherScreen",
"*ld.screenNumber:           otherScreen",
"*rptable.screenNumber:      otherScreen",
"*pp.screenNumber:           otherScreen",
"*zt1.screenNumber:          otherScreen",
"*zt2.screenNumber:          otherScreen",
"*zt3.screenNumber:          otherScreen",
"*zt4.screenNumber:          otherScreen",
"*groups.screenNumber:       otherScreen",
"*midpoint.screenNumber:     otherScreen",
"*head_pop.screenNumber:     otherScreen",
"*miss_pop.screenNumber:     otherScreen",
"*ld_qc.screenNumber:        otherScreen",
"*header_dump.screenNumber:  otherScreen",
"*tred.screenNumber:         otherScreen",
"*ld_edit.mayIcon:      True",
"*lines.mayIcon:        True",
"*ld.mayIcon:           True",
"*rptable.mayIcon:      True",
"*pp.mayIcon:           True",
"*zt1.mayIcon:          True",
"*zt2.mayIcon:          True",
"*zt3.mayIcon:          True",
"*zt4.mayIcon:          True",
"*groups.mayIcon:       True",
"*midpoint.mayIcon:     True",
"*head_pop.mayIcon:     True",
"*miss_pop.mayIcon:     True",
"*ld_qc.mayIcon:        True",
"*header_dump.mayIcon:  False",
"*ovjd.mayIcon:         True",
"*map.mayIcon:          True",
"*fgxp_2d.mayIcon:  True",
"*fgxp_3d.mayIcon:  True",
"*chart.mayIcon:    True",
"*ld_edit_popup.iconName:    LD edit",
"*lines_popup.iconName:    line table",
"*ld_popup.iconName:         LD table",
"*ld_qc_popup.iconName:      QC table",
"*rptable_popup.iconName:    RP table",
"*pp_popup.iconName:         PP table",
"*zt1_popup.iconName:       ZT1 table",
"*zt2_popup.iconName:       ZT2 table",
"*zt3_popup.iconName:       ZT3 table",
"*zt4_popup.iconName:       ZT4 table",
"*groups_popup.iconName:    source table",
"*midpoint_popup.iconName:  CMP table",
"*head_popup.iconName:      hdr table",
"*miss_popup.iconName:      miss table",
"*ovjd.mayIcon:              OVJD",
"*tred_popup.iconName:          TRED table",
"*tred.mayIcon:                 True",
"cfg*zfact.value:              80",
"*queue.optionCount: 4",
"*queue.optionElement_0: 5000A",
"*queue.optionElement_1: 650A",
"*queue.optionElement_2: 5000A_film",
"*queue.optionElement_3: paper_A",
"*queue.value:           5000A",
