#! /bin/sh

ns=256

ftnstrip < uh1.dat | suaddhead ns=$ns > junk1.su
ftnstrip < uh2.dat | suaddhead ns=$ns > junk2.su
ftnstrip < uv.dat | suaddhead ns=$ns > junk3.su

suxwigb < junk1.su title="radial"  &
suxwigb < junk2.su title="transv" &
suxwigb < junk3.su title="vertical" &

cat junk1.su junk2.su junk3.su > junk.out.su
suxwigb < junk.out.su title="all" &

exit 0
