//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisHvel.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisHvel_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisHvel *module = new CpseisHvel();
    return (jlong)module;
  }
}
