//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisVpick.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisVpick_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisVpick *module = new CpseisVpick();
    return (jlong)module;
  }
}
