//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisAvocorr.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define avocorr_wrap_create             avocorr_wrap_create_
#define avocorr_wrap_delete             avocorr_wrap_delete_
#define avocorr_wrap_update             avocorr_wrap_update_
#define avocorr_wrap_wrapup             avocorr_wrap_wrapup_
#define avocorr_wrap_oneset             avocorr_wrap_oneset_
#define avocorr_wrap_twosets            avocorr_wrap_twosets_
#elif NEED_CAPITALS
#define avocorr_wrap_create             AVOCORR_WRAP_CREATE
#define avocorr_wrap_delete             AVOCORR_WRAP_DELETE
#define avocorr_wrap_update             AVOCORR_WRAP_UPDATE
#define avocorr_wrap_wrapup             AVOCORR_WRAP_WRAPUP
#define avocorr_wrap_oneset             AVOCORR_WRAP_ONESET
#define avocorr_wrap_twosets            AVOCORR_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   avocorr_wrap_create;
    CpseisBase::ModuleDestroy  avocorr_wrap_delete;
    CpseisBase::ModuleUpdate   avocorr_wrap_update;
    CpseisBase::ModuleWrapup   avocorr_wrap_wrapup;
    CpseisBase::ModuleOneset   avocorr_wrap_oneset;
    CpseisBase::ModuleTwosets  avocorr_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisAvocorr::CpseisAvocorr() : CpseisBase ("AVOCORR",
                                       avocorr_wrap_create,
                                       avocorr_wrap_delete,
                                       avocorr_wrap_update,
                                       avocorr_wrap_wrapup,
                                       avocorr_wrap_oneset,
                                       avocorr_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
