//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisSynbp.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisSynbp_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisSynbp *module = new CpseisSynbp();
    return (jlong)module;
  }
}
