package org.cpseis.wrappers;

import org.cpseis.util.CpseisBase;

//////// DO NOT EDIT THIS FILE - it is machine generated ////////

public class CpseisDist extends CpseisBase
{
  static { System.loadLibrary("org_cpseis_wrappers_library"); }    // NOJAVAH

  public CpseisDist() { super("DIST"); }

  @Override protected native long nativeCreate();
}
