//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisSlab.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define slab_wrap_create             slab_wrap_create_
#define slab_wrap_delete             slab_wrap_delete_
#define slab_wrap_update             slab_wrap_update_
#define slab_wrap_wrapup             slab_wrap_wrapup_
#define slab_wrap_oneset             slab_wrap_oneset_
#define slab_wrap_twosets            slab_wrap_twosets_
#elif NEED_CAPITALS
#define slab_wrap_create             SLAB_WRAP_CREATE
#define slab_wrap_delete             SLAB_WRAP_DELETE
#define slab_wrap_update             SLAB_WRAP_UPDATE
#define slab_wrap_wrapup             SLAB_WRAP_WRAPUP
#define slab_wrap_oneset             SLAB_WRAP_ONESET
#define slab_wrap_twosets            SLAB_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   slab_wrap_create;
    CpseisBase::ModuleDestroy  slab_wrap_delete;
    CpseisBase::ModuleUpdate   slab_wrap_update;
    CpseisBase::ModuleWrapup   slab_wrap_wrapup;
    CpseisBase::ModuleOneset   slab_wrap_oneset;
    CpseisBase::ModuleTwosets  slab_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisSlab::CpseisSlab() : CpseisBase ("SLAB",
                                       slab_wrap_create,
                                       slab_wrap_delete,
                                       slab_wrap_update,
                                       slab_wrap_wrapup,
                                       slab_wrap_oneset,
                                       slab_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
