//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisFiltp.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisFiltp_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisFiltp *module = new CpseisFiltp();
    return (jlong)module;
  }
}
