//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisCleanup.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisCleanup_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisCleanup *module = new CpseisCleanup();
    return (jlong)module;
  }
}
