//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisSva.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define sva_wrap_create             sva_wrap_create_
#define sva_wrap_delete             sva_wrap_delete_
#define sva_wrap_update             sva_wrap_update_
#define sva_wrap_wrapup             sva_wrap_wrapup_
#define sva_wrap_oneset             sva_wrap_oneset_
#define sva_wrap_twosets            sva_wrap_twosets_
#elif NEED_CAPITALS
#define sva_wrap_create             SVA_WRAP_CREATE
#define sva_wrap_delete             SVA_WRAP_DELETE
#define sva_wrap_update             SVA_WRAP_UPDATE
#define sva_wrap_wrapup             SVA_WRAP_WRAPUP
#define sva_wrap_oneset             SVA_WRAP_ONESET
#define sva_wrap_twosets            SVA_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   sva_wrap_create;
    CpseisBase::ModuleDestroy  sva_wrap_delete;
    CpseisBase::ModuleUpdate   sva_wrap_update;
    CpseisBase::ModuleWrapup   sva_wrap_wrapup;
    CpseisBase::ModuleOneset   sva_wrap_oneset;
    CpseisBase::ModuleTwosets  sva_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisSva::CpseisSva() : CpseisBase ("SVA",
                                       sva_wrap_create,
                                       sva_wrap_delete,
                                       sva_wrap_update,
                                       sva_wrap_wrapup,
                                       sva_wrap_oneset,
                                       sva_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
