//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisAbra.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisAbra_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisAbra *module = new CpseisAbra();
    return (jlong)module;
  }
}
