//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisIntegrate.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisIntegrate_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisIntegrate *module = new CpseisIntegrate();
    return (jlong)module;
  }
}
