//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisIbsma.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define ibsma_wrap_create             ibsma_wrap_create_
#define ibsma_wrap_delete             ibsma_wrap_delete_
#define ibsma_wrap_update             ibsma_wrap_update_
#define ibsma_wrap_wrapup             ibsma_wrap_wrapup_
#define ibsma_wrap_oneset             ibsma_wrap_oneset_
#define ibsma_wrap_twosets            ibsma_wrap_twosets_
#elif NEED_CAPITALS
#define ibsma_wrap_create             IBSMA_WRAP_CREATE
#define ibsma_wrap_delete             IBSMA_WRAP_DELETE
#define ibsma_wrap_update             IBSMA_WRAP_UPDATE
#define ibsma_wrap_wrapup             IBSMA_WRAP_WRAPUP
#define ibsma_wrap_oneset             IBSMA_WRAP_ONESET
#define ibsma_wrap_twosets            IBSMA_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   ibsma_wrap_create;
    CpseisBase::ModuleDestroy  ibsma_wrap_delete;
    CpseisBase::ModuleUpdate   ibsma_wrap_update;
    CpseisBase::ModuleWrapup   ibsma_wrap_wrapup;
    CpseisBase::ModuleOneset   ibsma_wrap_oneset;
    CpseisBase::ModuleTwosets  ibsma_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisIbsma::CpseisIbsma() : CpseisBase ("IBSMA",
                                       ibsma_wrap_create,
                                       ibsma_wrap_delete,
                                       ibsma_wrap_update,
                                       ibsma_wrap_wrapup,
                                       ibsma_wrap_oneset,
                                       ibsma_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
