//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTablesave.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisTablesave_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisTablesave *module = new CpseisTablesave();
    return (jlong)module;
  }
}
