//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisAvosts.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisAvosts_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisAvosts *module = new CpseisAvosts();
    return (jlong)module;
  }
}
