//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTtrot.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisTtrot_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisTtrot *module = new CpseisTtrot();
    return (jlong)module;
  }
}
