//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisDmoprep.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisDmoprep_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisDmoprep *module = new CpseisDmoprep();
    return (jlong)module;
  }
}
