//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#ifndef _HH_CPSEIS_VALUEDUMP_HH_
#define _HH_CPSEIS_VALUEDUMP_HH_

#include "CpseisBase.hh"

//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//

class CpseisValuedump : public CpseisBase
  {
  public:

             CpseisValuedump();
    virtual ~CpseisValuedump() {}
  };

//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//

#endif

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
