//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisSlst.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisSlst_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisSlst *module = new CpseisSlst();
    return (jlong)module;
  }
}
