//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisValuedump.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisValuedump_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisValuedump *module = new CpseisValuedump();
    return (jlong)module;
  }
}
