//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisCombine.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisCombine_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisCombine *module = new CpseisCombine();
    return (jlong)module;
  }
}
