//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisSpct.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisSpct_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisSpct *module = new CpseisSpct();
    return (jlong)module;
  }
}
