//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisHrzstk.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisHrzstk_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisHrzstk *module = new CpseisHrzstk();
    return (jlong)module;
  }
}
