//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisHeadswap.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define headswap_wrap_create             headswap_wrap_create_
#define headswap_wrap_delete             headswap_wrap_delete_
#define headswap_wrap_update             headswap_wrap_update_
#define headswap_wrap_wrapup             headswap_wrap_wrapup_
#define headswap_wrap_oneset             headswap_wrap_oneset_
#define headswap_wrap_twosets            headswap_wrap_twosets_
#elif NEED_CAPITALS
#define headswap_wrap_create             HEADSWAP_WRAP_CREATE
#define headswap_wrap_delete             HEADSWAP_WRAP_DELETE
#define headswap_wrap_update             HEADSWAP_WRAP_UPDATE
#define headswap_wrap_wrapup             HEADSWAP_WRAP_WRAPUP
#define headswap_wrap_oneset             HEADSWAP_WRAP_ONESET
#define headswap_wrap_twosets            HEADSWAP_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   headswap_wrap_create;
    CpseisBase::ModuleDestroy  headswap_wrap_delete;
    CpseisBase::ModuleUpdate   headswap_wrap_update;
    CpseisBase::ModuleWrapup   headswap_wrap_wrapup;
    CpseisBase::ModuleOneset   headswap_wrap_oneset;
    CpseisBase::ModuleTwosets  headswap_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisHeadswap::CpseisHeadswap() : CpseisBase ("HEADSWAP",
                                       headswap_wrap_create,
                                       headswap_wrap_delete,
                                       headswap_wrap_update,
                                       headswap_wrap_wrapup,
                                       headswap_wrap_oneset,
                                       headswap_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
