//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisUngather.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define ungather_wrap_create             ungather_wrap_create_
#define ungather_wrap_delete             ungather_wrap_delete_
#define ungather_wrap_update             ungather_wrap_update_
#define ungather_wrap_wrapup             ungather_wrap_wrapup_
#define ungather_wrap_oneset             ungather_wrap_oneset_
#define ungather_wrap_twosets            ungather_wrap_twosets_
#elif NEED_CAPITALS
#define ungather_wrap_create             UNGATHER_WRAP_CREATE
#define ungather_wrap_delete             UNGATHER_WRAP_DELETE
#define ungather_wrap_update             UNGATHER_WRAP_UPDATE
#define ungather_wrap_wrapup             UNGATHER_WRAP_WRAPUP
#define ungather_wrap_oneset             UNGATHER_WRAP_ONESET
#define ungather_wrap_twosets            UNGATHER_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   ungather_wrap_create;
    CpseisBase::ModuleDestroy  ungather_wrap_delete;
    CpseisBase::ModuleUpdate   ungather_wrap_update;
    CpseisBase::ModuleWrapup   ungather_wrap_wrapup;
    CpseisBase::ModuleOneset   ungather_wrap_oneset;
    CpseisBase::ModuleTwosets  ungather_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisUngather::CpseisUngather() : CpseisBase ("UNGATHER",
                                       ungather_wrap_create,
                                       ungather_wrap_delete,
                                       ungather_wrap_update,
                                       ungather_wrap_wrapup,
                                       ungather_wrap_oneset,
                                       ungather_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
