//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTraceterp3d.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisTraceterp3d_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisTraceterp3d *module = new CpseisTraceterp3d();
    return (jlong)module;
  }
}
