//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTtrin.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define ttrin_wrap_create             ttrin_wrap_create_
#define ttrin_wrap_delete             ttrin_wrap_delete_
#define ttrin_wrap_update             ttrin_wrap_update_
#define ttrin_wrap_wrapup             ttrin_wrap_wrapup_
#define ttrin_wrap_oneset             ttrin_wrap_oneset_
#define ttrin_wrap_twosets            ttrin_wrap_twosets_
#elif NEED_CAPITALS
#define ttrin_wrap_create             TTRIN_WRAP_CREATE
#define ttrin_wrap_delete             TTRIN_WRAP_DELETE
#define ttrin_wrap_update             TTRIN_WRAP_UPDATE
#define ttrin_wrap_wrapup             TTRIN_WRAP_WRAPUP
#define ttrin_wrap_oneset             TTRIN_WRAP_ONESET
#define ttrin_wrap_twosets            TTRIN_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   ttrin_wrap_create;
    CpseisBase::ModuleDestroy  ttrin_wrap_delete;
    CpseisBase::ModuleUpdate   ttrin_wrap_update;
    CpseisBase::ModuleWrapup   ttrin_wrap_wrapup;
    CpseisBase::ModuleOneset   ttrin_wrap_oneset;
    CpseisBase::ModuleTwosets  ttrin_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisTtrin::CpseisTtrin() : CpseisBase ("TTRIN",
                                       ttrin_wrap_create,
                                       ttrin_wrap_delete,
                                       ttrin_wrap_update,
                                       ttrin_wrap_wrapup,
                                       ttrin_wrap_oneset,
                                       ttrin_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
