//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisAtrin.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisAtrin_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisAtrin *module = new CpseisAtrin();
    return (jlong)module;
  }
}
