//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisMfrs.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisMfrs_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisMfrs *module = new CpseisMfrs();
    return (jlong)module;
  }
}
