//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisFgdrev.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define fgdrev_wrap_create             fgdrev_wrap_create_
#define fgdrev_wrap_delete             fgdrev_wrap_delete_
#define fgdrev_wrap_update             fgdrev_wrap_update_
#define fgdrev_wrap_wrapup             fgdrev_wrap_wrapup_
#define fgdrev_wrap_oneset             fgdrev_wrap_oneset_
#define fgdrev_wrap_twosets            fgdrev_wrap_twosets_
#elif NEED_CAPITALS
#define fgdrev_wrap_create             FGDREV_WRAP_CREATE
#define fgdrev_wrap_delete             FGDREV_WRAP_DELETE
#define fgdrev_wrap_update             FGDREV_WRAP_UPDATE
#define fgdrev_wrap_wrapup             FGDREV_WRAP_WRAPUP
#define fgdrev_wrap_oneset             FGDREV_WRAP_ONESET
#define fgdrev_wrap_twosets            FGDREV_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   fgdrev_wrap_create;
    CpseisBase::ModuleDestroy  fgdrev_wrap_delete;
    CpseisBase::ModuleUpdate   fgdrev_wrap_update;
    CpseisBase::ModuleWrapup   fgdrev_wrap_wrapup;
    CpseisBase::ModuleOneset   fgdrev_wrap_oneset;
    CpseisBase::ModuleTwosets  fgdrev_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisFgdrev::CpseisFgdrev() : CpseisBase ("FGDREV",
                                       fgdrev_wrap_create,
                                       fgdrev_wrap_delete,
                                       fgdrev_wrap_update,
                                       fgdrev_wrap_wrapup,
                                       fgdrev_wrap_oneset,
                                       fgdrev_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
