//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisDmap3d.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define dmap3d_wrap_create             dmap3d_wrap_create_
#define dmap3d_wrap_delete             dmap3d_wrap_delete_
#define dmap3d_wrap_update             dmap3d_wrap_update_
#define dmap3d_wrap_wrapup             dmap3d_wrap_wrapup_
#define dmap3d_wrap_oneset             dmap3d_wrap_oneset_
#define dmap3d_wrap_twosets            dmap3d_wrap_twosets_
#elif NEED_CAPITALS
#define dmap3d_wrap_create             DMAP3D_WRAP_CREATE
#define dmap3d_wrap_delete             DMAP3D_WRAP_DELETE
#define dmap3d_wrap_update             DMAP3D_WRAP_UPDATE
#define dmap3d_wrap_wrapup             DMAP3D_WRAP_WRAPUP
#define dmap3d_wrap_oneset             DMAP3D_WRAP_ONESET
#define dmap3d_wrap_twosets            DMAP3D_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   dmap3d_wrap_create;
    CpseisBase::ModuleDestroy  dmap3d_wrap_delete;
    CpseisBase::ModuleUpdate   dmap3d_wrap_update;
    CpseisBase::ModuleWrapup   dmap3d_wrap_wrapup;
    CpseisBase::ModuleOneset   dmap3d_wrap_oneset;
    CpseisBase::ModuleTwosets  dmap3d_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisDmap3d::CpseisDmap3d() : CpseisBase ("DMAP3D",
                                       dmap3d_wrap_create,
                                       dmap3d_wrap_delete,
                                       dmap3d_wrap_update,
                                       dmap3d_wrap_wrapup,
                                       dmap3d_wrap_oneset,
                                       dmap3d_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
