//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisMix.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define mix_wrap_create             mix_wrap_create_
#define mix_wrap_delete             mix_wrap_delete_
#define mix_wrap_update             mix_wrap_update_
#define mix_wrap_wrapup             mix_wrap_wrapup_
#define mix_wrap_oneset             mix_wrap_oneset_
#define mix_wrap_twosets            mix_wrap_twosets_
#elif NEED_CAPITALS
#define mix_wrap_create             MIX_WRAP_CREATE
#define mix_wrap_delete             MIX_WRAP_DELETE
#define mix_wrap_update             MIX_WRAP_UPDATE
#define mix_wrap_wrapup             MIX_WRAP_WRAPUP
#define mix_wrap_oneset             MIX_WRAP_ONESET
#define mix_wrap_twosets            MIX_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   mix_wrap_create;
    CpseisBase::ModuleDestroy  mix_wrap_delete;
    CpseisBase::ModuleUpdate   mix_wrap_update;
    CpseisBase::ModuleWrapup   mix_wrap_wrapup;
    CpseisBase::ModuleOneset   mix_wrap_oneset;
    CpseisBase::ModuleTwosets  mix_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisMix::CpseisMix() : CpseisBase ("MIX",
                                       mix_wrap_create,
                                       mix_wrap_delete,
                                       mix_wrap_update,
                                       mix_wrap_wrapup,
                                       mix_wrap_oneset,
                                       mix_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
