//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisProject_data.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define project_data_wrap_create             project_data_wrap_create_
#define project_data_wrap_delete             project_data_wrap_delete_
#define project_data_wrap_update             project_data_wrap_update_
#define project_data_wrap_wrapup             project_data_wrap_wrapup_
#define project_data_wrap_oneset             project_data_wrap_oneset_
#define project_data_wrap_twosets            project_data_wrap_twosets_
#elif NEED_CAPITALS
#define project_data_wrap_create             PROJECT_DATA_WRAP_CREATE
#define project_data_wrap_delete             PROJECT_DATA_WRAP_DELETE
#define project_data_wrap_update             PROJECT_DATA_WRAP_UPDATE
#define project_data_wrap_wrapup             PROJECT_DATA_WRAP_WRAPUP
#define project_data_wrap_oneset             PROJECT_DATA_WRAP_ONESET
#define project_data_wrap_twosets            PROJECT_DATA_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   project_data_wrap_create;
    CpseisBase::ModuleDestroy  project_data_wrap_delete;
    CpseisBase::ModuleUpdate   project_data_wrap_update;
    CpseisBase::ModuleWrapup   project_data_wrap_wrapup;
    CpseisBase::ModuleOneset   project_data_wrap_oneset;
    CpseisBase::ModuleTwosets  project_data_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisProject_data::CpseisProject_data() : CpseisBase ("PROJECT_DATA",
                                       project_data_wrap_create,
                                       project_data_wrap_delete,
                                       project_data_wrap_update,
                                       project_data_wrap_wrapup,
                                       project_data_wrap_oneset,
                                       project_data_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
