//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisCtan.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisCtan_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisCtan *module = new CpseisCtan();
    return (jlong)module;
  }
}
