//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisFxdecon.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define fxdecon_wrap_create             fxdecon_wrap_create_
#define fxdecon_wrap_delete             fxdecon_wrap_delete_
#define fxdecon_wrap_update             fxdecon_wrap_update_
#define fxdecon_wrap_wrapup             fxdecon_wrap_wrapup_
#define fxdecon_wrap_oneset             fxdecon_wrap_oneset_
#define fxdecon_wrap_twosets            fxdecon_wrap_twosets_
#elif NEED_CAPITALS
#define fxdecon_wrap_create             FXDECON_WRAP_CREATE
#define fxdecon_wrap_delete             FXDECON_WRAP_DELETE
#define fxdecon_wrap_update             FXDECON_WRAP_UPDATE
#define fxdecon_wrap_wrapup             FXDECON_WRAP_WRAPUP
#define fxdecon_wrap_oneset             FXDECON_WRAP_ONESET
#define fxdecon_wrap_twosets            FXDECON_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   fxdecon_wrap_create;
    CpseisBase::ModuleDestroy  fxdecon_wrap_delete;
    CpseisBase::ModuleUpdate   fxdecon_wrap_update;
    CpseisBase::ModuleWrapup   fxdecon_wrap_wrapup;
    CpseisBase::ModuleOneset   fxdecon_wrap_oneset;
    CpseisBase::ModuleTwosets  fxdecon_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisFxdecon::CpseisFxdecon() : CpseisBase ("FXDECON",
                                       fxdecon_wrap_create,
                                       fxdecon_wrap_delete,
                                       fxdecon_wrap_update,
                                       fxdecon_wrap_wrapup,
                                       fxdecon_wrap_oneset,
                                       fxdecon_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
