//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisScdecon.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define scdecon_wrap_create             scdecon_wrap_create_
#define scdecon_wrap_delete             scdecon_wrap_delete_
#define scdecon_wrap_update             scdecon_wrap_update_
#define scdecon_wrap_wrapup             scdecon_wrap_wrapup_
#define scdecon_wrap_oneset             scdecon_wrap_oneset_
#define scdecon_wrap_twosets            scdecon_wrap_twosets_
#elif NEED_CAPITALS
#define scdecon_wrap_create             SCDECON_WRAP_CREATE
#define scdecon_wrap_delete             SCDECON_WRAP_DELETE
#define scdecon_wrap_update             SCDECON_WRAP_UPDATE
#define scdecon_wrap_wrapup             SCDECON_WRAP_WRAPUP
#define scdecon_wrap_oneset             SCDECON_WRAP_ONESET
#define scdecon_wrap_twosets            SCDECON_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   scdecon_wrap_create;
    CpseisBase::ModuleDestroy  scdecon_wrap_delete;
    CpseisBase::ModuleUpdate   scdecon_wrap_update;
    CpseisBase::ModuleWrapup   scdecon_wrap_wrapup;
    CpseisBase::ModuleOneset   scdecon_wrap_oneset;
    CpseisBase::ModuleTwosets  scdecon_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisScdecon::CpseisScdecon() : CpseisBase ("SCDECON",
                                       scdecon_wrap_create,
                                       scdecon_wrap_delete,
                                       scdecon_wrap_update,
                                       scdecon_wrap_wrapup,
                                       scdecon_wrap_oneset,
                                       scdecon_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
