//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisMtfun.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define mtfun_wrap_create             mtfun_wrap_create_
#define mtfun_wrap_delete             mtfun_wrap_delete_
#define mtfun_wrap_update             mtfun_wrap_update_
#define mtfun_wrap_wrapup             mtfun_wrap_wrapup_
#define mtfun_wrap_oneset             mtfun_wrap_oneset_
#define mtfun_wrap_twosets            mtfun_wrap_twosets_
#elif NEED_CAPITALS
#define mtfun_wrap_create             MTFUN_WRAP_CREATE
#define mtfun_wrap_delete             MTFUN_WRAP_DELETE
#define mtfun_wrap_update             MTFUN_WRAP_UPDATE
#define mtfun_wrap_wrapup             MTFUN_WRAP_WRAPUP
#define mtfun_wrap_oneset             MTFUN_WRAP_ONESET
#define mtfun_wrap_twosets            MTFUN_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   mtfun_wrap_create;
    CpseisBase::ModuleDestroy  mtfun_wrap_delete;
    CpseisBase::ModuleUpdate   mtfun_wrap_update;
    CpseisBase::ModuleWrapup   mtfun_wrap_wrapup;
    CpseisBase::ModuleOneset   mtfun_wrap_oneset;
    CpseisBase::ModuleTwosets  mtfun_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisMtfun::CpseisMtfun() : CpseisBase ("MTFUN",
                                       mtfun_wrap_create,
                                       mtfun_wrap_delete,
                                       mtfun_wrap_update,
                                       mtfun_wrap_wrapup,
                                       mtfun_wrap_oneset,
                                       mtfun_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
