//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisModmo2d.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define modmo2d_wrap_create             modmo2d_wrap_create_
#define modmo2d_wrap_delete             modmo2d_wrap_delete_
#define modmo2d_wrap_update             modmo2d_wrap_update_
#define modmo2d_wrap_wrapup             modmo2d_wrap_wrapup_
#define modmo2d_wrap_oneset             modmo2d_wrap_oneset_
#define modmo2d_wrap_twosets            modmo2d_wrap_twosets_
#elif NEED_CAPITALS
#define modmo2d_wrap_create             MODMO2D_WRAP_CREATE
#define modmo2d_wrap_delete             MODMO2D_WRAP_DELETE
#define modmo2d_wrap_update             MODMO2D_WRAP_UPDATE
#define modmo2d_wrap_wrapup             MODMO2D_WRAP_WRAPUP
#define modmo2d_wrap_oneset             MODMO2D_WRAP_ONESET
#define modmo2d_wrap_twosets            MODMO2D_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   modmo2d_wrap_create;
    CpseisBase::ModuleDestroy  modmo2d_wrap_delete;
    CpseisBase::ModuleUpdate   modmo2d_wrap_update;
    CpseisBase::ModuleWrapup   modmo2d_wrap_wrapup;
    CpseisBase::ModuleOneset   modmo2d_wrap_oneset;
    CpseisBase::ModuleTwosets  modmo2d_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisModmo2d::CpseisModmo2d() : CpseisBase ("MODMO2D",
                                       modmo2d_wrap_create,
                                       modmo2d_wrap_delete,
                                       modmo2d_wrap_update,
                                       modmo2d_wrap_wrapup,
                                       modmo2d_wrap_oneset,
                                       modmo2d_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
