//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisAvonrm.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define avonrm_wrap_create             avonrm_wrap_create_
#define avonrm_wrap_delete             avonrm_wrap_delete_
#define avonrm_wrap_update             avonrm_wrap_update_
#define avonrm_wrap_wrapup             avonrm_wrap_wrapup_
#define avonrm_wrap_oneset             avonrm_wrap_oneset_
#define avonrm_wrap_twosets            avonrm_wrap_twosets_
#elif NEED_CAPITALS
#define avonrm_wrap_create             AVONRM_WRAP_CREATE
#define avonrm_wrap_delete             AVONRM_WRAP_DELETE
#define avonrm_wrap_update             AVONRM_WRAP_UPDATE
#define avonrm_wrap_wrapup             AVONRM_WRAP_WRAPUP
#define avonrm_wrap_oneset             AVONRM_WRAP_ONESET
#define avonrm_wrap_twosets            AVONRM_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   avonrm_wrap_create;
    CpseisBase::ModuleDestroy  avonrm_wrap_delete;
    CpseisBase::ModuleUpdate   avonrm_wrap_update;
    CpseisBase::ModuleWrapup   avonrm_wrap_wrapup;
    CpseisBase::ModuleOneset   avonrm_wrap_oneset;
    CpseisBase::ModuleTwosets  avonrm_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisAvonrm::CpseisAvonrm() : CpseisBase ("AVONRM",
                                       avonrm_wrap_create,
                                       avonrm_wrap_delete,
                                       avonrm_wrap_update,
                                       avonrm_wrap_wrapup,
                                       avonrm_wrap_oneset,
                                       avonrm_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
