//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisFktmig.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisFktmig_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisFktmig *module = new CpseisFktmig();
    return (jlong)module;
  }
}
