//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisMvxp.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisMvxp_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisMvxp *module = new CpseisMvxp();
    return (jlong)module;
  }
}
