//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisMfrs.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define mfrs_wrap_create             mfrs_wrap_create_
#define mfrs_wrap_delete             mfrs_wrap_delete_
#define mfrs_wrap_update             mfrs_wrap_update_
#define mfrs_wrap_wrapup             mfrs_wrap_wrapup_
#define mfrs_wrap_oneset             mfrs_wrap_oneset_
#define mfrs_wrap_twosets            mfrs_wrap_twosets_
#elif NEED_CAPITALS
#define mfrs_wrap_create             MFRS_WRAP_CREATE
#define mfrs_wrap_delete             MFRS_WRAP_DELETE
#define mfrs_wrap_update             MFRS_WRAP_UPDATE
#define mfrs_wrap_wrapup             MFRS_WRAP_WRAPUP
#define mfrs_wrap_oneset             MFRS_WRAP_ONESET
#define mfrs_wrap_twosets            MFRS_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   mfrs_wrap_create;
    CpseisBase::ModuleDestroy  mfrs_wrap_delete;
    CpseisBase::ModuleUpdate   mfrs_wrap_update;
    CpseisBase::ModuleWrapup   mfrs_wrap_wrapup;
    CpseisBase::ModuleOneset   mfrs_wrap_oneset;
    CpseisBase::ModuleTwosets  mfrs_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisMfrs::CpseisMfrs() : CpseisBase ("MFRS",
                                       mfrs_wrap_create,
                                       mfrs_wrap_delete,
                                       mfrs_wrap_update,
                                       mfrs_wrap_wrapup,
                                       mfrs_wrap_oneset,
                                       mfrs_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
