//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisRegbin.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define regbin_wrap_create             regbin_wrap_create_
#define regbin_wrap_delete             regbin_wrap_delete_
#define regbin_wrap_update             regbin_wrap_update_
#define regbin_wrap_wrapup             regbin_wrap_wrapup_
#define regbin_wrap_oneset             regbin_wrap_oneset_
#define regbin_wrap_twosets            regbin_wrap_twosets_
#elif NEED_CAPITALS
#define regbin_wrap_create             REGBIN_WRAP_CREATE
#define regbin_wrap_delete             REGBIN_WRAP_DELETE
#define regbin_wrap_update             REGBIN_WRAP_UPDATE
#define regbin_wrap_wrapup             REGBIN_WRAP_WRAPUP
#define regbin_wrap_oneset             REGBIN_WRAP_ONESET
#define regbin_wrap_twosets            REGBIN_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   regbin_wrap_create;
    CpseisBase::ModuleDestroy  regbin_wrap_delete;
    CpseisBase::ModuleUpdate   regbin_wrap_update;
    CpseisBase::ModuleWrapup   regbin_wrap_wrapup;
    CpseisBase::ModuleOneset   regbin_wrap_oneset;
    CpseisBase::ModuleTwosets  regbin_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisRegbin::CpseisRegbin() : CpseisBase ("REGBIN",
                                       regbin_wrap_create,
                                       regbin_wrap_delete,
                                       regbin_wrap_update,
                                       regbin_wrap_wrapup,
                                       regbin_wrap_oneset,
                                       regbin_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
