//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTfatt.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisTfatt_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisTfatt *module = new CpseisTfatt();
    return (jlong)module;
  }
}
