//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisXp.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisXp_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisXp *module = new CpseisXp();
    return (jlong)module;
  }
}
