//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTtmo.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisTtmo_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisTtmo *module = new CpseisTtmo();
    return (jlong)module;
  }
}
