//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisVeledit.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisVeledit_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisVeledit *module = new CpseisVeledit();
    return (jlong)module;
  }
}
