//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisPairmerge.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisPairmerge_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisPairmerge *module = new CpseisPairmerge();
    return (jlong)module;
  }
}
