//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisWsep.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisWsep_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisWsep *module = new CpseisWsep();
    return (jlong)module;
  }
}
