//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#ifndef _HH_CPSEIS_CLEANUP_HH_
#define _HH_CPSEIS_CLEANUP_HH_

#include "CpseisBase.hh"

//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//

class CpseisCleanup : public CpseisBase
  {
  public:

             CpseisCleanup();
    virtual ~CpseisCleanup() {}
  };

//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//

#endif

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
