//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisStk.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisStk_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisStk *module = new CpseisStk();
    return (jlong)module;
  }
}
