//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisTsvf.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define tsvf_wrap_create             tsvf_wrap_create_
#define tsvf_wrap_delete             tsvf_wrap_delete_
#define tsvf_wrap_update             tsvf_wrap_update_
#define tsvf_wrap_wrapup             tsvf_wrap_wrapup_
#define tsvf_wrap_oneset             tsvf_wrap_oneset_
#define tsvf_wrap_twosets            tsvf_wrap_twosets_
#elif NEED_CAPITALS
#define tsvf_wrap_create             TSVF_WRAP_CREATE
#define tsvf_wrap_delete             TSVF_WRAP_DELETE
#define tsvf_wrap_update             TSVF_WRAP_UPDATE
#define tsvf_wrap_wrapup             TSVF_WRAP_WRAPUP
#define tsvf_wrap_oneset             TSVF_WRAP_ONESET
#define tsvf_wrap_twosets            TSVF_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   tsvf_wrap_create;
    CpseisBase::ModuleDestroy  tsvf_wrap_delete;
    CpseisBase::ModuleUpdate   tsvf_wrap_update;
    CpseisBase::ModuleWrapup   tsvf_wrap_wrapup;
    CpseisBase::ModuleOneset   tsvf_wrap_oneset;
    CpseisBase::ModuleTwosets  tsvf_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisTsvf::CpseisTsvf() : CpseisBase ("TSVF",
                                       tsvf_wrap_create,
                                       tsvf_wrap_delete,
                                       tsvf_wrap_update,
                                       tsvf_wrap_wrapup,
                                       tsvf_wrap_oneset,
                                       tsvf_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
