//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisIq.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisIq_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisIq *module = new CpseisIq();
    return (jlong)module;
  }
}
