//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#ifndef _HH_CPSEIS_COMBINE_HH_
#define _HH_CPSEIS_COMBINE_HH_

#include "CpseisBase.hh"

//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//

class CpseisCombine : public CpseisBase
  {
  public:

             CpseisCombine();
    virtual ~CpseisCombine() {}
  };

//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//

#endif

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
