//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisRnsyn.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define rnsyn_wrap_create             rnsyn_wrap_create_
#define rnsyn_wrap_delete             rnsyn_wrap_delete_
#define rnsyn_wrap_update             rnsyn_wrap_update_
#define rnsyn_wrap_wrapup             rnsyn_wrap_wrapup_
#define rnsyn_wrap_oneset             rnsyn_wrap_oneset_
#define rnsyn_wrap_twosets            rnsyn_wrap_twosets_
#elif NEED_CAPITALS
#define rnsyn_wrap_create             RNSYN_WRAP_CREATE
#define rnsyn_wrap_delete             RNSYN_WRAP_DELETE
#define rnsyn_wrap_update             RNSYN_WRAP_UPDATE
#define rnsyn_wrap_wrapup             RNSYN_WRAP_WRAPUP
#define rnsyn_wrap_oneset             RNSYN_WRAP_ONESET
#define rnsyn_wrap_twosets            RNSYN_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   rnsyn_wrap_create;
    CpseisBase::ModuleDestroy  rnsyn_wrap_delete;
    CpseisBase::ModuleUpdate   rnsyn_wrap_update;
    CpseisBase::ModuleWrapup   rnsyn_wrap_wrapup;
    CpseisBase::ModuleOneset   rnsyn_wrap_oneset;
    CpseisBase::ModuleTwosets  rnsyn_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisRnsyn::CpseisRnsyn() : CpseisBase ("RNSYN",
                                       rnsyn_wrap_create,
                                       rnsyn_wrap_delete,
                                       rnsyn_wrap_update,
                                       rnsyn_wrap_wrapup,
                                       rnsyn_wrap_oneset,
                                       rnsyn_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
