//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisFish.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define fish_wrap_create             fish_wrap_create_
#define fish_wrap_delete             fish_wrap_delete_
#define fish_wrap_update             fish_wrap_update_
#define fish_wrap_wrapup             fish_wrap_wrapup_
#define fish_wrap_oneset             fish_wrap_oneset_
#define fish_wrap_twosets            fish_wrap_twosets_
#elif NEED_CAPITALS
#define fish_wrap_create             FISH_WRAP_CREATE
#define fish_wrap_delete             FISH_WRAP_DELETE
#define fish_wrap_update             FISH_WRAP_UPDATE
#define fish_wrap_wrapup             FISH_WRAP_WRAPUP
#define fish_wrap_oneset             FISH_WRAP_ONESET
#define fish_wrap_twosets            FISH_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   fish_wrap_create;
    CpseisBase::ModuleDestroy  fish_wrap_delete;
    CpseisBase::ModuleUpdate   fish_wrap_update;
    CpseisBase::ModuleWrapup   fish_wrap_wrapup;
    CpseisBase::ModuleOneset   fish_wrap_oneset;
    CpseisBase::ModuleTwosets  fish_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisFish::CpseisFish() : CpseisBase ("FISH",
                                       fish_wrap_create,
                                       fish_wrap_delete,
                                       fish_wrap_update,
                                       fish_wrap_wrapup,
                                       fish_wrap_oneset,
                                       fish_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
