//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#ifndef _HH_CPSEIS_FLEXBIN_HH_
#define _HH_CPSEIS_FLEXBIN_HH_

#include "CpseisBase.hh"

//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//

class CpseisFlexbin : public CpseisBase
  {
  public:

             CpseisFlexbin();
    virtual ~CpseisFlexbin() {}
  };

//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//

#endif

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
