//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#ifndef _HH_CPSEIS_PICKSET_HH_
#define _HH_CPSEIS_PICKSET_HH_

#include "CpseisBase.hh"

//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//
//------------------------ start of class ----------------------------//

class CpseisPickset : public CpseisBase
  {
  public:

             CpseisPickset();
    virtual ~CpseisPickset() {}
  };

//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//
//------------------------- end of class -----------------------------//

#endif

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
