//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisApin.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisApin_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisApin *module = new CpseisApin();
    return (jlong)module;
  }
}
