//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisUtel.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisUtel_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisUtel *module = new CpseisUtel();
    return (jlong)module;
  }
}
