package org.cpseis.wrappers;

import org.cpseis.util.CpseisBase;

//////// DO NOT EDIT THIS FILE - it is machine generated ////////

public class CpseisVtrin extends CpseisBase
{
  static { System.loadLibrary("org_cpseis_wrappers_library"); }    // NOJAVAH

  public CpseisVtrin() { super("VTRIN"); }

  @Override protected native long nativeCreate();
}
