//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisIbsma.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisIbsma_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisIbsma *module = new CpseisIbsma();
    return (jlong)module;
  }
}
