//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisPickset.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisPickset_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisPickset *module = new CpseisPickset();
    return (jlong)module;
  }
}
