//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisSisc.hh"
#include <jni.h>

extern "C"
{
  JNIEXPORT jlong JNICALL Java_org_cpseis_wrappers_CpseisSisc_nativeCreate
    (JNIEnv *env, jobject obj)
  {
    CpseisSisc *module = new CpseisSisc();
    return (jlong)module;
  }
}
