//////// DO NOT EDIT THIS FILE - it is machine generated ////////

#include "CpseisGvs.hh"

//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//
//------------------ fortran spelling adjustments --------------------//

#if NEED_UNDERSCORE
#define gvs_wrap_create             gvs_wrap_create_
#define gvs_wrap_delete             gvs_wrap_delete_
#define gvs_wrap_update             gvs_wrap_update_
#define gvs_wrap_wrapup             gvs_wrap_wrapup_
#define gvs_wrap_oneset             gvs_wrap_oneset_
#define gvs_wrap_twosets            gvs_wrap_twosets_
#elif NEED_CAPITALS
#define gvs_wrap_create             GVS_WRAP_CREATE
#define gvs_wrap_delete             GVS_WRAP_DELETE
#define gvs_wrap_update             GVS_WRAP_UPDATE
#define gvs_wrap_wrapup             GVS_WRAP_WRAPUP
#define gvs_wrap_oneset             GVS_WRAP_ONESET
#define gvs_wrap_twosets            GVS_WRAP_TWOSETS
#endif

//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//
//----------------------- fortran prototypes -------------------------//

extern "C"
    {
    CpseisBase::ModuleCreate   gvs_wrap_create;
    CpseisBase::ModuleDestroy  gvs_wrap_delete;
    CpseisBase::ModuleUpdate   gvs_wrap_update;
    CpseisBase::ModuleWrapup   gvs_wrap_wrapup;
    CpseisBase::ModuleOneset   gvs_wrap_oneset;
    CpseisBase::ModuleTwosets  gvs_wrap_twosets;
    }

//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//
//------------------------ constructor -------------------------------//

CpseisGvs::CpseisGvs() : CpseisBase ("GVS",
                                       gvs_wrap_create,
                                       gvs_wrap_delete,
                                       gvs_wrap_update,
                                       gvs_wrap_wrapup,
                                       gvs_wrap_oneset,
                                       gvs_wrap_twosets) {}

//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
//------------------------------ end ---------------------------------//
