!!------------------------ gdiv_wrap.f90 --------------------------!!
!!------------------------ gdiv_wrap.f90 --------------------------!!
!!------------------------ gdiv_wrap.f90 --------------------------!!

!!!!!!!!!! DO NOT EDIT THIS FILE - it is machine generated !!!!!!!!!!

!!------------------------------ module -----------------------------------!!
!!------------------------------ module -----------------------------------!!
!!------------------------------ module -----------------------------------!!

      module gdiv_wrap_module
      use gdiv_module
      implicit none
      public

      type :: gdiv_wrap_struct
        type(gdiv_struct),pointer :: obj
      end type gdiv_wrap_struct

      end module gdiv_wrap_module

!!---------------------------- create ------------------------------------!!
!!---------------------------- create ------------------------------------!!
!!---------------------------- create ------------------------------------!!

      subroutine gdiv_wrap_create (fpoint)  
      use gdiv_wrap_module
      implicit none
      type(gdiv_wrap_struct),intent(out)   :: fpoint
      type(gdiv_struct)     ,pointer       :: obj           ! local

      nullify (obj)               ! needed for intel compiler.
      call gdiv_create (obj)
      fpoint%obj => obj

      end subroutine gdiv_wrap_create

!!---------------------------- delete ------------------------------------!!
!!---------------------------- delete ------------------------------------!!
!!---------------------------- delete ------------------------------------!!

      subroutine gdiv_wrap_delete (fpoint)   
      use gdiv_wrap_module
      implicit none
      type(gdiv_wrap_struct),intent(inout) :: fpoint
      type(gdiv_struct)     ,pointer       :: obj           ! local

      obj => fpoint%obj
      if (.not. associated(obj)) return
      call gdiv_delete (obj)
      fpoint%obj => obj

      end subroutine gdiv_wrap_delete

!!---------------------------- update ------------------------------------!!
!!---------------------------- update ------------------------------------!!
!!---------------------------- update ------------------------------------!!

      subroutine gdiv_wrap_update (fpoint)     
      use gdiv_wrap_module
      implicit none
      type(gdiv_wrap_struct),intent(inout) :: fpoint
      type(gdiv_struct)     ,pointer       :: obj           ! local

      obj => fpoint%obj
      if (.not. associated(obj)) return
      call gdiv_update (obj)

      end subroutine gdiv_wrap_update

!!---------------------------- wrapup ------------------------------------!!
!!---------------------------- wrapup ------------------------------------!!
!!---------------------------- wrapup ------------------------------------!!

      subroutine gdiv_wrap_wrapup (fpoint)      
      use gdiv_wrap_module
      implicit none
      type(gdiv_wrap_struct),intent(inout) :: fpoint
      type(gdiv_struct)     ,pointer       :: obj           ! local

      obj => fpoint%obj
      if (.not. associated(obj)) return
      call gdiv_wrapup (obj)

      end subroutine gdiv_wrap_wrapup

!!---------------------------- oneset ------------------------------------!!
!!---------------------------- oneset ------------------------------------!!
!!---------------------------- oneset ------------------------------------!!

      subroutine gdiv_wrap_oneset (fpoint,ntr,  &
                                   hd,tr,lenhd,lentr,num)
      use gdiv_wrap_module
      implicit none
      type(gdiv_wrap_struct),intent(inout) :: fpoint
      integer               ,intent(in)    :: lenhd,lentr,num  ! argument
      integer               ,intent(inout) :: ntr              ! argument
      double precision      ,intent(inout) :: hd(lenhd,num)    ! argument
      real                  ,intent(inout) :: tr(lentr,num)    ! argument
      type(gdiv_struct)     ,pointer       :: obj              ! local

      obj => fpoint%obj
      if (.not. associated(obj)) return
      call gdiv (obj,ntr,hd,tr)                ! might be commented out.

      end subroutine gdiv_wrap_oneset

!!---------------------------- twosets ------------------------------------!!
!!---------------------------- twosets ------------------------------------!!
!!---------------------------- twosets ------------------------------------!!

      subroutine gdiv_wrap_twosets (fpoint,ntr,                 &
                                    hd1,tr1,lenhd1,lentr1,num1, &
                                    hd2,tr2,lenhd2,lentr2,num2)
      use gdiv_wrap_module
      implicit none
      type(gdiv_wrap_struct),intent(inout) :: fpoint
      integer               ,intent(in)    :: lenhd1,lentr1,num1 ! argument
      integer               ,intent(in)    :: lenhd2,lentr2,num2 ! argument
      integer               ,intent(inout) :: ntr                ! argument
      double precision      ,intent(inout) :: hd1(lenhd1,num1)   ! argument
      real                  ,intent(inout) :: tr1(lentr1,num1)   ! argument
      double precision      ,intent(inout) :: hd2(lenhd2,num2)   ! argument
      real                  ,intent(inout) :: tr2(lentr2,num2)   ! argument
      type(gdiv_struct)     ,pointer       :: obj                ! local

      obj => fpoint%obj
      if (.not. associated(obj)) return
!!!!  call gdiv (obj,ntr,hd1,tr1,hd2,tr2)      ! might be commented out.

      end subroutine gdiv_wrap_twosets

!!----------------------------- end ---------------------------------------!!
!!----------------------------- end ---------------------------------------!!
!!----------------------------- end ---------------------------------------!!
