#! /bin/sh

# sample colormap:  red, white, blue
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,0,0 ghls=0,1.0,0 bhls=0,0,1.0 \
wrgb=1.0,0,0 grgb=1.0,1.0,1.0 brgb=0,0,1.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="Red White Blue" \
titlesize=10 \
legend=1  > redwhiteblue.ps


# sample colormap:  red, green, blue
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,0,0 ghls=1.0,1.0,1.0 bhls=0,0,1.0 \
wrgb=1.0,0,0 grgb=0,1.0,0 brgb=0,0,1.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="Red Green Blue" \
titlesize=10 \
legend=1  > redgreenblue.ps

# sample colormap:  red, light blue, blue
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=0.0,0,1.0 ghls=0,1.0,1.0 bhls=0,0,1.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="Red Light blue dark Blue" \
titlesize=10 \
legend=1  > redltbluedarkblue.ps

# sample colormap:  red, yellow , blue
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,0,0 ghls=1.0,1.0,0.0 bhls=0,0,1.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="Red Yellow Blue" \
titlesize=10 \
legend=1  > redyellowblue.ps

# sample colormap:   white, red, blue
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,1.0,1.0 ghls=1.0,0.0,0.0 bhls=0,0,1.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="White Red Blue" \
titlesize=10 \
 \
legend=1  > whiteredblue.ps

# sample colormap:   blue, red, white 
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=0.0,0.0,1.0 ghls=1.0,0.0,0.0 bhls=1.0,1.0,1.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="White Red Blue" \
titlesize=10 \
legend=1  > whiteredblue.ps

# sample colormap:   red, blue, white 
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=0.0,0.0,1.0 ghls=1.0,1.0,1.0 bhls=1.0,0.0,0.0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="Red blue white" \
titlesize=10 \
legend=1  > redbluewhite.ps

# sample colormap:   orange, light blue,  green
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,.5,0 ghls=0,.7,1.0 bhls=0,1.0,0 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="orange light blue green" \
titlesize=10 \
legend=1  > orltblgr.ps

# sample colormap: Green, light blue, Magenta
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,0,1.0 ghls=0,.9,1.0 bhls=0,.5,.5 \
xbox=0.0 ybox=0 width=2 height=3 \
d1s=.1 d2s=.1 \
title="Green Light Blue Magenta" \
titlesize=10 \
legend=1  > gltbmag.ps

# sample colormap:   blue, red, white 
suplane | sufilter | suaddnoise | supsimage bps=12 threecolor=1 \
whls=1.0,.5,0 ghls=0,.7,1.0 bhls=0,.5,1.0 \
width=2 height=3 \
d1s=.1 d2s=.1 \
title="Test pattern" \
titlesize=10 \
legend=1  > testpattern.ps



$CWPROOT/bin/psmerge translate=0.,0. in=redgreenblue.ps \
translate=1.0,0.1 in=redltbluedarkblue.ps \
translate=2.0,0.2 in=redwhiteblue.ps \
translate=3.0,0.3 in=redyellowblue.ps  \
translate=4.0,0.5 in=whiteredblue.ps \
translate=5.0,0.6 in=gltbmag.ps \
translate=6.0,0.7 in=orltblgr.ps > merge.ps

echo
echo
echo "view:  merge.ps  with your PostScript previewer"
echo
