#! /bin/sh

#set -x

nx=70 dx=50 fx=200
nz=101 dz=40 fz=0
DVDZ=0.0
dv=10
nt=401
dt=.006

susynlvfti  fpeak=30 fxo=0.2 fxm=.25 dxm=.05 nxm=1 \
	nxo=$nx dxo=.05 dt=$dt nt=$nt \
 	v00=2.0 dvdz=$DVDZ delta=0 epsilon=.1 dvdx=.0 ob=0 \
	ref="1:0.0,1.0;0.5,1.0" |
suaddnoise sn=5  >junkd

suximage <junkd xbox=750 perc=99.9 f2=$fx d2=$dx label2="Offset (m)" \
		label1="Time (s)" labelsize=26 title="One CDP gather"&

suvel2df  <junkd fv=1800 dv=$dv nv=40 offsetmax=4000 \
	tn=1.0 offsetm=4000 \
	fvh=1900 dvh=$dv nvh=40 xod=1.5 verbose=1 |
suxcontour nc=35 mpicks=picked.values  \
	d1=$dv f1=1900 d2=$dv f2=1800  \
	label1="Vh (m/s)" label2="Vnmo (m/s)" labelsize=26 \
	title="Semblance" &

echo

echo "Pick maximum semblance point by placing cursor on point"
echo "and typing:   s   and then  q "
