#! /bin/sh
# Purpose: Successively kill each of the reflectors in the standard
#	suplane "test pattern".  See README for details.
WIDTH=420
HEIGHT=400
WIDTHOFF1=0
WIDTHOFF2=430
WIDTHOFF3=860
HEIGHTOFF1=50
HEIGHTOFF2=500

amps=1,0,0,1	# In this demo, we try to kill a reflector of given slope

###MODEL###
# We make some simple data with suplane.  Note that in units of
# trace/timesample the default slopes in suplane are 0, 1, 2, so
# that the middle reflector is spatially just at Nyquist and the
# the steepest reflector is spatially aliased.
#
# In this demo, we "fool the program" (see the sudipfilt self-doc)
# by using nominal units in sudipfilt.  The data is created with
# "physical" parameters of dt=4ms and (nominally) dx=d2=0.016km=16m:
dt=1
dx=1

# First make the synthetic data for the dip filtering demo.
# Assume that trace spacing is measured in km.
suplane | sushw key=d2 a=0.016 >suplane.data

# Plot the model 
suxwigb <suplane.data title="Data: 3 sloping reflectors--Use dt=dx=1" \
	windowtitle="Data" \
	label1="Samples" label2="Trace" f1=1 d1=1 f2=1 d2=1\
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF1 &
 
# Zap the flat reflector
slopes=-1.0,-0.5,0.5,1.0
bias=0.0
sudipfilt <suplane.data dt=$dt dx=$dx \
	 slopes=$slopes amps=$amps bias=$bias |
suxwigb title="slope=$slopes amps=$amps bias=$bias" \
	windowtitle="zap flat" \
	label1="Samples" label2="Trace" f1=1 d1=1 f2=1 d2=1\
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 ybox=$HEIGHTOFF1 &

# Zap the middle reflector
slopes=0.5,0.75,1.25,1.5
bias=0.0
sudipfilt <suplane.data dt=$dt dx=$dx \
	 slopes=$slopes amps=$amps bias=$bias |
suxwigb title="slope=$slopes amps=$amps bias=$bias" \
	windowtitle="zap middle" \
	label1="Samples" label2="Trace" f1=1 d1=1 f2=1 d2=1\
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF1 &

# Zap the steep reflector
slopes=1.5,1.75,2.25,2.5
bias=0.0
sudipfilt <suplane.data dt=$dt dx=$dx \
	 slopes=$slopes amps=$amps bias=$bias |
suxwigb title="slope=$slopes amps=$amps bias=$bias" \
	windowtitle="try steep" \
	label1="Samples" label2="Trace" f1=1 d1=1 f2=1 d2=1\
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF2 &

# Failed because steep reflector is spatially aliased.  Here the
# bias parameter can help (see the sudipfilt self-doc).  Look at
# the F-K spectrum:
suspecfk <suplane.data |
suxwigb title="F-K Spectrum of Data" \
	windowtitle="F-K" \
	label1="Frequency" label2="K"\
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 ybox=$HEIGHTOFF2 &

# Try again, biasing actual slope 2 to slope 0
slopes=1.5,1.75,2.25,2.5
bias=2.0
sudipfilt <suplane.data dt=$dt dx=$dx \
	 slopes=$slopes amps=$amps bias=$bias |
suxwigb title="slope=$slopes amps=$amps bias=$bias" \
	windowtitle="zap steep" \
	label1="Samples" label2="Trace" f1=1 d1=1 f2=1 d2=1\
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF2 &

exit 0
