#! /bin/sh
# shell for uniformly sampling velocity from a layered model
set -v

nz=501 dz=5 fz=.0  labelz="Depth (m)"
nx=1000 dx=20 fx=0.0  labelx="Distance (m)"
ninf=6 npmax=201 
nt=1001
dt=0.004

#Raytrace
rayt2dan a3333file=a3333sm VP0file=VP0sm epsilonfile=epsilonsm \
deltafile=deltasm tfile=ttime fxo=0 nxo=401 dxo=50 fzo=0 nzo=51 dzo=50 fsx=0 \
nsx=200 dsx=100 nt=$nt nx=$nx nz=$nz dx=$dx dz=$dz fx=$fx fz=$fz dt=$dt fa=-75 \
na=76 amax=75 
