#! /bin/sh
# auto-correlation
# Author: Dave
set -x

### set parameters
panel=cdp371to380
cdpmin=371
cdpmax=380

### autocorrelate the selected cmp's
sugain <$panel tpow=2 |
suacor norm=1 |
suximage f2=$cdpmin d2=.033333 \
	label1="Time (sec)" title="Autocor: CMPs $cdpmin to $cdpmax" \
	perc=99 grid1=solid &
