#! /bin/ksh
# nmo, decon before stack, and stack
set -x

# set parameters
input=dmocmgs
stack=dmostack
integer cdp1=201 cdp2=800 fold=30

# nmo, decon before stack, and stack
integer count=fold*(cdp2-cdp1+1)
suwind <$input key=cdp min=$cdp1 max=$cdp2 count=$count |
sugain tpow=2 |
supef minlag=0.024 maxlag=0.250 |
sunmo par=stkvel.par |
sustack >$stack

# plot the stack
sugain <$stack gpow=0.5 |
suximage f2=$cdp1 d2=1 label2="CMP"\
        label1="Time (sec)" title="DMO Stack of CMPs $cdp1 to $cdp2" \
        perc=99 grid1=solid &
