#! /bin/ksh
# plot nmo stack for western data
# Author: Dave
set -x

# set parameters
stack=dmostack.pack
cdp1=201 cdp2=800 

suunpack2 <$stack |
sugain gpow=0.5 |
suximage f2=$cdp1 d2=1 label2="CMP"\
	label1="Time (sec)" title="DMO Stack of CMPs $cdp1 to $cdp2" \
	perc=99 grid1=solid &
