#! /bin/ksh
# Plot first break picks
# Author: Jack
# NOTE: Comment lines preceeding user input start with  #!#
#set -x

### From Firstbreak shell
cdp=601		# pick a cdp -- also used for naming output files
pickfile=fbpicks.save
#pickfile=fbpicks.$cdp

a2b <$pickfile >temp outpar=picks.p

xgraph <temp par=picks.p nplot=1 \
	label1="Time (sec)" label2="Distance" \
	title="First Breaks" \
	grid1=solid grid2=solid \
	linecolor=2 style=seismic &

### Clean up
rm temp
