#! /bin/ksh
# Plot deconvolution test panels for an input cmp gather
# Authors: Jack, Ken
set -x

### From Decontest
cdp=601  # pick a cdp -- also used for naming output files
fold=30
space=6  # 6 null traces between panels
deconpanel=decon.$cdp

### Plot deconvolution test panels
f2=0
d2=$(bc -l <<-END
	scale=5; 1/($fold + $space)
END)

sugain <$deconpanel tpow=1 gpow=.5 |
suxwigb f2=$f2 d2=$d2 perc=99 wbox=900 \
	title="File: $input  Deconvolution Test"  \
	label1="Time (s)"  label2="Deconvolution Test Number" &

#supswigb f2=$f2 d2=$d2 perc=99 \
#	title="File: $input  Deconvolution Test"  \
#	label1="Time (s)"  label2="Deconvolution Test Number" |
#rsh keller pwin
