#! /bin/ksh
# plot migration for western data
# Author: Dave

# set parameters
migdata=dmomig
dxcdp=13.36

# X plot
sugain <$migdata gpow=0.8 |
suximage f2=0.0 d2=0.01336 \
	label1="Time (sec)" label2="Distance (km)" \
	title="Migrated DMO Stack" perc=99 grid1=solid &
