#! /bin/ksh
# Plot dmocogs for western data
# Author: Dave
set -x

# plot common-offset gathers
suwind <dmocogs key=tracf min=1 max=4 count=600 |
sugain tpow=2 gpow=0.5 |
suximage f2=201 d2=1 \
	label1="Time (sec)" title="Dmo common-offset gather" \
	perc=99 grid1=solid &

# plot common-offset gathers
suwind <dmocmgs key=tracf min=1 max=4 count=600 |
sugain tpow=2 gpow=0.5 |
suximage f2=201 d2=1 \
	label1="Time (sec)" title="Dmo common-midpoint gathers" \
	perc=99 grid1=solid &
