#! /bin/ksh
# Plot filter panels created by Filtertest for an input cmp gather
# Authors: Jack, Ken
#set -x

### From Filtertest
cdp=601		# pick a cdp -- also used for naming output files
fold=30
space=6		# 6 null traces between panels
filpanel=fil.$cdp

### Plot filter panels
f2=0
d2=$(bc -l <<-END
	1/($fold + $space)
END)

suxwigb f2=$f2 d2=$d2 perc=98  \
	wbox=800 \
	title="File: $filpanel  Filter Test "  \
	label1="Time (s)"  label2="Filter Number" & 

sugain <$filpanel tpow=2.0 gpow=.5 |
supswigb f2=$f2 d2=$d2 perc=98  \
	title="File: $filpanel  Filter Test "  \
	label1="Time (s)"  label2="Filter Number" |
rsh keller pwin
