#! /bin/ksh
# shell to compute and plot 2-D spectrum for one of Oz's shot records
# Author: Jack

panel=cdp371to380
cdpmin=371

### get 2d spectrum of the selected cmp's
sugain <$panel tpow=2 gpow=0.3 |
sushw key=d2 a=.008 |
suspec2 |
suximage \
	title="2-D Transform of $panel" \
	label1="Frequency (Hz)" label2="Wavenumber (cycles/km)" \
	perc=98 grid1=solid grid2=solid &
