#! /bin/sh
# Invert the data created by CSHOT

recordfile=record

################
cd inversion.dir	# where inversion files are
################

echo "Run time information being stored in file:  $recordfile"
>$recordfile

(

	### Preprocessing
	rm -f DATA1
	cz1in <data1in
	rm -f PTRACES
	cz1

	### Inversion
	cxzco

) > $recordfile 2>&1


### Move record up to demo directory
mv -f $recordfile ..
echo "run time info now in file:  $recordfile"

### Plotting the section
ftnstrip <mara |
xmovie  n1=301 n2=250 f1=0.0 d1=40 f2=200 d2=80 perc=99 \
	-geometry 560x430+50+570 \
	title="Inversion of Marathon model" \
	label1="Depth (ft)"  label2="Range (ft)" &
