#! /bin/sh
# nmo correct the data, stack and apply bulk statics


#nmo correct data
###########################################################
sustkvel v=1640,9840,11480,13120 \
         h=100,2900,2000,2000 outpar=stkpar

sunmo < data_res.su par=stkpar > data_res_nmo.su
###########################################################


#stack the nmo-corrected data
###########################################################
susort < data_res_nmo.su | sustack normpow=1.0 key=cdp | \
suchw key1=sx key2=cdp a=0 b=1 c=0 d=1 | suchw key1=gx \
key2=cdp a=0 b=1 c=0 d=1 > data_stk.su
###########################################################


#apply bulk static shift to stacked data
###########################################################
sustaticrrs < data_stk.su > data_stk_bulk.su hdrs=5
###########################################################


#mute stack to keep full fold region only
###########################################################
sumute < data_stk_bulk.su > data_stk_bulk1.su \
xmute=0,4900,4950,19950,20000,32800 \
tmute=1.5,1.5,0.0,0.0,1.5,1.5 key=cdp
mv data_stk_bulk1.su data_stk_bulk.su
##########################################################

rm -f data_res_nmo.su

exit 0
