#! /bin/sh

suwind < data.su key=cdp min=11000 max=11000 | supswigp \
title="CMP gather - midpoint at 11000 ft" label1="Time (s)" \
label2="Offset (ft)" f2=10000 d2=-200 > cmp_11000_raw.ps

suwind < data_res.su key=cdp min=11000 max=11000 | supswigb \
title="CMP gather - midpoint at 11000 ft after residual refraction statics" \
label1="Time (s)" label2="Offset (ft)" f2=10000 d2=-200 > cmp_11000_rrs.ps

supsimage < data_stk.su title="Stack after residual refraction statics" \
label1="Time (s)" label2="Surface location (ft)" f2=0 d2=50 \
x2beg=4900 x2end=19950 > stk.ps

supsimage < data_stk_bulk.su \
title="Stack after residual refraction and bulk statics" \
label1="Time (s)" label2="Surface location (ft)" f2=0 d2=50 \
x2beg=4900 x2end=19950 > stk_bulk.ps

exit 0
