#! /bin/sh
# residual refraction statics script

# generate surfaces
##############################################################

make 

surfmaker

a2b < blvl_file.dat n1=1 > blvl_file.b
a2b < refr_file.dat n1=1 > refr_file.b
a2b < vel_file.dat n1=1 > vel_file.b

rm blvl_file.dat
rm refr_file.dat
rm vel_file.dat
##############################################################



#compute and apply residual refraction statics from
#user defined model
##############################################################
sustaticrrs < data.su > data_res.su hdrs=3 \
blvl_file=blvl_file.b refr_file=refr_file.b nsamp=657 \
fx=0.0 dx=50.0 V_r=9840.0 mx=657 mz=76 \
dzv=2.0 vfile=vel_file.b

sustaticrrs < data_res.su > data_res_2.su hdrs=4 nsamp=657 \
fx=0.0 dx=50.0

mv data_res_2.su data_res.su
rm -f data_res_2.su
#############################################################
exit 0
