#! /bin/sh

suwind < data.su key=cdp min=11000 max=11000 | suxwigb \
title="CMP gather - midpoint at 11000 ft" label1="Time (s)" \
xbox=20 ybox=20 wbox=400 hbox=400 \
label2="Offset (ft)" f2=10000 d2=-200 &

suwind < data_res.su key=cdp min=11000 max=11000 | suxwigb \
title="CMP gather - midpoint at 11000 ft after residual refraction statics" \
xbox=450 ybox=20 wbox=400 hbox=400 \
label1="Time (s)" label2="Offset (ft)" f2=10000 d2=-200 &

suximage < data_stk.su title="Stack after residual refraction statics" \
label1="Time (s)" label2="Surface location (ft)" f2=0 d2=50 \
xbox=20 ybox=520 wbox=400 hbox=400 \
x2beg=4900 x2end=19950 &

suximage < data_stk_bulk.su \
title="Stack after residual refraction and bulk statics" \
label1="Time (s)" label2="Surface location (ft)" f2=0 d2=50 \
xbox=450 ybox=520 wbox=400 hbox=400 \
x2beg=4900 x2end=19950 &

exit 0
