#! /bin/sh
# Run CSHOT with CWP X Graphics

demo=12

x1beg=-500 x1end=7500 x2beg=0 x2end=12000

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par

xgraph <demo${demo}plot par=demo${demo}par  \
	-geometry 600x400+650+0 \
	title="Primary Rays" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

cshot2

ftnstrip < demo${demo}traces | suaddhead ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Offset VSP (agc)" \
	ybox=70 \
	label1="Time in Seconds" label2="Trace" &
