#! /bin/sh
demo=decon2

tpow=1		# gain power before examining autocorrelations
		# tpow=2 would often be better for field data

###PURPOSE###
# Same as in demo1, except here gapped decon comes before
# spiking decon.  Again, you are to assume that the decon
# parameters are estimated from the autocorrelation shown in
# frame two.  Also see demo1 for the comments on making the data.
	
# First make the synthetic data for the deconvolution demo.
######START OF MODEL######
I=${CWPROOT}/include
L=${CWPROOT}/lib

make

./traces |
suaddhead ns=512 |
sushw key=dt a=4000 |
suaddnoise sn=200 |
suconv filter=1152,-384,-904,288,174,-34,-12 >modeldata

rm traces
######END OF MODEL######

# Plot the model
supswigp <modeldata title="Model Data: 64ms reverbs" \
	label1="Time (sec)" label2="Trace" >${demo}.1.eps

# Plot the autocorrelation with gain
sugain <modeldata tpow=$tpow |
suacor nt=31 |
supswigp title="Autocorrelation (with gain)" \
	label1="Time (sec)" label2="Trace" >${demo}.2.eps

# The autocorrelation shows that:
#       wavelet extends to about 30ms
#	first repetition ends at about 160ms
# this accords well with the actual 64ms reverberations and wavelet of 24ms


######DECON EXAMPLES######
# Attack reverberations
supef <modeldata minlag=.05 maxlag=.16 |
supswigp label1="Time"  label2="Trace" title="PEF: 50,160ms" >${demo}.3.eps

# Plot the autocorrelation after PEF
supef <modeldata minlag=.05 maxlag=.16 |
sugain pbal=1 |
suacor nt=31 |
supswigp title="Autocorrelation after PEF (with gain)" \
	label1="Time (sec)" label2="Trace" >${demo}.4.eps

# Spike it up
supef <modeldata minlag=.05 maxlag=.16 |
supef maxlag=.04 |
supswigp label1="Time"  label2="Trace" title="Spike: 4,40ms" >${demo}.5.eps

# Bandpass
supef <modeldata minlag=.05 maxlag=.16 |
supef maxlag=.04 |
sufilter f=5,15,80,100 |
supswigp label1="Time"  label2="Trace" \
title="Band pass after PEF & Spike" >${demo}.6.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0
