#! /bin/sh
WIDTH=420
HEIGHT=400
WIDTHOFF1=0
WIDTHOFF2=430
WIDTHOFF3=860
HEIGHTOFF1=50
HEIGHTOFF2=500

tpow=1		# gain power before examining autocorrelations
		# tpow=2 might be better for field data
mix=1,1,1

###PURPOSE###
# Same as in demo1, except here gapped decon comes before
# spiking decon.  Again, you are to assume that the decon
# parameters are estimated from the autocorrelation shown in
# frame two.  Also see demo1 for the comments on making the data.


# First make the synthetic data for the deconvolution demo.
######START OF MODEL######
I=${CWPROOT}/include
L=${CWPROOT}/lib

make

./traces |
suaddhead ns=512 |
sushw key=dt a=4000 |
suaddnoise sn=2000 |
suconv filter=1152,-384,-904,288,174,-34,-12 >modeldata

rm traces
######END OF MODEL######

# Plot the model 
suxwigb <modeldata title="Data: 64ms reverbs" \
	windowtitle="Data" \
	label1="Time (sec)" label2="Trace" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF1 &
 
# Plot the autocorrelation with gain
sugain <modeldata tpow=$tpow |
suacor nt=31 |
suxwigb title="Autocorrelation" \
	windowtitle="AutoCorr" \
	label1="Time (sec)" label2="Trace" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 ybox=$HEIGHTOFF1 &

# The autocorrelation shows that:
#       wavelet extends to about 30ms
#	first repetition ends at about 160ms
# this accords well with the actual 64ms reverberations and wavelet of 24ms


 
######DECON EXAMPLES######
# Attack reverberations
supef pnoise=0.0005 mix=$mix <modeldata minlag=.05 maxlag=.16 |
suxwigb label1="Time"  label2="Trace" title="PEF: 50,160ms" \
	windowtitle="PEF" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF1 &

# Plot the autocorrelation after PEF
supef pnoise=0.0005 mix=$mix <modeldata minlag=.05 maxlag=.16 |
sugain pbal=1 |
suacor nt=31 |
suxwigb title="Autocor after PEF" \
	windowtitle="AutoCorr/PEF" \
	label1="Time (sec)" label2="Trace" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF2 &

# Spike it up
supef pnoise=0.0005 mix=$mix <modeldata minlag=.05 maxlag=.16 |
supef pnoise=0.0005 mix=$mix maxlag=.04 |
suxwigb label1="Time"  label2="Trace" title="Spike: 4,40ms" \
	windowtitle="Spike" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 ybox=$HEIGHTOFF2 &

# Bandpass
supef pnoise=0.0005 mix=$mix <modeldata minlag=.05 maxlag=.16 |
supef pnoise=0.0005 mix=$mix maxlag=.04 |
sufilter f=5,15,80,100 |
suxwigb label1="Time"  label2="Trace" title="PEF, Spike, BP" \
	windowtitle="Final" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF2 &

exit 0
