#! /bin/sh

echo "running    sugain < modeldata scale=10 > junk.su"
echo 
echo 

time sugain < modeldata scale=10 > /dev/null


echo 
echo 
echo "Compare the above times with the same program run with"
echo "sucommand, with pipes initiated by change in fldr header field"
echo 
echo 

time sucommand < modeldata key=fldr command="sugain scale=10" dir=0 > /dev/null
echo 
echo 

echo 
echo 
echo "Compare the above times with the same program run with"
echo "sucommand, with pipes initiated by change in order of tracf"
echo 
echo 

echo 
echo 
time sucommand < modeldata key=tracf command="sugain scale=10" dir=+1 > /dev/null

echo 
echo 
exit 0

