#! /bin/sh

vmig=5.0
dxcdp=.008
tmig=0.0
np=5

# conventional divergence correction
sudivcor <  data.seis trms=$trms vrms=$vrms  > data.divcor

# dip dependent divergence correction
sudipdivcor <  data.seis np=$np tmig=$tmig vmig=$vmig dxcdp=$dxcdp > data.dipdivcor

exit 0
