#! /bin/sh
# create model data with susynlv


# The folowing shell generates 126 CMP gathers, each with 125 traces

# 
REF1="1.0:-1,0.2;4,0.2"
REF2="1.0:-2,2.0199;3.5495,0"
REF3="1.0:-2,4.3955;3.2384,0"
REF4="1.0:-2,8.8603;3.1155,0"
REF5="1.0:-2,29.3564;3.1763,0" 
##############################################


dvdz=.001  # velocity gradient (dv/dz)
v00=5.0  # P-wave velocity at surface (S-wave velocity for GAMM>>1) in km/s
nxo=300    # number of traces per CMP gather
fxo=0.016 dxo=0.008 
nxm=1 fxm=1.000 dxm=0.004   # to make 1 cdp gather

nt=250 dt=0.004 

susynlv v00=$v00 ndpfz=10 dvdz=$dvdz \
		dt=$dt nt=$nt verbose=1 \
		ref=$REF1 ref=$REF2 ref=$REF3 ref=$REF4 ref=$REF5 \
		nxo=$nxo fxo=$fxo dxo=$dxo \
		nxm=$nxm fxm=$fxm dxm=$dxm  > data.seis
