#! /bin/sh
# PostScript output



PSPREV=$PSPREVIEWER

demo=1

# plot input data
supsimage < data.seis  \
	label1="time (s)" label2="Midpoint (m)" \
	title="Input Data" > demo${demo}.1.eps

# plot output data
supsimage < data.divcor \
	label1="time (s)" label2="Midpoint (m)" \
	title="Conventional Diverg. Corr" > demo${demo}.2.eps

# plot output data
supsimage < data.dipdivcor \
	label1="Depth (m)" label2="Midpoint (m)" \
	title="Dip-dependent Diverg. Corr." > demo${demo}.3.eps


if test "$PSPREV" != ""
then
	echo "Previewing PostScript files with $PSPREV"
	for i in *.eps
	do
		$PSPREV < $i &
	done
else
	echo "PostScript previewer environment variable"
	echo "PSPREVIEWER not set"
fi

exit 0

