#! /bin/sh
# shell for viewing data using X-windows graphics
WIDTH=300
HEIGHT=300
XOFF1=0
YOFF1=0
XOFF2=450
YOFF2=450


# plot velocity profile
suximage < data.seis  \
	label1="time (s)" label2="Midpoint (m)" \
	hbox=$HEIGHT wbox=$WIDTH \
	xbox=$XOFF1 ybox=$YOFF1 \
	title="Input Data" &

suximage < data.divcor \
	label1="time (s)" label2="Midpoint (m)" \
	hbox=$HEIGHT wbox=$WIDTH \
	xbox=$XOFF2 ybox=$YOFF1 \
	title="Conventional Divergence Corr." &

suximage < data.dipdivcor  \
	label1="time (s)" label2="Midpoint (m)" \
	hbox=$HEIGHT wbox=$WIDTH \
	xbox=$XOFF2 ybox=$YOFF2 \
	title="Dip-dependent Divergence Corr." &


exit 0
