#! /bin/sh
# make velocity
set -x

nx=121 fx=0.00 dx=50 nz=51 fz=0.00 dz=50
v000=1500 dvdz=0.2 dvdx=0.3
l1c=1000 l2c=2000 exc=1
vlens=1000 tlens=1000 dlens=2500
xlens=2500 ylens=0 zlens=800
vzc=500 

makevel nx=$nx fx=$fx dx=$dx nz=$nz fz=$fz dz=$dz \
	v000=$v000 dvdz=$dvdz dvdx=$dvdx \
	l1c=$l1c l2c=$l2c exc=$exc \
	vlens=$vlens tlens=$tlens dlens=$dlens \
	xlens=$xlens ylens=$ylens zlens=$zlens \
	vzc=$vzc >data.v

exit 0
