#! /bin/sh
# shell for Kirchhoff modeling for arbitrary v(x,z)
demo=synvxz

nx=121 nz=51 dx=50 dz=50 fx=0.00 fz=0.00 

# plot velocity profile
psimage <data.v \
	n2=$nx n1=$nz d1=$dz d2=$dx f2=$fx perc=100 \
	label1="Depth (m)" label2="Midpoint (m)" \
	title="Velocity" >${demo}.1.eps

# window and plot synthetic seismograms on the screen
suwind<data.su key=offset min=0 max=0 |
supsimage  perc=99 \
	label1="Time (sec)" label2="Midpoint (m)" grid1=solid \
	title="Data (offset = 0 m)" >${demo}.2.eps

suwind<data.su key=offset min=1000 max=1000|
supsimage  perc=99\
	label1="Time (sec)" label2="Midpoint (m)" grid1=solid \
	title="Data (offset = 1000 m)" >${demo}.3.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0
