#! /bin/sh
# shell for Kirchhoff modeling for arbitrary v(x,z)

nx=121 nz=51 dx=50 dz=50 fx=0.00 fz=0.00 

# plot velocity profile
xmovie <data.v \
	n2=$nx n1=$nz d1=$dz d2=$dx f2=$fx perc=100 \
	label1="Depth (m)" label2="Midpoint (m)" \
	title="Velocity Model" \
	-geometry 600x250+0+25 &

# window and plot synthetic seismograms on the screen
suwind <data.su key=offset min=0 max=0 count=331 |
suxmovie perc=99 f2=1 d2=1\
	label1="Time (sec)" label2="Trace" \
	title="Offset: 0 m" \
	-geometry 550x400+650+25 &

suwind <data.su key=offset min=1000 max=1000 count=331 |
suxmovie perc=99 f2=1 d2=1\
	label1="Time (sec)" label2="Trace" \
	title="Offset: 1000 m" \
	-geometry 550x400+650+500 &

exit 0
