#! /bin/sh

demo=4

x1beg=0 x1end=10000

############
cd model.dir	# where model stuff is
############

# Examine model with CSHOT, use CWP X Graphics for display
cp param1.model param1

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 560x430+650+75 \
	title="Syncline: Model Plot " \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end &


# Build synthetic data with CSHOT, display with CWP X Graphics

# Make time section information
echo "Making time section (takes time) ..."

cp param1.traces param1
cshot1 >/dev/null

# Make time section
cshot2

# Move data to the inversion directory
mv demo${demo}traces ../inversion.dir

cd ../inversion.dir

# Display section
ftnstrip <demo${demo}traces | suaddhead ns=501 |
sushw key=dt a=4000 |
suxmovie d2=80 f2=1000 perc=98 \
	-geometry 560x430+50+75 \
	title="Syncline: Time Section" \
	label1="Time(secs)" label2="location(ft)" &

echo "Synthetic data generated"
echo "type:     Inversion       to run inversion demo"

exit 0
