#! /bin/sh
# Sufdmod2 --- example script for sufdmod2
# finite-difference modeling, part 2 the output files
# Author: John Stockwell
WIDTH=450
HEIGHT=450
WIDTHOFF1=50
WIDTHOFF2=530
HEIGHTOFF1=50
HEIGHTOFF2=530

suximage <vseis.out clip=1.0 \
	title="Vertical line of seismograms" \
	windowtitle="Vertical" \
	label1="Time (sec)" label2="Depth (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF2}+${HEIGHTOFF1} &

suximage <hseis.out clip=1.0 \
	title="Horizontal line of seismograms" \
	windowtitle="Horizontal" \
	label1="Time (sec)" label2="Distance (km)" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF2} &

suxwigb <sseis.out  \
	title="Source point seismogram" \
	windowtitle="Source" \
	label1="Time (sec)" label2="Trace" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF2} ybox=${HEIGHTOFF2} &

exit 0
