#! /bin/sh
# Sufdmod2 --- example script for sufdmod2
# finite-difference modeling: part 1, the movie
# Author: John Stockwell
WIDTH=450
HEIGHT=450
WIDTHOFF1=10
WIDTHOFF2=500
HEIGHTOFF1=50
HEIGHTOFF2=530

n1=100 d1=5 f1=0.0 label1="Depth (km)"
n2=100 d2=5 f2=0.0 label2="Distance (km)"
xs=250 zs=50 hsz=50 vsx=250 verbose=2
vsfile="vseis.out" ssfile="sseis.out" hsfile="hseis.out"
tmax=.4 mt=5 fpeak=35 fmax=40

#makevel nx=$n2 nz=$n1 v000=3000 >vel.out
unif2 tfile=model.out
unif2 < model.out n1=$n1 n2=$n2 method=spline > vel.out

ximage < vel.out wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 title="Wavespeed Profile" \
 n1=$n1 n2=$n2 legend=1 lheight=150 units="wave speed" &

sufdmod2 <vel.out nz=$n1 dz=$d1 nx=$n2 dx=$d2 verbose=1 \
	fpeak=$fpeak fmax=$fmax \
	xs=$xs zs=$zs hsz=$hsz vsx=$vsx hsfile=$hsfile \
	vsfile=$vsfile ssfile=$ssfile verbose=$verbose \
	tmax=$tmax abs=1,1,1,1 mt=$mt |
suxmovie  clip=1.0 \
	title="Acoustic Finite-Differencing" \
	windowtitle="Movie" \
	label1="$label1" label2="$label2" \
	n1=$n1 d1=$d1 f1=$f1 n2=$n2 d2=$d2 f2=$f2 \
	cmap=gray loop=1 \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF1}+${HEIGHTOFF1} &

exit 0
