 
################ makefile.depend ##################
 
############## fortran dependencies ###############
 
 
################ xml dependencies #################
 
 
############# c and c++ dependencies ##############
 

initusage.o:					\
		initusage.c			\
		initusage.h
 
################ end dependencies #################
 
