#! /bin/sh
# Compute figures 2 through 6 from CWP 153 paper by
# Anderson, Alkhalifah, and Tsvankin
#  several minutes of compute time

testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=1 dx=25 h=200 v=1500 \
file=vnmotable | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>isotropic_hale.eps

sutivel a=1500 b=750 d=0.0 e=0. >vnmotable
testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=5 dx=25 h=200 \
file=vnmotable | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>isotropic_tsvankin.eps


testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=2 dx=25 h=200 v=1500\
file=vnmotable | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>bleistein.eps


sutivel a=1500 b=750 d=0.1 e=0.2 >vnmotable
testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=5 dx=25 h=200 \
file=vnmotable | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>tsvankin21.eps


sutivel a=1500 b=750 d=0.2 e=0.2 >vnmotable
testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=5 dx=25 h=200 \
file=vnmotable | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>tsvankin22.eps


testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=6 dx=25 h=200 \
e=.2 d=.2 | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>weak22.eps

testtihaledmo | sufilter f=20,40,50,60  amps=1.,1.,0.,0. | \
sutihaledmo nxmax=33 option=6 dx=25 h=200 \
e=.2 d=.1 | supswigp label1="Time (s)" label2="Midpoint (km)" \
d1num=.05 x1end=0.25 \
>weak21.eps
