#! /bin/sh
# Compute figures 11 and 12 from CWP 153 paper by
# Anderson, Alkhalifah, and Tsvankin
#  (several hours of compute time)

offmin=0 offmax=3000 doffset=100
offset=0 h=0

# generate TI synthetic common midpoint gathers
susynlvfti >cmpgathers.su delta=0.05 epsilon=0.2 v00=3.0 fpeak=10 \
dxo=0.1 nxo=31 dxm=0.025 nxm=401 dt=0.010 nt=601 dvdz=0 dvdx=0 \
ref="1:2.0,1.0,2.34641,1.2;3.5,1.2" \
ref="1:1.8,1.0,2.3,1.5;3.5,1.5" \
ref="1:1.6,1.0,2.17735,2.0;3.5,2.0" \
ref="1:1.4,1.0,1.8,2.5;3.5,2.5" \
ref="1:1.2,1.0,1.2,3.0;3.5,3.0"

# do ti dmo on all of the data, one common offset at a time
sutivel a=3000 b=1000 d=0.05 e=0.2 >vnmotable
offset=$offmin
while [ "$offset" -le "$offmax" ]
do

	# compute h = $offset/2
	h=`bc -l <<-END
		scale=4
		$offset / 2
	END`


	suwind < cmpgathers.su key=offset min=$offset  max=$offset |\
	sunmo vnmo=3146 | \
	sutihaledmo option=5 nxmax=401 dx=25 file=vnmotable h=$h \
	>>tidmocogs.su

	# compute offset = offset+doffset
	offset=`bc -l <<-END
		scale=4
		$offset + $doffset
	END`

done

exit

# do isotropic dmo on all the data, one common offset at a time
offset=$offmin
while [ "$offset" -le "$offmax" ]
do

	# compute h = $offset/2
	h=`bc -l <<-END
		scale=4
		$offset / 2
	END`


	suwind < cmpgathers.su key=offset min=$offset  max=$offset |\
	sunmo vnmo=3146 | \
	sutihaledmo option=1 nxmax=401 dx=25 h=$h \
	>>dmocogs.su

	# compute offset = offset+doffset
	offset=`bc -l <<-END
		scale=4
		$offset + $doffset
	END`


done

# Plot a CMP gather at location 3.6 km after TI DMO
suwind <tidmocogs.su key=cdp min=144 max=144 count=31 |
supswigp \
	label1="Time (s)" \
	label2="Offset (km)" x1beg=1 x1end=2.7 \
	f2=0 d2=0.1 \
	perc=99. grid1=solid >TIDMOmodelgather.eps

# Plot a CMP gather at location 3.6 km after isotropic DMO
suwind <dmocogs.su key=cdp min=144 max=144 count=31 |
supswigp  \
	label1="Time (s)" \
	label2="Offset (km)" x1beg=1 x1end=2.7 \
	f2=0 d2=0.1 \
	perc=99. grid1=solid >DMOmodelgather.eps

exit
