#! /bin/sh
# Compute figures 11 and 12 from CWP 153 paper by
# Anderson, Alkhalifah, and Tsvankin
# (approx. 20 minutes of compute time on an IBM RS6000 model 530)

# make synthetic data with 30, 45, 60, 80, and 90 degree dips
# for offset 0 km
susynlvfti \
delta=0.05 epsilon=0.2 v00=2 fpeak=10 fxo=0 \
dxm=0.025 nxm=401 dt=0.010 nt=601 dvdz=0 dvdx=0 \
ref="1:2.0,1.0,2.34641,1.2;3.5,1.2" \
ref="1:1.8,1.0,2.3,1.5;3.5,1.5" \
ref="1:1.6,1.0,2.17735,2.0;3.5,2.0" \
ref="1:1.4,1.0,1.8,2.5;3.5,2.5" \
ref="1:1.2,1.0,1.2,3.0;3.5,3.0" | \
supsimage label1="Time (s)" label2="Midpoint (km)" \
d1num=1 x1end=3.5 n1tic=2 grid1=solid grid2=solid \
d2=0.025 f2=0.0 x2end=5.0 perc=99.5 f2num=0.0 d2num=1.0 n2tic=5 labelsize=32 \
>model0.eps


# make synthetic data with 30, 45, 60, 80, and 90 degree dips
# for offset 1.5 km
susynlvfti \
delta=0.05 epsilon=0.2 v00=2 fpeak=10 fxo=1.5 \
dxm=0.025 nxm=401 dt=0.010 nt=601 dvdz=0 dvdx=0 \
ref="1:2.0,1.0,2.34641,1.2;3.5,1.2" \
ref="1:1.8,1.0,2.3,1.5;3.5,1.5" \
ref="1:1.6,1.0,2.17735,2.0;3.5,2.0" \
ref="1:1.4,1.0,1.8,2.5;3.5,2.5" \
ref="1:1.2,1.0,1.2,3.0;3.5,3.0" >model1.5.su

supsimage <model1.5.su label1="Time (s)" label2="Midpoint (km)" \
d1num=1 x1end=3.5 n1tic=2 grid1=solid grid2=solid \
d2=0.025 f2=0.0 x2end=5.0 perc=99.5 f2num=0.0 d2num=1.0 n2tic=5 labelsize=32 \
>model1.5.eps

# NMO correct the 1.5 km offset data
sunmo <model1.5.su vnmo=2097 >NMOmodel1.5.su

supsimage <NMOmodel1.5.su label1="Time (s)" label2="Midpoint (km)" \
d1num=1 x1end=3.5 n1tic=2 grid1=solid grid2=solid \
d2=0.025 f2=0.0 x2end=5.0 perc=99.5 f2num=0.0 d2num=1.0 n2tic=5 labelsize=32 \
>NMOmodel1.5.eps

# run TI DMO
sutivel a=2000 b=1000 d=0.1 e=0.2 >vnmotable
sutihaledmo <NMOmodel1.5.su >TIDMOmodel1.5.su \
nxmax=401 option=5 dx=25 h=750 file=vnmotable

supsimage <TIDMOmodel1.5.su label1="Time (s)" label2="Midpoint (km)" \
d1num=1 x1end=3.5 n1tic=2 grid1=solid grid2=solid \
d2=0.025 f2=0.0 x2end=5.0 perc=99.5 f2num=0.0 d2num=1.0 n2tic=5 labelsize=32 \
>TIDMOmodel1.5.eps

# run isotropic DMO
sutihaledmo <NMOmodel1.5.su >DMOmodel1.5.su \
nxmax=401 option=1 dx=25 h=750 file=vnmotable

supsimage <DMOmodel1.5.su label1="Time (s)" label2="Midpoint (km)" \
d1num=1 x1end=3.5 n1tic=2 grid1=solid grid2=solid \
d2=0.025 f2=0.0 x2end=5.0 perc=99.5 f2num=0.0 d2num=1.0 n2tic=5 labelsize=32 \
>DMOmodel1.5.eps

exit 0
