#! /bin/sh
#### Create Figure 17 in the GBmod documentation
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL PSdemo
#------------------------------------------------


datadir=../../datadir/
modelfile=${datadir}model.data

##### Generate Finite-Offset section
fg=0.6

nangle=130 nxz=401 fangle=-65 langle=65
nt=101 dt=0.025 bw=0 ft=0.0

#### create zero offset section
triseis <$modelfile  xs=0,4 zs=0,0 xg=0,4 zg=0,0 \
	nangle=$nangle fangle=$fangle langle=$langle \
	kreflect=2 krecord=1 fpeak=8 lscale=0.5 \
	ns=101 fs=0 ds=0.04 dgds=1 bw=$bw \
        ng=1 fg=$fg dg=0 nt=$nt dt=$dt ft=$ft |
pswigb  n1=101 d1=$dt f1=$ft x1end=2.5 \
	n2=101 d2=0.04 f2=0 grid1=none \
 	perc=100 xcur=3.0 title="Finite-offset data" \
 	hbox=4 wbox=6 label1="Time (sec)" \
	label2="Midpoint (km)" |$PSPREVIEWER

exit 0
