#! /bin/sh

Hz=.
nxhz=3		
nyhz=3 
nhz=1

tetrafile=$Hz/tetrafile3.grid
hzfile=$Hz/hzfile3.grid

tetramod verbose=1 nhz=$nhz  \
	nxhz=$nxhz nyhz=$nyhz \
	z00=0 \
	z01=0 \
	z10=0 \
	z11=0 \
	v00=2 \
	v01=2 \
	v10=2 \
	v11=2 \
	dvdz00=1.0 \
	dvdz01=1.0 \
	dvdz10=1.0 \
	dvdz11=1.0 \
	hzfile=$hzfile > $tetrafile

exit 0
