#! /bin/sh

Hz=.

hzfile=$Hz/hzfile3.grid
tetrafile=$Hz/tetrafile3.grid

ntakeoff=9
nazimuth=19
ifwf2dump=1
nwf2dump=7

rayfile=$Hz/rayfile3.grid
ttfile=$Hz/ttfile3.su
wffile=$Hz/wffile3.grid
sttfile=$Hz/sttfile3.grid

sutetraray verbose=1 ntakeoff=$ntakeoff nazimuth=$nazimuth \
	edgemax=2.0 jpfile=$Hz/output.txt fsz=0.25\
        fsx=0.99 fsy=0.99 nxt=4 nyt=4\
	wffile=$wffile idumpwf=$idumpwf tmax=7\
	rayfile=$rayfile dtwf=0.05 takeoff=80\
	< $tetrafile > $ttfile ifwf2dump=$ifwf2dump \
        nwf2dump=$nwf2dump sttfile=$sttfile

exit 0
