#! /bin/sh
# PostScript output 

demo=wkbj

nx=121 nz=51 dx=50 dz=50 fx=0.00 fz=0.00 

psimage < data.v \
	n2=$nx n1=$nz d1=$dz d2=$dx f2=$fx perc=100 \
	label1="Depth (m)" label2="Midpoint (m)" \
	title="Velocity" >${demo}.1.eps

nz=51 dz=50 fz=0.0 xs=1500 labelz="Depth (m)"
nx=121 dx=50 fx=-1500 zs=0 labelx="Distance (m)"

psimage <tfile  \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	title="First-Arrival Time"   >${demo}.2.eps

psimage <afile \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	title="Propagation Angle"   >${demo}.3.eps

psimage <sfile  \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	title="Sigma"  >${demo}.4.eps 

psimage <bfile \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	title="Incident Angle (Ray Path)" >${demo}.5.eps

echo 
echo "Output PostScript files:"

echo -n "     "
for i in ${demo}.*.eps
do
	 echo -n "$i "
done
echo
echo "You may view these with your PostScript Previewer"

exit 0

