#! /bin/sh
# shell for  finite-difference solutions 
set -v

xs=1500 zs=0
nz=51 fz=0.0 dz=50
nx=121 dx=50 fx=-1500

wkbj <data.v >tfile  xs=$xs zs=$zs \
	nz=$nz dz=$dz fz=$fz nx=$nx dx=$dx fx=$fx

exit 0
