#! /bin/sh
# X windows plot of output

nx=121 nz=51 dx=50 dz=50 fx=0.00 fz=0.00 

xmovie <data.v -geometry 600x250+0+25 \
	n2=$nx n1=$nz d1=$dz d2=$dx f2=$fx perc=100 \
	label1="Depth (m)" label2="Midpoint (m)" cmap=gray \
	title="Velocity" &

nz=51 dz=50 fz=0.0 xs=1500 labelz="Depth (m)"
nx=121 dx=50 fx=-1500 zs=0 labelx="Distance (m)"

xmovie <tfile -geometry 600x250+0+325 \
	n1=$nz d1=$dz f1=$fz label1="$labelz" \
	n2=$nx d2=$dx f2=$fx label2="$labelx" cmap=default \
	title="First-Arrival Time" & 
xmovie <afile -geometry 600x250+650+25 \
	n1=$nz d1=$dz f1=$fz label1="$labelz" \
	n2=$nx d2=$dx f2=$fx label2="$labelx" cmap=default \
	title="Propagation Angle" & 
xmovie <sfile -geometry 600x250+650+320 \
	n1=$nz d1=$dz f1=$fz label1="$labelz" \
	n2=$nx d2=$dx f2=$fx label2="$labelx" cmap=hue \
	title="Sigma" &
xmovie <bfile -geometry 600x250+650+625 \
	n1=$nz d1=$dz f1=$fz label1="$labelz" \
	n2=$nx d2=$dx f2=$fx label2="$labelx" cmap=default \
	title="Incident Angle (Ray Path)" & 

exit 0

