#! /bin/sh
# Fimpulse -- view impulse responses
# output is in the form of PostScript files
#

# compile testtifowler
make


# Post-stack migration response 
./testtifowler v=3000 dt=0.004 nspk=4 t1=0.10 t2=0.25 t3=0.50 t4=0.75 | \
sufilter f=20,50,70,80  amps=1.,1.,0.,0. | \
sutifowler choose=3 option=2 vmin=3000 vmax=3000 nv=1  \
etamin=0.15 etamax=0.0 neta=1 salias=0.0  \
dx=25 lbtaber=0 lstaper=0 ncdps=33 | \
supswigp \
        label1="Time (s)" grid1=solid \
        label2="Midpoint (km)" \
        f2=0 d2=0.025 \
        perc=99.  >fdmoa.eps 

exit

# Compute impulse DMO response
testtifowler v=3000 dt=0.004 nspk=4 t1=0.10 t2=0.25 t3=0.50 t4=0.75 | \
sufilter f=20,50,70,80  amps=1.,1.,0.,0. | \
sutifowler choose=2 option=2 vmin=3000 vmax=3000 nv=1  \
etamin=0.15 etamax=0.0 neta=1 salias=0.0  \
dx=25 lbtaber=0 lstaper=0 ncdps=33 | \
supswigp \
        label1="Time (s)" grid1=solid \
        label2="Midpoint (km)" \
        f2=0 d2=0.025 \
        perc=99.  >fdmob.eps 

exit

# Compute DMO/Migration impulse response
testtifowler v=3000 dt=0.004 nspk=4 t1=0.10 t2=0.25 t3=0.50 t4=0.75 | \
sufilter f=20,50,70,80  amps=1.,1.,0.,0. | \
sutifowler choose=1 option=2 vmin=3000 vmax=3000 nv=1  \
etamin=0.0 etamax=0.30 neta=3 salias=0.0  \
dx=25 lbtaber=0 lstaper=0 ncdps=33 nxpad=300 | \
supswigp \
        label1="Time (s)" grid1=solid  \
        label2="Midpoint (km)" \
        f2=0 d2=0.025 \
        perc=99.  >fmigc.eps 

exit
