#! /bin/sh
#
# This is about a 6 1/2 hour wall clock time job

date
susynlvfti \
delta=0.0 epsilon=0.15 v00=3 fpeak=20 fxo=0 dxo=0.1 nxo=31 \
dxm=0.025 nxm=601 dt=0.010 nt=801 dvdz=0 dvdx=0 \
ref="1:2.0,1.0,2.34641,1.2;3.5,1.2" \
ref="1:1.8,1.0,2.3,1.5;3.5,1.5" \
ref="1:1.6,1.0,2.17735,2.0;3.5,2.0" \
ref="1:1.4,1.0,1.8,2.5;3.5,2.5" \
ref="1:1.2,1.0,1.2,3.0;3.5,3.0" >newgathers.su

sugain tpow=0.5 <newgathers.su | \
sutifowler \
	ncdps=601 choose=1 option=1 etamin=0. etamax=0.3 neta=7 \
	dx=25 vmin=2500 vmax=3500 nv=11 nvstack=125 nxpad=100 salias=1.0  \
	>junk.su

date

suwind <fowlernew.su key=igi min=15 max=15 > junk.su
suwind <junk.su key=offset min=2950 max=3050 > fgood.su
susort <junk.su offset cdp >vscan.su
suwind <fowlernew.su key=igi min=0 max=0 >junk.su
susort <junk.su offset cdp >vscaneta0.su	
suwind <vscaneta0.su key=offset min=3350 max=3450 >best0.su
suwind <fowlernew.su key=offset min=2950 max=3050 >junk.su
susort <junk.su igi cdp >etascan.su
rm junk.su

supsimage <fgood.su label1="Time (s)" \
        label2="Midpoint (km)" \
        f2=0 d2=0.025 \
         >fgood.eps

supsimage <best0.su label1="Time (s)" \
        label2="Midpoint (km)" \
        f2=0 d2=0.025 \
         >best0.eps

supsimage <vscan.su label1="Time (s)" \
        label2="Constant-velocity migration panels (eta=0.15)" \
        f2=0 d2=0.025 \
        clip=3.0 >vscan.eps

supsimage <vscaneta0.su label1="Time (s)" \
        label2="Constant-velocity migration panels (eta=0)" \
        f2=0 d2=0.025 \
        clip=3.0 >vscaneta0.eps

supsimage <etascan.su label1="Time (s)" \
        label2="Constant-eta migration panels (v=3000 m/s)" \
        f2=0 d2=0.025 \
        clip=3.0 >etascan.eps


date
exit
