#! /bin/sh

# make synthetic data with 30, 45, 60, 80, and 90 degree dips
# for offset 0 km
susynlvfti \
delta=0.0 epsilon=0.15 v00=3 fpeak=25 fxo=0 \
dxm=0.025 nxm=401 dt=0.010 nt=601 dvdz=0 dvdx=0 \
ref="1:2.0,1.0,2.34641,1.2;3.5,1.2" \
ref="1:1.8,1.0,2.3,1.5;3.5,1.5" \
ref="1:1.6,1.0,2.17735,2.0;3.5,2.0" \
ref="1:1.4,1.0,1.8,2.5;3.5,2.5" \
ref="1:1.2,1.0,1.2,3.0;3.5,3.0" >model.su 

sugain tpow=0.5 <model.su | \
sutifowler choose=3 etamin=0. etamax=0.25 neta=6 vmin=3000 vmax=3000 nv=1  \
salias=0.0 dx=25 dtout=0.010 lbtaber=0 lstaper=0 ncdps=401 >fzero.su

suximage <fzero.su &

suwind <fzero.su key=cdp min=0 max=200 tmax=2.5 | susort igi cdp >fzero2.su

suximage <fzero2.su &
exit

