#! /bin/sh

suwind <etascan.su key=igi min=0 max=10 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >etascana.eps

suwind <etascan.su key=igi min=15 max=25 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >etascanb.eps

psmerge in=etascanb.eps origin=0.0,0.0 translate=0.0,0.0 \
	in=etascana.eps origin=0.0,0.0 translate=0.0,3.0 \
	>etascanall.eps


suwind <vscan.su key=offset min=2550 max=2850 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >vscana.eps

suwind <vscan.su key=offset min=2850 max=3150 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >vscanb.eps

suwind <vscan.su key=offset min=3150 max=3450 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >vscanc.eps

psmerge in=vscanc.eps origin=0.0,0.0 translate=0.0,0.0 \
	in=vscanb.eps origin=0.0,0.0 translate=0.0,3.0 \
	in=vscana.eps origin=0.0,0.0 translate=0.0,6.0 \
	>vscanall.eps

suwind <vscaneta0.su key=offset min=2550 max=2850 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >vscaneta0a.eps

suwind <vscaneta0.su key=offset min=2850 max=3150 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >vscaneta0b.eps

suwind <vscaneta0.su key=offset min=3150 max=3450 | \
supsimage  label1="Time (s)" \
        f2=0 d2=0.025 hbox=2.67 \
        bclip=3.0 wclip=-1.0 >vscaneta0c.eps

psmerge in=vscaneta0c.eps origin=0.0,0.0 translate=0.0,0.0 \
	in=vscaneta0b.eps origin=0.0,0.0 translate=0.0,3.0 \
	in=vscaneta0a.eps origin=0.0,0.0 translate=0.0,6.0 \
	>vscaneta0all.eps
