#! /bin/sh
# shell for plotting synthetic data and migrated data

supsimage<data  perc=99.5\
	label1="Time (s)" label2="Midpoint (m)" \
	ybox=4 hbox=4 \
	title="Synthetic Data"  > syndata.eps

# Plotting migrated data

