#! /bin/sh
# dmo for synthetic data
set -v

# a convenient scratch area. Should be the place where the data made by
# Susynlvfti are located.
S=.

CMP=130


# set parameters
incmg=$S/cmgsynhti
outcmg=$S/dmocmghti
outeps=$S/output.eps
nxo=30 dxo=0.1 fxo=0.1
nxm=360 dxm=0.025 fxm=1.5
nt=401 dt=0.01 ft=0
v00=2.5 dvdz=0.0
cdpmin=1
cdpmax=360
noffmix=1
dxcdp=25
ETA=0.16667
VNMO0=2500


# sort to common-offset, nmo, dmo
susort <$incmg +offset +cdp |
sunmo cdp=1 smute=1.7 \
	tnmo=0.0 vnmo=$VNMO0 |
sudmotivz >$outcmg cdpmin=$cdpmin cdpmax=$cdpmax dxcdp=$dxcdp \
	noffmix=$noffmix verbose=1 \
	tdmo=0 etadmo=$ETA  vndmo=$VNMO0 smute=1.7


# Plot a CMP gather
suwind <$outcmg key=cdp min=$CMP max=$CMP count=$nxo |
supswigp -geometry 300x800+100+100 \
	n1=$nt d1=$dt f1=$ft label1="Time (s)" \
	n2=$nxo d2=$dxo f2=$fxo label2="Offset (km)" \
	title="DMO CMP $CMP" \
	perc=99.7 grid1=solid > $outeps

exit

# use one of the following dmo processes in the flow above

# generate vfile for sudmovz (used only for sudmovz
vtlvz dt=$dt nt=$nt v0=2191 a=$dvdz >vt.F

# v(z) DMO
sudmovz cdpmin=$cdpmin cdpmax=$cdpmax dxcdp=$dxcdp \
	noffmix=$noffmix verbose=1 fmax=31.25 \
	vfile=vt.F smute=1.7 |


# constant-velocity DMO
sudmofk cdpmin=$cdpmin cdpmax=$cdpmax dxcdp=$dxcdp \
	noffmix=$noffmix verbose=1 fmax=31.25 |

# squeezed DMO
sudmofk cdpmin=$cdpmin cdpmax=$cdpmax dxcdp=$dxcdp \
	noffmix=$noffmix verbose=1 fmax=31.25 \
	tdmo=0.00,0.25,0.50,1.00,1.50,2.00,2.50,3.00,3.50,4.00 \
	vdmo=1500,1578,1663,1857,2086,2358,2681,3065,3523,4068 \
	sdmo=0.6 |

c1111=1.6 c1313=.3 c1133=.493725
