#! /bin/sh
# Run CSHOT with CWP X Graphics

demo=14

x1beg=-1000 x1end=2000 x2beg=0 x2end=18000

cp param1.1 param1
cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par
xgraph <demo${demo}plot par=demo${demo}par  \
	-geometry 600x400+650+0 \
	title="Weathering Model" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

cp param1.2 param1
cshot1 >/dev/null
cshot2
suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Common Offset (agc)" \
	ybox=70 \
	label1="Time in Seconds" label2="Trace" &
