#! /bin/sh
#set -v
output=inv.su
psout=inversion.ps
nzo=20 nxo=20 nyo=20

sustrip<$output|pscube n1=$nzo n2=$nxo n3=$nyo > $psout

echo 
echo "You may view the file $psout with your PostScript previewer"
echo 

exit 0
