#! /bin/sh

set -x
output=data.su

nt=101 dt=0.1 ntr=121 offset=0 nspk=1 ix1=61 it1=51 

suspike  nt=$nt dt=$dt ntr=$ntr nspk=$nspk offset=$offset \
	ix1=$ix1 it1=$it1 >$output

supsimage<$output  > sudata.ps

 exit
