#! /bin/sh
set -x
input=data.su
output=inv.su
vfile=vfile

dt=0.15 offs=0. i=1 doff=0 n=1 dfxm=0 fxm=0 ny=11
nxm=11 dxm=1  dxo=0.5 nxo=20 dyo=0.5 nyo=20 fxo=0 fyo=0. dzo=0.5 
nzo=20 
fzo=0.  nz=101 dy=1 dz=0.1 fx=0. nxb=70 na=100 

sufrac<$input dt=$dt phase=0.5 |
suinvzco3d dt=$dt offs=$offs ny=$ny nxm=$nxm dxm=$dxm \
	dyo=$dyo nyo=$nyo ang=$ang \
	fxm=$fxm fxo=$fxo fyo=$fyo fzo=$fzo nzo=$nzo dzo=$dzo \
	dxo=$dxo nxo=$nxo  nx=$nx nz=$nz fx=$fx dx=$dx dy=$dy dz=$dz \
	fmax=  vfile=$vfile verbose=1 nxb=$nxb nxd=$nxd >$output

exit 0
