#! /bin/sh
# shell for running unif2 --- uniformly sampled Cshot model
# data is smoothed with smo2d
set -v


nx=1 dx=0.1 fx=0.  labelx="Distance (m)"
nz=101 dz=0.1 fz=.0  labelz="Depth (m)"
ninf=3 npmax=201 
xsmoothing=0 zsmoothing=0


unif2 <interface ninf=$ninf  npmax=$npmax \
	nz=$nz dz=$dz fz=$fz nx=$nx dx=$dx fx=$fx \
	v00=2.0,2.0,2.0,2.0 >vfile 

exit 0
