#! /bin/sh
#set -v
output=inv.su
psout=inversion.ps
nzo=20 nxo=20 nyo=20

suxmovie <$output loop=1 mode=0 n1=$nzo n2=$nxo n3=$nyo \
		title="Impulse Response 3D inline view " &
suxmovie <$output loop=1 mode=1 n1=$nzo n2=$nxo n3=$nyo \
		title="Impulse Response 3D crossline view " &
suxmovie <$output loop=1 mode=2 n1=$nzo n2=$nxo n3=$nyo \
		title="Impulse Response 3D depthslicev view " &


exit 0
