#! /bin/sh

WIDTH=600
HEIGHT=600
XOFF1=0
YOFF1=0
XOFF2=650
YOFF2=650

demo=4

# Examine model with CSHOT, use CWP X Graphics for display
# Change Data/modelgeometry to move subsurface shot around, etc.
# Display the model with subsurface rays

############
cd model.dir	# where model stuff is
############

cp param1.model param1

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par

xgraph <demo${demo}plot par=demo${demo}par style=seismic \
	-geometry 560x460+700-660 x2end=20000\
	title="Model for Demo $demo" \
	label1="Depth (m)"  label2="Range (m)" &


# Build synthetic data with CSHOT, display with CWP X Graphics

# Make time section information
echo "Making time section (takes time) ..."

cp param1.traces param1
cshot1 >/dev/null

# Make time section
cshot2

# Display section
suaddhead ns=500 <demo${demo}traces ftn=1 | sushw key=dt a=4000 |
suximage   f1=0.0 d1=.004 f2=0 d2=80 perc=99 \
	wbox=$WIDTH hbox=$HEIGHT xbox=$XOFF1 ybox=$YOFF1 \
	title="Synthetic Section" \
	label1="Time (s)" label2="Range (m)" &


# Move data to the miggbzo directory
mv demo${demo}traces ../miggbzo.dir
