#! /bin/sh
# Run CSHOT with CWP PS Graphics

demo=2
MACHINE=keller
USER="-l jkc"      # don't need if usernames the same on both machines

x1beg=0 x1end=10000 x2beg=0 x2end=10000

cshot1 |
cshotplot  >demo${demo}plot  outpar=demo${demo}par
psgraph <demo${demo}plot par=demo${demo}par style=seismic \
	title="Ray Plot " \
        hbox=6 grid1=dash grid2-dash \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end |
rsh $MACHINE $USER images
