#! /bin/sh
# Shell: Unisam2 
# use unisam2 to make a uniformly sampled wavespeed profiles
# Author: John Stockwell, 27 August 1992

set -x

# Background Velocity Model 1  
# constant wavespeed (of 1) model  101x101 samples
well1="1 1.5 1.8"               # make ascii data
well2="1 1.2 1.8"               # make ascii data

rm junkv
for i in $well1 $well2
do
	echo $i >> junkv
done


a2b < junkv n1=1 > infile.v    # convert to binary	
unisam2 < infile.v x1=0,50,100 n1=101 d1=1 x2=0,100 n2=101 d2=1 f2=0 > outfile.v 

mv outfile.v junkv

ximage legend=1 < junkv n1=101 n2=101 &

exit 0
