#! /bin/csh -f
#-------------------------------------------------------------------------------
#                              make_javadoc_html
#-------------------------------------------------------------------------------
# Make an html directory using javadoc.
#
# Run this script in the directory containing java source files.
# An html directory will be created (if necessary) just below the current directory.
# The html directory will be populated using javadoc.
#-------------------------------------------------------------------------------

if(! -d html) mkdir -p html

javadoc -source 1.5 -sourcepath . -d html -use -splitIndex *.java

##-------------------------------- end --------------------------------------##
##-------------------------------- end --------------------------------------##
##-------------------------------- end --------------------------------------##

