#! /bin/sh
#  Here is how to run linrort for linearized Rpp, Rps coefficients
#  using three examples; always uncomment the desired example
#  The file angle.in is the part of this demo script.

## Example 1: HTIxHTI medium, the symmetry axis of the lower HTI has
## azimuth 30 deg (i.e., is rotated by kappa=30 deg with respect to the
## upper HTI), the ranges of the incidence angles and azimuth are generated
## by the routine (a_file=-1).

linrort	hspace1=hti hspace2=hti a_file=-1 \
        fangle=0 langle=30 dangle=1 fazim=-180. lazim=180. dazim=15. kappa=30. \
        vp1=3.0  vs1=1.2 vp2=3.6 vs2=1.44  rho1=2.5 rho2=2.8 \
        eps1_v=-0.05 eps2_v=-0.05 delta1_v=0.10  delta2_v=-0.06 gamma1_v=-0.10 gamma2_v=-0.10 


## Example 2: ORTHO/ORTHO medium, the symmetry planes of the incidence
## and reflecting halfspaces are aligned, (with azimuth 0 deg, i.e.,
## kappa=0), the ranges of the incidence angles and azimuth are defined in
## the input file angle.in (a_file=angle.in). Notice error
## messages in info.out file.

#linrort  hspace1=ort hspace2=ort a_file=angle.in \
#        kappa=0. \
#        vp1=3.0  vs1=1.65 vp2=4.0 vs2=2.0  rho1=2.5 rho2=3.0 \
#        eps1_1=-0.15 eps1_2=0.15 eps2_1=-0.15 eps2_2=-0.25 \
#        delta1_1=-0.20 delta1_2=0.10 delta1_3=0.15 delta2_1=-0.10 delta2_2=-0.20 \
#        delta2_3=0.10 \
#        gamma1_1=0.10 gamma1_2=0.0 gamma2_1=-0.15 gamma2_2=0.0


## Example 3: VTI/ORTHO medium, the vertical symmetry plane [x1,x3] of
## the reflecting orthorhombic halfspaces has azimuth 20 deg (i.e.,
## kappa=20), the ranges of the incidence angles and azimuth are
## defined in the input file angle.in (a_file=angle.in). Notice error
## messages in info.out file.

#linrort  hspace1=VTI hspace2=ORT a_file=angle.in \
#	 kappa=20 \
#        vp1=2.0 vs1=1.2 vp2=2.8 vs2=1.6 rho1=2.5 rho2=2.2 \
#        eps1=0.31 delta1=0.21 gamma1=0.1 \
#        eps2_1=0.33 eps2_2=0.27 \
#        delta2_1=0.08 delta2_2=-0.09 delta2_3=-0.12 \
#        gamma2_1=0.18 gamma2_2=0.05

## END OF FILE ##





