#! /bin/sh

suspike nspk=1  ix1=32 it1=32 nt=64 ntr=64 > junk.spk

suximage title="Spike Data" wbox=350 hbox=350 xbox=10 ybox=400 < junk.spk &

sukfilter < junk.spk |
suximage title="K-Filtered Spike Data" \
ybox=400 wbox=350 hbox=350 xbox=400 &

sukfilter < junk.spk | 
suspeck1k2 |
suximage title="K-Filter only" ybox=400 xbox=800 wbox=350 hbox=350 &

suximage title="Spike Data" wbox=350 hbox=350 xbox=10 ybox=10 < junk.spk &

sukfilter < junk.spk |
sudipfilt dx=1.0 dt=1.0 slopes=.2,.3,.7,.8 amps=0,1,1,0 |
suximage title="K and Dip Filtered Spike Data" \
ybox=10 wbox=350 hbox=350 xbox=400 &

sukfilter < junk.spk | 
sudipfilt dx=1.0 dt=1.0 slopes=.2,.3,.7,.8 amps=0,1,1,0 |
suspeck1k2 |
suximage title="K and Dip Filter" ybox=10 xbox=800 wbox=350 hbox=350 &


exit 0
