#! /bin/sh
set -x

WIDTH=600
HEIGHT=600
XOFF1=0
YOFF1=0
XOFF2=650
YOFF2=650

demo=1

# necessary parameters
nt=101 dt=1.0 ft=0.0 dtsegy=1000000
nx=101 dx=1.0  fx=0.0
nz=101 dz=1.0  fz=0.0

# make velocity function

cd miggbzo.dir

# Gaussian beam migration
sumiggbzo <junks.su >junkmgb vfile=junkv \
	dt=1.0 nz=$nz dz=$dz fz=$fz \
	fmin=0.025 fmax=0.25 amin=-60 amax=60

# display output
suximage <junkmgb clip=.05   \
 label1="Depth (samples)" label2="Distance (samples)" \
        wbox=$WIDTH hbox=$HEIGHT xbox=$XOFF1 ybox=$YOFF1 \
	title="GB mig test, constant background velocity" &

exit

