/*<license>
 -------------------------------------------------------------------------------
  Copyright (c) 2007 ConocoPhillips Company
 
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 -------------------------------------------------------------------------------
 </license>*/
"#################  Version widget information       ##################",
"OOCbyt*version_1_3.background: LavenderBlush",
"OOCbyt*version_1_3.labelString:\
-----------------------------------------------\\n\
Please contact Bill Menger (281) 363-8571 / bmenger@fusiongeo.com\\n\
to request new options, report bugs, or to get user assistance.",
"################# End of version widget information ##################",
"*fontList: -*-*-bold-r-normal-*-*-120-*-*-p-*-*-*",
"*main_form.resizePolicy:   RESIZE_NONE",
"*main_form.allowOverlap:   False",
"*main_form.width:   550",
"*main_form.height:  650",
"*background:        lightgray",
"*foreground:        black",
"*dragInitiatorProtocolStyle:  DRAG_NONE",
"*dragReceiverProtocolStyle:  DRAG_NONE",
"OOCbyt*useColorObj: False",
"*XmToggleButton.selectColor: wheat",
"*wboxmessagetext: dark green",
"*filecas.labelString:      File",
"*optioncas.labelString:    Option",
"*zoomcas.labelString:      Zoom",
"*toolcas.labelString:      Tools",
"*pickcas.labelString:      Pick",
"*customcas.labelString:    Custom",
"*help.labelString:         Help",
"*addfile.labelString:      Setup/Change Plot...",
"*fileunder.labelString:    Underlay Plot...",
"*tieline.labelString:      Tieline Plot...",
"*tieunder.labelString:     Tieline Underlay Plot...",
"*quit.labelString:         Quit",
"*zup.labelString:          Zoom Up",
"*zupsep.labelString:       Zoom Up Separate Window",
"*zdown.labelString:        Zoom Down",
"*zorgin.labelString:       Original Size",
"*zop.labelString:          Zoom-Scan Options...",
"*color.labelString:        Color...",
"*savdef.labelString:       Save Defaults...",
"*resdef.labelString:       Restore Defaults...",
"*sysdef.labelString:       System Defaults",
"*units.labelString:        Units",
"*metric.labelString:       Metric",
"*english.labelString:      English",
"*showanno.labelString:     Always Show Annotation ",
"*showover.labelString:     Show Underlay",
"*tlsepop.labelString:      Tie Line: Adjust Bar",
"*tlscrlock.labelString:    Tie Line: Lock Scroll Bars",
"*tlshowamp.labelString:    Tie Line: Show Amps ",
"*remtline.labelString:     Tie Line: REMOVE",
"*tlreset.labelString:      Tie Line: Reset time Tie",
"*slave_plot.labelString:   Remote Plot...",
"*add_graph.labelString:    Open New Window...",
"*screens.labelString:      Open New Window on Screen-",
"*add_bw_graph.labelString: Open Wiggle Only Window...",
"*rem_graph.labelString:    Close this Window...",
"*cbar.labelString:         Color Bar...",
"*ginfo.labelString:        Plot Info...",
"*ovjd.labelString:         Ovjd...",
"*header_dump.labelString:  Header Dump...",
"*shift.labelString:        Shift...",
"*globals.labelString:      View Globals...",
"*plothead.labelString:     Header Plot",
"*remplothead.labelString:  Remove Header Plot",
"*addlab.labelString:       Add/Modify A Label",
"*delalllab.labelString:    Delete All Labels",
"*vel_estimator.labelString:      BETA TEST: Velocity Estimator",
"*ctx.labelString:          Context Sensitive Help...",
"*overview.labelString:     Overview Help...",
"*version.labelString:      Help on Version...",
"*mousehelp.labelString:    Show status line",
"*mute_menu.labelString:    Mute\\nPicking",
"*ref_menu.labelString:     SCRS\\nPicking",
"*gen_menu.labelString:     General\\nPicking",
"*sisc_menu.labelString:    SISC\\nPicking",
"*fish_menu.labelString:    FISH\\nPicking",
"*tred_menu.labelString:    Trace\\nEditing",
"*end_pick.labelString:     End\\nPicking",
"*vel_end.labelString:      End Velocity\\nEstimator",
"*vel_end.background:       red",
"*seis_pick_end.labelString: End Seismic\\nPick",
"*seis_pick_end.background: red",
"*remtieline_b.labelString: Remove\\nTie Line",
"OOCbyt*statline*XmText.fontList:   -*-*-bold-r-*-*-*-100-*-*-*-*-*-*",
"*sp_pop_popup.title:        Setup/Change Plot",
"*sp_under_pop_popup.title:  Underlay Plot",
"*tie_input_popup.title:     Tieline Plot",
"*tie_under_pop_popup.title: Tieline Under Plot",
"*zoomop_popup.title:        Zoom/Scan Options",
"*colorpop_popup.title:      Color Options",
"*addfile.accelerator:         Meta<Key>A",
"*addfile.acceleratorText:     Alt-A",
"*tieline.accelerator:         Meta<Key>T",
"*tieline.acceleratorText:     Alt-T",
"*quit.accelerator:            Meta<Key>Q",
"*quit.acceleratorText:        Alt-Q",
"*zup.accelerator:             Meta<Key>U",
"*zup.acceleratorText:         Alt-U",
"*zdown.accelerator:           Meta<Key>D",
"*zdown.acceleratorText:       Alt-D",
"*zoompop.accelerator:         Meta<Key>Y",
"*zoompop.acceleratorText:     Alt-Y",
"*zorgin.accelerator:          Meta<Key>S",
"*zorgin.acceleratorText:      Alt-S",
"*color.accelerator:           Meta<Key>K",
"*color.acceleratorText:       Alt-K",
" !",
"*cbar.accelerator:            Meta<Key>B",
"*cbar.acceleratorText:        Alt-B",
"*ovjd.accelerator:            Meta<Key>J",
"*ovjd.acceleratorText:        Alt-J",
"*globals.accelerator:         Meta<Key>G",
"*globals.acceleratorText:     Alt-G",
"*addlab.accelerator:          Meta<Key>L",
"*addlab.acceleratorText:      Alt-L",
"*header_dump.accelerator:     Meta<Key>H",
"*header_dump.acceleratorText: Alt-H",
"*filecas.mnemonic:           F",
"*zoomcas.mnemonic:           Z",
"*optioncas.mnemonic:         O",
"*pickcas.mnemonic:           P",
"*customcas.mnemonic:         C",
"*showanno.set:    True",
"*tlsepop.set:     True",
"*tlscrlock.set:   False",
"*tlshowamp.set:   False",
"*mousehelp.set:   True",
"*english.set:     True",
"*metric.set:      False",
"*movie*XmScale.scaleMultiple: 1",
"*header_dump.screenNumber: otherScreen",
"*all_headers_pop.screenNumber: otherScreen",
"*trace_edit.screenNumber: otherScreen",
