#! /bin/sh
# Run CSHOT with CWP X Graphics

demo=8

x1beg=0 x1end=5500 x2beg=-100 x2end=10000

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par

xgraph <demo${demo}plot par=demo${demo}par \
	-geometry 600x400+650+500 \
	title="Rays for demo$demo" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

cshot2

suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
suxwigb title="Primaries and Reverberations (agc)" \
	ybox=70 \
	label1="Time in Seconds"  label2="Trace" &
