#! /bin/sh
# PostScript output

demo=1
PSPREV=$PSPREVIEWER

supsimage <junk1 label1="Time (s)" label2="Midpoint (km)" \
> demo${demo}.1.eps

supsimage <junk2 label1="Time (s)" label2="Midpoint (km)" \
	title=""  > demo${demo}.2.eps

if test "$PSPREV" != ""
then
	echo "Previewing PostScript files with $PSPREV"
	for i in *.eps
	do
		$PSPREV < $i &
	done
else
	echo "PostScript previewer environment variable"
	echo "PSPREVIEWER not set"
fi

exit 0
