#! /bin/sh
set -x

nt=501 dt=.01 ft=0.0
nx=201 dx=0.05 fx=0.0
DVDZ=.5
DVDX=0.0
ANGXS=30

# default
susynlvfti > junk1

# make synthetic data
susynlvfti > junk2 angxs=$ANGXS \
	er=1 ob=0 v00=3.0 delta=.2 epsilon=.5 fpeak=15 \
	dvdx=$DVDX dxm=$dx nxm=$nx dt=$dt nt=$nt dvdz=$DVDZ smooth=1 \
	ref="1:0.0,1.5;1.0,1.5;2.,3.0;3.0,3.0;4.0,4.0;5.0,3.0;6.0,3.0"
exit 0
