#! /bin/sh
# set -x

# Demos shell for sugoupillaudpo
# Albena Mateeva, Feb, 2002

#----------------------------------------------------------------------------
# Example reflection coefficient series: rdemo.asc
#
# rdemo.asc has 250 samples:
# The first one, r[1]=-1.0, represents the earth surface (free surface);
# r[2]:r[250] represent subsurface interfaces equally spaced in time (dt=2ms).
#
#
# Creating input file for sugoupillaudpo:
#
a2b n1=1 < rdemo.asc | suaddhead ns=250 | sushw key=dt a=2000 > rdemo.su
#
#--------------------- show example reflectivity:
#
suxgraph < rdemo.su label1="Time (s)" label2="refl. coef." \
title="INPUT REFLECTIVITY" x1beg=0 x1end=.5 x2beg=-1 x2end=1 \
width=250 height=600  &
#----------------------------------------------------------------------------

####### compute and graph DISPLACEMENT primaries for a SURFACE SOURCE: 

#receiver at the earth surface
sugoupillaudpo < rdemo.su | \
suxgraph label1="time (s)" label2="displacement" \
title="SURFACE SOURCE / SURFACE RECEIVER" \
x1beg=0 x1end=.5 x2beg=-1 x2end=1 width=250 height=600 &

#receiver buried at 100 ms owt below the surface:
sugoupillaudpo k=101 < rdemo.su | \
suxgraph label1="time (s)" label2="displacement" \
title="SURFACE SOURCE / RECEIVER DEPTH 100 ms" \
x1beg=0 x1end=.5 x2beg=-1 x2end=1 width=250 height=600 &

####### compute and graph DISPLACEMENT primaries for a BURIED SOURCE: 

#receiver at the earth surface 
sugoupillaudpo l=76 < rdemo.su | \
suxgraph label1="time (s)" label2="displacement" \
title="SOURCE DEPTH 75 ms / SURFACE RECEIVER" \
x1beg=0 x1end=.5 x2beg=-1 x2end=1 width=250 height=600 &

#receiver at 100 ms owt below the surface:
sugoupillaudpo l=76 k=101 < rdemo.su | \
suxgraph label1="time (s)" label2="displacement" \
title="SOURCE DEPTH 75 ms / RECEIVER DEPTH 100 ms" \
x1beg=0 x1end=.5 x2beg=-1 x2end=1 width=250 height=600 &
 
####### compute and graph a PRESSURE primaries for a SURFACE SOURCE: 

#receiver burried at 100 ms owt below the surface:
sugoupillaudpo k=101 pV=-1 < rdemo.su | \
suxgraph label1="time (s)" label2="pressure" \
title="SURFACE SOURCE / RECEIVER DEPTH 100 ms" \
x1beg=0 x1end=.5 x2beg=-1 x2end=1 width=250 height=600 &

####### compute and graph PRESSURE primaries for a BURIED SOURCE: 

#receiver at 50 ms owt below the surface:
sugoupillaudpo l=76 k=51 pV=-1 < rdemo.su | \
suxgraph label1="time (s)" label2="pressure" \
title="SOURCE DEPTH 75 ms / RECEIVER DEPTH 50 ms" \
x1beg=0 x1end=.5 x2beg=-1 x2end=1 width=250 height=600 &

exit






