#! /bin/sh


sualford  \
inS11=S11.su  \
inS12=S12.su  \
inS21=S21.su  \
inS22=S22.su \
outS11=S11out.su  \
outS12=S12out.su  \
outS21=S21out.su  \
outS22=S22out.su \


suxwigb < S11out.su xbox=50 ybox=50 hbox=500 wbox=500 title="S11 out" clip=1 &
suxwigb < S12out.su xbox=550 ybox=50 hbox=500 wbox=500 title="S12 out" clip=1 &
suxwigb < S21out.su xbox=50 ybox=550 hbox=500 wbox=500 title="S21 out " clip=1 &
suxwigb < S22out.su xbox=550 ybox=550 hbox=500 wbox=500 title="S22 out" clip=1 &
