#! /bin/sh
# Run CSHOT with CWP PS Graphics

set -x

demo=5

x1beg=0 x1end=12000 x2beg=0 x2end=24000

cshot1>cshot1plot
cshotplot <cshot1plot  >demo${demo}plot  outpar=demo${demo}par
psgraph <demo${demo}plot par=demo${demo}par style=seismic \
	title=" Ray Plot" \
        ybox=3.5 hbox=4 grid1=dash grid2=dash \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

cshot2
psmovie<demo${demo}traces n1=501 n2=48 d1=0.004 d2=80 f2=$1 perc=98 \
ybox=3.5 hbox=4 \
label1="Time(secs)" \
label2="location(ft)" \
title="Marathon: Time Section"
