#!/bin/bash
EXE=$(basename $0)
echo "Running $EXE in $(pwd)"
cat <<EOF >hold_automounts.sh
#!/bin/bash
# hold_automounts.sh
EXE=\$(basename \$0)
echo "Running \$EXE"
EOF
echo "Created $(pwd)/hold_automounts.sh"
