#! /bin/sh
#<CPS_v1 type="SCRIPT" pretag="#"/>


#<copyright>
#*******************************************************************************
#***********                    COPYRIGHT NOTICE                     ***********
#*********** CONFIDENTIAL AND PROPRIETARY INFORMATION OF CONOCO INC. ***********
#***********  PROTECTED BY THE COPYRIGHT LAW AS AN UNPUBLISHED WORK  ***********
#*******************************************************************************
#</copyright>


#<brief_doc>
#-------------------------------------------------------------------------------
#                         C P S   S C R I P T
#
# Name   : sps_fix_dependencies
# Written: 1994-07-21   by: Ed Schmauch
# Revised: 2003-11-07   by: Tom Stoeckley
# Purpose: Take output from gcc -MM and put in nice format for makefile.
#
#-------------------------------------------------------------------------------
#</brief_doc>


#<descript_doc>
#-------------------------------------------------------------------------------
#                            DOCUMENTATION
#
# Take output from gcc -MM and put in nice format for makefile.
#
#------------------------------------------------------------------------------
#</descript_doc>


#<history_doc>
#------------------------------------------------------------------------------
#                           REVISION HISTORY
#
#     Date        Author     Description
#     ----        ------     -----------
#  7. 2003-11-07  Stoeckley  Fix spelling of name in brief_doc.
#  6. 2003-04-29  Stoeckley  Improve awk statement which removes long file
#                             specs, by keeping subdirectory under include
#                             only when include is actually present in the path.
#  5. 2003-03-18  Stoeckley  Improve the output formatting for easier reading;
#                             replace nawk with gawk.
#  4. 2000-11-22  Stoeckley  Change to keep subdirectory under "include".
#  3. 1999-12-15  Stoeckley  Updated documentation with original author info.
#  2. 1999-12-03  Goodger    Add doc section.
#  1. 1994-07-21  Schmauch   Initial version (originally called makeCheck).
#
#-------------------------------------------------------------------------------
#</history_doc>


##------------------- separate lines for each dependency --------------------##
##------------------- separate lines for each dependency --------------------##
##------------------- separate lines for each dependency --------------------##


awk '/:/ { print ""; for (i = 1; i <= NF; i++) { print $i }}
	!/:/ { for (i = 1; i <= NF; i++)  { print $i }}' |


##--------------- remove backslashes, I'll put in my own later --------------##
##--------------- remove backslashes, I'll put in my own later --------------##
##--------------- remove backslashes, I'll put in my own later --------------##


awk '!/\\/ {print $0 }' |


##------------------------- remove long file specs ------------------------##
##------------------------- remove long file specs ------------------------##
##------------------------- remove long file specs ------------------------##


# original statement:
#
# awk -F/ '{ print $NF }' |


# statement introduced 2000-11-22 (to keep subdirectory under "include"):
#
# awk -F/ '{ if (NF > 1) { if ($(NF-1) == "include") { print $NF }
#                         else { print $(NF-1)"/"$NF } }
#            else { print $NF } }' |


# more robust statement introduced 2003-04-28:

awk -F/ '{ if (NF > 2) { if ($(NF-2) == "include") { print $(NF-1)"/"$NF }
                         else { print $NF } }
           else { print $NF } }' |


##----------------------- output in makefile form -------------------------##
##----------------------- output in makefile form -------------------------##
##----------------------- output in makefile form -------------------------##


# Use nawk because awk has bug.
# nawk not available on linux.
# nawk replaced by gawk 2002-03-18.
# apparently awk does not have the bug on linux.
# awk still has bug on solaris, but it does not appear to cause a problem.
# gawk works correctly on both linux and solaris.


gawk 'BEGIN { FS = "\n"; RS = "" }
         { print ""
         if (NF > 1) { print $1"\t\t\t\t\t\\" } else { print $1 }
         for (i = 2; i < NF; i++) { print "\t\t"$i"\t\t\t\\" }
         if (NF > 1) print "\t\t"$NF}'


##-------------------------------- end -------------------------------------##
##-------------------------------- end -------------------------------------##
##-------------------------------- end -------------------------------------##

