#! /bin/sh
# Muting data:
#set -x

## Set parameters
data=junk.su			# A panel of data to be muted
mutepicks=mutepicks.$data	# output file of tmute= and xmute= values
parfile=par.$data

key=tracl

echo "Making test data"

suplane > $data

echo
echo
echo "Begin picking points of a line above which data are to be muted."
echo "To pick, place the cursor on the desired point to pick, and press "
echo "the \"s\" key. When all points are picked press \"q\"."
echo
echo

pause

suximage < $data mpicks=$mutepicks wbox=1000 hbox=500 

echo
echo
echo "Mute curve picked"
echo
echo

sort < $mutepicks  -n |
mkparfile string1=tmute string2=xmute > $parfile

echo
echo " Applying the mute"
echo

sumute < $data par=$parfile key=$key  > mute.$data

suximage < mute.$data  wbox=1000 hbox=500 
exit 0
