#! /bin/sh
# use zero-velocity layer and wave-equation datuming
# to datum data from topography to a horizontal surface

#static shift data from topography to a horizontal surface above
###################################################################
sustatic < demo.su > demo.su_zstat hdrs=2 sign=-1 sou_file=zsou.b \
rec_file=zrec.b ns=320 nr=320 no=1
###################################################################


# wave-equation datum from this horizontal surface to another
# horizontal surface located at a depth of 600 m (see Cshot
# plot of model) - two velocity fields are used: the thin lens
# velocity backs out the static shift introduced above, and the 
# diffraction term doesn't "turn on" until the original topographic
# surface is reached
###################################################################
sudatumfd < demo.su_zstat > demo.su_zstat_dat \
nt=501 nx=320 nz=161 nsx=1 dz=10.0 dx=50.0 buff=10 tap_len=5 \
mx=360 mz=161 vfile1=vfp1.b vfile2=vfp2.b dt=0.004 x_0=0.0
###################################################################

# The velocity models given with vfp1.b and vfp2.b start at the
# lateral position 0.0, so the value x_0 is set to 0.0.


exit 0
