#! /bin/sh
# Display data before and after processing

supsimage < demo.su f2=50 d2=50 label1="Time (s)" \
label2="Surface Location (ft)" title="Raw Data" > demo.su.ps

supsimage < demo.su_zstat_dat f2=50 d2=50 label1="Time (s)" \
label2="Surface Location (ft)" \
title="After Wave-Equation Datuming" > demo.su_zstat_dat.ps

psgraph <demo14plot par=demo14par style=seismic \
        title="Weathering Model" \
        label1="Depth (ft)"  label2="Range (ft)" \
        x1beg=-1000 x1end=4000 x2beg=0 x2end=18000 > model.ps

exit 0
