#! /bin/sh
# Display data before and after processing

suximage < demo.su f2=50 d2=50 label1="Time (s)" \
xbox=20 ybox=20 wbox=400 hbox=300 \
label2="Surface Location (ft)" title="Raw Data" &

suximage < demo.su_zstat_dat f2=50 d2=50 label1="Time (s)" \
xbox=450 ybox=20 wbox=400 hbox=300 \
label2="Surface Location (ft)" \
title="After Wave-Equation Datuming" &

xgraph <demo14plot par=demo14par style=seismic \
        -geometry 400x300+250+450 \
        title="Weathering Model" \
        label1="Depth (ft)"  label2="Range (ft)" \
        x1beg=-1000 x1end=4000 x2beg=0 x2end=18000 &

exit 0
