#! /bin/sh
# PostScript output



PSPREV=$PSPREVIEWER

demo=1

# plot input data
supsimage < data.seis -geometry 600x250+0+25 \
	label1="Time (s)" label2="Trace number " \
	title="Input Data" > demo${demo}.1.eps

# plot cw dmo data
suwind < data.cwdmo  key=cdp min=1 max=1 |
supsimage -geometry 600x250+0+25 \
	label1="Time (s)" label2="Trace number" \
	title="CW DMO Data" > demo${demo}.2.eps


if test "$PSPREV" != ""
then
	echo "Previewing PostScript files with $PSPREV"
	for i in *.eps
	do
		$PSPREV < $i &
	done
else
	echo "PostScript previewer environment variable"
	echo "PSPREVIEWER not set"
fi

exit 0

