#! /bin/sh
# shell for Kirchhoff modeling for arbitrary v(x,z)


# plot velocity profile
suxmovie < data.seis -geometry 600x600+0+0 \
	perc=99 \
	label1="Time (s)" label2="Trace number." \
	title="Input Data" &

suxmovie < data.cwdmo -geometry 600x600+700+700 \
	perc=99 \
	label1="Time (s)" label2="Trace number" \
	title="CW DMO Data" &

exit 0
