#! /bin/sh
#
#------------Geometry Assignment & Sort-----------------------------------
#
input=mig_950.data

suwind<$input key=offset min=950 max=950 |
suwind tmax=4.0 |suwind key=tracr min=101 max=301 |
supswigb label1="Depth (km)" label2="Midpoint (km)" d1=0.005 \
	f2=2.5 d2=0.025 wbox=7 hbox=5 perc=99. \
	title="Common-offset migration (offset=950 m)" |images
