#! /bin/sh
# shell for smoothing a uniformly sampling velocity 
set -v

n1=61 r1=150 dz=50 fz=-500 labelz="Depth (m)"
n2=201 r2=150 dx=50 fx=0 labelx="Midpoint (m)"
d1r=50 n1r=61 n2r=201 d2r=50

# smooth velocity and resample
smooth3d<vfile_mig r1=$r1 r2=$r2 d1=$dz d2=$dx n1=$n1 n2=$n2 n3=1 \
	verbose=1 iter=2 slowness=1>data.s
unisam2<data.s nx1=$n1 nx2=$n2 dx1=$dz dx2=$dx \
	 n1=$n1r n2=$n2r d1=$d1r d2=$d2r>vfile_smooth
	 
rm -f data.s
exit 0
