#! /bin/sh
# shell for Kirchhoff migration from topography.
#set -v
set -x

offset=950

        input=../Make_Data/shot_TOPO.data
        output=mig_$offset.data

        suwind <$input key=offset min=$offset max=$offset > input.tmp
	sumigtopo2d par=kzmigtopo.par infile=input.tmp \
        off0=$offset outfile=$output

exit
