#! /bin/sh
# shell for uniformly sampling velocity from a layered model
set -v

nz=61 dz=50 fz=-500.0  labelz="Depth (m)"
nx=201 dx=50 fx=0  labelx="Distance (m)"
ninf=1 npmax=2001 
unif2 <input_mig >vfile_mig method=mono ninf=$ninf npmax=$npmax \
	nz=$nz dz=$dz fz=$fz nx=$nx dx=$dx fx=$fx \
	v00=2000,2000 \
	x0=0.,0. \
	z0=0.,0. \
	dvdz=0.,0.6 \
	dvdx=0.,0.2
exit 0

