#! /bin/sh

# Generate synthetic data made up of linear reflectors and point 
# diffractors. Random noise is also added

echo "Building model data"

output=data.su
sn=30
>$output
susynlv nt=600 dt=0.004 nxm=100 dxm=0.02 v00=2.5 fpeak=18 \
	ref="0.09:0.0,0.3;0.6,0.3" \
	ref="0.15:0.67,0.5;2.0,0.5" \
	ref="0.4:0.0,1.3;0.93,1.3" \
	ref="0.4:1.0,1.5;2.0,1.5" \
	ref="0.8:0.0,2.3;1.3,2.3" \
	ref="0.8:1.37,2.5;2.0,2.5" \
	ref="1.0:0.8,0.9;0.82,0.9" \
	ref="2.0:1.1,1.8;1.12,1.8" \
	ref="2.4:1.18,2.1;1.2,2.1" |
sushw key=cdp a=1 b=0 j=100 | sushw key=offset a=0 b=20 j=100 > $output


exit 0
