#! /bin/sh
# Run CSHOT with CWP PostScript Graphics

demo=9
psfile1=demo${demo}1.eps
psfile2=demo${demo}2.eps

x1beg=0 x1end=5500 x2beg=-3500 x2end=13000

cshot1 |
cshotplot >demo${demo}plot  outpar=demo${demo}par

psgraph <demo${demo}plot par=demo${demo}par style=seismic \
	title="Rays for demo$demo" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end >$psfile1

# Put the PostScript on screen or printer according to local lore
cat $psfile1 | rsh dix -l jkc lpr -P$DixPrinter

cshot2
suaddhead <demo${demo}traces ftn=1 ns=501 |
sushw key=dt a=4000 |
sugain gagc=1 wagc=0.5 |
supswigb title="Caustic (agc)" \
	label1="Time in Seconds" label2="Trace" >$psfile2

# Put the PostScript on screen or printer according to local lore
cat $psfile2 | rsh dix -l jkc lpr -P$DixPrinter
