#! /bin/sh
# smooth velocity profiles with smooth2
WIDTH=1000
HEIGHT=800
WIDTHOFF=100
HEIGHTOFF=100

n1=100
n2=100
d1=10
d2=10
outfile=template
outfile2=template2

# use unif2 to output test datafile
# $outfile is an ascii file that shows the type of input unif2 requires
unif2  tfile=$outfile 
unif2 <$outfile method=spline >$outfile2

# smooth2, loop over different "r" values
>moviefile
for i in 1  3 5  7  9  11  13  15  17  19  21
do
	smooth2 < $outfile2 r1=$i r2=$i n1=100 n2=100 >>moviefile
done

xmovie <moviefile  n1=$n1 n2=$n2 d1=$d1 d2=$d2 loop=1 sleep=1000000 \
	 title="Smooth2 r1=r2=2*%g" windowtitle="Movie" \
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF}+${HEIGHTOFF} &

exit 0
