#! /bin/sh
# smooth velocity profiles with smooth3d
WIDTH=1000
HEIGHT=800
WIDTHOFF=100
HEIGHTOFF=100

n1=100
n2=100
n3=1
d1=10
d2=10
outfile=template
outfile2=template2

# use unif2 to output test datafile
# $outfile is an ascii file that shows the type of input unif2 requires
unif2  tfile=$outfile 
unif2 < $outfile method=spline > $outfile2

# smooth3d, loop over different "r" values
>moviefile
for i in 2 4 6 8 10 12 14 16
do
	smooth3d < $outfile2 r1=$i r2=$i n1=100 n2=100 n3=1 >>moviefile
done

xmovie <moviefile   n1=$n1 n2=$n2 d1=$d1 d2=$d2 loop=1\
	 title="Smooth3d r1=r2=2*%g "\
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF}+${HEIGHTOFF} &

exit 0
