#! /bin/sh
# smooth velocity profiles with smoothint
WIDTH=1000
HEIGHT=800
WIDTHOFF=100
HEIGHTOFF=100

n1=100
n2=100
d1=10
d2=10
outfile=template

# use unif2 to output test datafile
# $outfile is an ascii file that shows the type of input unif2 requires
unif2  tfile=$outfile 

# smoothint2, loop over different "r" values
>moviefile
for i in 200 400 600 800 1000 1200 1400 1600 1800 2000 2200
do
	smoothint2 < $outfile r=$i |
	unif2 method=spline >>moviefile
done
xmovie <moviefile  n1=$n1 n2=$n2 d1=$d1 d2=$d2 loop=1\
	 title="Smoothint r=200*%g "\
	-geometry ${WIDTH}x${HEIGHT}+${WIDTHOFF}+${HEIGHTOFF} &

exit 0
