#! /bin/sh
# shell for plotting the original and smoothed v(x,z) model
#set -v

nz=251 dz=10 fz=.0  labelz="Depth (m)"
nx=161 dx=25 fx=0000.0  labelx="Distance (m)"
ninf=5 npmax=201 

psimage <data.v  style=seismic \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	wbox=6 hbox=4 ybox=4 \
	title="Original Velocity"  > vxz.eps


n1=251 r1=200 dz=10 fz=0 labelz="Depth (m)"
n2=161 r2=200 dx=25 fx=0 labelx="Midpoint (m)"
d1r=50 n1r=51 n2r=81 d2r=50 

# plot smoothed velocity
psimage <vsfile  style=seismic \
	n1=$n1r d1=$d1r f1=$fz grid1=dot label1="$labelz" \
	n2=$n2r d2=$d2r f2=$fx grid2=dot label2="$labelx" \
	ybox=4 hbox=4 \
	title="Smoothed Velocity" > smooth.eps

echo 
echo "Output are PostScript files:   vxz.eps   smooth.eps"
echo 
echo "You may view these with your PostScript Previewer"

exit 0
