#! /bin/sh
# shell for plotting synthetic data
nt=501 fxm=0.5 dt=0.004 dxm=0.015

supsimage<data n1=$nt f2=$fxm d1=$dt d2=$dxm perc=99\
	label1="Time (s)" label2="Midpoint (km)" \
	ybox=4 hbox=4 \
	d1num=1 d2num=1 \
	title="Common Offset Data (Offset=100 m)"  > syndata.eps

# Plotting inverted data
n1=251 f2=0 d2=0.015 d1=0.01

supsimage<data.inv n1=$n1 f2=$f2 d1=$d1 d2=$d2 perc=99\
	label1="Depth (km)" label2="Midpoint (km)" \
	ybox=4 hbox=4 \
	title="Common Offset Inversion  (offset=100 m)" > invdata.eps

echo
echo "Output are the PostScript files:  syndata.eps invdata.eps"
echo
echo "You may view these with your PostScript Previewer"
