#! /bin/sh
# shell for Kirchhoff inversion 
set -x
input=data
output=data.inv
fxm=500 nxm=201 dxm=15  nxd=5 
nx=81 nz=51 dx=50 dz=50 fx=0 nxb=40 vfile=vsfile  
dxo=15 nxo=267 fxo=0 fzo=0 dzo=10 nzo=251 
fmax=50 ls=1 verbose=1 pert=1 vpfile=vpfile  

sufrac phasefac=0.25<$input |
suinvvxzco nxm=$nxm dxm=$dxm fxm=$fxm nxd=$nxd \
nx=$nx nz=$nz fx=$fx dx=$dx dz=$dz nxb=$nxb vfile=$vfile \
dxo=$dxo nxo=$nxo fxo=$fxo fzo=$fzo nzo=$nzo dzo=$dzo \
fmax=$fmax ls=$ls verbose=$verbose pert=$pert vpfile=$vpfile \
>$output

