#! /bin/sh
# shell for Kirchhoff integral modeling  
set -x
output=data

nt=501 dt=0.004 ft=0.0 tmin=0.2 
nxm=201 dxm=15 fxm=500 nxd=5  dxo=200 nxo=1 fxo=100
nx=81 nz=51 dx=50 dz=50 fx=0 nxb=50 
fpeak=30 ls=1 pert=1 vpfile=vpfile

susynvxz< vsfile  nt=$nt dt=$dt ft=$ft tmin=$tmin \
	nxm=$nxm dxm=$dxm fxm=$fxm nxd=$nxd fxo=$fxo dxo=$dxo nxo=$nxo\
        nx=$nx nz=$nz fx=$fx dx=$dx dz=$dz  nxb=$nxb\
        fpeak=$fpeak  ls=$ls pert=$pert vpfile=$vpfile\
 	ref="1:0,500;4000,500" \
 	ref="1:0,1000.;1000.0,1000.;1692.82,1400,2200,1400;4000,917.691"\
 	ref="1:500.,2000;1700,1700;2000,1400.;2300,1700;3500,2000"\
 	ref="1:0,2000;4000,2000">$output

exit 0
