#! /bin/sh
# shell for uniformly sampling velocity from a layered model
set -v

nz=251 dz=10 fz=.0  labelz="Depth (m)"
nx=161 dx=25 fx=0000.0  labelx="Distance (m)"
ninf=5 npmax=201 

unif2 <input >data.v  ninf=$ninf  npmax=$npmax \
	nz=$nz dz=$dz fz=$fz nx=$nx dx=$dx fx=$fx \
	v00=2000,1500,1000,1000,3500,4000 \
	dvdz=0,1,1.5,1.5,0,0 \
	dvdx=0,0,-0.2,0,0,0 

exit 0

