#! /bin/sh

WIDTH=550
HEIGHT=400
XOFF1=100
YOFF1=550
XOFF2=700
YOFF2=700

# Plot Synthetic common offset data 

nt=501 dt=0.004 ft=0.0  nx=201 dx=0.015 fx=0.5 offset=0.1 

suximage < data   perc=99\
 label1="Time (sec)" label2="Midpoint (km)" \
 	wbox=$WIDTH hbox=$HEIGHT xbox=$XOFF1 ybox=$YOFF1 \
	title="Common Offset Data (Offset = $offset km)" &


# Plot inverted data 

n1=251 n2=267 d1=10 d2=15 

suximage < data.inv   \
	label1="Depth (m)" label2="Midpoint (m)" \
 	wbox=$WIDTH hbox=$HEIGHT xbox=$XOFF2 ybox=$YOFF1 \
	title="Common Offset Inversion" & 

exit 0

