#! /bin/sh

set -x

# ------------- DataDemo1 ------------------------------
# This script generates a single shot gather for use with
# demo program DCDemo1, which downward continues receivers 
# on a single shot gather.  It uses the code mandata to do
# so.
#
# Here, the model is simply a horizontal reflector at 1500m
# depth, and data is gathered on a a horizontal recording
# surface.  The medium is constant velocity.

  foff=0	
  noff=200
  doff=12.5

  nts=1600
  dts=0.002

  fshot=0
  nshot=1
  dshot=12.5

  v0=2000
  freq=20

# compile sumandata
make

 sumandata >demo1.data nt=$nts dt=$dts dxg=$doff nxg=$noff \
  nxs=$nshot dxs=$dshot ls=0 fpeak=$freq v=$v0 \
  zdat=0.0 zref=1500.0  

suximage < demo1.data title="Input data for Demo 1" &

exit 0
