#! /bin/sh

set -x

# ------------- DataDemo2 ------------------------------
# This script generates a a set of shot gathers for use with
# demo program DCDemo2, which downward continues receivers 
# and sources in a data set. It uses the code mandata to do
# to so. 
#
# Here, the model is simply a horizontal reflector at 1500m
# depth, and data is gathered on a a horizontal recording
# surface.  The medium is constant velocity.

  foff=0	
  noff=100
  doff=12.5

  nts=1600
  dts=0.002

  fshot=0
  nshot=25
  dshot=12.5

  v0=2000
  freq=20

# compile sumandata
make

  sumandata >demo2.data nt=$nts dt=$dts dxg=$doff nxg=$noff \
  nxs=$nshot dxs=$dshot ls=0 fpeak=$freq v=$v0 \
  zdat=0.0 zref=1500.0  
