#! /bin/sh
# Run CWELL with CWP PostScript Graphics

demo=5
psfile=demo${demo}.eps

x1beg=0 x1end=6500 x2beg=-100 x2end=10000

cwell |
cshotplot >demo${demo}plot  outpar=demo${demo}par

psgraph <demo${demo}plot par=demo${demo}par style=seismic \
	title="Primaries" \
	label1="Depth (ft)"  label2="Range (ft)" \
	wbox=6 hbox=4 \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end >$psfile

# Put the PostScript on screen or printer according to local lore
#cat $psfile | rsh keller -l jkc pwin
#cat $psfile | rsh dix -l jkc lpr -P$DixPrinter
xpwin <$psfile


