#! /bin/sh
# Run cwell with CWP X Graphics

demo=5

x1beg=0 x1end=6500 x2beg=-100 x2end=10000

cwell |
cshotplot >demo${demo}plot  outpar=demo${demo}par

xgraph <demo${demo}plot par=demo${demo}par  \
	-geometry 600x400+0-500 \
	title="Primaries" \
	label1="Depth (ft)"  label2="Range (ft)" \
	x1beg=$x1beg x1end=$x1end x2beg=$x2beg x2end=$x2end &

