#! /bin/sh
#### Create Figure 15 in the GBmod-paper
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------


datadir=../../datadir
rayendsfile=${datadir}/rayends.data

#### generate and plot commom shot record
gbbeam<$rayendsfile \
        bw=0 xg=0,4 zg=0,0 ng=100 lscale=0.5 \
	krecord=1 fpeak=8 nt=101 dt=0.025 ft=0 |
xwigb   xbox=670 ybox=660 perc=100 xcur=3.0 \
        n1=101 d1=0.025 f1=0 hbox=300 wbox=650\
        n2=100 d2=0.04 f2=0 title="Common Shot Seismograms" \
        label1="Time (sec)" label2="Distance (km)" grid1=solid &
exit 0
