#! /bin/sh
# Run GBmod with Xwindow Graphics
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL Xdemo
#------------------------------------------------


datadir=../../datadir/
datafile=${datadir}model.data

##### Build syncline model (Figure 14)

trimodel xmin=-1 zmin=0 xmax=5.0 zmax=2.0 \
1	xedge=-1,0,1,2,3,4,5 \
	zedge=0,0,0,0,0,0,0 \
	sedge=0,0,0,0,0,0,0 \
2       xedge=-1,0,0.5,1.0,1.5,2,2.5,3,4,5 \
        zedge=1,1.1,1.2,1.5,1.7,1.5,1.2,1.1,1,1  \
        sedge=0,0,0,0,0,0,0,0,0,0 \
3	xedge=-1,0,1,2,3,4,5 \
	zedge=2,2,2,2,2,2,2 \
	sedge=0,0,0,0,0,0,0 \
	sfill=1,0.5,0,0,0.25,0,0 \
	sfill=1,1.8,0,0,0.1,0,0 \
	kedge=1,2,3 \
	> $datafile

sxplot < $datafile -geom 650x300+670+0 \
        label1="Depth (km)" label2="Distance (km)" \
	tricolor=none title="Syncline Model"&

exit 0
