# Master makefile for ./cwp

include $(CWPROOT)/src/Makefile.config

INSTALL:
	cd AzimVelan ; $(MAKE) 
	cd Cshot ; $(MAKE)
	cd Cwell ; $(MAKE)
	cd Cxzco ; $(MAKE)
	cd Cxzcs ; $(MAKE)
	cd Raytrace3D ; $(MAKE) 
	cd Triso ; $(MAKE)
	cd Vplusz; $(MAKE) 
	cd Vzest; $(MAKE) 

remake:
	cd AzimVelan ; $(MAKE) remake
	cd Cshot ; $(MAKE) remake
	cd Cwell ; $(MAKE) remake
	cd Cxzco ; $(MAKE) remake
	cd Cxzcs ; $(MAKE) remake
	cd Raytrace3D ; $(MAKE) remake
	cd Triso ; $(MAKE) remake
	cd Vplusz; $(MAKE) remake
	cd Vzest; $(MAKE) remake
