#!/bin/bash


# generate test dataset
susynlv nt=511 dt=0.002 nxo=401 dxo=0.025 fxo=0 nxs=601 dxs=0.0125 \
fxs=0 x0=0 z0=0 v00=1.5 dvdz=1 \
ref="1:-10,0.3;10,0.3" \
ref="1:-10,0.6;10,0.6" \
ref="-7,4.37;5,0" \
ref="-26.5,26.85;5.5,0" \
ref="-6,20.78;6.0,0" \
ref="1:-5.5,68.06;6.5,0" fpeak=25 |
sugain gpow=0.6 > shot_dat.su

# Set the cdp numbers and the cmp spacing in the cmp gather
sushw < shot_dat.su key=cdp a=1 b=1 c=1 j=401 |
susort cdp offset > shot_dat2.su

rm shot_dat.su

sushw <shot_dat2.su key=d2 a=12.5 > shot_dat1.su


exit 0

