#! /bin/sh

#####  Interactive program to test
#####  for model parameters at a specific
#####  point within the model

#####  This shell asumes that a modelfile
#####  is already generated
#####  Andreas Rueger CWP 02-03-97

#####  Data directory

file=elamod

#####  Path to executables
#B=${HOME}/Release/Rays/bin

model=$file.model

if [ ! -f  $model ]
then
	echo File $model does not exist
	exit
else
	elacheck file=$model
fi
exit
