#! /bin/sh

To run the 3D data viewing demo type names of the following shell scripts
on the commandline.

Make3Ddata --- generate 3D data file: data3d.su
Trip1      --- planes pass through the center of data cube
Trip2      --- planes on top and back sides of data cube
Trip3      --- planes on bottom and back sides of data cube
Trip4      --- planes on bottom and front sides of data cube
Clean.sh   --- clean up after demo

The following menu is accessed by placing the cursor on the Trip window
and pressing the far right mouse button:

    Full screen                --- expand plot to full screen
    Quit                       --- quit
    First vertical plane       --- turn on/off first vertical plane
    Second vertical plane      --- turn off/on second vertical plane
    Horizontal plane           --- turn on/off horizontal plane
    Plot Axes                  --- show x,y,z axes.

John Stockwell	 | john@dix.Mines.EDU
Center for Wave Phenomena (The Home of Seismic Un*x)
Colorado School of Mines
Golden, CO 80401 | http://www.cwp.mines.edu/cwpcodes
voice: (303) 273-3049

Our book:
Norman Bleistein, Jack K. Cohen, John W. Stockwell Jr., [2001],
Mathematics of multidimensional seismic imaging, migration, and inversion,
(Interdisciplinary Applied Mathematics, V. 13.), Springer-Verlag, New York.


