#! /bin/sh

sustrip < data3d.su > data3d.bin

# slices centered through cube
# push right hand mouse button to see menu, select planes to view

trip < data3d.bin verbose=1 n1=256 n2=32 n3=32 tbs=.5  \
cx=16 cy=16 cz=128 &
 

exit 0
