#! /bin/sh

sustrip < data3d.su > data3d.bin

# slices on top and back sides of cube
# push right hand mouse button to see menu, select planes to view

trip < data3d.bin verbose=1 n1=256 n2=32 n3=32 tbs=.2  \
cx=0 cy=0 cz=0 &
 

exit 0
