#! /bin/sh

sustrip < data3d.su > data3d.bin

# slices on bottom and front sides of cube
# push right hand mouse button to see menu, select planes to view

trip < data3d.bin verbose=1 n1=256 n2=32 n3=32 tbs=.2  \
cx=31 cy=31 cz=255 &
 

exit 0
