#!/bin/sh

#
# demo for dashed curves in psimage, pswigb and pswigp
#

CURVES="curve0,curve1,curve2,curve3,curve4,curve5,curve6,curve7,curve8,curve9,curve10,curve11"

NPAIRS=32,32,32,32,32,32,32,32,32,32,32,32
CURVEDASHES=0,1,2,3,4,5,6,7,8,9,10,11
suspike > spike.su

supsimage < spike.su \
 curve=$CURVES npair=$NPAIRS curvedash=$CURVEDASHES > spike1.ps

supswigb < spike.su \
 curve=$CURVES npair=$NPAIRS curvedash=$CURVEDASHES > spike2.ps

supswigp < spike.su \
 curve=$CURVES npair=$NPAIRS curvedash=$CURVEDASHES > spike3.ps

echo "open the files spike1.ps spike2.ps spike3.ps with your PostScript previewer"
exit 0
