#! /bin/sh
# make data for NMO demo, goes into file: modeldata
# Note that since dsx=dgx, full fold is at most 32 (NOT 64),
#  but in this quick demo we have only 12 shots, so fold is at most 12

######Work in kft instead of km (synlv puts 10^3 in header fields)######
#  ref="1:1,2;4,2"      reflector(s):  "amplitude:x1,z1;x2,z2;x3,z3;..."
REF1="0.0909091:-4.0,1.0;12.0,1.0"
REF2="0.1428570:-4.0,2.2;12.0,2.2"
REF3="0.1111110:-4.0,3.5;12.0,3.5"
REF4="0.2000000:-4.0,5.0;12.0,5.0"

fpeak=25.0  # should be half nyquist to avoid all spatial aliasing
dvdz=2.0    # velocity gradient (dv/dz)
dvdx=0.0    # velocity gradient (dv/dx)
v00=5.0     # P-wave velocity at surface in kft/s
ob=0	    # to eliminate the turned ray contribution
nxo=64 fxo=0.1 dxo=0.1   # offset information: number, first, spacing
nxs=12 fxs=1.4 dxs=-0.1  # shot information: number, first, spacing
nt=501 dt=0.004          # time information: number, spacing


echo "Making synthetic data for demo"
susynlv v00=$v00 fpeak=$fpeak ndpfz=10 dvdz=$dvdz ob=$ob \
		dt=$dt nt=$nt verbose=0 \
		ref=$REF1 ref=$REF2 ref=$REF3 ref=$REF4 \
		nxo=$nxo fxo=$fxo dxo=$dxo \
		nxs=$nxs fxs=$fxs dxs=$dxs  |
suchw key1=cdp key2=gx key3=sx b=1 c=1 d=2 |
suaddnoise sn=50 f1=4.0 f2=8.0 f3=20.0 f4=25.0 >modeldata

exit
