#! /bin/sh

#Plot the entire data set
# Note: 64 offsets at nominal unit spacing (tracl), so d2 = 1/64
supsimage <modeldata perc=99 title="Shot Gathers"\
	label1="Time (sec)" label2="Shot Gather" f2=1 d2=0.015625 >allshots.eps


# Plot some shot records (d2=5/64)
suwind <modeldata key=sx s=1400 j=250 |
sugain tpow=2 gpow=0.5 |
supsimage label1="Time" label2="Gather" \
	title="Every 5th Shot Record (display gained)" \
	f2=1 d2=0.078125 f2num=1 d2num=5 >shots.eps

echo 
echo "Output are PostScript files:  allshots.eps   shots.eps"
echo 
echo "You may view these with your PostScript Previewer"

exit
