#! /bin/sh
# view model in the file "model"

WIDTH=300
HEIGHT=400
WIDTHOFF=0
HEIGHTOFF=50

# Plot the model
nx=100 fx=0 dx=80
nz=110 fz=0 dz=50
unif2 <model ninf=4 nx=$nx nz=$nz dx=$dx dz=$dz \
	v00=5000.0,6000.0,8000.0,10000.0,15000.0 |
ximage  n1=$nz f1=$fz d1=$dz n2=$nx f2=$fx d2=$dx windowtitle="Model" \
	legend=1 units="wavespeed" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF ybox=$HEIGHTOFF &

exit
