#! /bin/sh
# do and display nmo and stack

WIDTH=300
WIDTHOFF3=630
WIDTHOFF4=945
HEIGHT=400
HEIGHTOFF=50

# Do NMO
sunmo <modeldata par=stkvel.p1 >nmodata

# Display NMO
suwind <nmodata key=sx s=1400 j=250 |
sugain tpow=2 gpow=0.5 |
suximage label1="Time" label2="Gather" \
	title="Every 5th Shot Record After NMO" \
	windowtitle="NMO" legend=1 units="amplitude" \
	f2=1 d2=0.078125 f2num=1 d2num=5 \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF &

# Sort to CDP's and stack
susort <nmodata |
sustack normpow=1.0 >stackdata

# Display Stack (cdps from 350-4600, spacing is 50, full fold from 1450-3500)
sugain <stackdata tpow=2 gpow=0.5 |
suximage label1="Time" label2="CMP" title="Stack" windowtitle="Stack" \
	f2=350 d2=50  legend=1 units="amplitude" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF4 ybox=$HEIGHTOFF &

exit
