#! /bin/sh
# cdp sort
# Authors: Dave, Jack
set -x

input=shots.pack
output=cdp.pack

### Window to full fold cmgs (30 fold)--Working with PACKED data!
suwind <$input key=cdp min=1462 max=2823 |
susort cdp offset >$output
exit


### Usually cdp is set, but in this case Dave did it on the fly ...
### set cdp = shotnumber*4-channelnumber and keep only cdps 201 to 800
#sushw <shot0to304.pack key=cdp j=120 b=-1 c=4 |
#suwind key=cdp min=201 max=800 >temp
