#! /bin/sh
# dmo
set -x

# set parameters
input=cdp201to800
temp=dmocogs
output=dmocmgs
smute=1.7
vnmo=1500,1550,1700,2000,2300,2600,3000
tnmo=0.00,0.40,1.00,2.00,3.00,4.00,6.00


# sort to common-offset, nmo, dmo, inverse-nmo
susort <$input offset cdp |
sunmo smute=$smute vnmo=$vnmo tnmo=$tnmo |
sudmofk cdpmin=201 cdpmax=800 dxcdp=13.335 noffmix=4 verbose=1 |
sunmo invert=1 smute=$smute vnmo=$vnmo tnmo=$tnmo >$temp

# sort back to common-midpoint
susort <$temp cdp offset >$output
