#! /bin/sh
# migration
set -x

# set parameters
input=dmostack
output=dmomig
dxcdp=13.36
fmax=45

# decon after stack, migrate
supef <$input minlag=0.024 maxlag=0.250 |
sufilter f=0.0,4.0,40,45 |
sumigtk dxcdp=$dxcdp fmax=$fmax verbose=1 \
        speed=1 ltaper=50 nxpad=350 vfile=vintavg >$output

# plot
sugain <$output gpow=0.5 |
suximage f2=201 d2=1 \
        label1="Time (sec)" label2="CMP" title="Migrated DMO Stack" \
        perc=99 grid1=solid
