#! /bin/sh
# Plot (approx) common offset section
# Author: Jack
# NOTE: Comment lines preceeding user input start with  #!#
set -x

#!# From values in Cos shell
minoffset=291 # minimum offset
doffset=106 # delta offset (take smallest)
j=0	# j is the index of the offset range (0 is near offset)

### Plot--note that in this example data is never unpacked to disk
section=cos.$j.pack
min=`bc -l <<END
	$minoffset + $j * $doffset
END`
suunpack2 <$section |
sugain tpow=2.0 gpow=0.5 |
suximage f2=$min d2=$doffset \
	label1="Time (sec)" title="Common Offset: offset approx $min" \
	perc=99 grid1=solid &
