#! /bin/sh
# read segy data from original tape from record 368 to 880
# We subsampled and deleted every other shot gather (i.e. kept even #s)
# Author: Jack

output=shots.pack
minrec=368
maxrec=880
dxg=16.66667

### Take a fast look to see if we are reading the tape OK
#segyread trmax=180 |
#segyclean |
#sugain tpow=2.0 gpow=0.5 |
#suximage &
#exit


### Take a fast look to see which header fields are set
### Funny items in f1,d1,f2,d2 suggest the use of segyclean or sushw
#segyread trmax=360 |
#surange
#exit


### Read desired shot records off of multi-reel data set
### Save the binary and ebcdic headers from each reel
#REEL=3
#segyread verbose=1 hfile=header.$REEL bfile=bhead.$REEL |
#suwind key=fldr j=2 min=$minrec |
#sufilter f=4,8,110,125 |
#suresamp nt=1001 dt=.004 |
#segyclean |
#sushw key=d2 a=$dxg |
#supack2 >$output
#pause process next tape

#REEL=4
#segyread verbose=1 hfile=header.$REEL bfile=bhead.$REEL |
#suwind key=fldr j=2 |
#sufilter f=4,8,110,125 |
#suresamp nt=1001 dt=.004 |
#segyclean |
#sushw key=d2 a=$dxg |
#supack2 >>$output
#pause process next tape


#REEL=5
#segyread verbose=1 hfile=header.$REEL bfile=bhead.$REEL |
#suwind key=fldr j=2 max=$maxrec |
#sufilter f=4,8,110,125 |
#suresamp nt=1001 dt=.004 |
#segyclean |
#sushw key=d2 a=$dxg |
#supack2 >>$output
