#! /bin/sh
# Sufdmod2 --- example script for sufdmod2
# finite-difference modeling
# Author: John Stockwell

set -v

n1=100 d1=5 f1=0.0 label1="Depth (km)"
n2=100 d2=5 f2=0.0 label2="Distance (km)"
xs=250 zs=250 hsz=250 vsx=250 verbose=2
vsfile="junk.vseis" ssfile="junk.sseis" hsfile="junk.hseis"
tmax=.5 mt=5

makevel nx=$n2 nz=$n1 v000=3000 > junkv

sufdmod2 <junkv nz=$n1 dz=$d1 nx=$n2 dx=$d2 verbose=1 \
	xs=$xs zs=$zs hsz=$hsz vsx=$vsx hsfile=$hsfile \
	vsfile=$vsfile ssfile=$ssfile verbose=$verbose \
	tmax=$tmax abs=0,1,1,1 mt=$mt |
supsmovie n1=$n1 n2=$n2 perc=99 | open
#suxmovie -geometry 650x650+680-0 \
#	n1=$n1 d1=$d1 f1=$f1 n2=$n2 d2=$d2 f2=$f2 \
#	grid1=dot grid2=dot cmap=hue loop=1 \
#	label1="$label1" label2="$label2" \
#	title="Acoustic Finite-Differencing" clip=1.0

