#! /bin/sh
# shell for  sugazmig
# Author: John Stockwell 12 Oct 1992
#

set -x

#### Example 1 --- compute and display impulse response
## use suspike to make test data
#n1=64
#n2=32
#suspike nspk=3 it1=16 ix1=16 it2=32 ix2=16 it3=48 ix3=16  |
#sushw key=dt a=50000 |
#sushw key=d2 a=.05 > junk.spike
#supsimage < junk.spike title="Suspike data" | open
#
#sugazmig < junk.spike tmig=0 vmig=1 |
#supsimage label1="Migrated Time (sec)" label2="Midpoint (km)" \
#	title="Gazdag Migration --- Impulse responses"  | open
#exit
#

#n1=101
#n2=101
#
## Example 2 ---- constant velocity migration of curved plane model
## use susynlv to make synthetic data
#susynlv nt=$n1 dt=0.04 ft=0.0 nxo=1 \
#	nxm=$n2 dxm=.05 fxm=0.0 er=0 ob=1  \
#	v00=1.0 dvdz=0 dvdx=0 smooth=1 \
#	ref="0,.5;1.0,.5;2.,.8;2.5,1.0;3.0,.8;4.0,.5;5.0,.5"  |
#sushw key=d2 a=.05 > junk.susyn

#supsimage  < junk.susyn label1="Time (sec)" label2="Distance (km)" \
#        title="Synthetic Data" | open

# apply gazdag 
#sugazmig  < junk.susyn tmig=0 vmig=1  > junk.out
#supsimage < junk.out label1="Migrated Time (sec)" label2="Midpoint (km)" \
#	title="Gazdag Migration"  | open

#n1=101
#n2=101
## Example 3 ---- variable velocity migration
## use susynlv to make synthetic data
#susynlv nt=$n1 dt=0.04 ft=0.0 nxo=1 \
#	nxm=$n2 dxm=.05 fxm=0.0 er=0 ob=1  \
#	v00=1.0 dvdz=.2 dvdx=0 smooth=1 \
#	ref="0,.5;1.0,.5;2.,.8;2.5,1.0;3.0,.8;4.0,.5;5.0,.5"  |
#sushw key=d2 a=.05 > junk.susyn
#
#supsimage  < junk.susyn label1="Time (sec)" label2="Distance (km)" \
#        title="Synthetic Data" | open
#
## apply gazdag migration --- background velocity specified by tmig and vmig
#sugazmig  < junk.susyn tmig=0,4 vmig=1,1.8  > junk.out
#supsimage < junk.out label1="Migrated Time (sec)" label2="Midpoint (km)" \
##	title="Gazdag Migration"  | open


