#! /bin/sh
HEIGHT=300
WIDTH=300
XOFF1=0
YOFF1=0
XOFF2=400
YOFF2=400

DATA=data.seis

suximage < data.seis perc=99 title="original data" \
hbox=$HEIGHT wbox=$WIDTH xbox=$XOFF1 ybox=$YOFF1 &


sugain  < data.seis  tpow=1 | suximage  perc=99 title=" tpow=1 " \
hbox=$HEIGHT wbox=$WIDTH xbox=$XOFF2 ybox=$YOFF1 &

sugain  < data.seis  tpow=2 | suximage  perc=99 title=" tpow=2 " \
hbox=$HEIGHT wbox=$WIDTH xbox=$XOFF1 ybox=$YOFF2 &

sugain  < data.seis  tpow=3 | suximage  perc=99 title=" tpow=3 " \
hbox=$HEIGHT wbox=$WIDTH xbox=$XOFF2 ybox=$YOFF2 &

exit 0
