!<CPS_v1 type="AUXILIARY_FILE"/>
!!-------------------------- superproc_frou.f90 -----------------------------!!
!!-------------------------- superproc_frou.f90 -----------------------------!!
!!-------------------------- superproc_frou.f90 -----------------------------!!

     ! other files are:  superproc.f90  superproc_crou.c  superproc_crou.h

!<license>
!-------------------------------------------------------------------------------
! Copyright (c) 2007 ConocoPhillips Company
!
! Permission is hereby granted, free of charge, to any person obtaining a copy
! of this software and associated documentation files (the "Software"), to deal
! in the Software without restriction, including without limitation the rights
! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
! copies of the Software, and to permit persons to whom the Software is
! furnished to do so, subject to the following conditions:
!
! The above copyright notice and this permission notice shall be included in all
! copies or substantial portions of the Software.
!
! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
! SOFTWARE.
!-------------------------------------------------------------------------------
!</license>


!<brief_doc>
!-------------------------------------------------------------------------------
!                        C P S  P R I M I T I V E
!
! Name       : SUPERPROC_FROU
! Category   : cfe
! Written    : 2003-11-03   by: Tom Stoeckley
! Revised    : 2003-11-04   by: Tom Stoeckley
! Maturity   : beta
! Purpose    : CFE Super Process Object Module.
! Portability: No known limitations, but see note with superproc_frou_list.
!
! Automatically generated by program SPS_BUILD_SUPERPROC.
! Automatically generated using SUPERPROC_FROU_TEMPLATE.
! Dates and revision history refer to revisions of SUPERPROC_FROU_TEMPLATE.
!
!-------------------------------------------------------------------------------
!</brief_doc>


!<history_doc>
!-------------------------------------------------------------------------------
!                           REVISION HISTORY
!
!     Date        Author     Description
!     ----        ------     -----------
!  2. 2003-11-04  Stoeckley  Add MATURITY key.
!  1. 2003-11-03  Stoeckley  Initial version of SUPERPROC_FROU_TEMPLATE.
!
!-------------------------------------------------------------------------------
!</history_doc>


!!-------------------------- process list ----------------------------------!!
!!-------------------------- process list ----------------------------------!!
!!-------------------------- process list ----------------------------------!!


!<process_list>
!PROCESS_COUNT=178
!ABAL                      AMPLITUDE_MOD             BETA                     
!ABRA                      VELOCITY_ANALYSIS         BETA                     
!ACORR                     DIAGNOSTICS               BETA                     
!ADNS                      SYNTHETICS                BETA                     
!ADPSUB                    MISCELLANEOUS             BETA                     
!ALAMO                     VELOCITY_ANALYSIS         BETA                     
!AMPDG                     DIAGNOSTICS               BETA                     
!APIN                      AMPLITUDE_MOD             BETA                     
!ATRIN                     IO                        BETA                     
!ATROT                     IO                        BETA                     
!AVAGRAD                   DIAGNOSTICS               BETA                     
!AVAST                     STACKS                    BETA                     
!AVOANS                    VELOCITY_ANALYSIS         BETA                     
!AVOCORR                   VELOCITY_ANALYSIS         BETA                     
!AVONRM                    VELOCITY_ANALYSIS         BETA                     
!AVOPCOMP                  AMPLITUDE_MOD             BETA                     
!AVOSTS                    VELOCITY_ANALYSIS         BETA                     
!AVOVAN                    VELOCITY_ANALYSIS         BETA                     
!AVOVIT                    VELOCITY_ANALYSIS         BETA                     
!BUNCH                     SORTS                     BETA                     
!C4WE                      FILTERS                   BETA                     
!CC3D                      STATICS                   BETA                     
!CFDS                      STATICS                   BETA                     
!CHART                     HEADERS                   BETA                     
!CLEANUP                   MISCELLANEOUS             BETA                     
!CLIP                      AMPLITUDE_MOD             BETA                     
!CNEARTS                   FILTERS                   BETA                     
!CODMO                     MIGRATIONS                BETA                     
!COLOR                     PLOT                      BETA                     
!COMBINE                   MISCELLANEOUS             BETA                     
!COMP                      STACKS                    BETA                     
!CTAN                      TRANSFORMS                BETA                     
!DABRA                     MIGRATIONS                BETA                     
!DBGAIN                    AMPLITUDE_MOD             BETA                     
!DECON                     FILTERS                   BETA                     
!DIST                      DIAGNOSTICS               BETA                     
!DMAP3D                    MIGRATIONS                BETA                     
!DMO3D                     MIGRATIONS                BETA                     
!DMOPREP                   SORTS                     BETA                     
!DRC                       MIGRATIONS                BETA                     
!DSIG                      FILTERS                   BETA                     
!EAGC                      AMPLITUDE_MOD             BETA                     
!EDA                       FILTERS                   BETA                     
!EDA3D                     FILTERS                   BETA                     
!TRACETERP3D               MISCELLANEOUS             BETA                     
!ELEV                      HEADERS                   BETA                     
!EXO                       AMPLITUDE_MOD             BETA                     
!EZCHECK                   MISCELLANEOUS             BETA                     
!FBAL                      FILTERS                   BETA                     
!FFAVA                     STACKS                    BETA                     
!FGD                       HEADERS                   BETA                     
!FGDREV                    HEADERS                   BETA                     
!FILL                      MISCELLANEOUS             BETA                     
!FILTP                     FILTERS                   BETA                     
!FISH                      STATICS                   BETA                     
!FKAP                      FILTERS                   BETA                     
!FKFILT                    FILTERS                   BETA                     
!FKTMIG                    MIGRATIONS                BETA                     
!FKTR                      TRANSFORMS                BETA                     
!FLEXBIN                   MISCELLANEOUS             BETA                     
!FXDECON                   FILTERS                   BETA                     
!GATHER                    SORTS                     BETA                     
!GDIV                      AMPLITUDE_MOD             BETA                     
!GENFILT                   FILTERS                   BETA                     
!GRAB                      STATICS                   BETA                     
!GSTACK                    STACKS                    BETA                     
!GSTK                      STACKS                    BETA                     
!GVS                       STACKS                    BETA                     
!HEADCHECK                 HEADERS                   BETA                     
!HEADMAP                   HEADERS                   BETA                     
!HEADSUM                   DIAGNOSTICS               BETA                     
!HEADSWAP                  HEADERS                   BETA                     
!HRZSTK                    STACKS                    BETA                     
!HSYN                      SYNTHETICS                BETA                     
!HSYNMOD                   SYNTHETICS                BETA                     
!HVEL                      VELOCITY_ANALYSIS         BETA                     
!IBSMA                     MISCELLANEOUS             BETA                     
!IMS                       STATICS                   BETA                     
!INTEGRATE                 FILTERS                   BETA
!IQ                        FILTERS                   BETA                     
!JOB_DATA                  MISCELLANEOUS             BETA                     
!KA                        MIGRATIONS                BETA                     
!KASTATS                   MISCELLANEOUS             BETA                     
!KDMO                      MIGRATIONS                BETA                     
!MADC                      FILTERS                   BETA                     
!MASKER                    MISCELLANEOUS             BETA                     
!MDIP                      FILTERS                   BETA                     
!MDS                       AMPLITUDE_MOD             BETA                     
!MFRS                      STATICS                   BETA                     
!MGD                       HEADERS                   BETA                     
!MIX                       FILTERS                   BETA                     
!MODMO                     TRANSFORMS                BETA                     
!MODMO2D                   TRANSFORMS                BETA                     
!MTFUN                     FILTERS                   BETA                     
!MUTE                      AMPLITUDE_MOD             BETA                     
!MVXP                      AMPLITUDE_MOD             BETA                     
!MZPC                      FILTERS                   BETA                     
!NMO                       TRANSFORMS                BETA                     
!NORM                      AMPLITUDE_MOD             BETA                     
!OFF2ANG                   TRANSFORMS                BETA                     
!PAIRMERGE                 MISCELLANEOUS             BETA                     
!PFILT3C                   FILTERS                   BETA                     
!PGPS                      IO                        BETA                     
!PH2OFF                    TRANSFORMS                BETA                     
!PICKSET                   IO                        BETA                     
!PROJECT_DATA              MISCELLANEOUS             BETA                     
!PSTMIG                    MIGRATIONS                BETA                     
!QEST                      FILTERS                   BETA                     
!RANDGTH                   MISCELLANEOUS             BETA                     
!RANLINE                   MISCELLANEOUS             BETA                     
!RCPOUT                    MISCELLANEOUS             BETA                     
!REG                       MISCELLANEOUS             BETA                     
!REG2D                     FILTERS                   BETA                     
!REGBIN                    FILTERS                   BETA                     
!RES                       TRANSFORMS                BETA                     
!RESTH                     HEADERS                   BETA                     
!RFAB                      FILTERS                   BETA                     
!RMUL                      FILTERS                   BETA                     
!RNSYN                     SYNTHETICS                BETA                     
!RTC                       STATICS                   BETA                     
!SCAB                      AMPLITUDE_MOD             BETA                     
!SCALE                     AMPLITUDE_MOD             BETA                     
!SCDECON                   FILTERS                   BETA                     
!SDIP                      FILTERS                   BETA                     
!SELDMO                    SORTS                     BETA                     
!SELECT                    HEADERS                   BETA                     
!SETMUTE                   AMPLITUDE_MOD             BETA                     
!SETPOLY                   HEADERS                   BETA                     
!SETWORD                   HEADERS                   BETA                     
!SHFT                      STATICS                   BETA                     
!SISC                      STATICS                   BETA                     
!SLAB                      MISCELLANEOUS             BETA                     
!SLICE                     MISCELLANEOUS             BETA                     
!SLICER                    MISCELLANEOUS             BETA                     
!SLST                      TRANSFORMS                BETA                     
!SPCT                      TRANSFORMS                BETA                     
!SPIKE                     SYNTHETICS                BETA                     
!SPLT                      PLOT                      BETA                     
!SPTI                      TRANSFORMS                BETA                     
!STK                       STACKS                    BETA                     
!STRETCH                   MIGRATIONS                BETA                     
!SVA                       VELOCITY_ANALYSIS         BETA                     
!SYNBP                     SYNTHETICS                BETA                     
!TABLESAVE                 SORTS                     BETA                     
!TABLESORT                 SORTS                     BETA                     
!TDC                       TRANSFORMS                BETA                     
!TDMP                      DIAGNOSTICS               BETA                     
!TELAV                     AMPLITUDE_MOD             BETA                     
!TFATT                     TRANSFORMS                BETA                     
!TPICK                     SYNTHETICS                BETA                     
!TPOW                      AMPLITUDE_MOD             BETA                     
!TREDIT                    HEADERS                   BETA                     
!TRIN                      IO                        BETA                     
!TRINSORT                  IO                        BETA                     
!TRMO                      VELOCITY_ANALYSIS         BETA                     
!TROT                      IO                        BETA                     
!TRSTATS                   MISCELLANEOUS             BETA                     
!TSEL                      MISCELLANEOUS             BETA                     
!TSLC                      SORTS                     BETA                     
!TSLICE                    SORTS                     BETA                     
!TSMUTE                    VELOCITY_ANALYSIS         BETA                     
!TSORT                     SORTS                     BETA                     
!PARALLELSORT              SORTS                     BETA                     
!TSVF                      FILTERS                   BETA                     
!TTMO                      VELOCITY_ANALYSIS         BETA                     
!TTRIN                     IO                        BETA                     
!TTROT                     IO                        BETA                     
!TVF                       FILTERS                   BETA                     
!UNGATHER                  SORTS                     BETA                     
!UTEL                      MISCELLANEOUS             BETA                     
!VALUEDUMP                 DIAGNOSTICS               BETA                     
!VC                        FILTERS                   BETA                     
!VELEDIT                   VELOCITY_ANALYSIS         BETA                     
!VPICK                     VELOCITY_ANALYSIS         BETA                     
!VTRIM                     VELOCITY_ANALYSIS         BETA                     
!VTRIN                     IO                        BETA                     
!XP                        AMPLITUDE_MOD             BETA                     
!</process_list>


!!------------------------------- module ----------------------------------!!
!!------------------------------- module ----------------------------------!!
!!------------------------------- module ----------------------------------!!


      module superproc_frou_module
      use named_constants_module
      use string_module
      implicit none
      public

      character(len=100),public,save :: SUPERPROC_FROU_IDENT = &
'$Id: superproc_frou_template,v 1.2 2003/11/04 16:52:50 Stoeckley production sps $'

      integer,parameter,public   :: SUPERPROC_PRODUCTION = 1
      integer,parameter,public   :: SUPERPROC_BETA       = 2
      integer,parameter,public   :: SUPERPROC_ALPHA      = 3
      integer,parameter,public   :: SUPERPROC_RAW        = 4
      integer,parameter,public   :: LEN_ALL              = 178
      integer,parameter,public   :: LEN_CHAR             = 99

      type :: superproc_proclist_struct
        character(len=LEN_CHAR) :: process
        character(len=LEN_CHAR) :: category
        integer                 :: maturity
      end type superproc_proclist_struct

      type(superproc_proclist_struct),save :: all(LEN_ALL)
      integer                        ,save :: view = SUPERPROC_BETA
      logical                        ,save :: first_time = .TRUE.

      end module superproc_frou_module


!!-------------------------- private list -----------------------------!!
!!-------------------------- private list -----------------------------!!
!!-------------------------- private list -----------------------------!!


      subroutine superproc_frou_private_list
      use superproc_frou_module
      implicit none

      all(  1)%process  = "ABAL"
      all(  1)%category = "AMPLITUDE_MOD"
      all(  1)%maturity = SUPERPROC_BETA
 
      all(  2)%process  = "ABRA"
      all(  2)%category = "VELOCITY_ANALYSIS"
      all(  2)%maturity = SUPERPROC_BETA
 
      all(  3)%process  = "ACORR"
      all(  3)%category = "DIAGNOSTICS"
      all(  3)%maturity = SUPERPROC_BETA
 
      all(  4)%process  = "ADNS"
      all(  4)%category = "SYNTHETICS"
      all(  4)%maturity = SUPERPROC_BETA
 
      all(  5)%process  = "ADPSUB"
      all(  5)%category = "MISCELLANEOUS"
      all(  5)%maturity = SUPERPROC_BETA
 
      all(  6)%process  = "ALAMO"
      all(  6)%category = "VELOCITY_ANALYSIS"
      all(  6)%maturity = SUPERPROC_BETA
 
      all(  7)%process  = "AMPDG"
      all(  7)%category = "DIAGNOSTICS"
      all(  7)%maturity = SUPERPROC_BETA
 
      all(  8)%process  = "APIN"
      all(  8)%category = "AMPLITUDE_MOD"
      all(  8)%maturity = SUPERPROC_BETA
 
      all(  9)%process  = "ATRIN"
      all(  9)%category = "IO"
      all(  9)%maturity = SUPERPROC_BETA
 
      all( 10)%process  = "ATROT"
      all( 10)%category = "IO"
      all( 10)%maturity = SUPERPROC_BETA
 
      all( 11)%process  = "AVAGRAD"
      all( 11)%category = "DIAGNOSTICS"
      all( 11)%maturity = SUPERPROC_BETA
 
      all( 12)%process  = "AVAST"
      all( 12)%category = "STACKS"
      all( 12)%maturity = SUPERPROC_BETA
 
      all( 13)%process  = "AVOANS"
      all( 13)%category = "VELOCITY_ANALYSIS"
      all( 13)%maturity = SUPERPROC_BETA
 
      all( 14)%process  = "AVOCORR"
      all( 14)%category = "VELOCITY_ANALYSIS"
      all( 14)%maturity = SUPERPROC_BETA
 
      all( 15)%process  = "AVONRM"
      all( 15)%category = "VELOCITY_ANALYSIS"
      all( 15)%maturity = SUPERPROC_BETA
 
      all( 16)%process  = "AVOPCOMP"
      all( 16)%category = "AMPLITUDE_MOD"
      all( 16)%maturity = SUPERPROC_BETA
 
      all( 17)%process  = "AVOSTS"
      all( 17)%category = "VELOCITY_ANALYSIS"
      all( 17)%maturity = SUPERPROC_BETA
 
      all( 18)%process  = "AVOVAN"
      all( 18)%category = "VELOCITY_ANALYSIS"
      all( 18)%maturity = SUPERPROC_BETA
 
      all( 19)%process  = "AVOVIT"
      all( 19)%category = "VELOCITY_ANALYSIS"
      all( 19)%maturity = SUPERPROC_BETA
 
      all( 20)%process  = "BUNCH"
      all( 20)%category = "SORTS"
      all( 20)%maturity = SUPERPROC_BETA
 
      all( 21)%process  = "C4WE"
      all( 21)%category = "FILTERS"
      all( 21)%maturity = SUPERPROC_BETA
 
      all( 22)%process  = "CC3D"
      all( 22)%category = "STATICS"
      all( 22)%maturity = SUPERPROC_BETA
 
      all( 23)%process  = "CFDS"
      all( 23)%category = "STATICS"
      all( 23)%maturity = SUPERPROC_BETA
 
      all( 24)%process  = "CHART"
      all( 24)%category = "HEADERS"
      all( 24)%maturity = SUPERPROC_BETA
 
      all( 25)%process  = "CLEANUP"
      all( 25)%category = "MISCELLANEOUS"
      all( 25)%maturity = SUPERPROC_BETA
 
      all( 26)%process  = "CLIP"
      all( 26)%category = "AMPLITUDE_MOD"
      all( 26)%maturity = SUPERPROC_BETA
 
      all( 27)%process  = "CNEARTS"
      all( 27)%category = "FILTERS"
      all( 27)%maturity = SUPERPROC_BETA
 
      all( 28)%process  = "CODMO"
      all( 28)%category = "MIGRATIONS"
      all( 28)%maturity = SUPERPROC_BETA
 
      all( 29)%process  = "COLOR"
      all( 29)%category = "PLOT"
      all( 29)%maturity = SUPERPROC_BETA
 
      all( 30)%process  = "COMBINE"
      all( 30)%category = "MISCELLANEOUS"
      all( 30)%maturity = SUPERPROC_BETA
 
      all( 31)%process  = "COMP"
      all( 31)%category = "STACKS"
      all( 31)%maturity = SUPERPROC_BETA
 
      all( 32)%process  = "CTAN"
      all( 32)%category = "TRANSFORMS"
      all( 32)%maturity = SUPERPROC_BETA
 
      all( 33)%process  = "DABRA"
      all( 33)%category = "MIGRATIONS"
      all( 33)%maturity = SUPERPROC_BETA
 
      all( 34)%process  = "DBGAIN"
      all( 34)%category = "AMPLITUDE_MOD"
      all( 34)%maturity = SUPERPROC_BETA
 
      all( 35)%process  = "DECON"
      all( 35)%category = "FILTERS"
      all( 35)%maturity = SUPERPROC_BETA
 
      all( 36)%process  = "DIST"
      all( 36)%category = "DIAGNOSTICS"
      all( 36)%maturity = SUPERPROC_BETA
 
      all( 37)%process  = "DMAP3D"
      all( 37)%category = "MIGRATIONS"
      all( 37)%maturity = SUPERPROC_BETA
 
      all( 38)%process  = "DMO3D"
      all( 38)%category = "MIGRATIONS"
      all( 38)%maturity = SUPERPROC_BETA
 
      all( 39)%process  = "DMOPREP"
      all( 39)%category = "SORTS"
      all( 39)%maturity = SUPERPROC_BETA
 
      all( 40)%process  = "DRC"
      all( 40)%category = "MIGRATIONS"
      all( 40)%maturity = SUPERPROC_BETA
 
      all( 41)%process  = "DSIG"
      all( 41)%category = "FILTERS"
      all( 41)%maturity = SUPERPROC_BETA
 
      all( 42)%process  = "EAGC"
      all( 42)%category = "AMPLITUDE_MOD"
      all( 42)%maturity = SUPERPROC_BETA
 
      all( 43)%process  = "EDA"
      all( 43)%category = "FILTERS"
      all( 43)%maturity = SUPERPROC_BETA
 
      all( 44)%process  = "EDA3D"
      all( 44)%category = "FILTERS"
      all( 44)%maturity = SUPERPROC_BETA
 
      all( 45)%process  = "ELEV"
      all( 45)%category = "HEADERS"
      all( 45)%maturity = SUPERPROC_BETA
 
      all( 46)%process  = "EXO"
      all( 46)%category = "AMPLITUDE_MOD"
      all( 46)%maturity = SUPERPROC_BETA
 
      all( 47)%process  = "EZCHECK"
      all( 47)%category = "MISCELLANEOUS"
      all( 47)%maturity = SUPERPROC_BETA
 
      all( 48)%process  = "FBAL"
      all( 48)%category = "FILTERS"
      all( 48)%maturity = SUPERPROC_BETA
 
      all( 49)%process  = "FFAVA"
      all( 49)%category = "STACKS"
      all( 49)%maturity = SUPERPROC_BETA
 
      all( 50)%process  = "FGD"
      all( 50)%category = "HEADERS"
      all( 50)%maturity = SUPERPROC_BETA
 
      all( 51)%process  = "FGDREV"
      all( 51)%category = "HEADERS"
      all( 51)%maturity = SUPERPROC_BETA
 
      all( 52)%process  = "FILL"
      all( 52)%category = "MISCELLANEOUS"
      all( 52)%maturity = SUPERPROC_BETA
 
      all( 53)%process  = "FILTP"
      all( 53)%category = "FILTERS"
      all( 53)%maturity = SUPERPROC_BETA
 
      all( 54)%process  = "FISH"
      all( 54)%category = "STATICS"
      all( 54)%maturity = SUPERPROC_BETA
 
      all( 55)%process  = "FKAP"
      all( 55)%category = "FILTERS"
      all( 55)%maturity = SUPERPROC_BETA
 
      all( 56)%process  = "FKFILT"
      all( 56)%category = "FILTERS"
      all( 56)%maturity = SUPERPROC_BETA
 
      all( 57)%process  = "FKTMIG"
      all( 57)%category = "MIGRATIONS"
      all( 57)%maturity = SUPERPROC_BETA
 
      all( 58)%process  = "FKTR"
      all( 58)%category = "TRANSFORMS"
      all( 58)%maturity = SUPERPROC_BETA
 
      all( 59)%process  = "FLEXBIN"
      all( 59)%category = "MISCELLANEOUS"
      all( 59)%maturity = SUPERPROC_BETA
 
      all( 60)%process  = "FXDECON"
      all( 60)%category = "FILTERS"
      all( 60)%maturity = SUPERPROC_BETA
 
      all( 61)%process  = "GATHER"
      all( 61)%category = "SORTS"
      all( 61)%maturity = SUPERPROC_BETA
 
      all( 62)%process  = "GDIV"
      all( 62)%category = "AMPLITUDE_MOD"
      all( 62)%maturity = SUPERPROC_BETA
 
      all( 63)%process  = "GENFILT"
      all( 63)%category = "FILTERS"
      all( 63)%maturity = SUPERPROC_BETA
 
      all( 64)%process  = "GRAB"
      all( 64)%category = "STATICS"
      all( 64)%maturity = SUPERPROC_BETA
 
      all( 65)%process  = "GSTACK"
      all( 65)%category = "STACKS"
      all( 65)%maturity = SUPERPROC_BETA
 
      all( 66)%process  = "GSTK"
      all( 66)%category = "STACKS"
      all( 66)%maturity = SUPERPROC_BETA
 
      all( 67)%process  = "GVS"
      all( 67)%category = "STACKS"
      all( 67)%maturity = SUPERPROC_BETA
 
      all( 68)%process  = "HEADCHECK"
      all( 68)%category = "HEADERS"
      all( 68)%maturity = SUPERPROC_BETA
 
      all( 69)%process  = "HEADMAP"
      all( 69)%category = "HEADERS"
      all( 69)%maturity = SUPERPROC_BETA
 
      all( 70)%process  = "HEADSUM"
      all( 70)%category = "DIAGNOSTICS"
      all( 70)%maturity = SUPERPROC_BETA
 
      all( 71)%process  = "HEADSWAP"
      all( 71)%category = "HEADERS"
      all( 71)%maturity = SUPERPROC_BETA
 
      all( 72)%process  = "HRZSTK"
      all( 72)%category = "STACKS"
      all( 72)%maturity = SUPERPROC_BETA
 
      all( 73)%process  = "HSYN"
      all( 73)%category = "SYNTHETICS"
      all( 73)%maturity = SUPERPROC_BETA
 
      all( 74)%process  = "HSYNMOD"
      all( 74)%category = "SYNTHETICS"
      all( 74)%maturity = SUPERPROC_BETA
 
      all( 75)%process  = "HVEL"
      all( 75)%category = "VELOCITY_ANALYSIS"
      all( 75)%maturity = SUPERPROC_BETA
 
      all( 76)%process  = "IBSMA"
      all( 76)%category = "MISCELLANEOUS"
      all( 76)%maturity = SUPERPROC_BETA
 
      all( 77)%process  = "IMS"
      all( 77)%category = "STATICS"
      all( 77)%maturity = SUPERPROC_BETA
 
      all( 78)%process  = "IQ"
      all( 78)%category = "FILTERS"
      all( 78)%maturity = SUPERPROC_BETA
 
      all( 79)%process  = "JOB_DATA"
      all( 79)%category = "MISCELLANEOUS"
      all( 79)%maturity = SUPERPROC_BETA
 
      all( 80)%process  = "KA"
      all( 80)%category = "MIGRATIONS"
      all( 80)%maturity = SUPERPROC_BETA
 
      all( 81)%process  = "KASTATS"
      all( 81)%category = "MISCELLANEOUS"
      all( 81)%maturity = SUPERPROC_BETA
 
      all( 82)%process  = "KDMO"
      all( 82)%category = "MIGRATIONS"
      all( 82)%maturity = SUPERPROC_BETA
 
      all( 83)%process  = "MADC"
      all( 83)%category = "FILTERS"
      all( 83)%maturity = SUPERPROC_BETA
 
      all( 84)%process  = "MASKER"
      all( 84)%category = "MISCELLANEOUS"
      all( 84)%maturity = SUPERPROC_BETA
 
      all( 85)%process  = "MDIP"
      all( 85)%category = "FILTERS"
      all( 85)%maturity = SUPERPROC_BETA
 
      all( 86)%process  = "MDS"
      all( 86)%category = "AMPLITUDE_MOD"
      all( 86)%maturity = SUPERPROC_BETA
 
      all( 87)%process  = "MFRS"
      all( 87)%category = "STATICS"
      all( 87)%maturity = SUPERPROC_BETA
 
      all( 88)%process  = "MGD"
      all( 88)%category = "HEADERS"
      all( 88)%maturity = SUPERPROC_BETA
 
      all( 89)%process  = "MIX"
      all( 89)%category = "FILTERS"
      all( 89)%maturity = SUPERPROC_BETA
 
      all( 90)%process  = "MODMO"
      all( 90)%category = "TRANSFORMS"
      all( 90)%maturity = SUPERPROC_BETA
 
      all( 91)%process  = "MODMO2D"
      all( 91)%category = "TRANSFORMS"
      all( 91)%maturity = SUPERPROC_BETA
 
      all( 92)%process  = "MTFUN"
      all( 92)%category = "FILTERS"
      all( 92)%maturity = SUPERPROC_BETA
 
      all( 93)%process  = "MUTE"
      all( 93)%category = "AMPLITUDE_MOD"
      all( 93)%maturity = SUPERPROC_BETA
 
      all( 94)%process  = "MVXP"
      all( 94)%category = "AMPLITUDE_MOD"
      all( 94)%maturity = SUPERPROC_BETA
 
      all( 95)%process  = "MZPC"
      all( 95)%category = "FILTERS"
      all( 95)%maturity = SUPERPROC_BETA
 
      all( 96)%process  = "NMO"
      all( 96)%category = "TRANSFORMS"
      all( 96)%maturity = SUPERPROC_BETA
 
      all( 97)%process  = "NORM"
      all( 97)%category = "AMPLITUDE_MOD"
      all( 97)%maturity = SUPERPROC_BETA
 
      all( 98)%process  = "OFF2ANG"
      all( 98)%category = "TRANSFORMS"
      all( 98)%maturity = SUPERPROC_BETA
 
      all( 99)%process  = "PAIRMERGE"
      all( 99)%category = "MISCELLANEOUS"
      all( 99)%maturity = SUPERPROC_BETA
 
      all(100)%process  = "PFILT3C"
      all(100)%category = "FILTERS"
      all(100)%maturity = SUPERPROC_BETA
 
      all(101)%process  = "PGPS"
      all(101)%category = "IO"
      all(101)%maturity = SUPERPROC_BETA
 
      all(102)%process  = "PH2OFF"
      all(102)%category = "TRANSFORMS"
      all(102)%maturity = SUPERPROC_BETA
 
      all(103)%process  = "PICKSET"
      all(103)%category = "IO"
      all(103)%maturity = SUPERPROC_BETA
 
      all(104)%process  = "PROJECT_DATA"
      all(104)%category = "MISCELLANEOUS"
      all(104)%maturity = SUPERPROC_BETA
 
      all(105)%process  = "PSTMIG"
      all(105)%category = "MIGRATIONS"
      all(105)%maturity = SUPERPROC_BETA
 
      all(106)%process  = "QEST"
      all(106)%category = "FILTERS"
      all(106)%maturity = SUPERPROC_BETA
 
      all(107)%process  = "RANDGTH"
      all(107)%category = "MISCELLANEOUS"
      all(107)%maturity = SUPERPROC_BETA
 
      all(108)%process  = "RANLINE"
      all(108)%category = "MISCELLANEOUS"
      all(108)%maturity = SUPERPROC_BETA
 
      all(109)%process  = "RCPOUT"
      all(109)%category = "MISCELLANEOUS"
      all(109)%maturity = SUPERPROC_BETA
 
      all(110)%process  = "REG"
      all(110)%category = "MISCELLANEOUS"
      all(110)%maturity = SUPERPROC_BETA
 
      all(111)%process  = "REG2D"
      all(111)%category = "FILTERS"
      all(111)%maturity = SUPERPROC_BETA
 
      all(112)%process  = "REGBIN"
      all(112)%category = "FILTERS"
      all(112)%maturity = SUPERPROC_BETA
 
      all(113)%process  = "RES"
      all(113)%category = "TRANSFORMS"
      all(113)%maturity = SUPERPROC_BETA
 
      all(114)%process  = "RESTH"
      all(114)%category = "HEADERS"
      all(114)%maturity = SUPERPROC_BETA
 
      all(115)%process  = "RFAB"
      all(115)%category = "FILTERS"
      all(115)%maturity = SUPERPROC_BETA
 
      all(116)%process  = "RMUL"
      all(116)%category = "FILTERS"
      all(116)%maturity = SUPERPROC_BETA
 
      all(117)%process  = "RNSYN"
      all(117)%category = "SYNTHETICS"
      all(117)%maturity = SUPERPROC_BETA
 
      all(118)%process  = "RTC"
      all(118)%category = "STATICS"
      all(118)%maturity = SUPERPROC_BETA
 
      all(119)%process  = "SCAB"
      all(119)%category = "AMPLITUDE_MOD"
      all(119)%maturity = SUPERPROC_BETA
 
      all(120)%process  = "SCALE"
      all(120)%category = "AMPLITUDE_MOD"
      all(120)%maturity = SUPERPROC_BETA
 
      all(121)%process  = "SCDECON"
      all(121)%category = "FILTERS"
      all(121)%maturity = SUPERPROC_BETA
 
      all(122)%process  = "SDIP"
      all(122)%category = "FILTERS"
      all(122)%maturity = SUPERPROC_BETA
 
      all(123)%process  = "SELDMO"
      all(123)%category = "SORTS"
      all(123)%maturity = SUPERPROC_BETA
 
      all(124)%process  = "SELECT"
      all(124)%category = "HEADERS"
      all(124)%maturity = SUPERPROC_BETA
 
      all(125)%process  = "SETMUTE"
      all(125)%category = "AMPLITUDE_MOD"
      all(125)%maturity = SUPERPROC_BETA
 
      all(126)%process  = "SETPOLY"
      all(126)%category = "HEADERS"
      all(126)%maturity = SUPERPROC_BETA
 
      all(127)%process  = "SETWORD"
      all(127)%category = "HEADERS"
      all(127)%maturity = SUPERPROC_BETA
 
      all(128)%process  = "SHFT"
      all(128)%category = "STATICS"
      all(128)%maturity = SUPERPROC_BETA
 
      all(129)%process  = "SISC"
      all(129)%category = "STATICS"
      all(129)%maturity = SUPERPROC_BETA
 
      all(130)%process  = "SLAB"
      all(130)%category = "MISCELLANEOUS"
      all(130)%maturity = SUPERPROC_BETA
 
      all(131)%process  = "SLICE"
      all(131)%category = "MISCELLANEOUS"
      all(131)%maturity = SUPERPROC_BETA
 
      all(132)%process  = "SLICER"
      all(132)%category = "MISCELLANEOUS"
      all(132)%maturity = SUPERPROC_BETA
 
      all(133)%process  = "SLST"
      all(133)%category = "TRANSFORMS"
      all(133)%maturity = SUPERPROC_BETA
 
      all(134)%process  = "SPCT"
      all(134)%category = "TRANSFORMS"
      all(134)%maturity = SUPERPROC_BETA
 
      all(135)%process  = "SPIKE"
      all(135)%category = "SYNTHETICS"
      all(135)%maturity = SUPERPROC_BETA
 
      all(136)%process  = "SPLT"
      all(136)%category = "PLOT"
      all(136)%maturity = SUPERPROC_BETA
 
      all(137)%process  = "SPTI"
      all(137)%category = "TRANSFORMS"
      all(137)%maturity = SUPERPROC_BETA
 
      all(138)%process  = "STK"
      all(138)%category = "STACKS"
      all(138)%maturity = SUPERPROC_BETA
 
      all(139)%process  = "STRETCH"
      all(139)%category = "MIGRATIONS"
      all(139)%maturity = SUPERPROC_BETA
 
      all(140)%process  = "SVA"
      all(140)%category = "VELOCITY_ANALYSIS"
      all(140)%maturity = SUPERPROC_BETA
 
      all(141)%process  = "SYNBP"
      all(141)%category = "SYNTHETICS"
      all(141)%maturity = SUPERPROC_BETA
 
      all(142)%process  = "TABLESAVE"
      all(142)%category = "SORTS"
      all(142)%maturity = SUPERPROC_BETA
 
      all(143)%process  = "TABLESORT"
      all(143)%category = "SORTS"
      all(143)%maturity = SUPERPROC_BETA
 
      all(144)%process  = "TDC"
      all(144)%category = "TRANSFORMS"
      all(144)%maturity = SUPERPROC_BETA
 
      all(145)%process  = "TDMP"
      all(145)%category = "DIAGNOSTICS"
      all(145)%maturity = SUPERPROC_BETA
 
      all(146)%process  = "TELAV"
      all(146)%category = "AMPLITUDE_MOD"
      all(146)%maturity = SUPERPROC_BETA
 
      all(147)%process  = "TFATT"
      all(147)%category = "TRANSFORMS"
      all(147)%maturity = SUPERPROC_BETA
 
      all(148)%process  = "TPICK"
      all(148)%category = "SYNTHETICS"
      all(148)%maturity = SUPERPROC_BETA
 
      all(149)%process  = "TPOW"
      all(149)%category = "AMPLITUDE_MOD"
      all(149)%maturity = SUPERPROC_BETA
 
      all(150)%process  = "TREDIT"
      all(150)%category = "HEADERS"
      all(150)%maturity = SUPERPROC_BETA
 
      all(151)%process  = "TRIN"
      all(151)%category = "IO"
      all(151)%maturity = SUPERPROC_BETA
 
      all(152)%process  = "TRINSORT"
      all(152)%category = "IO"
      all(152)%maturity = SUPERPROC_BETA
 
      all(153)%process  = "TRMO"
      all(153)%category = "VELOCITY_ANALYSIS"
      all(153)%maturity = SUPERPROC_BETA
 
      all(154)%process  = "TROT"
      all(154)%category = "IO"
      all(154)%maturity = SUPERPROC_BETA
 
      all(155)%process  = "TRSTATS"
      all(155)%category = "MISCELLANEOUS"
      all(155)%maturity = SUPERPROC_BETA
 
      all(156)%process  = "TSEL"
      all(156)%category = "MISCELLANEOUS"
      all(156)%maturity = SUPERPROC_BETA
 
      all(157)%process  = "TSLC"
      all(157)%category = "SORTS"
      all(157)%maturity = SUPERPROC_BETA
 
      all(158)%process  = "TSLICE"
      all(158)%category = "SORTS"
      all(158)%maturity = SUPERPROC_BETA
 
      all(159)%process  = "TSMUTE"
      all(159)%category = "VELOCITY_ANALYSIS"
      all(159)%maturity = SUPERPROC_BETA
 
      all(160)%process  = "TSORT"
      all(160)%category = "SORTS"
      all(160)%maturity = SUPERPROC_BETA
 
      all(161)%process  = "TSVF"
      all(161)%category = "FILTERS"
      all(161)%maturity = SUPERPROC_BETA
 
      all(162)%process  = "TTMO"
      all(162)%category = "VELOCITY_ANALYSIS"
      all(162)%maturity = SUPERPROC_BETA
 
      all(163)%process  = "TTRIN"
      all(163)%category = "IO"
      all(163)%maturity = SUPERPROC_BETA
 
      all(164)%process  = "TTROT"
      all(164)%category = "IO"
      all(164)%maturity = SUPERPROC_BETA
 
      all(165)%process  = "TVF"
      all(165)%category = "FILTERS"
      all(165)%maturity = SUPERPROC_BETA
 
      all(166)%process  = "UNGATHER"
      all(166)%category = "SORTS"
      all(166)%maturity = SUPERPROC_BETA
 
      all(167)%process  = "UTEL"
      all(167)%category = "MISCELLANEOUS"
      all(167)%maturity = SUPERPROC_BETA
 
      all(168)%process  = "VALUEDUMP"
      all(168)%category = "DIAGNOSTICS"
      all(168)%maturity = SUPERPROC_BETA
 
      all(169)%process  = "VC"
      all(169)%category = "FILTERS"
      all(169)%maturity = SUPERPROC_BETA
 
      all(170)%process  = "VELEDIT"
      all(170)%category = "VELOCITY_ANALYSIS"
      all(170)%maturity = SUPERPROC_BETA
 
      all(171)%process  = "VPICK"
      all(171)%category = "VELOCITY_ANALYSIS"
      all(171)%maturity = SUPERPROC_BETA
 
      all(172)%process  = "VTRIM"
      all(172)%category = "VELOCITY_ANALYSIS"
      all(172)%maturity = SUPERPROC_BETA
 
      all(173)%process  = "VTRIN"
      all(173)%category = "IO"
      all(173)%maturity = SUPERPROC_BETA
 
      all(174)%process  = "XP"
      all(174)%category = "AMPLITUDE_MOD"
      all(174)%maturity = SUPERPROC_BETA
 
      all(175)%process  = "INTEGRATE"
      all(175)%category = "FILTERS"
      all(175)%maturity = SUPERPROC_BETA
 
      all(176)%process  = "WSEP"
      all(176)%category = "IO"
      all(176)%maturity = SUPERPROC_BETA
 
      all(177)%process  = "PARALLELSORT"
      all(177)%category = "SORTS"
      all(177)%maturity = SUPERPROC_BETA
 
      all(178)%process  = "TRACETERP3D"
      all(178)%category = "MISCELLANEOUS"
      all(178)%maturity = SUPERPROC_BETA
 
      first_time = .FALSE.

      end subroutine superproc_frou_private_list


!!------------------------------ nlist -----------------------------------!!
!!------------------------------ nlist -----------------------------------!!
!!------------------------------ nlist -----------------------------------!!


      subroutine superproc_frou_nlist (nprocess_list,category)
      use superproc_frou_module
      implicit none
      integer         ,intent(out)         :: nprocess_list       ! argument
      character(len=*),intent(in)          :: category            ! argument
      integer                              :: i                   ! local

      if (first_time) call superproc_frou_private_list

      nprocess_list = 0

      select case (category)
        case ('ALL_PROCESSES')
          do i=1,LEN_ALL
            if (view >= all(i)%maturity) nprocess_list = nprocess_list + 1
          enddo

        case default
          do i=1,LEN_ALL
            if (all(i)%category == category .and.    &
                view >= all(i)%maturity) nprocess_list = nprocess_list + 1
          enddo
      end select

      end subroutine superproc_frou_nlist


!!------------------------------ list -----------------------------------!!
!!------------------------------ list -----------------------------------!!
!!------------------------------ list -----------------------------------!!

       ! Note: The Portland Group compiler requires process_list below
       ! to be declared with (:) rather than (*) in order for the code
       ! to work.  Therefore, since the subroutines in this file are
       ! intentionally called without an explicit interface, an explicit
       ! interface for this subroutine must be placed into the superproc.f90
       ! file.

      subroutine superproc_frou_list (process_list,category)
      use superproc_frou_module
      implicit none
      character(len=*),intent(out)         :: process_list(:)     ! argument
      character(len=*),intent(in)          :: category            ! argument
      integer                              :: i,n                 ! local

      if (first_time) call superproc_frou_private_list

      n = 0

      select case (category)
        case ('ALL_PROCESSES')
            do i=1,LEN_ALL
              if (view >= all(i)%maturity) then
                n = n + 1
                process_list(n) = all(i)%process
              endif
            enddo

        case default
            do i=1,LEN_ALL
              if (all(i)%category == category .and.  &
                  view >= all(i)%maturity) then
                n = n + 1
                process_list(n) = all(i)%process
              endif
            enddo
      end select

      end subroutine superproc_frou_list


!!------------------------------ validate ----------------------------------!!
!!------------------------------ validate ----------------------------------!!
!!------------------------------ validate ----------------------------------!!


      subroutine superproc_frou_validate (name,valid)
      use superproc_frou_module
      implicit none
      character(len=*),intent(in)      :: name                 ! argument
      logical         ,intent(out)     :: valid                ! argument
      integer                          :: i                    ! local

      if (first_time) call superproc_frou_private_list

      valid = .false.
      do i=1,LEN_ALL
        if (all(i)%process == name .and.  &
            view >= all(i)%maturity) then
          valid = .true.
          exit
        endif
      enddo

      end subroutine superproc_frou_validate


!!------------------------------- set view ---------------------------------!!
!!------------------------------- set view ---------------------------------!!
!!------------------------------- set view ---------------------------------!!


      subroutine superproc_frou_set_view (desired_view)
      use superproc_frou_module
      implicit none
      integer,intent(in)        :: desired_view                  ! argument

      if (desired_view >= SUPERPROC_PRODUCTION .and. &
          desired_view <= SUPERPROC_RAW) then
        view = desired_view
      endif

      end subroutine superproc_frou_set_view


!!------------------------------- get rcs ident ----------------------------!!
!!------------------------------- get rcs ident ----------------------------!!
!!------------------------------- get rcs ident ----------------------------!!


      subroutine superproc_frou_get_rcs_ident (name, ident)
      use superproc_frou_module
      implicit none
      character(len=*)          ,intent(in)    :: name          ! argument
      character(len=*)          ,intent(out)   :: ident         ! argument

      select case (name)

      case ("ABAL"         ) ; call ABAL_superwrap_rcs                  (ident)
      case ("ABRA"         ) ; call ABRA_superwrap_rcs                  (ident)
      case ("ACORR"        ) ; call ACORR_superwrap_rcs                 (ident)
      case ("ADNS"         ) ; call ADNS_superwrap_rcs                  (ident)
      case ("ADPSUB"       ) ; call ADPSUB_superwrap_rcs                (ident)
      case ("ALAMO"        ) ; call ALAMO_superwrap_rcs                 (ident)
      case ("AMPDG"        ) ; call AMPDG_superwrap_rcs                 (ident)
      case ("APIN"         ) ; call APIN_superwrap_rcs                  (ident)
      case ("ATRIN"        ) ; call ATRIN_superwrap_rcs                 (ident)
      case ("ATROT"        ) ; call ATROT_superwrap_rcs                 (ident)
      case ("AVAGRAD"      ) ; call AVAGRAD_superwrap_rcs               (ident)
      case ("AVAST"        ) ; call AVAST_superwrap_rcs                 (ident)
      case ("AVOANS"       ) ; call AVOANS_superwrap_rcs                (ident)
      case ("AVOCORR"      ) ; call AVOCORR_superwrap_rcs               (ident)
      case ("AVONRM"       ) ; call AVONRM_superwrap_rcs                (ident)
      case ("AVOPCOMP"     ) ; call AVOPCOMP_superwrap_rcs              (ident)
      case ("AVOSTS"       ) ; call AVOSTS_superwrap_rcs                (ident)
      case ("AVOVAN"       ) ; call AVOVAN_superwrap_rcs                (ident)
      case ("AVOVIT"       ) ; call AVOVIT_superwrap_rcs                (ident)
      case ("BUNCH"        ) ; call BUNCH_superwrap_rcs                 (ident)
      case ("C4WE"         ) ; call C4WE_superwrap_rcs                  (ident)
      case ("CC3D"         ) ; call CC3D_superwrap_rcs                  (ident)
      case ("CFDS"         ) ; call CFDS_superwrap_rcs                  (ident)
      case ("CHART"        ) ; call CHART_superwrap_rcs                 (ident)
      case ("CLEANUP"      ) ; call CLEANUP_superwrap_rcs               (ident)
      case ("CLIP"         ) ; call CLIP_superwrap_rcs                  (ident)
      case ("CNEARTS"      ) ; call CNEARTS_superwrap_rcs               (ident)
      case ("CODMO"        ) ; call CODMO_superwrap_rcs                 (ident)
      case ("COLOR"        ) ; call COLOR_superwrap_rcs                 (ident)
      case ("COMBINE"      ) ; call COMBINE_superwrap_rcs               (ident)
      case ("COMP"         ) ; call COMP_superwrap_rcs                  (ident)
      case ("CTAN"         ) ; call CTAN_superwrap_rcs                  (ident)
      case ("DABRA"        ) ; call DABRA_superwrap_rcs                 (ident)
      case ("DBGAIN"       ) ; call DBGAIN_superwrap_rcs                (ident)
      case ("DECON"        ) ; call DECON_superwrap_rcs                 (ident)
      case ("DIST"         ) ; call DIST_superwrap_rcs                  (ident)
      case ("DMAP3D"       ) ; call DMAP3D_superwrap_rcs                (ident)
      case ("DMO3D"        ) ; call DMO3D_superwrap_rcs                 (ident)
      case ("DMOPREP"      ) ; call DMOPREP_superwrap_rcs               (ident)
      case ("DRC"          ) ; call DRC_superwrap_rcs                   (ident)
      case ("DSIG"         ) ; call DSIG_superwrap_rcs                  (ident)
      case ("EAGC"         ) ; call EAGC_superwrap_rcs                  (ident)
      case ("EDA"          ) ; call EDA_superwrap_rcs                   (ident)
      case ("EDA3D"        ) ; call EDA3D_superwrap_rcs                 (ident)
      case ("TRACETERP3D"  ) ; call TRACETERP3D_superwrap_rcs           (ident)
      case ("ELEV"         ) ; call ELEV_superwrap_rcs                  (ident)
      case ("EXO"          ) ; call EXO_superwrap_rcs                   (ident)
      case ("EZCHECK"      ) ; call EZCHECK_superwrap_rcs               (ident)
      case ("FBAL"         ) ; call FBAL_superwrap_rcs                  (ident)
      case ("FFAVA"        ) ; call FFAVA_superwrap_rcs                 (ident)
      case ("FGD"          ) ; call FGD_superwrap_rcs                   (ident)
      case ("FGDREV"       ) ; call FGDREV_superwrap_rcs                (ident)
      case ("FILL"         ) ; call FILL_superwrap_rcs                  (ident)
      case ("FILTP"        ) ; call FILTP_superwrap_rcs                 (ident)
      case ("FISH"         ) ; call FISH_superwrap_rcs                  (ident)
      case ("FKAP"         ) ; call FKAP_superwrap_rcs                  (ident)
      case ("FKFILT"       ) ; call FKFILT_superwrap_rcs                (ident)
      case ("FKTMIG"       ) ; call FKTMIG_superwrap_rcs                (ident)
      case ("FKTR"         ) ; call FKTR_superwrap_rcs                  (ident)
      case ("FLEXBIN"      ) ; call FLEXBIN_superwrap_rcs               (ident)
      case ("FXDECON"      ) ; call FXDECON_superwrap_rcs               (ident)
      case ("GATHER"       ) ; call GATHER_superwrap_rcs                (ident)
      case ("GDIV"         ) ; call GDIV_superwrap_rcs                  (ident)
      case ("GENFILT"      ) ; call GENFILT_superwrap_rcs               (ident)
      case ("GRAB"         ) ; call GRAB_superwrap_rcs                  (ident)
      case ("GSTACK"       ) ; call GSTACK_superwrap_rcs                (ident)
      case ("GSTK"         ) ; call GSTK_superwrap_rcs                  (ident)
      case ("GVS"          ) ; call GVS_superwrap_rcs                   (ident)
      case ("HEADCHECK"    ) ; call HEADCHECK_superwrap_rcs             (ident)
      case ("HEADMAP"      ) ; call HEADMAP_superwrap_rcs               (ident)
      case ("HEADSUM"      ) ; call HEADSUM_superwrap_rcs               (ident)
      case ("HEADSWAP"     ) ; call HEADSWAP_superwrap_rcs              (ident)
      case ("HRZSTK"       ) ; call HRZSTK_superwrap_rcs                (ident)
      case ("HSYN"         ) ; call HSYN_superwrap_rcs                  (ident)
      case ("HSYNMOD"      ) ; call HSYNMOD_superwrap_rcs               (ident)
      case ("HVEL"         ) ; call HVEL_superwrap_rcs                  (ident)
      case ("IBSMA"        ) ; call IBSMA_superwrap_rcs                 (ident)
      case ("IMS"          ) ; call IMS_superwrap_rcs                   (ident)
      case ("INTEGRATE"    ) ; call INTEGRATE_superwrap_rcs             (ident)
      case ("IQ"           ) ; call IQ_superwrap_rcs                    (ident)
      case ("JOB_DATA"     ) ; call JOB_DATA_superwrap_rcs              (ident)
      case ("KA"           ) ; call KA_superwrap_rcs                    (ident)
      case ("KASTATS"      ) ; call KASTATS_superwrap_rcs               (ident)
      case ("KDMO"         ) ; call KDMO_superwrap_rcs                  (ident)
      case ("MADC"         ) ; call MADC_superwrap_rcs                  (ident)
      case ("MASKER"       ) ; call MASKER_superwrap_rcs                (ident)
      case ("MDIP"         ) ; call MDIP_superwrap_rcs                  (ident)
      case ("MDS"          ) ; call MDS_superwrap_rcs                   (ident)
      case ("MFRS"         ) ; call MFRS_superwrap_rcs                  (ident)
      case ("MGD"          ) ; call MGD_superwrap_rcs                   (ident)
      case ("MIX"          ) ; call MIX_superwrap_rcs                   (ident)
      case ("MODMO"        ) ; call MODMO_superwrap_rcs                 (ident)
      case ("MODMO2D"      ) ; call MODMO2D_superwrap_rcs               (ident)
      case ("MTFUN"        ) ; call MTFUN_superwrap_rcs                 (ident)
      case ("MUTE"         ) ; call MUTE_superwrap_rcs                  (ident)
      case ("MVXP"         ) ; call MVXP_superwrap_rcs                  (ident)
      case ("MZPC"         ) ; call MZPC_superwrap_rcs                  (ident)
      case ("NMO"          ) ; call NMO_superwrap_rcs                   (ident)
      case ("NORM"         ) ; call NORM_superwrap_rcs                  (ident)
      case ("OFF2ANG"      ) ; call OFF2ANG_superwrap_rcs               (ident)
      case ("PAIRMERGE"    ) ; call PAIRMERGE_superwrap_rcs             (ident)
      case ("PFILT3C"      ) ; call PFILT3C_superwrap_rcs               (ident)
      case ("PGPS"         ) ; call PGPS_superwrap_rcs                  (ident)
      case ("PH2OFF"       ) ; call PH2OFF_superwrap_rcs                (ident)
      case ("PICKSET"      ) ; call PICKSET_superwrap_rcs               (ident)
      case ("PROJECT_DATA" ) ; call PROJECT_DATA_superwrap_rcs          (ident)
      case ("PSTMIG"       ) ; call PSTMIG_superwrap_rcs                (ident)
      case ("QEST"         ) ; call QEST_superwrap_rcs                  (ident)
      case ("RANDGTH"      ) ; call RANDGTH_superwrap_rcs               (ident)
      case ("RANLINE"      ) ; call RANLINE_superwrap_rcs               (ident)
      case ("RCPOUT"       ) ; call RCPOUT_superwrap_rcs                (ident)
      case ("REG"          ) ; call REG_superwrap_rcs                   (ident)
      case ("REG2D"        ) ; call REG2D_superwrap_rcs                 (ident)
      case ("REGBIN"       ) ; call REGBIN_superwrap_rcs                (ident)
      case ("RES"          ) ; call RES_superwrap_rcs                   (ident)
      case ("RESTH"        ) ; call RESTH_superwrap_rcs                 (ident)
      case ("RFAB"         ) ; call RFAB_superwrap_rcs                  (ident)
      case ("RMUL"         ) ; call RMUL_superwrap_rcs                  (ident)
      case ("RNSYN"        ) ; call RNSYN_superwrap_rcs                 (ident)
      case ("RTC"          ) ; call RTC_superwrap_rcs                   (ident)
      case ("SCAB"         ) ; call SCAB_superwrap_rcs                  (ident)
      case ("SCALE"        ) ; call SCALE_superwrap_rcs                 (ident)
      case ("SCDECON"      ) ; call SCDECON_superwrap_rcs               (ident)
      case ("SDIP"         ) ; call SDIP_superwrap_rcs                  (ident)
      case ("SELDMO"       ) ; call SELDMO_superwrap_rcs                (ident)
      case ("SELECT"       ) ; call SELECT_superwrap_rcs                (ident)
      case ("SETMUTE"      ) ; call SETMUTE_superwrap_rcs               (ident)
      case ("SETPOLY"      ) ; call SETPOLY_superwrap_rcs               (ident)
      case ("SETWORD"      ) ; call SETWORD_superwrap_rcs               (ident)
      case ("SHFT"         ) ; call SHFT_superwrap_rcs                  (ident)
      case ("SISC"         ) ; call SISC_superwrap_rcs                  (ident)
      case ("SLAB"         ) ; call SLAB_superwrap_rcs                  (ident)
      case ("SLICE"        ) ; call SLICE_superwrap_rcs                 (ident)
      case ("SLICER"       ) ; call SLICER_superwrap_rcs                (ident)
      case ("SLST"         ) ; call SLST_superwrap_rcs                  (ident)
      case ("SPCT"         ) ; call SPCT_superwrap_rcs                  (ident)
      case ("SPIKE"        ) ; call SPIKE_superwrap_rcs                 (ident)
      case ("SPLT"         ) ; call SPLT_superwrap_rcs                  (ident)
      case ("SPTI"         ) ; call SPTI_superwrap_rcs                  (ident)
      case ("STK"          ) ; call STK_superwrap_rcs                   (ident)
      case ("STRETCH"      ) ; call STRETCH_superwrap_rcs               (ident)
      case ("SVA"          ) ; call SVA_superwrap_rcs                   (ident)
      case ("SYNBP"        ) ; call SYNBP_superwrap_rcs                 (ident)
      case ("TABLESAVE"    ) ; call TABLESAVE_superwrap_rcs             (ident)
      case ("TABLESORT"    ) ; call TABLESORT_superwrap_rcs             (ident)
      case ("TDC"          ) ; call TDC_superwrap_rcs                   (ident)
      case ("TDMP"         ) ; call TDMP_superwrap_rcs                  (ident)
      case ("TELAV"        ) ; call TELAV_superwrap_rcs                 (ident)
      case ("TFATT"        ) ; call TFATT_superwrap_rcs                 (ident)
      case ("TPICK"        ) ; call TPICK_superwrap_rcs                 (ident)
      case ("TPOW"         ) ; call TPOW_superwrap_rcs                  (ident)
      case ("TREDIT"       ) ; call TREDIT_superwrap_rcs                (ident)
      case ("TRIN"         ) ; call TRIN_superwrap_rcs                  (ident)
      case ("TRINSORT"     ) ; call TRINSORT_superwrap_rcs              (ident)
      case ("TRMO"         ) ; call TRMO_superwrap_rcs                  (ident)
      case ("TROT"         ) ; call TROT_superwrap_rcs                  (ident)
      case ("TRSTATS"      ) ; call TRSTATS_superwrap_rcs               (ident)
      case ("TSEL"         ) ; call TSEL_superwrap_rcs                  (ident)
      case ("TSLC"         ) ; call TSLC_superwrap_rcs                  (ident)
      case ("TSLICE"       ) ; call TSLICE_superwrap_rcs                (ident)
      case ("TSMUTE"       ) ; call TSMUTE_superwrap_rcs                (ident)
      case ("TSORT"        ) ; call TSORT_superwrap_rcs                 (ident)
      case ("PARALLELSORT"        ) ; call PARALLELSORT_superwrap_rcs                 (ident)
      case ("TSVF"         ) ; call TSVF_superwrap_rcs                  (ident)
      case ("TTMO"         ) ; call TTMO_superwrap_rcs                  (ident)
      case ("TTRIN"        ) ; call TTRIN_superwrap_rcs                 (ident)
      case ("TTROT"        ) ; call TTROT_superwrap_rcs                 (ident)
      case ("TVF"          ) ; call TVF_superwrap_rcs                   (ident)
      case ("UNGATHER"     ) ; call UNGATHER_superwrap_rcs              (ident)
      case ("UTEL"         ) ; call UTEL_superwrap_rcs                  (ident)
      case ("VALUEDUMP"    ) ; call VALUEDUMP_superwrap_rcs             (ident)
      case ("VC"           ) ; call VC_superwrap_rcs                    (ident)
      case ("VELEDIT"      ) ; call VELEDIT_superwrap_rcs               (ident)
      case ("VPICK"        ) ; call VPICK_superwrap_rcs                 (ident)
      case ("VTRIM"        ) ; call VTRIM_superwrap_rcs                 (ident)
      case ("VTRIN"        ) ; call VTRIN_superwrap_rcs                 (ident)
      case ("WSEP"         ) ; call WSEP_superwrap_rcs                  (ident)
      case ("XP"           ) ; call XP_superwrap_rcs                    (ident)

      case default; ident = 'invalid process '//name
                    print *, "Invalid process "//trim(name)
      end select

      end subroutine superproc_frou_get_rcs_ident


!!--------------------------------- end ------------------------------------!!
!!--------------------------------- end ------------------------------------!!
!!--------------------------------- end ------------------------------------!!

