#! /bin/sh
# shell for plotting the original and smoothed v(x,z) model
#set -v

nz=51 dz=50 fz=.0  labelz="Depth (m)"
nx=71 dx=50 fx=0000.0  labelx="Distance (m)"
ninf=0 npmax=201 

psimage <vfile  style=seismic \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	wbox=6 hbox=4 ybox=4 \
	title="Velocity"  > vel.eps


echo
echo "Output as the PostScript file:   vel.eps "
echo
echo "You may view this with your PostScript Previewer"

exit 0
