#! /bin/sh
# shell for Kirchhoff modeling for linear v(x,z)
set -x

 nt=725 dt=0.004 ft=0.0 tmin=0.2 nxs=6 dxs=0.3 fxs=0.05
 fxo=0.1 dxo=0.025 nxo=60
  fpeak=30 er=0 ls=1 
 susynlv  nt=$nt dt=$dt ft=$ft nxs=$nxs dxs=$dxs fxs=$fxs  fxo=$fxo\
  dxo=$dxo nxo=$nxo tmin=$tmin v00=1.5 dvdx=0.0 dvdz=0.8 \
  fpeak=$fpeak er=1 ls=1\
 	ref="1:0,0.5;1,1.5;2.,1.5,3,0.5">data

