#! /bin/sh
# shell for plotting synthetic data and migrated data

WIDTH=400
HEIGHT=600
WIDTHOFF1=10
WIDTHOFF2=440
WIDTHOFF3=860
HEIGHTOFF1=20

suximage<data  perc=99.5 legend=1 units=amp cmap=hsv5 \
	label1="Time (s)" label2="Midpoint (m)" \
	title="Synthetic Data" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 ybox=$HEIGHTOFF1 &

# Plotting migrated data

suximage<kd.data perc=99.5 legend=1 units=amp cmap=hsv5 \
	label1="Depth (km)" label2="Midpoint (km)" \
	title="Kirchhoff Depth Migration" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF1 &
