#! /bin/sh
# This shell shows how to generate different sweeps using the SUVIBRO

WIDTH=300
HEIGHT=300
WIDTHOFF1=0
WIDTHOFF2=315
WIDTHOFF3=630
WIDTHOFF4=945
HEIGHTOFF1=5
HEIGHTOFF2=335
HEIGHTOFF3=665

perc=99

# Generate Linear Sweep
suvibro sweep=1 f1=8. f2=72. tv=10. t1=0.5 t2=1.5  |
suxwigb perc=$perc \
	title="Linear"\
	label1="Time (sec)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF1} ybox=${HEIGHTOFF1} &
suvibro sweep=1 f1=8. f2=72. tv=10. t1=0.5 t2=1.5 | suspecfx | 
suxwigb perc=$perc \
	title="Amp.spec. of linear"\
	label1="Freq (hz)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF2} ybox=${HEIGHTOFF1} &

#Generate Linear-Segment Sweep
suvibro sweep=2 tseg=0.0,0.50,2.00,4.00,6.50,8.00,10.0 \
	fseg=8.0,15.0,25.0,40.0,50.0,64.0,72.0 |
suxwigb perc=$perc \
	title="Linear-Segment"\
	label1="Time (sec)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF3} ybox=${HEIGHTOFF1} &
suvibro sweep=2 tseg=0.0,0.50,2.00,4.00,6.50,8.00,10.0 \
	fseg=8.0,15.0,25.0,40.0,50.0,64.0,72.0 | suspecfx |
suxwigb perc=$perc \
	title="Amp.spec. of linear-segment"\
	label1="Freq (hz)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF4} ybox=${HEIGHTOFF1} &

#Generate dB per Octave Sweep (Down-sweep)
suvibro sweep=3 f1=72. f2=8. swconst=6. |
suxwigb perc=$perc \
	title="dB/Octave"\
	label1="Time (sec)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF1} ybox=${HEIGHTOFF2} &
suvibro sweep=3 f1=72. f2=8. swconst=6. | suspecfx |
suxwigb perc=$perc \
	title="Amp.spec. of dB/Octave"\
	label1="Freq (hz)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF2} ybox=${HEIGHTOFF2} &

#Generate dB per Hertz Sweep
suvibro sweep=4 f1=8. f2=72. swconst=0.22 |
suxwigb perc=$perc \
	title="dB/Hertz"\
	label1="Time (sec)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF3} ybox=${HEIGHTOFF2} &
suvibro sweep=4 f1=8. f2=72. swconst=0.22 | suspecfx | 
suxwigb perc=$perc \
	title="Amp.spec. of dB/Hertz"\
	label1="Freq (hz)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF4} ybox=${HEIGHTOFF2} &

#Generate T-power Sweep (Down-sweep)
suvibro sweep=5 f1=72. f2=8. swconst=0.3 |
suxwigb perc=$perc \
	title="T-power"\
	label1="Time (sec)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF1} ybox=${HEIGHTOFF3} &
suvibro sweep=5 f1=72. f2=8. swconst=0.3 | suspecfx | 
suxwigb perc=$perc \
	title="Amp.spec. of T-power"\
	label1="Freq (hz)" label2="" \
	wbox=${WIDTH} hbox=${HEIGHT} xbox=${WIDTHOFF2} ybox=${HEIGHTOFF3} &
exit 0
