#! /bin/sh
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL PSdemo
#------------------------------------------------


datadir=../../datadir/
modelfile=${datadir}model.data
rayendsfile=${datadir}rayends.data

##### Generate Common-shot section

nt=151 dt=0.025 bw=0 ft=0.0 ng=101 lscale=0.5 

gbbeam<$rayendsfile \
       	bw=$bw fpeak=8 lscale=$lscale ng=101\
	xg=0,4 zg=0,0 nt=$nt dt=$dt ft=$ft |
pswigb   n1=$nt d1=$dt f1=$ft x1end=3.5 \
        n2=101 d2=0.04 f2=0 grid1=none perc=100 \
        xcur=3.0 title="Reflection from lower syncline" \
        hbox=4 wbox=6 label1="Time (sec)" label1="Time (sec)"\
        label2="Midpoint (km)" > seis.eps

cat seis.eps | $PSPREVIEWER

exit 0
