#! /bin/sh
#### Shoot rays (Figure 20)
#------------------------------------------------
# RUN THIS SHELL WITH MASTER SHELL PSdemo
#------------------------------------------------

datadir=../../datadir/
modelfile=${datadir}model.data
rayendsfile=${datadir}rayends.data
rayfile=${datadir}rays.data

nangle=260 fangle=-65 langle=65 nxz=401 
x=2.72 prim=1

####   shoot the rays
triray <$modelfile >$rayendsfile rayfile=$rayfile \
    	nangle=$nangle fangle=$fangle langle=$langle \
        nxz=$nxz xs=$x zs=0 krecord=1 prim=$prim \
        refseq=3,1 refseq=1,-1 

psgraph <$rayfile hbox=4 wbox=6 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=3 x2beg=-1.0 x2end=5 style=seismic \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" |
	$PSPREVIEWER

psgraph <$rayfile hbox=4 wbox=6 nplot=`cat outpar` n=$nxz \
        x1beg=0 x1end=3 x2beg=-1.0 x2end=5 style=seismic \
        label1="Depth (km)" label2="Distance (km)" title="Raypaths" > rays.eps


exit 0
